set_project("emulatelaunchd")
set_version("0.0.1")
add_repositories("charon " .. (os.getenv("CHARON_REPO") or "https://github.com/kern0x1b/charon.git"))
add_addons("charon " .. (os.getenv("CHARON_ADDON") or "v0.8.15"))
set_config("apple_minimum", "6.1.3")
includes("@addon/charon/apple-ios")
includes("@addon/charon/emulate")
set_allowedplats("iphoneos")
set_allowedarchs("iphoneos|armv7")
set_defaultplat("iphoneos")
set_defaultarchs("iphoneos|armv7")

target("emulatelaunchd")
    add_rules("@addon/charon/daemon")
    add_files("main.c")
    add_frameworks("CoreFoundation")
    set_values("charon.version", "1.0")
    set_values("charon.control", "control")
