#!/usr/bin/env python3
"""Generate the (dictionary, property) pair list the ImageIO property-mapping harness asks about.

Every pair comes out of the header's own "Possible keys for kCGImagePropertyXxxDictionary" sections,
so the list cannot drift from the header it names. Usage:

    python3 gen-property-pairs.py <SDK>/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h

prints a C header on stdout. The host's own ImageIO is the oracle, so the SDK given here is the one
the port builds against and the harness reads the names out of it at run time.
"""
import re
import sys

DICT_SECTION = re.compile(r"/\* Possible keys for (kCGImageProperty\w+Dictionary) \*/")
DECL = re.compile(r"IMAGEIO_EXTERN const CFStringRef (kCGImageProperty\w+)\s")
DICT_DECL = re.compile(r"IMAGEIO_EXTERN const CFStringRef (kCGImageProperty\w+Dictionary)\s")


def pairs(header):
    """[(dictionary, property)] in header order, one entry per property the header declares."""
    current = None
    out = []
    for line in open(header, errors="replace"):
        section = DICT_SECTION.search(line)
        if section:
            current = section.group(1)
            continue
        if DICT_DECL.search(line):
            current = None  # a dictionary constant ends the section it belonged to
            continue
        decl = DECL.search(line)
        if decl and current:
            out.append((current, decl.group(1)))
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    header = sys.argv[1]
    found = pairs(header)
    seen = set()
    unique = []
    for d, p in found:
        if (d, p) in seen:
            continue  # two constants can share one string; the pair is asked once
        seen.add((d, p))
        unique.append((d, p))
    print("/* Generated by: python3 gen-property-pairs.py <iOS SDK>/System/Library/Frameworks/ImageIO.framework/Headers/CGImageProperties.h")
    print("   SDK used: the one this tree builds against; this file is generated, not edited. */")
    print("/* %d pairs: every property the header declares under a dictionary it names. */" % len(unique))
    print("typedef struct {")
    print("    CFStringRef dictionary;")
    print("    CFStringRef property;")
    print("} charon_pair;")
    print()
    print("static size_t charon_pairs(charon_pair *out)")
    print("{")
    for i, (d, p) in enumerate(unique):
        print("    out[%d].dictionary = %s; out[%d].property = %s;" % (i, d, i, p))
    print("    return %d;" % len(unique))
    print("}")


if __name__ == "__main__":
    main()