#import <FileProvider/FileProvider.h>
#import <objc/runtime.h>

// The iOS 11.0 band of this framework, generated by tools/corpus/gen-ledger-objects.py from
// tools/corpus/spec/*.json. // Corpus rank 7 of coordination/corpus/crash-demand-top.tsv. The spec is the whole of what this file is, and
// it names what the file must NOT do as well as what it does, because inventing behaviour the
// release cannot have is the whole risk in carrying a framework.

// CARRIED AND CALLABLE, and the differential must NOT call it: calling it on the host
// asks this machine to mount a provider domain. The port carries it so an app does not
// crash naming it; the harness never invokes it.
//   never called: +[NSFileProviderManager addDomain:completionHandler:]
//   never called: +[NSFileProviderManager removeDomain:completionHandler:]
//   never called: -[NSFileProviderManager signalEnumeratorForContainerItemIdentifier:completionHandler:]

// Carried surface, each entry one the corpus names:
//   -[NSFileProviderDomain initWithIdentifier:displayName:pathRelativeToDocumentStorage:]
//   identifier
//   displayName
//   pathRelativeToDocumentStorage
//   volumeUUID

// A carried domain is DATA. What an app does with one is read its identifier, its display name and where
// it sits relative to the document storage, and hand it to the manager - and the manager is where this
// release's own behaviour would have to come from, which it has none of.
//
// THE IVARS ARE ON THIS CLASS. The first version of this file put them on a separate
// NSFileProviderDomainCharonStorage and had initWithIdentifier: return one of those, which is not an
// NSFileProviderDomain at all. The compiler said so -
//     incompatible pointer types returning 'NSFileProviderDomainCharonStorage *' from a function with
//     result type 'NSFileProviderDomain *'
// - and it was right: a caller holding that object back is holding the wrong class, and the port has to
// answer as a real NSFileProviderDomain. So the state lives here and the init fills it in.

// -initWithIdentifier:displayName: is declared by this class and answered by the 16.0 CATEGORY, because
// release-split refuses one object whose symbols first appear in two releases. That is the same reason as
// UIAction.m's pragma and the same reason it carries its reason on the line.
#pragma clang diagnostic ignored "-Wincomplete-implementation"
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"
@implementation NSFileProviderDomain {
  NSString *_charonIdentifier;
  NSString *_charonDisplayName;
  NSString *_charonRelative;
  NSUUID *_charonVolumeUUID;
  BOOL _charonUserEnabled;
  BOOL _charonIsReplicated;
  BOOL _charonHidden;
  BOOL _charonSupportsSyncingTrash;
}
@synthesize identifier = _charonIdentifier;
@synthesize displayName = _charonDisplayName;
@synthesize pathRelativeToDocumentStorage = _charonRelative;

@synthesize volumeUUID = _charonVolumeUUID;

// The four flags the 16.0 header carries, stored here and filled through the one method the category can
// reach, because a category has no ivar of its own on this target.
- (void)charon_setUserEnabled:(BOOL)userEnabled replicated:(BOOL)replicated
                     hidden:(BOOL)hidden supportsSyncingTrash:(BOOL)supportsSyncingTrash
{
  _charonUserEnabled = userEnabled;
  _charonIsReplicated = replicated;
  _charonHidden = hidden;
  _charonSupportsSyncingTrash = supportsSyncingTrash;
}
- (BOOL)charon_userEnabled { return _charonUserEnabled; }
- (BOOL)charon_replicated { return _charonIsReplicated; }
- (BOOL)charon_hidden { return _charonHidden; }
- (BOOL)charon_supportsSyncingTrash { return _charonSupportsSyncingTrash; }

// NOT BUILT IN THIS OBJECT, AND SAID SO RATHER THAN CLAIMED. -initWithIdentifier:displayName: and the
// members below are this class's own at 16.0 and later, or are API_UNAVAILABLE(ios) in the SDK's own header,
// so this object does not define them. @dynamic leaves respondsToSelector: answering NO, which is the truth,
// where a method that answered NO would be a name the port claims and does not carry.
@dynamic hidden;
@dynamic disconnected;
@dynamic replicated;
@dynamic testingModes;
@dynamic supportsSyncingTrash;
@dynamic backingStoreIdentity;

- (id)initWithIdentifier:(NSString *)identifier
             displayName:(NSString *)displayName
pathRelativeToDocumentStorage:(NSString *)relative {
  self = [super init];
  if (self) {
    _charonIdentifier = [identifier copy];
    _charonDisplayName = [displayName copy];
    _charonRelative = [relative copy];
  }
  return self;
}
@end

#import <FileProvider/FileProvider.h>
#import <objc/runtime.h>

// The iOS 11.0 band of this framework, generated by tools/corpus/gen-ledger-objects.py from
// tools/corpus/spec/*.json. // Corpus rank 8 of coordination/corpus/crash-demand-top.tsv. The spec is the whole of what this file is, and
// it names what the file must NOT do as well as what it does, because inventing behaviour the
// release cannot have is the whole risk in carrying a framework.

// CARRIED AND CALLABLE, and the differential must NOT call it: calling it on the host
// asks this machine to mount a provider domain. The port carries it so an app does not
// crash naming it; the harness never invokes it.
//   never called: +[NSFileProviderManager addDomain:completionHandler:]
//   never called: +[NSFileProviderManager removeDomain:completionHandler:]
//   never called: -[NSFileProviderManager signalEnumeratorForContainerItemIdentifier:completionHandler:]

// Carried surface, each entry one the corpus names:
//   +[NSFileProviderManager getDomainsWithCompletionHandler:]

// NO CLASS IS EMITTED HERE, AND THAT IS THE POINT. NSFileProviderManager is defined by
// FileProvider/NSFileProviderManager.m, which is main s work and is not mine to touch. A second
// @implementation for one class is a duplicate class symbol at load - the nm sweep calls it "class defined
// twice" and the process dies before main ever runs - so the generator REFUSES to emit a class any object
// in the tree already defines, naming the file that has it, and this piece exists to hold the policy the
// manager needs without owning the class.
//
// The names below are CARRIED by that file and are never invoked by a differential: addDomain and
// removeDomain would ask this machine to mount a provider domain, and signalEnumerator would ask it to
// watch one. They are in this spec so the check that reads them has one place to read them from.
