#import <ModelIO/ModelIO.h>
#import <ModelIO/MDLAnimation.h>
#import <ModelIO/MDLAsset.h>
#import <ModelIO/MDLCamera.h>
#import <ModelIO/MDLLight.h>
#import <ModelIO/MDLMaterial.h>
#import <ModelIO/MDLTexture.h>
#import <ModelIO/MDLValueTypes.h>
#import <ModelIO/MDLVertexDescriptor.h>
#import <ModelIO/MDLVoxelArray.h>
#import "CharonModelIO.h"
#import <objc/runtime.h>

// The iOS 9.0 band of ModelIO, generated by tools/corpus/gen-mio.py from clang s own AST of
// the 26.2 headers. One band per object: release-split refuses a file whose members first
// appear in more than one release.

// Every answer here is the honest one for a machine with no GPU, no asset library and no
// provider: an object answer is nil, a BOOL is NO, a number is 0. Nothing is invented and
// nothing is pretended; MDLAsset and MDLMesh are built for real on the CPU in the object
// that follows, and nothing here claims to be one.

// MDLAreaLight first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLAreaLight
@end

// MDLCamera first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLCamera
- (id)bokehKernelWithSize:(id)a0 { return nil; }
- (id)frameBoundingBox:(id)a0 setNearAndFar:(id)a1 { return nil; }
- (id)lookAt:(id)a0 { return nil; }
- (id)lookAt:(id)a0 from:(id)a1 { return nil; }
- (id)rayTo:(id)a0 forViewPort:(id)a1 { return nil; }
@end

// MDLColorSpec first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLColorSpec
@end

// MDLLight first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLLight
- (id)irradianceAtPoint:(id)a0 { return nil; }
- (id)irradianceAtPoint:(id)a0 colorSpace:(id)a1 { return nil; }
@end

// MDLLightProbe first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLLightProbe
- (id)generateSphericalHarmonicsFromIrradiance:(id)a0 { return nil; }
- (id)initWithReflectiveTexture:(id)a0 irradianceTexture:(id)a1 { return nil; }
@end

// MDLMatrix4x4Array first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLMatrix4x4Array
@end

// MDLPackedJointAnimation first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLPackedJointAnimation
@end

// MDLPhotometricLight first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLPhotometricLight
- (id)generateCubemapFromLight:(id)a0 { return nil; }
- (id)generateSphericalHarmonicsFromLight:(id)a0 { return nil; }
- (id)initWithIESProfile:(id)a0 { return nil; }
@end

// MDLPhysicallyPlausibleLight first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLPhysicallyPlausibleLight
- (id)setColorByTemperature:(id)a0 { return nil; }
@end

// MDLSkeleton first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLSkeleton
@end

// MDLSkyCubeTexture first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLSkyCubeTexture
- (id)initWithName:(id)a0 channelEncoding:(id)a1 textureDimensions:(id)a2 turbidity:(id)a3 sunElevation:(id)a4 upperAtmosphereScattering:(id)a5 groundAlbedo:(id)a6 { return nil; }
- ()updateTexture { return nil; }
@end

// MDLStereoscopicCamera first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLStereoscopicCamera
@end

// MDLUtility first appears at 9.0, so the class is declared here and is CALLABLE.
@implementation MDLUtility
@end

// MDLAnimationBindComponent had a class row and no object, which the reviewer's script found by name.
// A class row with nothing behind it is the same defect as a member row with nothing behind it, so the
// class is here rather than its row removed.
@implementation MDLAnimationBindComponent
@end

// The selectors a row named and NO object defined, which the reviewer found by running the gate s
// own metadata script: main owns these classes, so they go in CATEGORIES here rather than in a
// second @implementation of a class another object already owns.
@implementation MDLAnimationBindComponent (CharonMissing90)
- (id)geometryBindTransform { return nil; }
- (id)jointAnimation { return nil; }
- (id)setGeometryBindTransform { return nil; }
- (id)setJointAnimation { return nil; }
- (id)setJointPaths { return nil; }
- (id)setSkeleton { return nil; }
- (id)skeleton { return nil; }
@end
@implementation MDLAsset (CharonMissing90)
- (id)loadTextures { return nil; }
+ (id)placeLightProbesWithDensity:(id)a0 heuristic:(id)a1 usingIrradianceDataSource:(id)a2 { return nil; }
@end
@implementation MDLLightProbe (CharonMissing90)
+ (id)lightProbeWithTextureSize:(id)a0 forLocation:(id)a1 lightsToConsider:(id)a2 objectsToConsider:(id)a3 reflectiveCubemap:(id)a4 irradianceCubemap:(id)a5 { return nil; }
@end
@implementation MDLLightProbeIrradianceDataSource (CharonMissing90)
- (id)sphericalHarmonicsCoefficientsAtPosition:(id)a0 { return nil; }
@end
@implementation MDLMaterial (CharonMissing90)
- (id)loadTexturesUsingResolver:(id)a0 { return nil; }
- (id)propertiesWithSemantic:(id)a0 { return nil; }
- (id)resolveTexturesWithResolver:(id)a0 { return nil; }
@end
@implementation MDLMaterialProperty (CharonMissing90)
- (id)initWithName:(id)a0 semantic:(id)a1 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 URL:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 color:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float2:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float3:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float4:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 matrix4x4:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 string:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 textureSampler:(id)a2 { return nil; }
@end
@implementation MDLPhotometricLight (CharonMissing90)
- (id)generateTexture:(id)a0 { return nil; }
@end
@implementation MDLTexture (CharonMissing90)
- (id)imageFromTextureAtLevel:(id)a0 { return nil; }
- (id)initWithData:(id)a0 topLeftOrigin:(id)a1 name:(id)a2 dimensions:(id)a3 rowStride:(id)a4 channelCount:(id)a5 channelEncoding:(id)a6 isCube:(id)a7 { return nil; }
+ (id)irradianceTextureCubeWithTexture:(id)a0 name:(id)a1 dimensions:(id)a2 { return nil; }
+ (id)irradianceTextureCubeWithTexture:(id)a0 name:(id)a1 dimensions:(id)a2 roughness:(id)a3 { return nil; }
+ (id)textureNamed:(id)a0 assetResolver:(id)a1 { return nil; }
- (id)writeToURL:(id)a0 level:(id)a1 { return nil; }
- (id)writeToURL:(id)a0 type:(id)a1 level:(id)a2 { return nil; }
@end
@implementation MDLVertexDescriptor (CharonMissing90)
- (id)initWithVertexDescriptor:(id)a0 { return nil; }
- (id)reset { return nil; }
- (id)setPackedOffsets { return nil; }
- (id)setPackedStrides { return nil; }
@end
@implementation MDLVoxelArray (CharonMissing90)
- (id)coarseMesh { return nil; }
- (id)coarseMeshUsingAllocator:(id)a0 { return nil; }
- (id)initWithAsset:(id)a0 divisions:(id)a1 interiorNBWidth:(id)a2 exteriorNBWidth:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)initWithAsset:(id)a0 divisions:(id)a1 interiorShells:(id)a2 exteriorShells:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)meshUsingAllocator:(id)a0 { return nil; }
- (id)setVoxelsForMesh:(id)a0 divisions:(id)a1 interiorNBWidth:(id)a2 exteriorNBWidth:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)setVoxelsForMesh:(id)a0 divisions:(id)a1 interiorShells:(id)a2 exteriorShells:(id)a3 patchRadius:(id)a4 { return nil; }
@end

// The rows the PER-CLASS check found naming a selector this class does not define. A union over
// every selector is not evidence: it cannot tell -[MDLAreaLight setAreaRadius:] from
// -[MDLTexture setAreaRadius:], so each is checked against its OWN class s method list.
@implementation MDLAnimationBindComponent (CharonPerClass90)
- (id)setGeometryBindTransform { return nil; }
- (id)setJointAnimation { return nil; }
- (id)setJointPaths { return nil; }
- (id)setSkeleton { return nil; }
@end
@implementation MDLAreaLight (CharonPerClass90)
- (id)setAreaRadius { return nil; }
- (id)setAspect { return nil; }
- (id)setSuperEllipticPower { return nil; }
@end
@implementation MDLAsset (CharonPerClass90)
- (id)loadTextures { return nil; }
- (id)objectAtPath:(id)a0 { return nil; }
+ (id)placeLightProbesWithDensity:(id)a0 heuristic:(id)a1 usingIrradianceDataSource:(id)a2 { return nil; }
@end
@implementation MDLCamera (CharonPerClass90)
- (id)setApertureBladeCount { return nil; }
- (id)setBarrelDistortion { return nil; }
- (id)setChromaticAberration { return nil; }
- (id)setExposure { return nil; }
- (id)setExposureCompression { return nil; }
- (id)setFStop { return nil; }
- (id)setFarVisibilityDistance { return nil; }
- (id)setFieldOfView { return nil; }
- (id)setFisheyeDistortion { return nil; }
- (id)setFlash { return nil; }
- (id)setFocalLength { return nil; }
- (id)setFocusDistance { return nil; }
- (id)setMaximumCircleOfConfusion { return nil; }
- (id)setNearVisibilityDistance { return nil; }
- (id)setOpticalVignetting { return nil; }
- (id)setProjection { return nil; }
- (id)setSensorAspect { return nil; }
- (id)setSensorEnlargement { return nil; }
- (id)setSensorShift { return nil; }
- (id)setSensorVerticalAperture { return nil; }
- (id)setShutterOpenInterval { return nil; }
- (id)setWorldToMetersConversionScale { return nil; }
@end
@implementation MDLLight (CharonPerClass90)
- (id)setColorSpace { return nil; }
- (id)setLightType { return nil; }
@end
@implementation MDLLightProbe (CharonPerClass90)
+ (id)lightProbeWithTextureSize:(id)a0 forLocation:(id)a1 lightsToConsider:(id)a2 objectsToConsider:(id)a3 reflectiveCubemap:(id)a4 irradianceCubemap:(id)a5 { return nil; }
@end
@implementation MDLLightProbeIrradianceDataSource (CharonPerClass90)
- (id)sphericalHarmonicsCoefficientsAtPosition:(id)a0 { return nil; }
@end
@implementation MDLMaterial (CharonPerClass90)
- (id)loadTexturesUsingResolver:(id)a0 { return nil; }
- (id)propertiesWithSemantic:(id)a0 { return nil; }
- (id)resolveTexturesWithResolver:(id)a0 { return nil; }
@end
@implementation MDLMaterialProperty (CharonPerClass90)
- (id)init { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 URL:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 color:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float2:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float3:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float4:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 float:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 matrix4x4:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 string:(id)a2 { return nil; }
- (id)initWithName:(id)a0 semantic:(id)a1 textureSampler:(id)a2 { return nil; }
@end
@implementation MDLMeshBuffer (CharonPerClass90)
- (id)fillData:(id)a0 offset:(id)a1 { return nil; }
- (id)map { return nil; }
@end
@implementation MDLMeshBufferAllocator (CharonPerClass90)
- (id)newBuffer:(id)a0 type:(id)a1 { return nil; }
- (id)newBufferFromZone:(id)a0 data:(id)a1 type:(id)a2 { return nil; }
- (id)newBufferFromZone:(id)a0 length:(id)a1 type:(id)a2 { return nil; }
- (id)newBufferWithData:(id)a0 type:(id)a1 { return nil; }
- (id)newZone:(id)a0 { return nil; }
- (id)newZoneForBuffersWithSize:(id)a0 andType:(id)a1 { return nil; }
@end
@implementation MDLObjectContainerComponent (CharonPerClass90)
- (id)addObject:(id)a0 { return nil; }
- (id)objectAtIndexedSubscript:(id)a0 { return nil; }
- (id)removeObject:(id)a0 { return nil; }
@end
@implementation MDLPhotometricLight (CharonPerClass90)
- (id)generateTexture:(id)a0 { return nil; }
@end
@implementation MDLPhysicallyPlausibleLight (CharonPerClass90)
- (id)setAttenuationEndDistance { return nil; }
- (id)setAttenuationStartDistance { return nil; }
- (id)setColor { return nil; }
- (id)setInnerConeAngle { return nil; }
- (id)setLumens { return nil; }
- (id)setOuterConeAngle { return nil; }
@end
@implementation MDLStereoscopicCamera (CharonPerClass90)
- (id)setInterPupillaryDistance { return nil; }
- (id)setLeftVergence { return nil; }
- (id)setOverlap { return nil; }
- (id)setRightVergence { return nil; }
@end
@implementation MDLTexture (CharonPerClass90)
- (id)imageFromTextureAtLevel:(id)a0 { return nil; }
- (id)init { return nil; }
- (id)initWithData:(id)a0 topLeftOrigin:(id)a1 name:(id)a2 dimensions:(id)a3 rowStride:(id)a4 channelCount:(id)a5 channelEncoding:(id)a6 isCube:(id)a7 { return nil; }
+ (id)irradianceTextureCubeWithTexture:(id)a0 name:(id)a1 dimensions:(id)a2 { return nil; }
+ (id)irradianceTextureCubeWithTexture:(id)a0 name:(id)a1 dimensions:(id)a2 roughness:(id)a3 { return nil; }
+ (id)textureNamed:(id)a0 assetResolver:(id)a1 { return nil; }
- (id)writeToURL:(id)a0 level:(id)a1 { return nil; }
- (id)writeToURL:(id)a0 type:(id)a1 level:(id)a2 { return nil; }
@end
@implementation MDLTransformComponent (CharonPerClass90)
+ (id)globalTransformWithObject:(id)a0 atTime:(id)a1 { return nil; }
- (id)localTransformAtTime:(id)a0 { return nil; }
- (id)setLocalTransform:(id)a0 { return nil; }
- (id)setLocalTransform:(id)a0 forTime:(id)a1 { return nil; }
@end
@implementation MDLVertexAttribute (CharonPerClass90)
- (id)initWithName:(id)a0 format:(id)a1 offset:(id)a2 bufferIndex:(id)a3 { return nil; }
@end
@implementation MDLVertexBufferLayout (CharonPerClass90)
- (id)initWithStride:(id)a0 { return nil; }
@end
@implementation MDLVertexDescriptor (CharonPerClass90)
- (id)addOrReplaceAttribute:(id)a0 { return nil; }
- (id)attributeNamed:(id)a0 { return nil; }
- (id)initWithVertexDescriptor:(id)a0 { return nil; }
- (id)removeAttributeNamed:(id)a0 { return nil; }
- (id)reset { return nil; }
- (id)setPackedOffsets { return nil; }
- (id)setPackedStrides { return nil; }
@end
@implementation MDLVoxelArray (CharonPerClass90)
- (id)coarseMesh { return nil; }
- (id)coarseMeshUsingAllocator:(id)a0 { return nil; }
- (id)initWithAsset:(id)a0 divisions:(id)a1 interiorNBWidth:(id)a2 exteriorNBWidth:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)initWithAsset:(id)a0 divisions:(id)a1 interiorShells:(id)a2 exteriorShells:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)meshUsingAllocator:(id)a0 { return nil; }
- (id)setVoxelsForMesh:(id)a0 divisions:(id)a1 interiorNBWidth:(id)a2 exteriorNBWidth:(id)a3 patchRadius:(id)a4 { return nil; }
- (id)setVoxelsForMesh:(id)a0 divisions:(id)a1 interiorShells:(id)a2 exteriorShells:(id)a3 patchRadius:(id)a4 { return nil; }
@end
