static const char *const charon_expected[][3] = {
    {"interactions", "a fresh view holds no interactions", "- class=array"},
    {"interactions", "adding one tells it where it went", "will(view) did(view) "},
    {"interactions", "and the view lists it", "first"},
    {"interactions", "and the interaction knows its view", "the view"},
    {"interactions", "a second one goes after the first", "first,second"},
    {"interactions", "the list handed out is a copy", "a copy"},
    {"interactions", "adding to another view takes it off the first", "will(nil) did(nil) will(view) did(view) "},
    {"interactions", "the first view no longer lists it", "second"},
    {"interactions", "the other view does", "first"},
    {"interactions", "adding to the same view again", ""},
    {"interactions", "and it is listed once", "second"},
    {"interactions", "removing tells it that it left", "will(nil) did(nil) "},
    {"interactions", "and the view forgets it", "-"},
    {"interactions", "and it has no view", "none"},
    {"interactions", "removing what is not there says nothing", "silence"},
    {"interactions", "removing a stranger says nothing either", "silence"},
    {"interactions", "adding nil", "NSInternalInconsistencyException: Invalid parameter not satisfying: interaction != nil"},
    {"interactions", "removing nil", "NSInternalInconsistencyException: Invalid parameter not satisfying: interaction != nil"},
    {"interactions", "and the list after both", "-"},
    {"interactions", "a whole list can be set", "fourth,fifth"},
    {"interactions", "and each one was told", "will(view) did(view) | will(view) did(view) "},
    {"interactions", "setting a shorter list drops the rest", "fifth"},
    {"interactions", "and the dropped one was told it left", "will(nil) did(nil) "},
    {"interactions", "setting the list to nil", "NSInternalInconsistencyException: Invalid parameter not satisfying: interactions"},
    {"interactions", "and the list after that", "fifth"},
    {"interactions", "setting an empty list empties it", "-"},
    {"interactions", "a fresh view has no attributed label", "nil"},
    {"interactions", "the attributed label answers its own text", "Hello"},
    {"interactions", "and the plain label follows it", "Hello"},
    {"interactions", "and the attribute survives the round trip", "prompt"},
    {"interactions", "a plain label comes back attributed", "Plain"},
    {"interactions", "with nothing in its attributes", "0"},
    {"interactions", "the attributed one set last wins", "Second / Second"},
    {"interactions", "the plain one set last wins too", "Third / Third"},
    {"interactions", "setting nil clears both", "nil / nil"},
    {"interactions", "the hint and the value work the same way", "A hint / A hint / A value / A value"},
    {"interactions", "the stored string is a copy, not the caller's", "Before"},
    {"interactions", "a label's own text is not an attributed label", "nil"},
    {"systemspacing", "leading after trailing, multiplier 0.5", "constant 4 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "top below bottom, multiplier 0.5", "constant 4 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "leading after trailing, multiplier 1", "constant 8 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "top below bottom, multiplier 1", "constant 8 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "leading after trailing, multiplier 2", "constant 16 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "top below bottom, multiplier 2", "constant 16 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "leading after trailing, multiplier 3", "constant 24 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "top below bottom, multiplier 3", "constant 24 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "at least the system spacing", "constant 8 multiplier 1 relation 1 attributes 5 6 priority 1000"},
    {"systemspacing", "at most the system spacing", "constant 8 multiplier 1 relation -1 attributes 5 6 priority 1000"},
    {"systemspacing", "at least, below", "constant 8 multiplier 1 relation 1 attributes 3 4 priority 1000"},
    {"systemspacing", "at most, below", "constant 8 multiplier 1 relation -1 attributes 3 4 priority 1000"},
    {"systemspacing", "against the container's own edge", "constant 8 multiplier 1 relation 0 attributes 5 5 priority 1000"},
    {"systemspacing", "a multiplier of 0", "constant 0 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "a multiplier of 0, downwards", "constant 0 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "a multiplier of 0.25", "constant 2 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "a multiplier of 0.25, downwards", "constant 2 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "a multiplier of -0.5", "constant 0 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "a multiplier of -0.5, downwards", "constant 0 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"systemspacing", "a multiplier of -2", "constant 0 multiplier 1 relation 0 attributes 5 6 priority 1000"},
    {"systemspacing", "a multiplier of -2, downwards", "constant 0 multiplier 1 relation 0 attributes 3 4 priority 1000"},
    {"gesturename", "the name starts out empty", "(nil)"},
    {"gesturename", "a name that was set comes back", "tap"},
    {"gesturename", "the name is copied, not held", "first"},
    {"gesturename", "the copy is a different object", "a copy"},
    {"gesturename", "clearing the name works", "(nil)"},
    {"gesturename", "two recognizers keep their own names", "tap/pan"},
    {"batchupdates", "the rows the table ends up with", "4"},
    {"contentsize", "accessibility of UICTContentSizeCategoryXS", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryS", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryM", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryL", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryXL", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryXXL", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryXXXL", "no"},
    {"contentsize", "accessibility of UICTContentSizeCategoryAccessibilityM", "yes"},
    {"contentsize", "accessibility of UICTContentSizeCategoryAccessibilityL", "yes"},
    {"contentsize", "accessibility of UICTContentSizeCategoryAccessibilityXL", "yes"},
    {"contentsize", "accessibility of UICTContentSizeCategoryAccessibilityXXL", "yes"},
    {"contentsize", "accessibility of UICTContentSizeCategoryAccessibilityXXXL", "yes"},
    {"contentsize", "accessibility of _UICTContentSizeCategoryUnspecified", "no"},
    {"contentsize", "accessibility of an unknown string", "no"},
    {"contentsize", "accessibility of nil", "no"},
    {"contentsize", "every pair of categories", "0-1-1-1-1-1-1-1-1-1-1-1110-1-1-1-1-1-1-1-1-1-11110-1-1-1-1-1-1-1-1-111110-1-1-1-1-1-1-1-1111110-1-1-1-1-1-1-11111110-1-1-1-1-1-111111110-1-1-1-1-1111111110-1-1-1-11111111110-1-1-111111111110-1-1111111111110-111111111111101-1-1-1-1-1-1-1-1-1-1-1-10"},
    {"contentsize", "nil against a category", "-1"},
    {"contentsize", "an unknown string raises", "NSInternalInconsistencyException: UIContentSizeCategoryCompareToCategory cannot be used to order arbitrary strings, only UIContentSizeCategory objects (comparing nonsense to UICTContentSizeCategoryL)."},
    {"contentsize", "the large title style", "UICTFontTextStyleTitle0"},
};
static const unsigned charon_expected_count = 85;
