//
//  CharonMatterMTRDoorLockClusterSetUserParams.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRDoorLockClusterSetUserParams is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  it of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

@interface MTRDoorLockClusterSetUserParams () {
    NSNumber * _Nullable _charon_userUniqueId;
}
@end

@implementation MTRDoorLockClusterSetUserParams

@synthesize operationType = _operationType;
@synthesize userIndex = _userIndex;
@synthesize userName = _userName;
@synthesize userUniqueID = _userUniqueID;
@synthesize userStatus = _userStatus;
@synthesize userType = _userType;
@synthesize credentialRule = _credentialRule;
@synthesize timedInvokeTimeoutMs = _timedInvokeTimeoutMs;
@synthesize serverSideProcessingTimeout = _serverSideProcessingTimeout;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRDoorLockClusterSetUserParams *copied = [[MTRDoorLockClusterSetUserParams allocWithZone:zone] init];
    copied->_operationType = self->_operationType;
    copied->_userIndex = self->_userIndex;
    copied->_userName = self->_userName;
    copied->_userUniqueID = self->_userUniqueID;
    copied->_userStatus = self->_userStatus;
    copied->_userType = self->_userType;
    copied->_credentialRule = self->_credentialRule;
    copied->_timedInvokeTimeoutMs = self->_timedInvokeTimeoutMs;
    copied->_serverSideProcessingTimeout = self->_serverSideProcessingTimeout;
    copied->_charon_userUniqueId = self->_charon_userUniqueId;
    return copied;
}

// The properties the SDK declares in a CATEGORY of this class - MTRGroupsClusterAddGroupParams
// carries the old `groupId` beside the `groupID` of its own @interface, and 17 classes
// are shaped so. Their accessors are written out over the storage of the port's own above,
// because a category cannot hold an ivar and clang refuses @synthesize for one in either
// place: `property declared in category 'Deprecated' cannot be implemented in class
// implementation` and `@synthesize not allowed in a category's implementation`.
- (NSNumber * _Nullable)userUniqueId
{
    return _charon_userUniqueId;
}

- (void)setUserUniqueId:(NSNumber * _Nullable)userUniqueId
{
    _charon_userUniqueId = userUniqueId;
}

@end
