//
//  CharonMatterMTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


static NSString *charonDescribeObject(id value)
{
    return [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct

@synthesize energy = _energy;
@synthesize startTimestamp = _startTimestamp;
@synthesize endTimestamp = _endTimestamp;
@synthesize startSystime = _startSystime;
@synthesize endSystime = _endSystime;
@synthesize apparentEnergy = _apparentEnergy;
@synthesize reactiveEnergy = _reactiveEnergy;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct *copied = [[MTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct allocWithZone:zone] init];
    copied->_energy = self->_energy;
    copied->_startTimestamp = self->_startTimestamp;
    copied->_endTimestamp = self->_endTimestamp;
    copied->_startSystime = self->_startSystime;
    copied->_endSystime = self->_endSystime;
    copied->_apparentEnergy = self->_apparentEnergy;
    copied->_reactiveEnergy = self->_reactiveEnergy;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _energy = @0;
    return self;
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"energy:%@; ", charonDescribeObject(self->_energy)];
    [text appendFormat:@"startTimestamp:%@; ", charonDescribeObject(self->_startTimestamp)];
    [text appendFormat:@"endTimestamp:%@; ", charonDescribeObject(self->_endTimestamp)];
    [text appendFormat:@"startSystime:%@; ", charonDescribeObject(self->_startSystime)];
    [text appendFormat:@"endSystime:%@; ", charonDescribeObject(self->_endSystime)];
    [text appendFormat:@"apparentEnergy:%@; ", charonDescribeObject(self->_apparentEnergy)];
    [text appendFormat:@"reactiveEnergy:%@; ", charonDescribeObject(self->_reactiveEnergy)];
    [text appendString:@">"];
    return text;
}
@end
