//
//  CharonMatterMTRBaseClusterColorControl.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRBaseClusterColorControl is a MTRGenericBaseCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 57 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRBaseClusterColorControl () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRBaseClusterColorControl

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRBaseClusterColorControl class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRBaseDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRBaseDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    return self;
}

// CurrentHue, a NSNumber.
- (void)readAttributeCurrentHueWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CurrentHue"];
    completion(written, nil);
}

- (void)subscribeAttributeCurrentHueWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CurrentHue"] = @"subscribed";
}

// CurrentSaturation, a NSNumber.
- (void)readAttributeCurrentSaturationWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CurrentSaturation"];
    completion(written, nil);
}

- (void)subscribeAttributeCurrentSaturationWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CurrentSaturation"] = @"subscribed";
}

// RemainingTime, a NSNumber.
- (void)readAttributeRemainingTimeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"RemainingTime"];
    completion(written, nil);
}

- (void)subscribeAttributeRemainingTimeWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"RemainingTime"] = @"subscribed";
}

// CurrentX, a NSNumber.
- (void)readAttributeCurrentXWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CurrentX"];
    completion(written, nil);
}

- (void)subscribeAttributeCurrentXWithParams:(MTRSubscribeParams *)params
                     subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                               reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CurrentX"] = @"subscribed";
}

// CurrentY, a NSNumber.
- (void)readAttributeCurrentYWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CurrentY"];
    completion(written, nil);
}

- (void)subscribeAttributeCurrentYWithParams:(MTRSubscribeParams *)params
                     subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                               reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CurrentY"] = @"subscribed";
}

// DriftCompensation, a NSNumber.
- (void)readAttributeDriftCompensationWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"DriftCompensation"];
    completion(written, nil);
}

- (void)subscribeAttributeDriftCompensationWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"DriftCompensation"] = @"subscribed";
}

// CompensationText, a NSString.
- (void)readAttributeCompensationTextWithCompletion:(void (^)(NSString * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CompensationText"];
    completion(written, nil);
}

- (void)subscribeAttributeCompensationTextWithParams:(MTRSubscribeParams *)params
                             subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                       reportHandler:(void (^)(NSString * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CompensationText"] = @"subscribed";
}

// ColorTemperatureMireds, a NSNumber.
- (void)readAttributeColorTemperatureMiredsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorTemperatureMireds"];
    completion(written, nil);
}

- (void)subscribeAttributeColorTemperatureMiredsWithParams:(MTRSubscribeParams *)params
                                   subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                             reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorTemperatureMireds"] = @"subscribed";
}

// ColorMode, a NSNumber.
- (void)readAttributeColorModeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorMode"];
    completion(written, nil);
}

- (void)subscribeAttributeColorModeWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorMode"] = @"subscribed";
}

// Options, a NSNumber.
- (void)readAttributeOptionsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Options"];
    completion(written, nil);
}

- (void)writeAttributeOptionsWithValue:(NSNumber * _Nonnull)value completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterColorControl charon_port_values][@"Options"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)writeAttributeOptionsWithValue:(NSNumber * _Nonnull)value params:(MTRWriteParams * _Nullable)params completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterColorControl charon_port_values][@"Options"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)subscribeAttributeOptionsWithParams:(MTRSubscribeParams *)params
                    subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                              reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Options"] = @"subscribed";
}

// NumberOfPrimaries, a NSNumber.
- (void)readAttributeNumberOfPrimariesWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"NumberOfPrimaries"];
    completion(written, nil);
}

- (void)subscribeAttributeNumberOfPrimariesWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"NumberOfPrimaries"] = @"subscribed";
}

// Primary1X, a NSNumber.
- (void)readAttributePrimary1XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary1X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary1XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary1X"] = @"subscribed";
}

// Primary1Y, a NSNumber.
- (void)readAttributePrimary1YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary1Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary1YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary1Y"] = @"subscribed";
}

// Primary1Intensity, a NSNumber.
- (void)readAttributePrimary1IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary1Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary1IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary1Intensity"] = @"subscribed";
}

// Primary2X, a NSNumber.
- (void)readAttributePrimary2XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary2X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary2XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary2X"] = @"subscribed";
}

// Primary2Y, a NSNumber.
- (void)readAttributePrimary2YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary2Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary2YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary2Y"] = @"subscribed";
}

// Primary2Intensity, a NSNumber.
- (void)readAttributePrimary2IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary2Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary2IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary2Intensity"] = @"subscribed";
}

// Primary3X, a NSNumber.
- (void)readAttributePrimary3XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary3X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary3XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary3X"] = @"subscribed";
}

// Primary3Y, a NSNumber.
- (void)readAttributePrimary3YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary3Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary3YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary3Y"] = @"subscribed";
}

// Primary3Intensity, a NSNumber.
- (void)readAttributePrimary3IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary3Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary3IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary3Intensity"] = @"subscribed";
}

// Primary4X, a NSNumber.
- (void)readAttributePrimary4XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary4X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary4XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary4X"] = @"subscribed";
}

// Primary4Y, a NSNumber.
- (void)readAttributePrimary4YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary4Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary4YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary4Y"] = @"subscribed";
}

// Primary4Intensity, a NSNumber.
- (void)readAttributePrimary4IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary4Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary4IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary4Intensity"] = @"subscribed";
}

// Primary5X, a NSNumber.
- (void)readAttributePrimary5XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary5X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary5XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary5X"] = @"subscribed";
}

// Primary5Y, a NSNumber.
- (void)readAttributePrimary5YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary5Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary5YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary5Y"] = @"subscribed";
}

// Primary5Intensity, a NSNumber.
- (void)readAttributePrimary5IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary5Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary5IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary5Intensity"] = @"subscribed";
}

// Primary6X, a NSNumber.
- (void)readAttributePrimary6XWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary6X"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary6XWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary6X"] = @"subscribed";
}

// Primary6Y, a NSNumber.
- (void)readAttributePrimary6YWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary6Y"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary6YWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary6Y"] = @"subscribed";
}

// Primary6Intensity, a NSNumber.
- (void)readAttributePrimary6IntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"Primary6Intensity"];
    completion(written, nil);
}

- (void)subscribeAttributePrimary6IntensityWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"Primary6Intensity"] = @"subscribed";
}

// WhitePointX, a NSNumber.
- (void)readAttributeWhitePointXWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"WhitePointX"];
    completion(written, nil);
}

- (void)subscribeAttributeWhitePointXWithParams:(MTRSubscribeParams *)params
                        subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                  reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"WhitePointX"] = @"subscribed";
}

// WhitePointY, a NSNumber.
- (void)readAttributeWhitePointYWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"WhitePointY"];
    completion(written, nil);
}

- (void)subscribeAttributeWhitePointYWithParams:(MTRSubscribeParams *)params
                        subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                  reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"WhitePointY"] = @"subscribed";
}

// ColorPointRX, a NSNumber.
- (void)readAttributeColorPointRXWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointRX"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointRXWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointRX"] = @"subscribed";
}

// ColorPointRY, a NSNumber.
- (void)readAttributeColorPointRYWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointRY"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointRYWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointRY"] = @"subscribed";
}

// ColorPointRIntensity, a NSNumber.
- (void)readAttributeColorPointRIntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointRIntensity"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointRIntensityWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointRIntensity"] = @"subscribed";
}

// ColorPointGX, a NSNumber.
- (void)readAttributeColorPointGXWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointGX"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointGXWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointGX"] = @"subscribed";
}

// ColorPointGY, a NSNumber.
- (void)readAttributeColorPointGYWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointGY"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointGYWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointGY"] = @"subscribed";
}

// ColorPointGIntensity, a NSNumber.
- (void)readAttributeColorPointGIntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointGIntensity"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointGIntensityWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointGIntensity"] = @"subscribed";
}

// ColorPointBX, a NSNumber.
- (void)readAttributeColorPointBXWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointBX"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointBXWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointBX"] = @"subscribed";
}

// ColorPointBY, a NSNumber.
- (void)readAttributeColorPointBYWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointBY"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointBYWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointBY"] = @"subscribed";
}

// ColorPointBIntensity, a NSNumber.
- (void)readAttributeColorPointBIntensityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorPointBIntensity"];
    completion(written, nil);
}

- (void)subscribeAttributeColorPointBIntensityWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorPointBIntensity"] = @"subscribed";
}

// EnhancedCurrentHue, a NSNumber.
- (void)readAttributeEnhancedCurrentHueWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"EnhancedCurrentHue"];
    completion(written, nil);
}

- (void)subscribeAttributeEnhancedCurrentHueWithParams:(MTRSubscribeParams *)params
                               subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                         reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"EnhancedCurrentHue"] = @"subscribed";
}

// EnhancedColorMode, a NSNumber.
- (void)readAttributeEnhancedColorModeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"EnhancedColorMode"];
    completion(written, nil);
}

- (void)subscribeAttributeEnhancedColorModeWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"EnhancedColorMode"] = @"subscribed";
}

// ColorLoopActive, a NSNumber.
- (void)readAttributeColorLoopActiveWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorLoopActive"];
    completion(written, nil);
}

- (void)subscribeAttributeColorLoopActiveWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorLoopActive"] = @"subscribed";
}

// ColorLoopDirection, a NSNumber.
- (void)readAttributeColorLoopDirectionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorLoopDirection"];
    completion(written, nil);
}

- (void)subscribeAttributeColorLoopDirectionWithParams:(MTRSubscribeParams *)params
                               subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                         reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorLoopDirection"] = @"subscribed";
}

// ColorLoopTime, a NSNumber.
- (void)readAttributeColorLoopTimeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorLoopTime"];
    completion(written, nil);
}

- (void)subscribeAttributeColorLoopTimeWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorLoopTime"] = @"subscribed";
}

// ColorLoopStartEnhancedHue, a NSNumber.
- (void)readAttributeColorLoopStartEnhancedHueWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorLoopStartEnhancedHue"];
    completion(written, nil);
}

- (void)subscribeAttributeColorLoopStartEnhancedHueWithParams:(MTRSubscribeParams *)params
                                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorLoopStartEnhancedHue"] = @"subscribed";
}

// ColorLoopStoredEnhancedHue, a NSNumber.
- (void)readAttributeColorLoopStoredEnhancedHueWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorLoopStoredEnhancedHue"];
    completion(written, nil);
}

- (void)subscribeAttributeColorLoopStoredEnhancedHueWithParams:(MTRSubscribeParams *)params
                                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorLoopStoredEnhancedHue"] = @"subscribed";
}

// ColorCapabilities, a NSNumber.
- (void)readAttributeColorCapabilitiesWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorCapabilities"];
    completion(written, nil);
}

- (void)subscribeAttributeColorCapabilitiesWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorCapabilities"] = @"subscribed";
}

// ColorTempPhysicalMinMireds, a NSNumber.
- (void)readAttributeColorTempPhysicalMinMiredsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorTempPhysicalMinMireds"];
    completion(written, nil);
}

- (void)subscribeAttributeColorTempPhysicalMinMiredsWithParams:(MTRSubscribeParams *)params
                                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorTempPhysicalMinMireds"] = @"subscribed";
}

// ColorTempPhysicalMaxMireds, a NSNumber.
- (void)readAttributeColorTempPhysicalMaxMiredsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ColorTempPhysicalMaxMireds"];
    completion(written, nil);
}

- (void)subscribeAttributeColorTempPhysicalMaxMiredsWithParams:(MTRSubscribeParams *)params
                                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ColorTempPhysicalMaxMireds"] = @"subscribed";
}

// CoupleColorTempToLevelMinMireds, a NSNumber.
- (void)readAttributeCoupleColorTempToLevelMinMiredsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"CoupleColorTempToLevelMinMireds"];
    completion(written, nil);
}

- (void)subscribeAttributeCoupleColorTempToLevelMinMiredsWithParams:(MTRSubscribeParams *)params
                                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"CoupleColorTempToLevelMinMireds"] = @"subscribed";
}

// StartUpColorTemperatureMireds, a NSNumber.
- (void)readAttributeStartUpColorTemperatureMiredsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"StartUpColorTemperatureMireds"];
    completion(written, nil);
}

- (void)writeAttributeStartUpColorTemperatureMiredsWithValue:(NSNumber * _Nullable)value completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterColorControl charon_port_values][@"StartUpColorTemperatureMireds"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)writeAttributeStartUpColorTemperatureMiredsWithValue:(NSNumber * _Nullable)value params:(MTRWriteParams * _Nullable)params completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterColorControl charon_port_values][@"StartUpColorTemperatureMireds"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)subscribeAttributeStartUpColorTemperatureMiredsWithParams:(MTRSubscribeParams *)params
                                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                    reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"StartUpColorTemperatureMireds"] = @"subscribed";
}

// GeneratedCommandList, a NSArray.
- (void)readAttributeGeneratedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"GeneratedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeGeneratedCommandListWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"GeneratedCommandList"] = @"subscribed";
}

// AcceptedCommandList, a NSArray.
- (void)readAttributeAcceptedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"AcceptedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeAcceptedCommandListWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"AcceptedCommandList"] = @"subscribed";
}

// AttributeList, a NSArray.
- (void)readAttributeAttributeListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"AttributeList"];
    completion(written, nil);
}

- (void)subscribeAttributeAttributeListWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"AttributeList"] = @"subscribed";
}

// FeatureMap, a NSNumber.
- (void)readAttributeFeatureMapWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"FeatureMap"];
    completion(written, nil);
}

- (void)subscribeAttributeFeatureMapWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"FeatureMap"] = @"subscribed";
}

// ClusterRevision, a NSNumber.
- (void)readAttributeClusterRevisionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterColorControl charon_port_values][@"ClusterRevision"];
    completion(written, nil);
}

- (void)subscribeAttributeClusterRevisionWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterColorControl charon_port_values][@"ClusterRevision"] = @"subscribed";
}

// The cached read of CurrentHue: no value and the error, because there is no node.
+ (void)readAttributeCurrentHueWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of CurrentSaturation: no value and the error, because there is no node.
+ (void)readAttributeCurrentSaturationWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of RemainingTime: no value and the error, because there is no node.
+ (void)readAttributeRemainingTimeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of CurrentX: no value and the error, because there is no node.
+ (void)readAttributeCurrentXWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of CurrentY: no value and the error, because there is no node.
+ (void)readAttributeCurrentYWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of DriftCompensation: no value and the error, because there is no node.
+ (void)readAttributeDriftCompensationWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of CompensationText: no value and the error, because there is no node.
+ (void)readAttributeCompensationTextWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSString * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorTemperatureMireds: no value and the error, because there is no node.
+ (void)readAttributeColorTemperatureMiredsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorMode: no value and the error, because there is no node.
+ (void)readAttributeColorModeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Options: no value and the error, because there is no node.
+ (void)readAttributeOptionsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of NumberOfPrimaries: no value and the error, because there is no node.
+ (void)readAttributeNumberOfPrimariesWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary1X: no value and the error, because there is no node.
+ (void)readAttributePrimary1XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary1Y: no value and the error, because there is no node.
+ (void)readAttributePrimary1YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary1Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary1IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary2X: no value and the error, because there is no node.
+ (void)readAttributePrimary2XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary2Y: no value and the error, because there is no node.
+ (void)readAttributePrimary2YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary2Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary2IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary3X: no value and the error, because there is no node.
+ (void)readAttributePrimary3XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary3Y: no value and the error, because there is no node.
+ (void)readAttributePrimary3YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary3Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary3IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary4X: no value and the error, because there is no node.
+ (void)readAttributePrimary4XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary4Y: no value and the error, because there is no node.
+ (void)readAttributePrimary4YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary4Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary4IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary5X: no value and the error, because there is no node.
+ (void)readAttributePrimary5XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary5Y: no value and the error, because there is no node.
+ (void)readAttributePrimary5YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary5Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary5IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary6X: no value and the error, because there is no node.
+ (void)readAttributePrimary6XWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary6Y: no value and the error, because there is no node.
+ (void)readAttributePrimary6YWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of Primary6Intensity: no value and the error, because there is no node.
+ (void)readAttributePrimary6IntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of WhitePointX: no value and the error, because there is no node.
+ (void)readAttributeWhitePointXWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of WhitePointY: no value and the error, because there is no node.
+ (void)readAttributeWhitePointYWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointRX: no value and the error, because there is no node.
+ (void)readAttributeColorPointRXWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointRY: no value and the error, because there is no node.
+ (void)readAttributeColorPointRYWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointRIntensity: no value and the error, because there is no node.
+ (void)readAttributeColorPointRIntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointGX: no value and the error, because there is no node.
+ (void)readAttributeColorPointGXWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointGY: no value and the error, because there is no node.
+ (void)readAttributeColorPointGYWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointGIntensity: no value and the error, because there is no node.
+ (void)readAttributeColorPointGIntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointBX: no value and the error, because there is no node.
+ (void)readAttributeColorPointBXWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointBY: no value and the error, because there is no node.
+ (void)readAttributeColorPointBYWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorPointBIntensity: no value and the error, because there is no node.
+ (void)readAttributeColorPointBIntensityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of EnhancedCurrentHue: no value and the error, because there is no node.
+ (void)readAttributeEnhancedCurrentHueWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of EnhancedColorMode: no value and the error, because there is no node.
+ (void)readAttributeEnhancedColorModeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorLoopActive: no value and the error, because there is no node.
+ (void)readAttributeColorLoopActiveWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorLoopDirection: no value and the error, because there is no node.
+ (void)readAttributeColorLoopDirectionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorLoopTime: no value and the error, because there is no node.
+ (void)readAttributeColorLoopTimeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorLoopStartEnhancedHue: no value and the error, because there is no node.
+ (void)readAttributeColorLoopStartEnhancedHueWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorLoopStoredEnhancedHue: no value and the error, because there is no node.
+ (void)readAttributeColorLoopStoredEnhancedHueWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorCapabilities: no value and the error, because there is no node.
+ (void)readAttributeColorCapabilitiesWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorTempPhysicalMinMireds: no value and the error, because there is no node.
+ (void)readAttributeColorTempPhysicalMinMiredsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ColorTempPhysicalMaxMireds: no value and the error, because there is no node.
+ (void)readAttributeColorTempPhysicalMaxMiredsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of CoupleColorTempToLevelMinMireds: no value and the error, because there is no node.
+ (void)readAttributeCoupleColorTempToLevelMinMiredsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of StartUpColorTemperatureMireds: no value and the error, because there is no node.
+ (void)readAttributeStartUpColorTemperatureMiredsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of GeneratedCommandList: no value and the error, because there is no node.
+ (void)readAttributeGeneratedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of AcceptedCommandList: no value and the error, because there is no node.
+ (void)readAttributeAcceptedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of AttributeList: no value and the error, because there is no node.
+ (void)readAttributeAttributeListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of FeatureMap: no value and the error, because there is no node.
+ (void)readAttributeFeatureMapWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// The cached read of ClusterRevision: no value and the error, because there is no node.
+ (void)readAttributeClusterRevisionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterColorControl charon_port_no_node_error]);
}

// moveToHue. It answers: there is nothing to reach on a release with no fabric.
- (void)moveToHueWithParams:(MTRColorControlClusterMoveToHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveHue. It answers: there is nothing to reach on a release with no fabric.
- (void)moveHueWithParams:(MTRColorControlClusterMoveHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// stepHue. It answers: there is nothing to reach on a release with no fabric.
- (void)stepHueWithParams:(MTRColorControlClusterStepHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveToSaturation. It answers: there is nothing to reach on a release with no fabric.
- (void)moveToSaturationWithParams:(MTRColorControlClusterMoveToSaturationParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveSaturation. It answers: there is nothing to reach on a release with no fabric.
- (void)moveSaturationWithParams:(MTRColorControlClusterMoveSaturationParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// stepSaturation. It answers: there is nothing to reach on a release with no fabric.
- (void)stepSaturationWithParams:(MTRColorControlClusterStepSaturationParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveToHueAndSaturation. It answers: there is nothing to reach on a release with no fabric.
- (void)moveToHueAndSaturationWithParams:(MTRColorControlClusterMoveToHueAndSaturationParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveToColor. It answers: there is nothing to reach on a release with no fabric.
- (void)moveToColorWithParams:(MTRColorControlClusterMoveToColorParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveColor. It answers: there is nothing to reach on a release with no fabric.
- (void)moveColorWithParams:(MTRColorControlClusterMoveColorParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// stepColor. It answers: there is nothing to reach on a release with no fabric.
- (void)stepColorWithParams:(MTRColorControlClusterStepColorParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveToColorTemperature. It answers: there is nothing to reach on a release with no fabric.
- (void)moveToColorTemperatureWithParams:(MTRColorControlClusterMoveToColorTemperatureParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// enhancedMoveToHue. It answers: there is nothing to reach on a release with no fabric.
- (void)enhancedMoveToHueWithParams:(MTRColorControlClusterEnhancedMoveToHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// enhancedMoveHue. It answers: there is nothing to reach on a release with no fabric.
- (void)enhancedMoveHueWithParams:(MTRColorControlClusterEnhancedMoveHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// enhancedStepHue. It answers: there is nothing to reach on a release with no fabric.
- (void)enhancedStepHueWithParams:(MTRColorControlClusterEnhancedStepHueParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// enhancedMoveToHueAndSaturation. It answers: there is nothing to reach on a release with no fabric.
- (void)enhancedMoveToHueAndSaturationWithParams:(MTRColorControlClusterEnhancedMoveToHueAndSaturationParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// colorLoopSet. It answers: there is nothing to reach on a release with no fabric.
- (void)colorLoopSetWithParams:(MTRColorControlClusterColorLoopSetParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// stopMoveStep. It answers: there is nothing to reach on a release with no fabric.
- (void)stopMoveStepWithParams:(MTRColorControlClusterStopMoveStepParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// moveColorTemperature. It answers: there is nothing to reach on a release with no fabric.
- (void)moveColorTemperatureWithParams:(MTRColorControlClusterMoveColorTemperatureParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// stepColorTemperature. It answers: there is nothing to reach on a release with no fabric.
- (void)stepColorTemperatureWithParams:(MTRColorControlClusterStepColorTemperatureParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

@end
