//
//  CharonMatterMTRCommissionerControlClusterCommissioningRequestResultEvent.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRCommissionerControlClusterCommissioningRequestResultEvent is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

@implementation MTRCommissionerControlClusterCommissioningRequestResultEvent

@synthesize requestID = _requestID;
@synthesize clientNodeID = _clientNodeID;
@synthesize statusCode = _statusCode;
@synthesize fabricIndex = _fabricIndex;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRCommissionerControlClusterCommissioningRequestResultEvent *copied = [[MTRCommissionerControlClusterCommissioningRequestResultEvent allocWithZone:zone] init];
    copied->_requestID = self->_requestID;
    copied->_clientNodeID = self->_clientNodeID;
    copied->_statusCode = self->_statusCode;
    copied->_fabricIndex = self->_fabricIndex;
    return copied;
}

@end
