//
//  CharonMatterMTRBaseClusterPowerTopology.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRBaseClusterPowerTopology is a MTRGenericBaseCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 8 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRBaseClusterPowerTopology () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRBaseClusterPowerTopology

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRBaseClusterPowerTopology class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRBaseDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRBaseDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    return self;
}

// AvailableEndpoints, a NSArray.
- (void)readAttributeAvailableEndpointsWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"AvailableEndpoints"];
    completion(written, nil);
}

- (void)subscribeAttributeAvailableEndpointsWithParams:(MTRSubscribeParams *)params
                               subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                         reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"AvailableEndpoints"] = @"subscribed";
}

// ActiveEndpoints, a NSArray.
- (void)readAttributeActiveEndpointsWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"ActiveEndpoints"];
    completion(written, nil);
}

- (void)subscribeAttributeActiveEndpointsWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"ActiveEndpoints"] = @"subscribed";
}

// ElectricalCircuitNodes, a NSArray.
- (void)readAttributeElectricalCircuitNodesWithParams:(MTRReadParams * _Nullable)params completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)params;
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"ElectricalCircuitNodes"];
    completion(written, nil);
}

- (void)writeAttributeElectricalCircuitNodesWithValue:(NSArray * _Nonnull)value completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterPowerTopology charon_port_values][@"ElectricalCircuitNodes"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)writeAttributeElectricalCircuitNodesWithValue:(NSArray * _Nonnull)value params:(MTRWriteParams * _Nullable)params completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterPowerTopology charon_port_values][@"ElectricalCircuitNodes"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)subscribeAttributeElectricalCircuitNodesWithParams:(MTRSubscribeParams *)params
                                   subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                             reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"ElectricalCircuitNodes"] = @"subscribed";
}

// GeneratedCommandList, a NSArray.
- (void)readAttributeGeneratedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"GeneratedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeGeneratedCommandListWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"GeneratedCommandList"] = @"subscribed";
}

// AcceptedCommandList, a NSArray.
- (void)readAttributeAcceptedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"AcceptedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeAcceptedCommandListWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"AcceptedCommandList"] = @"subscribed";
}

// AttributeList, a NSArray.
- (void)readAttributeAttributeListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"AttributeList"];
    completion(written, nil);
}

- (void)subscribeAttributeAttributeListWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"AttributeList"] = @"subscribed";
}

// FeatureMap, a NSNumber.
- (void)readAttributeFeatureMapWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"FeatureMap"];
    completion(written, nil);
}

- (void)subscribeAttributeFeatureMapWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"FeatureMap"] = @"subscribed";
}

// ClusterRevision, a NSNumber.
- (void)readAttributeClusterRevisionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterPowerTopology charon_port_values][@"ClusterRevision"];
    completion(written, nil);
}

- (void)subscribeAttributeClusterRevisionWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterPowerTopology charon_port_values][@"ClusterRevision"] = @"subscribed";
}

// The cached read of AvailableEndpoints: no value and the error, because there is no node.
+ (void)readAttributeAvailableEndpointsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of ActiveEndpoints: no value and the error, because there is no node.
+ (void)readAttributeActiveEndpointsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of ElectricalCircuitNodes: no value and the error, because there is no node.
+ (void)readAttributeElectricalCircuitNodesWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of GeneratedCommandList: no value and the error, because there is no node.
+ (void)readAttributeGeneratedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of AcceptedCommandList: no value and the error, because there is no node.
+ (void)readAttributeAcceptedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of AttributeList: no value and the error, because there is no node.
+ (void)readAttributeAttributeListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of FeatureMap: no value and the error, because there is no node.
+ (void)readAttributeFeatureMapWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

// The cached read of ClusterRevision: no value and the error, because there is no node.
+ (void)readAttributeClusterRevisionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterPowerTopology charon_port_no_node_error]);
}

@end
