//
//  CharonMatterMTRBridgedDeviceBasicClusterLeaveEvent.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers and from the framework's own
//  source at the tag this repository pins, the same way the cluster objects beside it are.
//
//  MTRBridgedDeviceBasicClusterLeaveEvent is the DEPRECATED SPELLING of MTRBridgedDeviceBasicInformationClusterLeaveEvent, which its own header says in so many words:
//      MTR_DEPRECATED("Please use MTRBridgedDeviceBasicInformationClusterLeaveEvent", ios(...), ...)
//
//  The framework's own @implementation for a class shaped this way is `@dynamic` and nothing else - one
//  member per line, no ivar, no accessor, no -init, no -copyWithZone: and no -description - so every member
//  lives in MTRBridgedDeviceBasicInformationClusterLeaveEvent's storage and ONE storage serves the pair. Writing an ivar of its own would give the two
//  names two storages over one set of members, and
//  tests/backports/host/matter/params-diff.sh is what measures the difference: it writes a member through
//  this class and reads it back through MTRBridgedDeviceBasicInformationClusterLeaveEvent, and reads the shape the runtime reports for the class.
//
//  Nothing in it reaches a fabric.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

@implementation MTRBridgedDeviceBasicClusterLeaveEvent

@end
