//
//  CharonMatterMTRDeviceEnergyManagementClusterSlotStruct.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRDeviceEnergyManagementClusterSlotStruct is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

@implementation MTRDeviceEnergyManagementClusterSlotStruct

@synthesize minDuration = _minDuration;
@synthesize maxDuration = _maxDuration;
@synthesize defaultDuration = _defaultDuration;
@synthesize elapsedSlotTime = _elapsedSlotTime;
@synthesize remainingSlotTime = _remainingSlotTime;
@synthesize slotIsPausable = _slotIsPausable;
@synthesize minPauseDuration = _minPauseDuration;
@synthesize maxPauseDuration = _maxPauseDuration;
@synthesize manufacturerESAState = _manufacturerESAState;
@synthesize nominalPower = _nominalPower;
@synthesize minPower = _minPower;
@synthesize maxPower = _maxPower;
@synthesize nominalEnergy = _nominalEnergy;
@synthesize costs = _costs;
@synthesize minPowerAdjustment = _minPowerAdjustment;
@synthesize maxPowerAdjustment = _maxPowerAdjustment;
@synthesize minDurationAdjustment = _minDurationAdjustment;
@synthesize maxDurationAdjustment = _maxDurationAdjustment;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRDeviceEnergyManagementClusterSlotStruct *copied = [[MTRDeviceEnergyManagementClusterSlotStruct allocWithZone:zone] init];
    copied->_minDuration = self->_minDuration;
    copied->_maxDuration = self->_maxDuration;
    copied->_defaultDuration = self->_defaultDuration;
    copied->_elapsedSlotTime = self->_elapsedSlotTime;
    copied->_remainingSlotTime = self->_remainingSlotTime;
    copied->_slotIsPausable = self->_slotIsPausable;
    copied->_minPauseDuration = self->_minPauseDuration;
    copied->_maxPauseDuration = self->_maxPauseDuration;
    copied->_manufacturerESAState = self->_manufacturerESAState;
    copied->_nominalPower = self->_nominalPower;
    copied->_minPower = self->_minPower;
    copied->_maxPower = self->_maxPower;
    copied->_nominalEnergy = self->_nominalEnergy;
    copied->_costs = self->_costs;
    copied->_minPowerAdjustment = self->_minPowerAdjustment;
    copied->_maxPowerAdjustment = self->_maxPowerAdjustment;
    copied->_minDurationAdjustment = self->_minDurationAdjustment;
    copied->_maxDurationAdjustment = self->_maxDurationAdjustment;
    return copied;
}

@end
