//
//  CharonMatterMTRThreadNetworkDiagnosticsClusterNeighborTableStruct.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRThreadNetworkDiagnosticsClusterNeighborTableStruct is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


// What -description prints for one member: %@ for an object pointer, and the member's own type's text for
// anything else. The host's own string is the oracle; see tests/backports/host/matter/params-probe.m.
static NSString *charonDescribeObject(id value)
{
    // Deliberately NOT a nil check: `[nil description]` is nil, and %@ prints a nil argument as `(null)`,
    // which is what the host prints for a nil member - `subjects:(null)` in the measured
    // MTRAccessControlClusterAccessControlEntryStruct string. A `(nil)` here was the port's own spelling and
    // it differed from the host's on every nil member.
    return [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRThreadNetworkDiagnosticsClusterNeighborTableStruct

@synthesize extAddress = _extAddress;
@synthesize age = _age;
@synthesize rloc16 = _rloc16;
@synthesize linkFrameCounter = _linkFrameCounter;
@synthesize mleFrameCounter = _mleFrameCounter;
@synthesize lqi = _lqi;
@synthesize averageRssi = _averageRssi;
@synthesize lastRssi = _lastRssi;
@synthesize frameErrorRate = _frameErrorRate;
@synthesize messageErrorRate = _messageErrorRate;
@synthesize rxOnWhenIdle = _rxOnWhenIdle;
@synthesize fullThreadDevice = _fullThreadDevice;
@synthesize fullNetworkData = _fullNetworkData;
@synthesize isChild = _isChild;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRThreadNetworkDiagnosticsClusterNeighborTableStruct *copied = [[MTRThreadNetworkDiagnosticsClusterNeighborTableStruct allocWithZone:zone] init];
    copied->_extAddress = self->_extAddress;
    copied->_age = self->_age;
    copied->_rloc16 = self->_rloc16;
    copied->_linkFrameCounter = self->_linkFrameCounter;
    copied->_mleFrameCounter = self->_mleFrameCounter;
    copied->_lqi = self->_lqi;
    copied->_averageRssi = self->_averageRssi;
    copied->_lastRssi = self->_lastRssi;
    copied->_frameErrorRate = self->_frameErrorRate;
    copied->_messageErrorRate = self->_messageErrorRate;
    copied->_rxOnWhenIdle = self->_rxOnWhenIdle;
    copied->_fullThreadDevice = self->_fullThreadDevice;
    copied->_fullNetworkData = self->_fullNetworkData;
    copied->_isChild = self->_isChild;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _extAddress = @0;
    _age = @0;
    _rloc16 = @0;
    _linkFrameCounter = @0;
    _mleFrameCounter = @0;
    _lqi = @0;
    _frameErrorRate = @0;
    _messageErrorRate = @0;
    _rxOnWhenIdle = @0;
    _fullThreadDevice = @0;
    _fullNetworkData = @0;
    _isChild = @0;
    return self;
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"extAddress:%@; ", charonDescribeObject(self.extAddress)];
    [text appendFormat:@"age:%@; ", charonDescribeObject(self.age)];
    [text appendFormat:@"rloc16:%@; ", charonDescribeObject(self.rloc16)];
    [text appendFormat:@"linkFrameCounter:%@; ", charonDescribeObject(self.linkFrameCounter)];
    [text appendFormat:@"mleFrameCounter:%@; ", charonDescribeObject(self.mleFrameCounter)];
    [text appendFormat:@"lqi:%@; ", charonDescribeObject(self.lqi)];
    [text appendFormat:@"averageRssi:%@; ", charonDescribeObject(self.averageRssi)];
    [text appendFormat:@"lastRssi:%@; ", charonDescribeObject(self.lastRssi)];
    [text appendFormat:@"frameErrorRate:%@; ", charonDescribeObject(self.frameErrorRate)];
    [text appendFormat:@"messageErrorRate:%@; ", charonDescribeObject(self.messageErrorRate)];
    [text appendFormat:@"rxOnWhenIdle:%@; ", charonDescribeObject(self.rxOnWhenIdle)];
    [text appendFormat:@"fullThreadDevice:%@; ", charonDescribeObject(self.fullThreadDevice)];
    [text appendFormat:@"fullNetworkData:%@; ", charonDescribeObject(self.fullNetworkData)];
    [text appendFormat:@"isChild:%@; ", charonDescribeObject(self.isChild)];
    [text appendString:@">"];
    return text;
}
@end
