//
//  CharonMatterMTRCameraAVStreamManagementClusterCaptureSnapshotResponseParams.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRCameraAVStreamManagementClusterCaptureSnapshotResponseParams is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


static NSString *charonDescribeObject(id value)
{
    return [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRCameraAVStreamManagementClusterCaptureSnapshotResponseParams

@synthesize data = _data;
@synthesize imageCodec = _imageCodec;
@synthesize resolution = _resolution;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRCameraAVStreamManagementClusterCaptureSnapshotResponseParams *copied = [[MTRCameraAVStreamManagementClusterCaptureSnapshotResponseParams allocWithZone:zone] init];
    copied->_data = self->_data;
    copied->_imageCodec = self->_imageCodec;
    copied->_resolution = self->_resolution;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _data = [NSData data];
    _imageCodec = @0;
    return self;
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"data:%@; ", charonDescribeObject(self->_data)];
    [text appendFormat:@"imageCodec:%@; ", charonDescribeObject(self->_imageCodec)];
    [text appendFormat:@"resolution:%@; ", charonDescribeObject(self->_resolution)];
    [text appendString:@">"];
    return text;
}
@end
