//
//  CharonMatterMTRUnitTestingClusterTestComplexNullableOptionalResponseParams.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRUnitTestingClusterTestComplexNullableOptionalResponseParams is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  it of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


// What -description prints for one member: %@ for an object pointer, and the member's own type's text for
// anything else. The host's own string is the oracle; see tests/backports/host/matter/params-probe.m.
static NSString *charonDescribeObject(id value)
{
    return value == nil ? @"(nil)" : [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRUnitTestingClusterTestComplexNullableOptionalResponseParams

@synthesize nullableIntWasNull = _nullableIntWasNull;
@synthesize nullableIntValue = _nullableIntValue;
@synthesize optionalIntWasPresent = _optionalIntWasPresent;
@synthesize optionalIntValue = _optionalIntValue;
@synthesize nullableOptionalIntWasPresent = _nullableOptionalIntWasPresent;
@synthesize nullableOptionalIntWasNull = _nullableOptionalIntWasNull;
@synthesize nullableOptionalIntValue = _nullableOptionalIntValue;
@synthesize nullableStringWasNull = _nullableStringWasNull;
@synthesize nullableStringValue = _nullableStringValue;
@synthesize optionalStringWasPresent = _optionalStringWasPresent;
@synthesize optionalStringValue = _optionalStringValue;
@synthesize nullableOptionalStringWasPresent = _nullableOptionalStringWasPresent;
@synthesize nullableOptionalStringWasNull = _nullableOptionalStringWasNull;
@synthesize nullableOptionalStringValue = _nullableOptionalStringValue;
@synthesize nullableStructWasNull = _nullableStructWasNull;
@synthesize nullableStructValue = _nullableStructValue;
@synthesize optionalStructWasPresent = _optionalStructWasPresent;
@synthesize optionalStructValue = _optionalStructValue;
@synthesize nullableOptionalStructWasPresent = _nullableOptionalStructWasPresent;
@synthesize nullableOptionalStructWasNull = _nullableOptionalStructWasNull;
@synthesize nullableOptionalStructValue = _nullableOptionalStructValue;
@synthesize nullableListWasNull = _nullableListWasNull;
@synthesize nullableListValue = _nullableListValue;
@synthesize optionalListWasPresent = _optionalListWasPresent;
@synthesize optionalListValue = _optionalListValue;
@synthesize nullableOptionalListWasPresent = _nullableOptionalListWasPresent;
@synthesize nullableOptionalListWasNull = _nullableOptionalListWasNull;
@synthesize nullableOptionalListValue = _nullableOptionalListValue;
@synthesize timedInvokeTimeoutMs = _timedInvokeTimeoutMs;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRUnitTestingClusterTestComplexNullableOptionalResponseParams *copied = [[MTRUnitTestingClusterTestComplexNullableOptionalResponseParams allocWithZone:zone] init];
    copied->_nullableIntWasNull = self->_nullableIntWasNull;
    copied->_nullableIntValue = self->_nullableIntValue;
    copied->_optionalIntWasPresent = self->_optionalIntWasPresent;
    copied->_optionalIntValue = self->_optionalIntValue;
    copied->_nullableOptionalIntWasPresent = self->_nullableOptionalIntWasPresent;
    copied->_nullableOptionalIntWasNull = self->_nullableOptionalIntWasNull;
    copied->_nullableOptionalIntValue = self->_nullableOptionalIntValue;
    copied->_nullableStringWasNull = self->_nullableStringWasNull;
    copied->_nullableStringValue = self->_nullableStringValue;
    copied->_optionalStringWasPresent = self->_optionalStringWasPresent;
    copied->_optionalStringValue = self->_optionalStringValue;
    copied->_nullableOptionalStringWasPresent = self->_nullableOptionalStringWasPresent;
    copied->_nullableOptionalStringWasNull = self->_nullableOptionalStringWasNull;
    copied->_nullableOptionalStringValue = self->_nullableOptionalStringValue;
    copied->_nullableStructWasNull = self->_nullableStructWasNull;
    copied->_nullableStructValue = self->_nullableStructValue;
    copied->_optionalStructWasPresent = self->_optionalStructWasPresent;
    copied->_optionalStructValue = self->_optionalStructValue;
    copied->_nullableOptionalStructWasPresent = self->_nullableOptionalStructWasPresent;
    copied->_nullableOptionalStructWasNull = self->_nullableOptionalStructWasNull;
    copied->_nullableOptionalStructValue = self->_nullableOptionalStructValue;
    copied->_nullableListWasNull = self->_nullableListWasNull;
    copied->_nullableListValue = self->_nullableListValue;
    copied->_optionalListWasPresent = self->_optionalListWasPresent;
    copied->_optionalListValue = self->_optionalListValue;
    copied->_nullableOptionalListWasPresent = self->_nullableOptionalListWasPresent;
    copied->_nullableOptionalListWasNull = self->_nullableOptionalListWasNull;
    copied->_nullableOptionalListValue = self->_nullableOptionalListValue;
    copied->_timedInvokeTimeoutMs = self->_timedInvokeTimeoutMs;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _nullableIntWasNull = @0;
    _optionalIntWasPresent = @0;
    _nullableOptionalIntWasPresent = @0;
    _nullableStringWasNull = @0;
    _optionalStringWasPresent = @0;
    _nullableOptionalStringWasPresent = @0;
    _nullableStructWasNull = @0;
    _optionalStructWasPresent = @0;
    _nullableOptionalStructWasPresent = @0;
    _nullableListWasNull = @0;
    _optionalListWasPresent = @0;
    _nullableOptionalListWasPresent = @0;
    return self;
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"nullableIntWasNull:%@; ", charonDescribeObject(self.nullableIntWasNull)];
    [text appendFormat:@"nullableIntValue:%@; ", charonDescribeObject(self.nullableIntValue)];
    [text appendFormat:@"optionalIntWasPresent:%@; ", charonDescribeObject(self.optionalIntWasPresent)];
    [text appendFormat:@"optionalIntValue:%@; ", charonDescribeObject(self.optionalIntValue)];
    [text appendFormat:@"nullableOptionalIntWasPresent:%@; ", charonDescribeObject(self.nullableOptionalIntWasPresent)];
    [text appendFormat:@"nullableOptionalIntWasNull:%@; ", charonDescribeObject(self.nullableOptionalIntWasNull)];
    [text appendFormat:@"nullableOptionalIntValue:%@; ", charonDescribeObject(self.nullableOptionalIntValue)];
    [text appendFormat:@"nullableStringWasNull:%@; ", charonDescribeObject(self.nullableStringWasNull)];
    [text appendFormat:@"nullableStringValue:%@; ", charonDescribeObject(self.nullableStringValue)];
    [text appendFormat:@"optionalStringWasPresent:%@; ", charonDescribeObject(self.optionalStringWasPresent)];
    [text appendFormat:@"optionalStringValue:%@; ", charonDescribeObject(self.optionalStringValue)];
    [text appendFormat:@"nullableOptionalStringWasPresent:%@; ", charonDescribeObject(self.nullableOptionalStringWasPresent)];
    [text appendFormat:@"nullableOptionalStringWasNull:%@; ", charonDescribeObject(self.nullableOptionalStringWasNull)];
    [text appendFormat:@"nullableOptionalStringValue:%@; ", charonDescribeObject(self.nullableOptionalStringValue)];
    [text appendFormat:@"nullableStructWasNull:%@; ", charonDescribeObject(self.nullableStructWasNull)];
    [text appendFormat:@"nullableStructValue:%@; ", charonDescribeObject(self.nullableStructValue)];
    [text appendFormat:@"optionalStructWasPresent:%@; ", charonDescribeObject(self.optionalStructWasPresent)];
    [text appendFormat:@"optionalStructValue:%@; ", charonDescribeObject(self.optionalStructValue)];
    [text appendFormat:@"nullableOptionalStructWasPresent:%@; ", charonDescribeObject(self.nullableOptionalStructWasPresent)];
    [text appendFormat:@"nullableOptionalStructWasNull:%@; ", charonDescribeObject(self.nullableOptionalStructWasNull)];
    [text appendFormat:@"nullableOptionalStructValue:%@; ", charonDescribeObject(self.nullableOptionalStructValue)];
    [text appendFormat:@"nullableListWasNull:%@; ", charonDescribeObject(self.nullableListWasNull)];
    [text appendFormat:@"nullableListValue:%@; ", charonDescribeObject(self.nullableListValue)];
    [text appendFormat:@"optionalListWasPresent:%@; ", charonDescribeObject(self.optionalListWasPresent)];
    [text appendFormat:@"optionalListValue:%@; ", charonDescribeObject(self.optionalListValue)];
    [text appendFormat:@"nullableOptionalListWasPresent:%@; ", charonDescribeObject(self.nullableOptionalListWasPresent)];
    [text appendFormat:@"nullableOptionalListWasNull:%@; ", charonDescribeObject(self.nullableOptionalListWasNull)];
    [text appendFormat:@"nullableOptionalListValue:%@; ", charonDescribeObject(self.nullableOptionalListValue)];
    [text appendFormat:@"timedInvokeTimeoutMs:%@; ", charonDescribeObject(self.timedInvokeTimeoutMs)];
    [text appendString:@">"];
    return text;
}
@end
