//
//  CharonMatterMTRBaseClusterTimeSynchronization.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRBaseClusterTimeSynchronization is a MTRGenericBaseCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 18 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRBaseClusterTimeSynchronization () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRBaseClusterTimeSynchronization

@synthesize AcceptedCommandListValues = _AcceptedCommandListValues;
@synthesize AttributeListValues = _AttributeListValues;
@synthesize ClusterRevisionValues = _ClusterRevisionValues;
@synthesize DSTOffsetValues = _DSTOffsetValues;
@synthesize DSTOffsetListMaxSizeValues = _DSTOffsetListMaxSizeValues;
@synthesize DefaultNTPValues = _DefaultNTPValues;
@synthesize FeatureMapValues = _FeatureMapValues;
@synthesize GeneratedCommandListValues = _GeneratedCommandListValues;
@synthesize GranularityValues = _GranularityValues;
@synthesize LocalTimeValues = _LocalTimeValues;
@synthesize NTPServerAvailableValues = _NTPServerAvailableValues;
@synthesize SupportsDNSResolveValues = _SupportsDNSResolveValues;
@synthesize TimeSourceValues = _TimeSourceValues;
@synthesize TimeZoneValues = _TimeZoneValues;
@synthesize TimeZoneDatabaseValues = _TimeZoneDatabaseValues;
@synthesize TimeZoneListMaxSizeValues = _TimeZoneListMaxSizeValues;
@synthesize TrustedTimeSourceValues = _TrustedTimeSourceValues;
@synthesize UTCTimeValues = _UTCTimeValues;

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRBaseClusterTimeSynchronization class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRBaseDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRBaseDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    _charon_device = device;
    _charon_endpoint = endpointID;
    _charon_queue = queue;
    return self;
}

// UTCTime, a NSNumber.
- (void)readAttributeUTCTimeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"UTCTime"];
    completion(written, nil);
}

- (void)subscribeAttributeUTCTimeWithParams:(MTRSubscribeParams *)params
                    subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                              reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"UTCTime"] = @"subscribed";
}

// Granularity, a NSNumber.
- (void)readAttributeGranularityWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"Granularity"];
    completion(written, nil);
}

- (void)subscribeAttributeGranularityWithParams:(MTRSubscribeParams *)params
                        subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                  reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"Granularity"] = @"subscribed";
}

// TimeSource, a NSNumber.
- (void)readAttributeTimeSourceWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeSource"];
    completion(written, nil);
}

- (void)subscribeAttributeTimeSourceWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeSource"] = @"subscribed";
}

// TrustedTimeSource, a MTRTimeSynchronizationClusterTrustedTimeSourceStruct.
- (void)readAttributeTrustedTimeSourceWithCompletion:(void (^)(MTRTimeSynchronizationClusterTrustedTimeSourceStruct * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"TrustedTimeSource"];
    completion(written, nil);
}

- (void)subscribeAttributeTrustedTimeSourceWithParams:(MTRSubscribeParams *)params
                              subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                        reportHandler:(void (^)(MTRTimeSynchronizationClusterTrustedTimeSourceStruct * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"TrustedTimeSource"] = @"subscribed";
}

// DefaultNTP, a NSString.
- (void)readAttributeDefaultNTPWithCompletion:(void (^)(NSString * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"DefaultNTP"];
    completion(written, nil);
}

- (void)subscribeAttributeDefaultNTPWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSString * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"DefaultNTP"] = @"subscribed";
}

// TimeZone, a NSArray.
- (void)readAttributeTimeZoneWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZone"];
    completion(written, nil);
}

- (void)subscribeAttributeTimeZoneWithParams:(MTRSubscribeParams *)params
                     subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                               reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZone"] = @"subscribed";
}

// DSTOffset, a NSArray.
- (void)readAttributeDSTOffsetWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"DSTOffset"];
    completion(written, nil);
}

- (void)subscribeAttributeDSTOffsetWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"DSTOffset"] = @"subscribed";
}

// LocalTime, a NSNumber.
- (void)readAttributeLocalTimeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"LocalTime"];
    completion(written, nil);
}

- (void)subscribeAttributeLocalTimeWithParams:(MTRSubscribeParams *)params
                      subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"LocalTime"] = @"subscribed";
}

// TimeZoneDatabase, a NSNumber.
- (void)readAttributeTimeZoneDatabaseWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZoneDatabase"];
    completion(written, nil);
}

- (void)subscribeAttributeTimeZoneDatabaseWithParams:(MTRSubscribeParams *)params
                             subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                       reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZoneDatabase"] = @"subscribed";
}

// NTPServerAvailable, a NSNumber.
- (void)readAttributeNTPServerAvailableWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"NTPServerAvailable"];
    completion(written, nil);
}

- (void)subscribeAttributeNTPServerAvailableWithParams:(MTRSubscribeParams *)params
                               subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                         reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"NTPServerAvailable"] = @"subscribed";
}

// TimeZoneListMaxSize, a NSNumber.
- (void)readAttributeTimeZoneListMaxSizeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZoneListMaxSize"];
    completion(written, nil);
}

- (void)subscribeAttributeTimeZoneListMaxSizeWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"TimeZoneListMaxSize"] = @"subscribed";
}

// DSTOffsetListMaxSize, a NSNumber.
- (void)readAttributeDSTOffsetListMaxSizeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"DSTOffsetListMaxSize"];
    completion(written, nil);
}

- (void)subscribeAttributeDSTOffsetListMaxSizeWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"DSTOffsetListMaxSize"] = @"subscribed";
}

// SupportsDNSResolve, a NSNumber.
- (void)readAttributeSupportsDNSResolveWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"SupportsDNSResolve"];
    completion(written, nil);
}

- (void)subscribeAttributeSupportsDNSResolveWithParams:(MTRSubscribeParams *)params
                               subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                         reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"SupportsDNSResolve"] = @"subscribed";
}

// GeneratedCommandList, a NSArray.
- (void)readAttributeGeneratedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"GeneratedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeGeneratedCommandListWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"GeneratedCommandList"] = @"subscribed";
}

// AcceptedCommandList, a NSArray.
- (void)readAttributeAcceptedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"AcceptedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeAcceptedCommandListWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"AcceptedCommandList"] = @"subscribed";
}

// AttributeList, a NSArray.
- (void)readAttributeAttributeListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"AttributeList"];
    completion(written, nil);
}

- (void)subscribeAttributeAttributeListWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"AttributeList"] = @"subscribed";
}

// FeatureMap, a NSNumber.
- (void)readAttributeFeatureMapWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"FeatureMap"];
    completion(written, nil);
}

- (void)subscribeAttributeFeatureMapWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"FeatureMap"] = @"subscribed";
}

// ClusterRevision, a NSNumber.
- (void)readAttributeClusterRevisionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterTimeSynchronization charon_port_values][@"ClusterRevision"];
    completion(written, nil);
}

- (void)subscribeAttributeClusterRevisionWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterTimeSynchronization charon_port_values][@"ClusterRevision"] = @"subscribed";
}

// The cached read of UTCTime: no value and the error, because there is no node.
+ (void)readAttributeUTCTimeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of Granularity: no value and the error, because there is no node.
+ (void)readAttributeGranularityWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of TimeSource: no value and the error, because there is no node.
+ (void)readAttributeTimeSourceWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of TrustedTimeSource: no value and the error, because there is no node.
+ (void)readAttributeTrustedTimeSourceWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(MTRTimeSynchronizationClusterTrustedTimeSourceStruct * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of DefaultNTP: no value and the error, because there is no node.
+ (void)readAttributeDefaultNTPWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSString * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of TimeZone: no value and the error, because there is no node.
+ (void)readAttributeTimeZoneWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of DSTOffset: no value and the error, because there is no node.
+ (void)readAttributeDSTOffsetWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of LocalTime: no value and the error, because there is no node.
+ (void)readAttributeLocalTimeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of TimeZoneDatabase: no value and the error, because there is no node.
+ (void)readAttributeTimeZoneDatabaseWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of NTPServerAvailable: no value and the error, because there is no node.
+ (void)readAttributeNTPServerAvailableWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of TimeZoneListMaxSize: no value and the error, because there is no node.
+ (void)readAttributeTimeZoneListMaxSizeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of DSTOffsetListMaxSize: no value and the error, because there is no node.
+ (void)readAttributeDSTOffsetListMaxSizeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of SupportsDNSResolve: no value and the error, because there is no node.
+ (void)readAttributeSupportsDNSResolveWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of GeneratedCommandList: no value and the error, because there is no node.
+ (void)readAttributeGeneratedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of AcceptedCommandList: no value and the error, because there is no node.
+ (void)readAttributeAcceptedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of AttributeList: no value and the error, because there is no node.
+ (void)readAttributeAttributeListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of FeatureMap: no value and the error, because there is no node.
+ (void)readAttributeFeatureMapWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// The cached read of ClusterRevision: no value and the error, because there is no node.
+ (void)readAttributeClusterRevisionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterTimeSynchronization charon_port_no_node_error]);
}

// setUTCTime. It answers: there is nothing to reach on a release with no fabric.
- (void)setUTCTimeWithParams:(MTRTimeSynchronizationClusterSetUTCTimeParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// setTrustedTimeSource. It answers: there is nothing to reach on a release with no fabric.
- (void)setTrustedTimeSourceWithParams:(MTRTimeSynchronizationClusterSetTrustedTimeSourceParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// setTimeZone. It answers: there is nothing to reach on a release with no fabric.
- (void)setTimeZoneWithParams:(MTRTimeSynchronizationClusterSetTimeZoneParams *)params completion:(void (^)(MTRTimeSynchronizationClusterSetTimeZoneResponseParams * data, NSError * error))completion
{
    (void)params;
    if (completion) {
        completion(nil, nil);
    }
}

// setDSTOffset. It answers: there is nothing to reach on a release with no fabric.
- (void)setDSTOffsetWithParams:(MTRTimeSynchronizationClusterSetDSTOffsetParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// setDefaultNTP. It answers: there is nothing to reach on a release with no fabric.
- (void)setDefaultNTPWithParams:(MTRTimeSynchronizationClusterSetDefaultNTPParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

@end
