//
//  CharonMatterMTRBaseClusterThreadNetworkDirectory.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRBaseClusterThreadNetworkDirectory is a MTRGenericBaseCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 8 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRBaseClusterThreadNetworkDirectory () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRBaseClusterThreadNetworkDirectory

@synthesize AcceptedCommandListValues = _AcceptedCommandListValues;
@synthesize AttributeListValues = _AttributeListValues;
@synthesize ClusterRevisionValues = _ClusterRevisionValues;
@synthesize FeatureMapValues = _FeatureMapValues;
@synthesize GeneratedCommandListValues = _GeneratedCommandListValues;
@synthesize PreferredExtendedPanIDValues = _PreferredExtendedPanIDValues;
@synthesize ThreadNetworkTableSizeValues = _ThreadNetworkTableSizeValues;
@synthesize ThreadNetworksValues = _ThreadNetworksValues;

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRBaseClusterThreadNetworkDirectory class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRBaseDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRBaseDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    _charon_device = device;
    _charon_endpoint = endpointID;
    _charon_queue = queue;
    return self;
}

// PreferredExtendedPanID, a NSData.
- (void)readAttributePreferredExtendedPanIDWithCompletion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"PreferredExtendedPanID"];
    completion(written, nil);
}

- (void)writeAttributePreferredExtendedPanIDWithValue:(NSData * _Nullable)value completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"PreferredExtendedPanID"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)writeAttributePreferredExtendedPanIDWithValue:(NSData * _Nullable)value params:(MTRWriteParams * _Nullable)params completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"PreferredExtendedPanID"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)subscribeAttributePreferredExtendedPanIDWithParams:(MTRSubscribeParams *)params
                                   subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                             reportHandler:(void (^)(NSData * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"PreferredExtendedPanID"] = @"subscribed";
}

// ThreadNetworks, a NSArray.
- (void)readAttributeThreadNetworksWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ThreadNetworks"];
    completion(written, nil);
}

- (void)subscribeAttributeThreadNetworksWithParams:(MTRSubscribeParams *)params
                           subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                     reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ThreadNetworks"] = @"subscribed";
}

// ThreadNetworkTableSize, a NSNumber.
- (void)readAttributeThreadNetworkTableSizeWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ThreadNetworkTableSize"];
    completion(written, nil);
}

- (void)subscribeAttributeThreadNetworkTableSizeWithParams:(MTRSubscribeParams *)params
                                   subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                             reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ThreadNetworkTableSize"] = @"subscribed";
}

// GeneratedCommandList, a NSArray.
- (void)readAttributeGeneratedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"GeneratedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeGeneratedCommandListWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"GeneratedCommandList"] = @"subscribed";
}

// AcceptedCommandList, a NSArray.
- (void)readAttributeAcceptedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"AcceptedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeAcceptedCommandListWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"AcceptedCommandList"] = @"subscribed";
}

// AttributeList, a NSArray.
- (void)readAttributeAttributeListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"AttributeList"];
    completion(written, nil);
}

- (void)subscribeAttributeAttributeListWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"AttributeList"] = @"subscribed";
}

// FeatureMap, a NSNumber.
- (void)readAttributeFeatureMapWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"FeatureMap"];
    completion(written, nil);
}

- (void)subscribeAttributeFeatureMapWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"FeatureMap"] = @"subscribed";
}

// ClusterRevision, a NSNumber.
- (void)readAttributeClusterRevisionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ClusterRevision"];
    completion(written, nil);
}

- (void)subscribeAttributeClusterRevisionWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterThreadNetworkDirectory charon_port_values][@"ClusterRevision"] = @"subscribed";
}

// The cached read of PreferredExtendedPanID: no value and the error, because there is no node.
+ (void)readAttributePreferredExtendedPanIDWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of ThreadNetworks: no value and the error, because there is no node.
+ (void)readAttributeThreadNetworksWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of ThreadNetworkTableSize: no value and the error, because there is no node.
+ (void)readAttributeThreadNetworkTableSizeWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of GeneratedCommandList: no value and the error, because there is no node.
+ (void)readAttributeGeneratedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of AcceptedCommandList: no value and the error, because there is no node.
+ (void)readAttributeAcceptedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of AttributeList: no value and the error, because there is no node.
+ (void)readAttributeAttributeListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of FeatureMap: no value and the error, because there is no node.
+ (void)readAttributeFeatureMapWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// The cached read of ClusterRevision: no value and the error, because there is no node.
+ (void)readAttributeClusterRevisionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterThreadNetworkDirectory charon_port_no_node_error]);
}

// addNetwork. It answers: there is nothing to reach on a release with no fabric.
- (void)addNetworkWithParams:(MTRThreadNetworkDirectoryClusterAddNetworkParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// removeNetwork. It answers: there is nothing to reach on a release with no fabric.
- (void)removeNetworkWithParams:(MTRThreadNetworkDirectoryClusterRemoveNetworkParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// getOperationalDataset. It answers: there is nothing to reach on a release with no fabric.
- (void)getOperationalDatasetWithParams:(MTRThreadNetworkDirectoryClusterGetOperationalDatasetParams *)params completion:(void (^)(MTRThreadNetworkDirectoryClusterOperationalDatasetResponseParams * data, NSError * error))completion
{
    (void)params;
    if (completion) {
        completion(nil, nil);
    }
}

@end
