//
//  CharonMatterMTRClusterRVCOperationalState.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRClusterRVCOperationalState is a MTRGenericCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 0 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRClusterRVCOperationalState () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRClusterRVCOperationalState

@synthesize AcceptedCommandListValues = _AcceptedCommandListValues;
@synthesize AttributeListValues = _AttributeListValues;
@synthesize ClusterRevisionValues = _ClusterRevisionValues;
@synthesize CountdownTimeValues = _CountdownTimeValues;
@synthesize CurrentPhaseValues = _CurrentPhaseValues;
@synthesize FeatureMapValues = _FeatureMapValues;
@synthesize GeneratedCommandListValues = _GeneratedCommandListValues;
@synthesize OperationalErrorValues = _OperationalErrorValues;
@synthesize OperationalStateValues = _OperationalStateValues;
@synthesize OperationalStateListValues = _OperationalStateListValues;
@synthesize PhaseListValues = _PhaseListValues;

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRClusterRVCOperationalState class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    _charon_device = device;
    _charon_endpoint = endpointID;
    _charon_queue = queue;
    return self;
}

// PhaseList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributePhaseListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"PhaseList"];
}

// CurrentPhase, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeCurrentPhaseWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"CurrentPhase"];
}

// CountdownTime, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeCountdownTimeWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"CountdownTime"];
}

// OperationalStateList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeOperationalStateListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"OperationalStateList"];
}

// OperationalState, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeOperationalStateWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"OperationalState"];
}

// OperationalError, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeOperationalErrorWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"OperationalError"];
}

// GeneratedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeGeneratedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"GeneratedCommandList"];
}

// AcceptedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAcceptedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"AcceptedCommandList"];
}

// AttributeList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAttributeListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"AttributeList"];
}

// FeatureMap, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeFeatureMapWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"FeatureMap"];
}

// ClusterRevision, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeClusterRevisionWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterRVCOperationalState charon_port_values][@"ClusterRevision"];
}

// pause. It answers: there is nothing to reach on a release with no fabric.
- (void)pauseWithParams:(MTRRVCOperationalStateClusterPauseParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

// pause. It answers: there is nothing to reach on a release with no fabric.
- (void)pauseWithExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)expectedValues;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

// resume. It answers: there is nothing to reach on a release with no fabric.
- (void)resumeWithParams:(MTRRVCOperationalStateClusterResumeParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

// resume. It answers: there is nothing to reach on a release with no fabric.
- (void)resumeWithExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)expectedValues;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

// goHome. It answers: there is nothing to reach on a release with no fabric.
- (void)goHomeWithParams:(MTRRVCOperationalStateClusterGoHomeParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

// goHome. It answers: there is nothing to reach on a release with no fabric.
- (void)goHomeWithExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(void (^)(MTRRVCOperationalStateClusterOperationalCommandResponseParams * data, NSError * error))completion
{
    (void)expectedValues;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil, nil);
    }
}

@end
