//
//  CharonMatterMTRTestClusterClusterNullablesAndOptionalsStruct.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRTestClusterClusterNullablesAndOptionalsStruct is a plain data class: no protocol of its own. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  it of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

@implementation MTRTestClusterClusterNullablesAndOptionalsStruct

@synthesize nullableInt = _nullableInt;
@synthesize optionalInt = _optionalInt;
@synthesize nullableOptionalInt = _nullableOptionalInt;
@synthesize nullableString = _nullableString;
@synthesize optionalString = _optionalString;
@synthesize nullableOptionalString = _nullableOptionalString;
@synthesize nullableStruct = _nullableStruct;
@synthesize optionalStruct = _optionalStruct;
@synthesize nullableOptionalStruct = _nullableOptionalStruct;
@synthesize nullableList = _nullableList;
@synthesize optionalList = _optionalList;
@synthesize nullableOptionalList = _nullableOptionalList;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRTestClusterClusterNullablesAndOptionalsStruct *copied = [[MTRTestClusterClusterNullablesAndOptionalsStruct allocWithZone:zone] init];
    copied->_nullableInt = self->_nullableInt;
    copied->_optionalInt = self->_optionalInt;
    copied->_nullableOptionalInt = self->_nullableOptionalInt;
    copied->_nullableString = self->_nullableString;
    copied->_optionalString = self->_optionalString;
    copied->_nullableOptionalString = self->_nullableOptionalString;
    copied->_nullableStruct = self->_nullableStruct;
    copied->_optionalStruct = self->_optionalStruct;
    copied->_nullableOptionalStruct = self->_nullableOptionalStruct;
    copied->_nullableList = self->_nullableList;
    copied->_optionalList = self->_optionalList;
    copied->_nullableOptionalList = self->_nullableOptionalList;
    return copied;
}

@end
