//
//  CharonMatterMTRClusterAudioOutput.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRClusterAudioOutput is a MTRGenericCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 0 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// This cluster's @interface is the SDK's own - iPhoneOS 16.4 declares MTRClusterAudioOutput - and it marks
// -initWithDevice:endpointID:queue: NS_DESIGNATED_INITIALIZER, so clang asks the initializer below to call
// a designated initializer of the superclass. MTRCluster.h:40 declares -init NS_UNAVAILABLE, so that call
// cannot be written: `self = [super init]` is `error: 'init' is unavailable`. The initializer therefore does
// what it can - it keeps the three arguments in the ivars below - and this one diagnostic is silenced HERE
// and named, the way MTLRasterizationRate13.m silences its own. The four ways of writing the chain that
// were measured, and the repository's convention, are in coordination/crutches.md.
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRClusterAudioOutput () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRClusterAudioOutput

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRClusterAudioOutput class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    _charon_device = device;
    _charon_endpoint = endpointID;
    _charon_queue = queue;
    return self;
}

// OutputList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeOutputListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"OutputList"];
}

// CurrentOutput, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeCurrentOutputWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"CurrentOutput"];
}

// GeneratedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeGeneratedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"GeneratedCommandList"];
}

// AcceptedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAcceptedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"AcceptedCommandList"];
}

// AttributeList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAttributeListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"AttributeList"];
}

// FeatureMap, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeFeatureMapWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"FeatureMap"];
}

// ClusterRevision, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeClusterRevisionWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterAudioOutput charon_port_values][@"ClusterRevision"];
}

// selectOutput. It answers: there is nothing to reach on a release with no fabric.
- (void)selectOutputWithParams:(MTRAudioOutputClusterSelectOutputParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// renameOutput. It answers: there is nothing to reach on a release with no fabric.
- (void)renameOutputWithParams:(MTRAudioOutputClusterRenameOutputParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

@end
