//
//  CharonMatterMTRDoorLockClusterGetUserResponseParams.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRDoorLockClusterGetUserResponseParams is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  it of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


// What -description prints for one member: %@ for an object pointer, and the member's own type's text for
// anything else. The host's own string is the oracle; see tests/backports/host/matter/params-probe.m.
static NSString *charonDescribeObject(id value)
{
    return value == nil ? @"(nil)" : [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRDoorLockClusterGetUserResponseParams

@synthesize userIndex = _userIndex;
@synthesize userName = _userName;
@synthesize userUniqueID = _userUniqueID;
@synthesize userStatus = _userStatus;
@synthesize userType = _userType;
@synthesize credentialRule = _credentialRule;
@synthesize credentials = _credentials;
@synthesize creatorFabricIndex = _creatorFabricIndex;
@synthesize lastModifiedFabricIndex = _lastModifiedFabricIndex;
@synthesize nextUserIndex = _nextUserIndex;
@synthesize timedInvokeTimeoutMs = _timedInvokeTimeoutMs;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRDoorLockClusterGetUserResponseParams *copied = [[MTRDoorLockClusterGetUserResponseParams allocWithZone:zone] init];
    copied->_userIndex = self->_userIndex;
    copied->_userName = self->_userName;
    copied->_userUniqueID = self->_userUniqueID;
    copied->_userStatus = self->_userStatus;
    copied->_userType = self->_userType;
    copied->_credentialRule = self->_credentialRule;
    copied->_credentials = self->_credentials;
    copied->_creatorFabricIndex = self->_creatorFabricIndex;
    copied->_lastModifiedFabricIndex = self->_lastModifiedFabricIndex;
    copied->_nextUserIndex = self->_nextUserIndex;
    copied->_timedInvokeTimeoutMs = self->_timedInvokeTimeoutMs;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _userIndex = @0;
    return self;
}

// The properties the SDK declares in a CATEGORY of this class - MTRGroupsClusterAddGroupParams
// carries the old `groupId` beside the `groupID` of its own @interface, and 17 classes
// are shaped so. Their accessors are written out over the storage above, because a category
// cannot hold an ivar and clang refuses @synthesize for one in either place.
- (NSNumber * _Nullable)userUniqueId
{
    return _userUniqueID;
}

- (void)setUserUniqueId:(NSNumber * _Nullable)userUniqueId
{
    _userUniqueID = [userUniqueId copy];
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"userIndex:%@; ", charonDescribeObject(self.userIndex)];
    [text appendFormat:@"userName:%@; ", charonDescribeObject(self.userName)];
    [text appendFormat:@"userUniqueID:%@; ", charonDescribeObject(self.userUniqueID)];
    [text appendFormat:@"userStatus:%@; ", charonDescribeObject(self.userStatus)];
    [text appendFormat:@"userType:%@; ", charonDescribeObject(self.userType)];
    [text appendFormat:@"credentialRule:%@; ", charonDescribeObject(self.credentialRule)];
    [text appendFormat:@"credentials:%@; ", charonDescribeObject(self.credentials)];
    [text appendFormat:@"creatorFabricIndex:%@; ", charonDescribeObject(self.creatorFabricIndex)];
    [text appendFormat:@"lastModifiedFabricIndex:%@; ", charonDescribeObject(self.lastModifiedFabricIndex)];
    [text appendFormat:@"nextUserIndex:%@; ", charonDescribeObject(self.nextUserIndex)];
    [text appendFormat:@"timedInvokeTimeoutMs:%@; ", charonDescribeObject(self.timedInvokeTimeoutMs)];
    [text appendString:@">"];
    return text;
}
@end
