//
//  CharonMatterMTRClusterCameraAVSettingsUserLevelManagement.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRClusterCameraAVSettingsUserLevelManagement is a MTRGenericCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 0 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRClusterCameraAVSettingsUserLevelManagement () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRClusterCameraAVSettingsUserLevelManagement

@synthesize AcceptedCommandListValues = _AcceptedCommandListValues;
@synthesize AttributeListValues = _AttributeListValues;
@synthesize ClusterRevisionValues = _ClusterRevisionValues;
@synthesize DPTZStreamsValues = _DPTZStreamsValues;
@synthesize FeatureMapValues = _FeatureMapValues;
@synthesize GeneratedCommandListValues = _GeneratedCommandListValues;
@synthesize MPTZPositionValues = _MPTZPositionValues;
@synthesize MPTZPresetsValues = _MPTZPresetsValues;
@synthesize MaxPresetsValues = _MaxPresetsValues;
@synthesize MovementStateValues = _MovementStateValues;
@synthesize PanMaxValues = _PanMaxValues;
@synthesize PanMinValues = _PanMinValues;
@synthesize TiltMaxValues = _TiltMaxValues;
@synthesize TiltMinValues = _TiltMinValues;
@synthesize ZoomMaxValues = _ZoomMaxValues;

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRClusterCameraAVSettingsUserLevelManagement class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    _charon_device = device;
    _charon_endpoint = endpointID;
    _charon_queue = queue;
    return self;
}

// MPTZPosition, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeMPTZPositionWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"MPTZPosition"];
}

// MaxPresets, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeMaxPresetsWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"MaxPresets"];
}

// MPTZPresets, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeMPTZPresetsWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"MPTZPresets"];
}

// DPTZStreams, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeDPTZStreamsWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"DPTZStreams"];
}

// ZoomMax, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeZoomMaxWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"ZoomMax"];
}

// TiltMin, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeTiltMinWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"TiltMin"];
}

// TiltMax, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeTiltMaxWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"TiltMax"];
}

// PanMin, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributePanMinWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"PanMin"];
}

// PanMax, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributePanMaxWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"PanMax"];
}

// MovementState, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeMovementStateWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"MovementState"];
}

// GeneratedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeGeneratedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"GeneratedCommandList"];
}

// AcceptedCommandList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAcceptedCommandListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"AcceptedCommandList"];
}

// AttributeList, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeAttributeListWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"AttributeList"];
}

// FeatureMap, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeFeatureMapWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"FeatureMap"];
}

// ClusterRevision, a value dictionary, the only type these headers state for it.
- (NSDictionary<NSString *, id> *)readAttributeClusterRevisionWithParams:(MTRReadParams * _Nullable)params
{
    (void)params;
    return [MTRClusterCameraAVSettingsUserLevelManagement charon_port_values][@"ClusterRevision"];
}

// MPTZSetPosition. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZSetPositionWithParams:(MTRCameraAVSettingsUserLevelManagementClusterMPTZSetPositionParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZSetPosition. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZSetPositionWithExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)expectedValues;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZRelativeMove. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZRelativeMoveWithParams:(MTRCameraAVSettingsUserLevelManagementClusterMPTZRelativeMoveParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZRelativeMove. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZRelativeMoveWithExpectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedValues expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)expectedValues;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZMoveToPreset. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZMoveToPresetWithParams:(MTRCameraAVSettingsUserLevelManagementClusterMPTZMoveToPresetParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZSavePreset. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZSavePresetWithParams:(MTRCameraAVSettingsUserLevelManagementClusterMPTZSavePresetParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// MPTZRemovePreset. It answers: there is nothing to reach on a release with no fabric.
- (void)MPTZRemovePresetWithParams:(MTRCameraAVSettingsUserLevelManagementClusterMPTZRemovePresetParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// DPTZSetViewport. It answers: there is nothing to reach on a release with no fabric.
- (void)DPTZSetViewportWithParams:(MTRCameraAVSettingsUserLevelManagementClusterDPTZSetViewportParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

// DPTZRelativeMove. It answers: there is nothing to reach on a release with no fabric.
- (void)DPTZRelativeMoveWithParams:(MTRCameraAVSettingsUserLevelManagementClusterDPTZRelativeMoveParams *)params expectedValues:(NSArray<NSDictionary<NSString *, id> *> *)expectedDataValueDictionaries expectedValueInterval:(NSNumber *)expectedValueIntervalMs completion:(MTRStatusCompletion)completion
{
    (void)params;
    (void)expectedDataValueDictionaries;
    (void)expectedValueIntervalMs;
    if (completion) {
        completion(nil);
    }
}

@end
