//
//  CharonMatterMTRRefrigeratorAlarmClusterNotifyEvent.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers, the same way the cluster
//  objects beside it are: every property below was read out of the header, nothing here is transcribed by
//  hand, and no line of any other source is copied, translated or derived here.
//
//  MTRRefrigeratorAlarmClusterNotifyEvent is a plain data class: NSCopying. It arrived in iOS 16.0. Every property the header
//  declares is synthesised here with its own ivar, and the copy is by declaration so that it owns them.
//  Nothing in it reaches a fabric - it holds what the caller put in it and hands back what it holds.
//
//  Two imports, and each is load-bearing. Matter.h is the framework's own declarations, and it declares
//  no of the 923 classes of this family: an object that re-declares one of those is the
//  compiler's `duplicate interface definition for class`. CharonMatterTypes.h is the port's, and it carries
//  the declarations the library's SDK does not have: the class itself where that SDK declares none, and a
//  class extension with the properties a later SDK added where it declares an older shape of the same name.
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"


// What -description prints for one member: %@ for an object pointer, and the member's own type's text for
// anything else. The host's own string is the oracle; see tests/backports/host/matter/params-probe.m.
static NSString *charonDescribeObject(id value)
{
    return value == nil ? @"(nil)" : [value description];
}

static NSString *charonDescribeScalar(long long value)
{
    return [@(value) stringValue];
}

@implementation MTRRefrigeratorAlarmClusterNotifyEvent

@synthesize active = _active;
@synthesize inactive = _inactive;
@synthesize state = _state;
@synthesize mask = _mask;

// NSCopying, by declaration: the copy owns its own ivars, so writing to the copy never
// reaches back into the original.
- (id)copyWithZone:(NSZone *)zone
{
    MTRRefrigeratorAlarmClusterNotifyEvent *copied = [[MTRRefrigeratorAlarmClusterNotifyEvent allocWithZone:zone] init];
    copied->_active = self->_active;
    copied->_inactive = self->_inactive;
    copied->_state = self->_state;
    copied->_mask = self->_mask;
    return copied;
}

- (instancetype)init
{
    self = [super init];
    if (!self) {
        return nil;
    }
    _active = @0;
    _inactive = @0;
    _state = @0;
    _mask = @0;
    return self;
}

- (NSString *)description
{
    NSMutableString *text = [NSMutableString stringWithFormat:@"<%@: ", NSStringFromClass([self class])];
    [text appendFormat:@"active:%@; ", charonDescribeObject(self.active)];
    [text appendFormat:@"inactive:%@; ", charonDescribeObject(self.inactive)];
    [text appendFormat:@"state:%@; ", charonDescribeObject(self.state)];
    [text appendFormat:@"mask:%@; ", charonDescribeObject(self.mask)];
    [text appendString:@">"];
    return text;
}
@end
