//
//  CharonMatterMTRBaseClusterBooleanStateConfiguration.m
//  Matter
//
//  GENERATED by tools/matter-generate.py from the SDK's own Matter headers. Every name, type and
//  availability below was read out of those headers; nothing here is transcribed by hand and nothing
//  comes from any other source. The shape of a generated cluster - a read, a write and a subscribe
//  per attribute, a params object per command - is the SDK's own shape. The connectedhomeip tree
//  (project-chip/connectedhomeip, v1.7-te2, Apache-2.0) was read once under .agent-work to confirm
//  that shape and no line of it is copied, translated or derived here, which is why this file
//  carries no licence header from it.
//
//  MTRBaseClusterBooleanStateConfiguration is a MTRGenericBaseCluster, declared by the SDK this package compiles against so the compiler knows
//  the signatures, and the release has no such class at all - so this file is the class. A category on
//  a class the device does not have is never loaded, and the port's job here is to BE the class, which
//  is the shape every other port in this package takes.
//
//  Every attribute reads and writes a plain value the caller set, in one table keyed by the
//  cluster and guarded by a lock, because armv7 has no thread-local storage to rely on. Every
//  command answers through its completion. Nothing here reaches a fabric: the 13 cache reads
//  the header declares are not emitted, because a release with no Matter hardware has no node to
//  read from are implemented and answer as Apple documents: no value, and an error.
//
#import <Foundation/Foundation.h>
#import <Matter/Matter.h>
#import "CharonMatterTypes.h"

// A class EXTENSION, not a category: it carries the storage and is invisible at
// runtime, so the port's class is still the only implementation of the name.
@interface MTRBaseClusterBooleanStateConfiguration () {
    id _charon_device;
    NSNumber *_charon_endpoint;
    dispatch_queue_t _charon_queue;
}
@end

@implementation MTRBaseClusterBooleanStateConfiguration

@synthesize AcceptedCommandListValues = _AcceptedCommandListValues;
@synthesize AlarmsActiveValues = _AlarmsActiveValues;
@synthesize AlarmsEnabledValues = _AlarmsEnabledValues;
@synthesize AlarmsSupportedValues = _AlarmsSupportedValues;
@synthesize AlarmsSuppressedValues = _AlarmsSuppressedValues;
@synthesize AttributeListValues = _AttributeListValues;
@synthesize ClusterRevisionValues = _ClusterRevisionValues;
@synthesize CurrentSensitivityLevelValues = _CurrentSensitivityLevelValues;
@synthesize DefaultSensitivityLevelValues = _DefaultSensitivityLevelValues;
@synthesize FeatureMapValues = _FeatureMapValues;
@synthesize GeneratedCommandListValues = _GeneratedCommandListValues;
@synthesize SensorFaultValues = _SensorFaultValues;
@synthesize SupportedSensitivityLevelsValues = _SupportedSensitivityLevelsValues;

// The values the caller has written, by attribute name: one table, keyed by the
// object, guarded by a lock, because armv7 has no thread-local storage to rely on.
+ (NSMutableDictionary *)charon_port_values
{
    static NSMutableDictionary *table;
    @synchronized ([MTRBaseClusterBooleanStateConfiguration class]) {
        if (!table) {
            table = [NSMutableDictionary dictionary];
        }
    }
    return table;
}

// The error a member that would need a node answers, on a release with no Matter
// hardware: there is nothing to read from and nothing to commission onto.
+ (NSError *)charon_port_no_node_error
{
    return [NSError errorWithDomain:NSCocoaErrorDomain code:4096 userInfo:nil];
}

// - (instancetype)initWithDevice:(MTRBaseDevice *)device
// endpointID:(NSNumber *)endpointID
// queue:(dispatch_queue_t)queue
- (instancetype)initWithDevice:(MTRBaseDevice *)device
                              endpointID:(NSNumber *)endpointID
                                   queue:(dispatch_queue_t)queue
{
    return self;
}

// CurrentSensitivityLevel, a NSNumber.
- (void)readAttributeCurrentSensitivityLevelWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"CurrentSensitivityLevel"];
    completion(written, nil);
}

- (void)writeAttributeCurrentSensitivityLevelWithValue:(NSNumber * _Nonnull)value completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"CurrentSensitivityLevel"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)writeAttributeCurrentSensitivityLevelWithValue:(NSNumber * _Nonnull)value params:(MTRWriteParams * _Nullable)params completion:(MTRStatusCompletion)completion
{
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"CurrentSensitivityLevel"] = value;
    if (completion) {
        completion(nil);
    }
}

- (void)subscribeAttributeCurrentSensitivityLevelWithParams:(MTRSubscribeParams *)params
                                    subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                              reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"CurrentSensitivityLevel"] = @"subscribed";
}

// SupportedSensitivityLevels, a NSNumber.
- (void)readAttributeSupportedSensitivityLevelsWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"SupportedSensitivityLevels"];
    completion(written, nil);
}

- (void)subscribeAttributeSupportedSensitivityLevelsWithParams:(MTRSubscribeParams *)params
                                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"SupportedSensitivityLevels"] = @"subscribed";
}

// DefaultSensitivityLevel, a NSNumber.
- (void)readAttributeDefaultSensitivityLevelWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"DefaultSensitivityLevel"];
    completion(written, nil);
}

- (void)subscribeAttributeDefaultSensitivityLevelWithParams:(MTRSubscribeParams *)params
                                    subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                              reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"DefaultSensitivityLevel"] = @"subscribed";
}

// AlarmsActive, a NSNumber.
- (void)readAttributeAlarmsActiveWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsActive"];
    completion(written, nil);
}

- (void)subscribeAttributeAlarmsActiveWithParams:(MTRSubscribeParams *)params
                         subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                   reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsActive"] = @"subscribed";
}

// AlarmsSuppressed, a NSNumber.
- (void)readAttributeAlarmsSuppressedWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsSuppressed"];
    completion(written, nil);
}

- (void)subscribeAttributeAlarmsSuppressedWithParams:(MTRSubscribeParams *)params
                             subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                       reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsSuppressed"] = @"subscribed";
}

// AlarmsEnabled, a NSNumber.
- (void)readAttributeAlarmsEnabledWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsEnabled"];
    completion(written, nil);
}

- (void)subscribeAttributeAlarmsEnabledWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsEnabled"] = @"subscribed";
}

// AlarmsSupported, a NSNumber.
- (void)readAttributeAlarmsSupportedWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsSupported"];
    completion(written, nil);
}

- (void)subscribeAttributeAlarmsSupportedWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AlarmsSupported"] = @"subscribed";
}

// SensorFault, a NSNumber.
- (void)readAttributeSensorFaultWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"SensorFault"];
    completion(written, nil);
}

- (void)subscribeAttributeSensorFaultWithParams:(MTRSubscribeParams *)params
                        subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                  reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"SensorFault"] = @"subscribed";
}

// GeneratedCommandList, a NSArray.
- (void)readAttributeGeneratedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"GeneratedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeGeneratedCommandListWithParams:(MTRSubscribeParams *)params
                                 subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                           reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"GeneratedCommandList"] = @"subscribed";
}

// AcceptedCommandList, a NSArray.
- (void)readAttributeAcceptedCommandListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AcceptedCommandList"];
    completion(written, nil);
}

- (void)subscribeAttributeAcceptedCommandListWithParams:(MTRSubscribeParams *)params
                                subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                          reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AcceptedCommandList"] = @"subscribed";
}

// AttributeList, a NSArray.
- (void)readAttributeAttributeListWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AttributeList"];
    completion(written, nil);
}

- (void)subscribeAttributeAttributeListWithParams:(MTRSubscribeParams *)params
                          subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                    reportHandler:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"AttributeList"] = @"subscribed";
}

// FeatureMap, a NSNumber.
- (void)readAttributeFeatureMapWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"FeatureMap"];
    completion(written, nil);
}

- (void)subscribeAttributeFeatureMapWithParams:(MTRSubscribeParams *)params
                       subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                 reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"FeatureMap"] = @"subscribed";
}

// ClusterRevision, a NSNumber.
- (void)readAttributeClusterRevisionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    if (!completion) {
        return;
    }
    id written = [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"ClusterRevision"];
    completion(written, nil);
}

- (void)subscribeAttributeClusterRevisionWithParams:(MTRSubscribeParams *)params
                            subscriptionEstablished:(MTRSubscriptionEstablishedHandler _Nullable)subscriptionEstablished
                                      reportHandler:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))reportHandler
{
    (void)params;
    (void)subscriptionEstablished;
    (void)reportHandler;
    [MTRBaseClusterBooleanStateConfiguration charon_port_values][@"ClusterRevision"] = @"subscribed";
}

// The cached read of CurrentSensitivityLevel: no value and the error, because there is no node.
+ (void)readAttributeCurrentSensitivityLevelWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of SupportedSensitivityLevels: no value and the error, because there is no node.
+ (void)readAttributeSupportedSensitivityLevelsWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of DefaultSensitivityLevel: no value and the error, because there is no node.
+ (void)readAttributeDefaultSensitivityLevelWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AlarmsActive: no value and the error, because there is no node.
+ (void)readAttributeAlarmsActiveWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AlarmsSuppressed: no value and the error, because there is no node.
+ (void)readAttributeAlarmsSuppressedWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AlarmsEnabled: no value and the error, because there is no node.
+ (void)readAttributeAlarmsEnabledWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AlarmsSupported: no value and the error, because there is no node.
+ (void)readAttributeAlarmsSupportedWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of SensorFault: no value and the error, because there is no node.
+ (void)readAttributeSensorFaultWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of GeneratedCommandList: no value and the error, because there is no node.
+ (void)readAttributeGeneratedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AcceptedCommandList: no value and the error, because there is no node.
+ (void)readAttributeAcceptedCommandListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of AttributeList: no value and the error, because there is no node.
+ (void)readAttributeAttributeListWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of FeatureMap: no value and the error, because there is no node.
+ (void)readAttributeFeatureMapWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// The cached read of ClusterRevision: no value and the error, because there is no node.
+ (void)readAttributeClusterRevisionWithClusterStateCache:(MTRClusterStateCacheContainer *)clusterStateCacheContainer endpoint:(NSNumber *)endpoint queue:(dispatch_queue_t)queue completion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion
{
    (void)clusterStateCacheContainer;
    (void)endpoint;
    (void)queue;
    if (!completion) {
        return;
    }
    completion(nil, [MTRBaseClusterBooleanStateConfiguration charon_port_no_node_error]);
}

// suppressAlarm. It answers: there is nothing to reach on a release with no fabric.
- (void)suppressAlarmWithParams:(MTRBooleanStateConfigurationClusterSuppressAlarmParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

// enableDisableAlarm. It answers: there is nothing to reach on a release with no fabric.
- (void)enableDisableAlarmWithParams:(MTRBooleanStateConfigurationClusterEnableDisableAlarmParams *)params completion:(MTRStatusCompletion)completion
{
    (void)params;
    if (completion) {
        completion(nil);
    }
}

@end
