#import "CharonGC.h"

@implementation CharonGCTables

+ (NSArray *)extendedSpecs
{
    static NSArray *specs;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        specs = @[
            @{@"kind": @"dpad", @"aliases": @[@"Direction Pad"], @"local": @"Direction Pad", @"unmappedLocal": @"Direction Pad", @"sf": @"dpad", @"unmappedSf": @"dpad", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @0},
            @{@"kind": @"dpad", @"aliases": @[@"Left Thumbstick"], @"local": @"Left Thumbstick", @"unmappedLocal": @"Left Thumbstick", @"sf": @"l.joystick", @"unmappedSf": @"l.joystick", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @1},
            @{@"kind": @"dpad", @"aliases": @[@"Right Thumbstick"], @"local": @"Right Thumbstick", @"unmappedLocal": @"Right Thumbstick", @"sf": @"r.joystick", @"unmappedSf": @"r.joystick", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @2},
            @{@"kind": @"button", @"aliases": @[@"Button Menu"], @"local": @"Menu Button", @"unmappedLocal": @"Menu Button", @"sf": @"line.horizontal.3.circle", @"unmappedSf": @"line.horizontal.3.circle", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @3},
            @{@"kind": @"button", @"aliases": @[@"Button Home"], @"local": @"Home Button", @"unmappedLocal": @"Home Button", @"sf": @"house.circle", @"unmappedSf": @"house.circle", @"analog": @1, @"system": @1, @"collection": [NSNull null], @"order": @4},
            @{@"kind": @"button", @"aliases": @[@"Button A"], @"local": @"A Button", @"unmappedLocal": @"A Button", @"sf": @"a.circle", @"unmappedSf": @"a.circle", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @5},
            @{@"kind": @"button", @"aliases": @[@"Button B"], @"local": @"B Button", @"unmappedLocal": @"B Button", @"sf": @"b.circle", @"unmappedSf": @"b.circle", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @6},
            @{@"kind": @"button", @"aliases": @[@"Button X"], @"local": @"X Button", @"unmappedLocal": @"X Button", @"sf": @"x.circle", @"unmappedSf": @"x.circle", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @7},
            @{@"kind": @"button", @"aliases": @[@"Button Y"], @"local": @"Y Button", @"unmappedLocal": @"Y Button", @"sf": @"y.circle", @"unmappedSf": @"y.circle", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @8},
            @{@"kind": @"button", @"aliases": @[@"Left Shoulder"], @"local": @"L1 Button", @"unmappedLocal": @"L1 Button", @"sf": @"l1.rectangle.roundedbottom", @"unmappedSf": @"l1.rectangle.roundedbottom", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @9},
            @{@"kind": @"button", @"aliases": @[@"Right Shoulder"], @"local": @"R1 Button", @"unmappedLocal": @"R1 Button", @"sf": @"r1.rectangle.roundedbottom", @"unmappedSf": @"r1.rectangle.roundedbottom", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @10},
            @{@"kind": @"button", @"aliases": @[@"Left Trigger"], @"local": @"L2 Button", @"unmappedLocal": @"L2 Button", @"sf": @"l2.rectangle.roundedtop", @"unmappedSf": @"l2.rectangle.roundedtop", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @11},
            @{@"kind": @"button", @"aliases": @[@"Right Trigger"], @"local": @"R2 Button", @"unmappedLocal": @"R2 Button", @"sf": @"r2.rectangle.roundedtop", @"unmappedSf": @"r2.rectangle.roundedtop", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @12},
            @{@"kind": @"button", @"aliases": @[@"Left Thumbstick Button"], @"local": @"Left Thumbstick Button", @"unmappedLocal": @"Left Thumbstick Button", @"sf": @"l.joystick.down", @"unmappedSf": @"l.joystick.down", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @13},
            @{@"kind": @"button", @"aliases": @[@"Right Thumbstick Button"], @"local": @"Right Thumbstick Button", @"unmappedLocal": @"Right Thumbstick Button", @"sf": @"r.joystick.press.down", @"unmappedSf": @"r.joystick.press.down", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @14},
            @{@"kind": @"button", @"aliases": @[@"Left Bumper"], @"local": @"L4 Button", @"unmappedLocal": @"L4 Button", @"sf": @"l4.button.horizontal", @"unmappedSf": @"l4.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @15},
            @{@"kind": @"button", @"aliases": @[@"Right Bumper"], @"local": @"R4 Button", @"unmappedLocal": @"R4 Button", @"sf": @"r4.button.horizontal", @"unmappedSf": @"r4.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @16},
            @{@"kind": @"button", @"aliases": @[@"Back Left Button 0", @"Paddle 3"], @"local": @"M2 Button", @"unmappedLocal": @"M2 Button", @"sf": @"m2.button.horizontal", @"unmappedSf": @"m2.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @17},
            @{@"kind": @"button", @"aliases": @[@"Back Left Button 1", @"Paddle 4"], @"local": @"M4 Button", @"unmappedLocal": @"M4 Button", @"sf": @"m4.button.horizontal", @"unmappedSf": @"m4.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @18},
            @{@"kind": @"button", @"aliases": @[@"Back Right Button 0", @"Paddle 1"], @"local": @"M1 Button", @"unmappedLocal": @"M1 Button", @"sf": @"m1.button.horizontal", @"unmappedSf": @"m1.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @19},
            @{@"kind": @"button", @"aliases": @[@"Back Right Button 1", @"Paddle 2"], @"local": @"M3 Button", @"unmappedLocal": @"M3 Button", @"sf": @"m3.button.horizontal", @"unmappedSf": @"m3.button.horizontal", @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @20},
            @{@"kind": @"button", @"aliases": @[@"Button Options"], @"local": @"Options Button", @"unmappedLocal": @"Options Button", @"sf": @"ellipsis.circle", @"unmappedSf": @"ellipsis.circle", @"analog": @1, @"system": @1, @"collection": [NSNull null], @"order": @21},
            @{@"kind": @"axis", @"aliases": @[@"Direction Pad X Axis"], @"local": @"Direction Pad (Horizontal)", @"unmappedLocal": @"Direction Pad (Horizontal)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Direction Pad Y Axis"], @"local": @"Direction Pad (Vertical)", @"unmappedLocal": @"Direction Pad (Vertical)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Left Thumbstick X Axis"], @"local": @"Left Thumbstick (Horizontal)", @"unmappedLocal": @"Left Thumbstick (Horizontal)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Left Thumbstick Y Axis"], @"local": @"Left Thumbstick (Vertical)", @"unmappedLocal": @"Left Thumbstick (Vertical)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Right Thumbstick X Axis"], @"local": @"Right Thumbstick (Horizontal)", @"unmappedLocal": @"Right Thumbstick (Horizontal)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Right Thumbstick Y Axis"], @"local": @"Right Thumbstick (Vertical)", @"unmappedLocal": @"Right Thumbstick (Vertical)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Down"], @"local": @"Direction Pad (Down)", @"unmappedLocal": @"Direction Pad (Down)", @"sf": @"dpad.down.fill", @"unmappedSf": @"dpad.down.fill", @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Left"], @"local": @"Direction Pad (Left)", @"unmappedLocal": @"Direction Pad (Left)", @"sf": @"dpad.left.fill", @"unmappedSf": @"dpad.left.fill", @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Right"], @"local": @"Direction Pad (Right)", @"unmappedLocal": @"Direction Pad (Right)", @"sf": @"dpad.right.fill", @"unmappedSf": @"dpad.right.fill", @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Up"], @"local": @"Direction Pad (Up)", @"unmappedLocal": @"Direction Pad (Up)", @"sf": @"dpad.up.fill", @"unmappedSf": @"dpad.up.fill", @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Left Thumbstick Down"], @"local": @"Left Thumbstick (Down)", @"unmappedLocal": @"Left Thumbstick (Down)", @"sf": @"l.joystick.tilt.down", @"unmappedSf": @"l.joystick.tilt.down", @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Left Thumbstick Left"], @"local": @"Left Thumbstick (Left)", @"unmappedLocal": @"Left Thumbstick (Left)", @"sf": @"l.joystick.tilt.left", @"unmappedSf": @"l.joystick.tilt.left", @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Left Thumbstick Right"], @"local": @"Left Thumbstick (Right)", @"unmappedLocal": @"Left Thumbstick (Right)", @"sf": @"l.joystick.tilt.right", @"unmappedSf": @"l.joystick.tilt.right", @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Left Thumbstick Up"], @"local": @"Left Thumbstick (Up)", @"unmappedLocal": @"Left Thumbstick (Up)", @"sf": @"l.joystick.tilt.up", @"unmappedSf": @"l.joystick.tilt.up", @"analog": @1, @"system": @0, @"collection": @"Left Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Right Thumbstick Down"], @"local": @"Right Thumbstick (Down)", @"unmappedLocal": @"Right Thumbstick (Down)", @"sf": @"r.joystick.tilt.down", @"unmappedSf": @"r.joystick.tilt.down", @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Right Thumbstick Left"], @"local": @"Right Thumbstick (Left)", @"unmappedLocal": @"Right Thumbstick (Left)", @"sf": @"r.joystick.tilt.left", @"unmappedSf": @"r.joystick.tilt.left", @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Right Thumbstick Right"], @"local": @"Right Thumbstick (Right)", @"unmappedLocal": @"Right Thumbstick (Right)", @"sf": @"r.joystick.tilt.right", @"unmappedSf": @"r.joystick.tilt.right", @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Right Thumbstick Up"], @"local": @"Right Thumbstick (Up)", @"unmappedLocal": @"Right Thumbstick (Up)", @"sf": @"r.joystick.tilt.up", @"unmappedSf": @"r.joystick.tilt.up", @"analog": @1, @"system": @0, @"collection": @"Right Thumbstick", @"order": @-1}
        ];
    });
    return specs;
}

+ (NSArray *)microSpecs
{
    static NSArray *specs;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        specs = @[
            @{@"kind": @"dpad", @"aliases": @[@"Direction Pad"], @"local": @"Touch Surface", @"unmappedLocal": @"Touch Surface", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @0},
            @{@"kind": @"button", @"aliases": @[@"Button Menu"], @"local": @"Menu Button", @"unmappedLocal": @"Menu Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @1},
            @{@"kind": @"button", @"aliases": @[@"Button A"], @"local": @"Touch Surface Button", @"unmappedLocal": @"Touch Surface Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @2},
            @{@"kind": @"button", @"aliases": @[@"Button X"], @"local": @"Play/Pause Button", @"unmappedLocal": @"Play/Pause Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @3},
            @{@"kind": @"axis", @"aliases": @[@"Direction Pad X Axis"], @"local": @"Touch Surface (Horizontal)", @"unmappedLocal": @"Touch Surface (Horizontal)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Direction Pad Y Axis"], @"local": @"Touch Surface (Vertical)", @"unmappedLocal": @"Touch Surface (Vertical)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Down"], @"local": @"Touch Surface (Down)", @"unmappedLocal": @"Touch Surface (Down)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Left"], @"local": @"Touch Surface (Left)", @"unmappedLocal": @"Touch Surface (Left)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Right"], @"local": @"Touch Surface (Right)", @"unmappedLocal": @"Touch Surface (Right)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Direction Pad Up"], @"local": @"Touch Surface (Up)", @"unmappedLocal": @"Touch Surface (Up)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Direction Pad", @"order": @-1}
        ];
    });
    return specs;
}

+ (NSArray *)mouseSpecs
{
    static NSArray *specs;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        specs = @[
            @{@"kind": @"button", @"aliases": @[@"Left Button"], @"local": @"Left Button", @"unmappedLocal": @"Left Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @0},
            @{@"kind": @"button", @"aliases": @[@"Right Button"], @"local": @"Right Button", @"unmappedLocal": @"Right Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @1},
            @{@"kind": @"button", @"aliases": @[@"Middle Button"], @"local": @"Middle Button", @"unmappedLocal": @"Middle Button", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @2},
            @{@"kind": @"cursor", @"aliases": @[@"Scroll"], @"local": @"Scroll", @"unmappedLocal": @"Scroll", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": [NSNull null], @"order": @3},
            @{@"kind": @"axis", @"aliases": @[@"Scroll X Axis"], @"local": @"Scroll (Horizontal)", @"unmappedLocal": @"Scroll (Horizontal)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1},
            @{@"kind": @"axis", @"aliases": @[@"Scroll Y Axis"], @"local": @"Scroll (Vertical)", @"unmappedLocal": @"Scroll (Vertical)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Scroll Down"], @"local": @"Scroll (Down)", @"unmappedLocal": @"Scroll (Down)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Scroll Left"], @"local": @"Scroll (Left)", @"unmappedLocal": @"Scroll (Left)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Scroll Right"], @"local": @"Scroll (Right)", @"unmappedLocal": @"Scroll (Right)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1},
            @{@"kind": @"button", @"aliases": @[@"Scroll Up"], @"local": @"Scroll (Up)", @"unmappedLocal": @"Scroll (Up)", @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @1, @"system": @0, @"collection": @"Scroll", @"order": @-1}
        ];
    });
    return specs;
}

+ (NSArray *)keyboardSpecs
{
    static NSArray *specs;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        specs = @[
            @{@"kind": @"button", @"aliases": @[GCKeyA], @"local": GCKeyA, @"unmappedLocal": GCKeyA, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @0, @"keyCode": @(GCKeyCodeKeyA)},
            @{@"kind": @"button", @"aliases": @[GCKeyB], @"local": GCKeyB, @"unmappedLocal": GCKeyB, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @1, @"keyCode": @(GCKeyCodeKeyB)},
            @{@"kind": @"button", @"aliases": @[GCKeyC], @"local": GCKeyC, @"unmappedLocal": GCKeyC, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @2, @"keyCode": @(GCKeyCodeKeyC)},
            @{@"kind": @"button", @"aliases": @[GCKeyD], @"local": GCKeyD, @"unmappedLocal": GCKeyD, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @3, @"keyCode": @(GCKeyCodeKeyD)},
            @{@"kind": @"button", @"aliases": @[GCKeyE], @"local": GCKeyE, @"unmappedLocal": GCKeyE, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @4, @"keyCode": @(GCKeyCodeKeyE)},
            @{@"kind": @"button", @"aliases": @[GCKeyF], @"local": GCKeyF, @"unmappedLocal": GCKeyF, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @5, @"keyCode": @(GCKeyCodeKeyF)},
            @{@"kind": @"button", @"aliases": @[GCKeyG], @"local": GCKeyG, @"unmappedLocal": GCKeyG, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @6, @"keyCode": @(GCKeyCodeKeyG)},
            @{@"kind": @"button", @"aliases": @[GCKeyH], @"local": GCKeyH, @"unmappedLocal": GCKeyH, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @7, @"keyCode": @(GCKeyCodeKeyH)},
            @{@"kind": @"button", @"aliases": @[GCKeyI], @"local": GCKeyI, @"unmappedLocal": GCKeyI, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @8, @"keyCode": @(GCKeyCodeKeyI)},
            @{@"kind": @"button", @"aliases": @[GCKeyJ], @"local": GCKeyJ, @"unmappedLocal": GCKeyJ, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @9, @"keyCode": @(GCKeyCodeKeyJ)},
            @{@"kind": @"button", @"aliases": @[GCKeyK], @"local": GCKeyK, @"unmappedLocal": GCKeyK, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @10, @"keyCode": @(GCKeyCodeKeyK)},
            @{@"kind": @"button", @"aliases": @[GCKeyL], @"local": GCKeyL, @"unmappedLocal": GCKeyL, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @11, @"keyCode": @(GCKeyCodeKeyL)},
            @{@"kind": @"button", @"aliases": @[GCKeyM], @"local": GCKeyM, @"unmappedLocal": GCKeyM, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @12, @"keyCode": @(GCKeyCodeKeyM)},
            @{@"kind": @"button", @"aliases": @[GCKeyN], @"local": GCKeyN, @"unmappedLocal": GCKeyN, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @13, @"keyCode": @(GCKeyCodeKeyN)},
            @{@"kind": @"button", @"aliases": @[GCKeyO], @"local": GCKeyO, @"unmappedLocal": GCKeyO, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @14, @"keyCode": @(GCKeyCodeKeyO)},
            @{@"kind": @"button", @"aliases": @[GCKeyP], @"local": GCKeyP, @"unmappedLocal": GCKeyP, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @15, @"keyCode": @(GCKeyCodeKeyP)},
            @{@"kind": @"button", @"aliases": @[GCKeyQ], @"local": GCKeyQ, @"unmappedLocal": GCKeyQ, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @16, @"keyCode": @(GCKeyCodeKeyQ)},
            @{@"kind": @"button", @"aliases": @[GCKeyR], @"local": GCKeyR, @"unmappedLocal": GCKeyR, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @17, @"keyCode": @(GCKeyCodeKeyR)},
            @{@"kind": @"button", @"aliases": @[GCKeyS], @"local": GCKeyS, @"unmappedLocal": GCKeyS, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @18, @"keyCode": @(GCKeyCodeKeyS)},
            @{@"kind": @"button", @"aliases": @[GCKeyT], @"local": GCKeyT, @"unmappedLocal": GCKeyT, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @19, @"keyCode": @(GCKeyCodeKeyT)},
            @{@"kind": @"button", @"aliases": @[GCKeyU], @"local": GCKeyU, @"unmappedLocal": GCKeyU, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @20, @"keyCode": @(GCKeyCodeKeyU)},
            @{@"kind": @"button", @"aliases": @[GCKeyV], @"local": GCKeyV, @"unmappedLocal": GCKeyV, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @21, @"keyCode": @(GCKeyCodeKeyV)},
            @{@"kind": @"button", @"aliases": @[GCKeyW], @"local": GCKeyW, @"unmappedLocal": GCKeyW, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @22, @"keyCode": @(GCKeyCodeKeyW)},
            @{@"kind": @"button", @"aliases": @[GCKeyX], @"local": GCKeyX, @"unmappedLocal": GCKeyX, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @23, @"keyCode": @(GCKeyCodeKeyX)},
            @{@"kind": @"button", @"aliases": @[GCKeyY], @"local": GCKeyY, @"unmappedLocal": GCKeyY, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @24, @"keyCode": @(GCKeyCodeKeyY)},
            @{@"kind": @"button", @"aliases": @[GCKeyZ], @"local": GCKeyZ, @"unmappedLocal": GCKeyZ, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @25, @"keyCode": @(GCKeyCodeKeyZ)},
            @{@"kind": @"button", @"aliases": @[GCKeyOne], @"local": GCKeyOne, @"unmappedLocal": GCKeyOne, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @26, @"keyCode": @(GCKeyCodeOne)},
            @{@"kind": @"button", @"aliases": @[GCKeyTwo], @"local": GCKeyTwo, @"unmappedLocal": GCKeyTwo, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @27, @"keyCode": @(GCKeyCodeTwo)},
            @{@"kind": @"button", @"aliases": @[GCKeyThree], @"local": GCKeyThree, @"unmappedLocal": GCKeyThree, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @28, @"keyCode": @(GCKeyCodeThree)},
            @{@"kind": @"button", @"aliases": @[GCKeyFour], @"local": GCKeyFour, @"unmappedLocal": GCKeyFour, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @29, @"keyCode": @(GCKeyCodeFour)},
            @{@"kind": @"button", @"aliases": @[GCKeyFive], @"local": GCKeyFive, @"unmappedLocal": GCKeyFive, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @30, @"keyCode": @(GCKeyCodeFive)},
            @{@"kind": @"button", @"aliases": @[GCKeySix], @"local": GCKeySix, @"unmappedLocal": GCKeySix, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @31, @"keyCode": @(GCKeyCodeSix)},
            @{@"kind": @"button", @"aliases": @[GCKeySeven], @"local": GCKeySeven, @"unmappedLocal": GCKeySeven, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @32, @"keyCode": @(GCKeyCodeSeven)},
            @{@"kind": @"button", @"aliases": @[GCKeyEight], @"local": GCKeyEight, @"unmappedLocal": GCKeyEight, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @33, @"keyCode": @(GCKeyCodeEight)},
            @{@"kind": @"button", @"aliases": @[GCKeyNine], @"local": GCKeyNine, @"unmappedLocal": GCKeyNine, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @34, @"keyCode": @(GCKeyCodeNine)},
            @{@"kind": @"button", @"aliases": @[GCKeyZero], @"local": GCKeyZero, @"unmappedLocal": GCKeyZero, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @35, @"keyCode": @(GCKeyCodeZero)},
            @{@"kind": @"button", @"aliases": @[GCKeyReturnOrEnter], @"local": GCKeyReturnOrEnter, @"unmappedLocal": GCKeyReturnOrEnter, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @36, @"keyCode": @(GCKeyCodeReturnOrEnter)},
            @{@"kind": @"button", @"aliases": @[GCKeyEscape], @"local": GCKeyEscape, @"unmappedLocal": GCKeyEscape, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @37, @"keyCode": @(GCKeyCodeEscape)},
            @{@"kind": @"button", @"aliases": @[GCKeyDeleteOrBackspace], @"local": GCKeyDeleteOrBackspace, @"unmappedLocal": GCKeyDeleteOrBackspace, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @38, @"keyCode": @(GCKeyCodeDeleteOrBackspace)},
            @{@"kind": @"button", @"aliases": @[GCKeyTab], @"local": GCKeyTab, @"unmappedLocal": GCKeyTab, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @39, @"keyCode": @(GCKeyCodeTab)},
            @{@"kind": @"button", @"aliases": @[GCKeySpacebar], @"local": GCKeySpacebar, @"unmappedLocal": GCKeySpacebar, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @40, @"keyCode": @(GCKeyCodeSpacebar)},
            @{@"kind": @"button", @"aliases": @[GCKeyHyphen], @"local": GCKeyHyphen, @"unmappedLocal": GCKeyHyphen, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @41, @"keyCode": @(GCKeyCodeHyphen)},
            @{@"kind": @"button", @"aliases": @[GCKeyEqualSign], @"local": GCKeyEqualSign, @"unmappedLocal": GCKeyEqualSign, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @42, @"keyCode": @(GCKeyCodeEqualSign)},
            @{@"kind": @"button", @"aliases": @[GCKeyOpenBracket], @"local": GCKeyOpenBracket, @"unmappedLocal": GCKeyOpenBracket, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @43, @"keyCode": @(GCKeyCodeOpenBracket)},
            @{@"kind": @"button", @"aliases": @[GCKeyCloseBracket], @"local": GCKeyCloseBracket, @"unmappedLocal": GCKeyCloseBracket, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @44, @"keyCode": @(GCKeyCodeCloseBracket)},
            @{@"kind": @"button", @"aliases": @[GCKeyBackslash], @"local": GCKeyBackslash, @"unmappedLocal": GCKeyBackslash, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @45, @"keyCode": @(GCKeyCodeBackslash)},
            @{@"kind": @"button", @"aliases": @[GCKeyNonUSPound], @"local": GCKeyNonUSPound, @"unmappedLocal": GCKeyNonUSPound, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @46, @"keyCode": @(GCKeyCodeNonUSPound)},
            @{@"kind": @"button", @"aliases": @[GCKeySemicolon], @"local": GCKeySemicolon, @"unmappedLocal": GCKeySemicolon, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @47, @"keyCode": @(GCKeyCodeSemicolon)},
            @{@"kind": @"button", @"aliases": @[GCKeyQuote], @"local": GCKeyQuote, @"unmappedLocal": GCKeyQuote, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @48, @"keyCode": @(GCKeyCodeQuote)},
            @{@"kind": @"button", @"aliases": @[GCKeyGraveAccentAndTilde], @"local": GCKeyGraveAccentAndTilde, @"unmappedLocal": GCKeyGraveAccentAndTilde, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @49, @"keyCode": @(GCKeyCodeGraveAccentAndTilde)},
            @{@"kind": @"button", @"aliases": @[GCKeyComma], @"local": GCKeyComma, @"unmappedLocal": GCKeyComma, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @50, @"keyCode": @(GCKeyCodeComma)},
            @{@"kind": @"button", @"aliases": @[GCKeyPeriod], @"local": GCKeyPeriod, @"unmappedLocal": GCKeyPeriod, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @51, @"keyCode": @(GCKeyCodePeriod)},
            @{@"kind": @"button", @"aliases": @[GCKeySlash], @"local": GCKeySlash, @"unmappedLocal": GCKeySlash, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @52, @"keyCode": @(GCKeyCodeSlash)},
            @{@"kind": @"button", @"aliases": @[GCKeyCapsLock], @"local": GCKeyCapsLock, @"unmappedLocal": GCKeyCapsLock, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @53, @"keyCode": @(GCKeyCodeCapsLock)},
            @{@"kind": @"button", @"aliases": @[GCKeyF1], @"local": GCKeyF1, @"unmappedLocal": GCKeyF1, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @54, @"keyCode": @(GCKeyCodeF1)},
            @{@"kind": @"button", @"aliases": @[GCKeyF2], @"local": GCKeyF2, @"unmappedLocal": GCKeyF2, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @55, @"keyCode": @(GCKeyCodeF2)},
            @{@"kind": @"button", @"aliases": @[GCKeyF3], @"local": GCKeyF3, @"unmappedLocal": GCKeyF3, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @56, @"keyCode": @(GCKeyCodeF3)},
            @{@"kind": @"button", @"aliases": @[GCKeyF4], @"local": GCKeyF4, @"unmappedLocal": GCKeyF4, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @57, @"keyCode": @(GCKeyCodeF4)},
            @{@"kind": @"button", @"aliases": @[GCKeyF5], @"local": GCKeyF5, @"unmappedLocal": GCKeyF5, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @58, @"keyCode": @(GCKeyCodeF5)},
            @{@"kind": @"button", @"aliases": @[GCKeyF6], @"local": GCKeyF6, @"unmappedLocal": GCKeyF6, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @59, @"keyCode": @(GCKeyCodeF6)},
            @{@"kind": @"button", @"aliases": @[GCKeyF7], @"local": GCKeyF7, @"unmappedLocal": GCKeyF7, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @60, @"keyCode": @(GCKeyCodeF7)},
            @{@"kind": @"button", @"aliases": @[GCKeyF8], @"local": GCKeyF8, @"unmappedLocal": GCKeyF8, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @61, @"keyCode": @(GCKeyCodeF8)},
            @{@"kind": @"button", @"aliases": @[GCKeyF9], @"local": GCKeyF9, @"unmappedLocal": GCKeyF9, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @62, @"keyCode": @(GCKeyCodeF9)},
            @{@"kind": @"button", @"aliases": @[GCKeyF10], @"local": GCKeyF10, @"unmappedLocal": GCKeyF10, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @63, @"keyCode": @(GCKeyCodeF10)},
            @{@"kind": @"button", @"aliases": @[GCKeyF11], @"local": GCKeyF11, @"unmappedLocal": GCKeyF11, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @64, @"keyCode": @(GCKeyCodeF11)},
            @{@"kind": @"button", @"aliases": @[GCKeyF12], @"local": GCKeyF12, @"unmappedLocal": GCKeyF12, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @65, @"keyCode": @(GCKeyCodeF12)},
            @{@"kind": @"button", @"aliases": @[GCKeyPrintScreen], @"local": GCKeyPrintScreen, @"unmappedLocal": GCKeyPrintScreen, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @66, @"keyCode": @(GCKeyCodePrintScreen)},
            @{@"kind": @"button", @"aliases": @[GCKeyScrollLock], @"local": GCKeyScrollLock, @"unmappedLocal": GCKeyScrollLock, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @67, @"keyCode": @(GCKeyCodeScrollLock)},
            @{@"kind": @"button", @"aliases": @[GCKeyPause], @"local": GCKeyPause, @"unmappedLocal": GCKeyPause, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @68, @"keyCode": @(GCKeyCodePause)},
            @{@"kind": @"button", @"aliases": @[GCKeyInsert], @"local": GCKeyInsert, @"unmappedLocal": GCKeyInsert, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @69, @"keyCode": @(GCKeyCodeInsert)},
            @{@"kind": @"button", @"aliases": @[GCKeyHome], @"local": GCKeyHome, @"unmappedLocal": GCKeyHome, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @70, @"keyCode": @(GCKeyCodeHome)},
            @{@"kind": @"button", @"aliases": @[GCKeyPageUp], @"local": GCKeyPageUp, @"unmappedLocal": GCKeyPageUp, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @71, @"keyCode": @(GCKeyCodePageUp)},
            @{@"kind": @"button", @"aliases": @[GCKeyDeleteForward], @"local": GCKeyDeleteForward, @"unmappedLocal": GCKeyDeleteForward, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @72, @"keyCode": @(GCKeyCodeDeleteForward)},
            @{@"kind": @"button", @"aliases": @[GCKeyEnd], @"local": GCKeyEnd, @"unmappedLocal": GCKeyEnd, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @73, @"keyCode": @(GCKeyCodeEnd)},
            @{@"kind": @"button", @"aliases": @[GCKeyPageDown], @"local": GCKeyPageDown, @"unmappedLocal": GCKeyPageDown, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @74, @"keyCode": @(GCKeyCodePageDown)},
            @{@"kind": @"button", @"aliases": @[GCKeyRightArrow], @"local": GCKeyRightArrow, @"unmappedLocal": GCKeyRightArrow, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @75, @"keyCode": @(GCKeyCodeRightArrow)},
            @{@"kind": @"button", @"aliases": @[GCKeyLeftArrow], @"local": GCKeyLeftArrow, @"unmappedLocal": GCKeyLeftArrow, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @76, @"keyCode": @(GCKeyCodeLeftArrow)},
            @{@"kind": @"button", @"aliases": @[GCKeyDownArrow], @"local": GCKeyDownArrow, @"unmappedLocal": GCKeyDownArrow, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @77, @"keyCode": @(GCKeyCodeDownArrow)},
            @{@"kind": @"button", @"aliases": @[GCKeyUpArrow], @"local": GCKeyUpArrow, @"unmappedLocal": GCKeyUpArrow, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @78, @"keyCode": @(GCKeyCodeUpArrow)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadNumLock], @"local": GCKeyKeypadNumLock, @"unmappedLocal": GCKeyKeypadNumLock, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @79, @"keyCode": @(GCKeyCodeKeypadNumLock)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadSlash], @"local": GCKeyKeypadSlash, @"unmappedLocal": GCKeyKeypadSlash, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @80, @"keyCode": @(GCKeyCodeKeypadSlash)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadAsterisk], @"local": GCKeyKeypadAsterisk, @"unmappedLocal": GCKeyKeypadAsterisk, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @81, @"keyCode": @(GCKeyCodeKeypadAsterisk)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadHyphen], @"local": GCKeyKeypadHyphen, @"unmappedLocal": GCKeyKeypadHyphen, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @82, @"keyCode": @(GCKeyCodeKeypadHyphen)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadPlus], @"local": GCKeyKeypadPlus, @"unmappedLocal": GCKeyKeypadPlus, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @83, @"keyCode": @(GCKeyCodeKeypadPlus)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadEnter], @"local": GCKeyKeypadEnter, @"unmappedLocal": GCKeyKeypadEnter, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @84, @"keyCode": @(GCKeyCodeKeypadEnter)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad1], @"local": GCKeyKeypad1, @"unmappedLocal": GCKeyKeypad1, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @85, @"keyCode": @(GCKeyCodeKeypad1)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad2], @"local": GCKeyKeypad2, @"unmappedLocal": GCKeyKeypad2, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @86, @"keyCode": @(GCKeyCodeKeypad2)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad3], @"local": GCKeyKeypad3, @"unmappedLocal": GCKeyKeypad3, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @87, @"keyCode": @(GCKeyCodeKeypad3)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad4], @"local": GCKeyKeypad4, @"unmappedLocal": GCKeyKeypad4, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @88, @"keyCode": @(GCKeyCodeKeypad4)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad5], @"local": GCKeyKeypad5, @"unmappedLocal": GCKeyKeypad5, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @89, @"keyCode": @(GCKeyCodeKeypad5)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad6], @"local": GCKeyKeypad6, @"unmappedLocal": GCKeyKeypad6, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @90, @"keyCode": @(GCKeyCodeKeypad6)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad7], @"local": GCKeyKeypad7, @"unmappedLocal": GCKeyKeypad7, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @91, @"keyCode": @(GCKeyCodeKeypad7)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad8], @"local": GCKeyKeypad8, @"unmappedLocal": GCKeyKeypad8, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @92, @"keyCode": @(GCKeyCodeKeypad8)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad9], @"local": GCKeyKeypad9, @"unmappedLocal": GCKeyKeypad9, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @93, @"keyCode": @(GCKeyCodeKeypad9)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypad0], @"local": GCKeyKeypad0, @"unmappedLocal": GCKeyKeypad0, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @94, @"keyCode": @(GCKeyCodeKeypad0)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadPeriod], @"local": GCKeyKeypadPeriod, @"unmappedLocal": GCKeyKeypadPeriod, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @95, @"keyCode": @(GCKeyCodeKeypadPeriod)},
            @{@"kind": @"button", @"aliases": @[GCKeyNonUSBackslash], @"local": GCKeyNonUSBackslash, @"unmappedLocal": GCKeyNonUSBackslash, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @96, @"keyCode": @(GCKeyCodeNonUSBackslash)},
            @{@"kind": @"button", @"aliases": @[GCKeyApplication], @"local": GCKeyApplication, @"unmappedLocal": GCKeyApplication, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @97, @"keyCode": @(GCKeyCodeApplication)},
            @{@"kind": @"button", @"aliases": @[GCKeyPower], @"local": GCKeyPower, @"unmappedLocal": GCKeyPower, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @98, @"keyCode": @(GCKeyCodePower)},
            @{@"kind": @"button", @"aliases": @[GCKeyKeypadEqualSign], @"local": GCKeyKeypadEqualSign, @"unmappedLocal": GCKeyKeypadEqualSign, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @99, @"keyCode": @(GCKeyCodeKeypadEqualSign)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational1], @"local": GCKeyInternational1, @"unmappedLocal": GCKeyInternational1, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @100, @"keyCode": @(GCKeyCodeInternational1)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational2], @"local": GCKeyInternational2, @"unmappedLocal": GCKeyInternational2, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @101, @"keyCode": @(GCKeyCodeInternational2)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational3], @"local": GCKeyInternational3, @"unmappedLocal": GCKeyInternational3, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @102, @"keyCode": @(GCKeyCodeInternational3)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational4], @"local": GCKeyInternational4, @"unmappedLocal": GCKeyInternational4, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @103, @"keyCode": @(GCKeyCodeInternational4)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational5], @"local": GCKeyInternational5, @"unmappedLocal": GCKeyInternational5, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @104, @"keyCode": @(GCKeyCodeInternational5)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational6], @"local": GCKeyInternational6, @"unmappedLocal": GCKeyInternational6, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @105, @"keyCode": @(GCKeyCodeInternational6)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational7], @"local": GCKeyInternational7, @"unmappedLocal": GCKeyInternational7, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @106, @"keyCode": @(GCKeyCodeInternational7)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational8], @"local": GCKeyInternational8, @"unmappedLocal": GCKeyInternational8, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @107, @"keyCode": @(GCKeyCodeInternational8)},
            @{@"kind": @"button", @"aliases": @[GCKeyInternational9], @"local": GCKeyInternational9, @"unmappedLocal": GCKeyInternational9, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @108, @"keyCode": @(GCKeyCodeInternational9)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG1], @"local": GCKeyLANG1, @"unmappedLocal": GCKeyLANG1, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @109, @"keyCode": @(GCKeyCodeLANG1)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG2], @"local": GCKeyLANG2, @"unmappedLocal": GCKeyLANG2, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @110, @"keyCode": @(GCKeyCodeLANG2)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG3], @"local": GCKeyLANG3, @"unmappedLocal": GCKeyLANG3, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @111, @"keyCode": @(GCKeyCodeLANG3)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG4], @"local": GCKeyLANG4, @"unmappedLocal": GCKeyLANG4, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @112, @"keyCode": @(GCKeyCodeLANG4)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG5], @"local": GCKeyLANG5, @"unmappedLocal": GCKeyLANG5, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @113, @"keyCode": @(GCKeyCodeLANG5)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG6], @"local": GCKeyLANG6, @"unmappedLocal": GCKeyLANG6, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @114, @"keyCode": @(GCKeyCodeLANG6)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG7], @"local": GCKeyLANG7, @"unmappedLocal": GCKeyLANG7, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @115, @"keyCode": @(GCKeyCodeLANG7)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG8], @"local": GCKeyLANG8, @"unmappedLocal": GCKeyLANG8, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @116, @"keyCode": @(GCKeyCodeLANG8)},
            @{@"kind": @"button", @"aliases": @[GCKeyLANG9], @"local": GCKeyLANG9, @"unmappedLocal": GCKeyLANG9, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @117, @"keyCode": @(GCKeyCodeLANG9)},
            @{@"kind": @"button", @"aliases": @[GCKeyLeftControl], @"local": GCKeyLeftControl, @"unmappedLocal": GCKeyLeftControl, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @118, @"keyCode": @(GCKeyCodeLeftControl)},
            @{@"kind": @"button", @"aliases": @[GCKeyLeftShift], @"local": GCKeyLeftShift, @"unmappedLocal": GCKeyLeftShift, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @119, @"keyCode": @(GCKeyCodeLeftShift)},
            @{@"kind": @"button", @"aliases": @[GCKeyLeftAlt], @"local": GCKeyLeftAlt, @"unmappedLocal": GCKeyLeftAlt, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @120, @"keyCode": @(GCKeyCodeLeftAlt)},
            @{@"kind": @"button", @"aliases": @[GCKeyLeftGUI], @"local": GCKeyLeftGUI, @"unmappedLocal": GCKeyLeftGUI, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @121, @"keyCode": @(GCKeyCodeLeftGUI)},
            @{@"kind": @"button", @"aliases": @[GCKeyRightControl], @"local": GCKeyRightControl, @"unmappedLocal": GCKeyRightControl, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @122, @"keyCode": @(GCKeyCodeRightControl)},
            @{@"kind": @"button", @"aliases": @[GCKeyRightShift], @"local": GCKeyRightShift, @"unmappedLocal": GCKeyRightShift, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @123, @"keyCode": @(GCKeyCodeRightShift)},
            @{@"kind": @"button", @"aliases": @[GCKeyRightAlt], @"local": GCKeyRightAlt, @"unmappedLocal": GCKeyRightAlt, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @124, @"keyCode": @(GCKeyCodeRightAlt)},
            @{@"kind": @"button", @"aliases": @[GCKeyRightGUI], @"local": GCKeyRightGUI, @"unmappedLocal": GCKeyRightGUI, @"sf": [NSNull null], @"unmappedSf": [NSNull null], @"analog": @0, @"system": @0, @"collection": [NSNull null], @"order": @125, @"keyCode": @(GCKeyCodeRightGUI)},
        ];
    });
    return specs;
}

@end
