#!/usr/bin/env python3
# rename-intents.py: the port's Intents sources, with every Apple class name in them replaced by a
# name of the port's own, so a host build can link them beside the host's Intents and reach the
# PORT's implementations rather than the framework's.
#
# Why the tree's own tool cannot do this, stated with the command that shows it:
#
#     $ xcrun clang -fobjc-arc -target arm64-apple-macos13.0 -isysroot $(xcrun --show-sdk-path --sdk macosx) \
#           -fsyntax-only -w -I packages/a/apple-backports/Intents packages/a/apple-backports/Intents/IN10_0_1.m
#     packages/a/apple-backports/Intents/CharonIntents262.h:39:1: error: duplicate interface definition
#                                                                 for class 'INMessageLinkMetadata'
#
# prefix_selectors.py needs a host AST of the source, and the port's sources do not build for the
# host at all, because CharonIntents262.h re-declares the classes the 16.4 SDK lacks and the host's
# Intents has. The rename therefore has to be TEXTUAL and has to happen before the host build, and
# it has to cover that header's declarations too - which is the whole of the reason the previous
# attempt's lookup got the framework's class: the port's class and the framework's were the same
# object, so 220 of 330 lines were red with every port object linked in.
#
# The list is the port's OWN class inventory, from the objects the library builds, so a name the port
# does not define is not renamed and a name it does is:
#
#     xcrun nm -gU <the port's objects> | _OBJC_CLASS_$_<name>
#
# and the substitution is textual and word-bounded, so `INMessage` becomes `ccharonHostINMessage` and
# `INMessageLinkMetadata` becomes `ccharonHostINMessageLinkMetadata` - the longest first, so a class
# whose name is a prefix of another does not take the other's suffix into its own. Every rewrite is
# counted and printed, and a name the file does not contain is not a rewrite.
#
#     rename-intents.py OUTDIR OBJ.o [OBJ.o ...]
#
# The outdir comes FIRST because the shell expands the object glob into many arguments and the
# tool would otherwise take the second object as the output directory.
#
# reads the object list, copies every packages/a/apple-backports/Intents/*.h and *.m into OUTDIR with
# the substitution applied, and writes the rename list to OUTDIR/rename.h as one -D per name, which
# is the form a compile takes.

import os
import re
import subprocess
import sys

PREFIX = "ccharonHost_"


def class_names(objects):
    """Every class the port's own objects define, read off their symbols."""
    out = subprocess.run(["xcrun", "nm", "-gU"] + list(objects), capture_output=True, text=True, check=True).stdout
    names = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[1] != "U" and parts[2].startswith("_OBJC_CLASS_$_"):
            names.add(parts[2][len("_OBJC_CLASS_$_"):])
    return names


def ordered(names):
    """Longest name first, so a class that is a prefix of another cannot take its suffix."""
    return sorted(names, key=lambda n: (-len(n), n))


def rewrite(text, ordered_names):
    """Every whole-word occurrence of every name, once each, counted."""
    counts = {}
    for name in ordered_names:
        pattern = re.compile(r"\b%s\b" % re.escape(name))
        text, n = pattern.subn(PREFIX + name, text)
        if n:
            counts[name] = n
    return text, counts


def main():
    outdir, objects = sys.argv[1], sys.argv[2:]
    os.makedirs(outdir, exist_ok=True)
    names = class_names(objects)
    sequence = ordered(names)
    with open(os.path.join(outdir, "rename.h"), "w", encoding="utf-8") as handle:
        handle.write("// Generated by tests/backports/host/intents/rename-intents.py from the port's own\n"
                     "// objects, so every define here is a class the port really defines.  One per\n"
                     "// line, longest name first.\n"
                     "//\n"
                     "// A #define and not a -D: this file is passed with -include, and a -D line read as\n"
                     "// source is the error 'missing context for method definition' at its first line.\n")
        for name in sequence:
            handle.write("#define %s %s%s\n" % (name, PREFIX, name))

    total, touched = 0, []
    for name in sorted(os.listdir("packages/a/apple-backports/Intents")):
        if not name.endswith((".m", ".h")):
            continue
        source = os.path.join("packages/a/apple-backports/Intents", name)
        with open(source, encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        # An #import or #include line is a PATH and keeps its name.  The header it names is the
        # framework's and the class that header declares is used here only as a type, so renaming
        # inside the path asks for a header the port does not have:
        #     #import <Intents/INParameter.h>  ->  #import <Intents/ccharonHost_INParameter.h>
        #     fatal error: 'Intents/ccharonHost_INParameter.h' file not found
        # So the lines are taken out, the rest is rewritten, and they go back in whole.
        lines = text.split("\n")
        kept = [line for line in lines if line.lstrip().startswith(("#import", "#include"))]
        for index in range(len(lines)):
            if lines[index].lstrip().startswith(("#import", "#include")):
                lines[index] = ""
        blanked, counts = rewrite("\n".join(lines), sequence)
        restored = blanked.split("\n")
        cursor = 0
        for index in range(len(restored)):
            if not restored[index].strip() and cursor < len(kept) and kept[cursor].lstrip().startswith(("#import", "#include")):
                restored[index] = kept[cursor]
                cursor += 1
        while cursor < len(kept):
            restored.insert(0, kept[cursor])
            cursor += 1
        text = "\n".join(restored)
        with open(os.path.join(outdir, name), "w", encoding="utf-8") as handle:
            handle.write(text)
        if counts:
            n = sum(counts.values())
            total += n
            touched.append((name, n, len(counts)))
    for name, n, classes in sorted(touched, key=lambda t: -t[1]):
        print("  %-40s %5d substitutions over %4d classes" % (name, n, classes))
    print("  %d names in the list, %d files, %d substitutions" % (len(sequence), len(touched), total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
