// The UIKit constants first exported by iOS 18.0
// (facts/UIKit/UIKitConstants180.md).
//
// One object carries one release: every symbol here is first exported by the oldest
// held release that has it, so a band from 18.0 on re-exports the release's own and the
// bands below keep this one.
//
// Every value below was read out of a real dyld shared cache, /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore,
// never from a header and never from a host framework.

#import <UIKit/UIKit.h>

const NSAttributedStringKey NSAdaptiveImageGlyphAttributeName = @"CTAdaptiveImageProvider";
const NSAttributedStringDocumentAttributeKey NSDefaultFontExcludedDocumentAttribute = @"NoDefaultFonts";
const NSAttributedStringKey NSTextHighlightColorSchemeAttributeName = @"NSTextHighlightColorScheme";
const NSTextHighlightColorScheme NSTextHighlightColorSchemeBlue = @"NSTextHighlightColorSchemeBlue";
const NSTextHighlightColorScheme NSTextHighlightColorSchemeDefault = @"NSTextHighlightColorSchemeDefault";
const NSTextHighlightColorScheme NSTextHighlightColorSchemeMint = @"NSTextHighlightColorSchemeMint";
const NSTextHighlightColorScheme NSTextHighlightColorSchemeOrange = @"NSTextHighlightColorSchemeOrange";
const NSTextHighlightColorScheme NSTextHighlightColorSchemePink = @"NSTextHighlightColorSchemePink";
const NSTextHighlightColorScheme NSTextHighlightColorSchemePurple = @"NSTextHighlightColorSchemePurple";
const NSAttributedStringKey NSTextHighlightStyleAttributeName = @"NSTextHighlightStyle";
const NSTextHighlightStyle NSTextHighlightStyleDefault = @"NSTextHighlightStyleDefault";
const NSAttributedStringDocumentReadingOptionKey NSTextKit1ListMarkerFormatDocumentOption = @"TextKit1ListMarkerFormat";
NSString *const UIAccessibilityCustomActionCategoryEdit = @"UIAccessibilityCustomActionCategoryEdit";
const UIAccessibilityPriority UIAccessibilityPriorityDefault = @"UIAccessibilityPriorityDefault";
const UIAccessibilityPriority UIAccessibilityPriorityHigh = @"UIAccessibilityPriorityHigh";
const UIAccessibilityPriority UIAccessibilityPriorityLow = @"UIAccessibilityPriorityLow";
const NSAttributedStringKey UIAccessibilitySpeechAttributeAnnouncementPriority = @"UIAccessibilitySpeechAttributeAnnouncementPriority";
const UIAccessibilityTraits UIAccessibilityTraitSupportsZoom = 70368744177664;
const UIAccessibilityTraits UIAccessibilityTraitToggleButton = 9007199254740992;
const UIActivityItemsConfigurationInteraction UIActivityItemsConfigurationInteractionCopy = @"copy";
const UIActivityItemsConfigurationMetadataKey UIActivityItemsConfigurationMetadataKeyCollaborationModeRestrictions = @"collaborationModeRestrictions";
const UIActivityItemsConfigurationMetadataKey UIActivityItemsConfigurationMetadataKeyShareRecipients = @"shareRecipients";
const UIActivityType UIActivityTypeAddToHomeScreen = @"com.apple.UIKit.activity.AddToHomeScreen";
const UICollectionLayoutSectionOrthogonalScrollingDecelerationRate UICollectionLayoutSectionOrthogonalScrollingDecelerationRateAutomatic = -1.0;
const UICollectionLayoutSectionOrthogonalScrollingDecelerationRate UICollectionLayoutSectionOrthogonalScrollingDecelerationRateFast = 0.99;
const UICollectionLayoutSectionOrthogonalScrollingDecelerationRate UICollectionLayoutSectionOrthogonalScrollingDecelerationRateNormal = 0.998;
const UIDocumentCreationIntent UIDocumentCreationIntentDefault = @"UIDocumentCreationIntentDefault";
const UIFontTextStyle UIFontTextStyleExtraLargeTitle = @"UICTFontTextStyleExtraLargeTitle";
const UIFontTextStyle UIFontTextStyleExtraLargeTitle2 = @"UICTFontTextStyleExtraLargeTitle2";
const UIMenuIdentifier UIMenuAutoFill = @"com.apple.menu.autofill";
const NSNotificationName UISceneSystemProtectionDidChangeNotification = @"UISceneSystemProtectionDidChangeNotification";
const UITextContentType UITextContentTypeBirthdate = @"bday";
const UITextContentType UITextContentTypeBirthdateDay = @"bday-day";
const UITextContentType UITextContentTypeBirthdateMonth = @"bday-month";
const UITextContentType UITextContentTypeBirthdateYear = @"bday-year";
const UITextContentType UITextContentTypeCellularEID = @"esim-eid";
const UITextContentType UITextContentTypeCellularIMEI = @"esim-imei";
const UITextContentType UITextContentTypeCreditCardExpiration = @"cc-exp";
const UITextContentType UITextContentTypeCreditCardExpirationMonth = @"cc-exp-month";
const UITextContentType UITextContentTypeCreditCardExpirationYear = @"cc-exp-year";
const UITextContentType UITextContentTypeCreditCardFamilyName = @"cc-family-name";
const UITextContentType UITextContentTypeCreditCardGivenName = @"cc-given-name";
const UITextContentType UITextContentTypeCreditCardMiddleName = @"cc-additional-name";
const UITextContentType UITextContentTypeCreditCardName = @"cc-name";
const UITextContentType UITextContentTypeCreditCardSecurityCode = @"cc-csc";
const UITextContentType UITextContentTypeCreditCardType = @"cc-type";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerDecreaseFontSizeChangeType = @"UITextFormattingViewControllerDecreaseFontSizeChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerDecreaseIndentationChangeType = @"UITextFormattingViewControllerDecreaseIndentationChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerFontAttributesComponentKey = @"UITextFormattingViewControllerFontAttributesComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerFontChangeType = @"UITextFormattingViewControllerFontChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerFontPickerComponentKey = @"UITextFormattingViewControllerFontPickerComponent";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerFontPointSizeComponentKey = @"UITextFormattingViewControllerFontPointSizeComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerFontSizeChangeType = @"UITextFormattingViewControllerFontSizeChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerFontSizeComponentKey = @"UITextFormattingViewControllerFontSizeComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerFormattingStyleChangeType = @"UITextFormattingViewControllerFormattingStyleChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerFormattingStylesComponentKey = @"UITextFormattingViewControllerFormattingStylesComponent";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightBlue = @"UITextFormattingViewControllerHighlightBlue";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerHighlightChangeType = @"UITextFormattingViewControllerHighlightChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerHighlightComponentKey = @"UITextFormattingViewControllerHighlightComponent";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightDefault = @"UITextFormattingViewControllerHighlightDefault";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightMint = @"UITextFormattingViewControllerHighlightMint";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightOrange = @"UITextFormattingViewControllerHighlightOrange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerHighlightPickerComponentKey = @"UITextFormattingViewControllerHighlightPickerComponent";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightPink = @"UITextFormattingViewControllerHighlightPink";
const UITextFormattingViewControllerHighlight UITextFormattingViewControllerHighlightPurple = @"UITextFormattingViewControllerHighlightPurple";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerIncreaseFontSizeChangeType = @"UITextFormattingViewControllerIncreaseFontSizeChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerIncreaseIndentationChangeType = @"UITextFormattingViewControllerIncreaseIndentationChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerLineHeightComponentKey = @"UITextFormattingViewControllerLineHeightComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerLineHeightPointSizeChangeType = @"UITextFormattingViewControllerLineHeightPointSizeChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerListStylesComponentKey = @"UITextFormattingViewControllerListStylesComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerRemoveBoldChangeType = @"UITextFormattingViewControllerRemoveBoldChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerRemoveItalicChangeType = @"UITextFormattingViewControllerRemoveItalicChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerRemoveStrikethroughChangeType = @"UITextFormattingViewControllerRemoveStrikethroughChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerRemoveUnderlineChangeType = @"UITextFormattingViewControllerRemoveUnderlineChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerSetBoldChangeType = @"UITextFormattingViewControllerSetBoldChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerSetItalicChangeType = @"UITextFormattingViewControllerSetItalicChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerSetStrikethroughChangeType = @"UITextFormattingViewControllerSetStrikethroughChange";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerSetUnderlineChangeType = @"UITextFormattingViewControllerSetUnderlineChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerTextAlignmentAndJustificationComponentKey = @"UITextFormattingViewControllerTextAlignmentAndJustificationComponent";
const UITextFormattingViewControllerTextAlignment UITextFormattingViewControllerTextAlignmentCenter = @"UITextFormattingViewControllerTextAlignmentCenter";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerTextAlignmentChangeType = @"UITextFormattingViewControllerTextAlignmentChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerTextAlignmentComponentKey = @"UITextFormattingViewControllerTextAlignmentComponent";
const UITextFormattingViewControllerTextAlignment UITextFormattingViewControllerTextAlignmentJustified = @"UITextFormattingViewControllerTextAlignmentJustified";
const UITextFormattingViewControllerTextAlignment UITextFormattingViewControllerTextAlignmentLeft = @"UITextFormattingViewControllerTextAlignmentLeft";
const UITextFormattingViewControllerTextAlignment UITextFormattingViewControllerTextAlignmentNatural = @"UITextFormattingViewControllerTextAlignmentNatural";
const UITextFormattingViewControllerTextAlignment UITextFormattingViewControllerTextAlignmentRight = @"UITextFormattingViewControllerTextAlignmentRight";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerTextColorChangeType = @"UITextFormattingViewControllerTextColorChange";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerTextColorComponentKey = @"UITextFormattingViewControllerTextColorComponent";
const UITextFormattingViewControllerComponentKey UITextFormattingViewControllerTextIndentationComponentKey = @"UITextFormattingViewControllerTextIndentationComponent";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerTextListChangeType = @"UITextFormattingViewControllerTextListChange";
const UITextFormattingViewControllerTextList UITextFormattingViewControllerTextListDecimal = @"UITextFormattingViewControllerTextListDecimal";
const UITextFormattingViewControllerTextList UITextFormattingViewControllerTextListDisc = @"UITextFormattingViewControllerTextListDisc";
const UITextFormattingViewControllerTextList UITextFormattingViewControllerTextListHyphen = @"UITextFormattingViewControllerTextListHyphen";
const UITextFormattingViewControllerTextList UITextFormattingViewControllerTextListOther = @"UITextFormattingViewControllerTextListOther";
const UITextFormattingViewControllerChangeType UITextFormattingViewControllerUndefinedChangeType = @"UITextFormattingViewControllerUndefinedChange";
const NSAttributedStringKey UITextItemTagAttributeName = @"UITextItemTagAttribute";
