#!/usr/bin/env python3
"""Rewrites cases.m's per-constant declarations and reads FROM ladder.tsv, so the two cannot drift.

    python3 gen-constant-cases.py [--check]

THE CONSTANT LIST WAS HAND-COPIED into cases.m - an `extern` and a read for each of the 135 - and a
hand-copied list is a list that goes stale: twelve kVTProfileLevel constants the port must carry were
measured by the ladder and nothing asked the host for them, because cases.m did not name them. So the
list is generated, from the same table place-by-ladder.py places by, and --check says whether the file on
disk is what this would write.

WHAT IT COVERS, and what it deliberately does not: the list is the constants the ladder PLACES and the
port DEFINES. A constant with no rung is not read, because the host's VideoToolbox may not export it and
the differential would then compare against a symbol that is not there.

The two locals in each block are not tidiness, and they are reproduced exactly: -[NSString UTF8String] is
NS_RETURNS_INNER_POINTER, and casting the symbol inline inside the brackets makes the compiler read the
whole expression as a message to a non-Objective-C pointer. That is twenty errors, so a local of the
right type comes first and the message is sent to it.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORKTREE = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
PACKAGE = os.path.join(WORKTREE, "packages", "a", "apple-backports", "VideoToolbox")
TABLE = os.path.join(HERE, "ladder.tsv")
CASES = os.path.join(HERE, "cases.m")

PROLOGUE = '''#import <Foundation/Foundation.h>
#import <VideoToolbox/VideoToolbox.h>
#import "videotoolbox-cases.h"

// GENERATED by gen-constant-cases.py from ladder.tsv - do not hand-edit. The declarations below and the
// reads further down are what the ladder PLACES and the port DEFINES; a hand-copied list is a list that
// goes stale, and twelve kVTProfileLevel constants went exactly that way until this existed.
//
// The value of each is read out of WHICHER build is linked in: the host's own VideoToolbox, or the
// port's file with the names renamed. compare.py requires them to agree, one check per constant - and a
// value the host did not print is never written into the port.
//
// The two locals below are not tidiness. -[NSString UTF8String] is NS_RETURNS_INNER_POINTER, and
// casting the symbol inline inside the brackets makes the compiler read the whole thing as a
// message to a non-Objective-C pointer, which is twenty errors. A local of the right type first
// and the message on it is what compiles.
'''


def wanted():
    """The constants to ask about: the ladder places them, and an object of ours defines them."""
    placed, native = set(), set()
    for line in open(TABLE):
        if line.startswith("#") or not line.strip():
            continue
        name, _, release = line.rstrip("\n").partition("\t")
        if not name:
            continue
        if release.strip() in ("", "-"):
            native.add(name)
        else:
            placed.add(name)
    defined = set()
    for entry in sorted(os.listdir(PACKAGE)):
        if not entry.startswith("VideoToolboxConstants") or not entry.endswith(".m"):
            continue
        for name in re.findall(r"^const CFStringRef (\w+) = CFSTR",
                               open(os.path.join(PACKAGE, entry)).read(), re.M):
            defined.add(name)
    missing = sorted(defined - placed - native)
    assert not missing, ("these constants are defined but ladder.tsv does not measure them, so nothing "
                         "says which object holds them: %s" % missing)
    return sorted(defined)


def render(names):
    out = [PROLOGUE]
    out += ["extern const CFStringRef %s;" % n for n in names]
    out += ["", "void videotoolbox_run(CertificateRecorder record)", "{"]
    for name in names:
        out += ["    {",
                "        NSString *value = (__bridge NSString *)(%s);" % name,
                "        const char *utf8 = value.UTF8String;",
                '        record(@"%s", utf8 ? @(utf8) : @"(unreadable)");' % name,
                "    }"]
    out += ["}"]
    return "\n".join(out) + "\n"


def main():
    names = wanted()
    text = render(names)
    if "--check" in sys.argv:
        on_disk = open(CASES).read()
        if on_disk == text:
            print("cases.m is what the ladder says: %d constants" % len(names))
            return 0
        print("FAIL cases.m is not what the ladder says: %d constants on disk, %d generated"
              % (on_disk.count("extern const CFStringRef"), len(names)))
        return 1
    with open(CASES, "w") as handle:
        handle.write(text)
    print("cases.m written: %d constants" % len(names))
    return 0


if __name__ == "__main__":
    sys.exit(main())
