#!/usr/bin/env python3
"""Renames the port's four time functions, so a host binary can carry the port's build and the host's
own side by side without either shadowing the other. The names are the header's own, so the case file
spells one set and the port's file spells the other."""
import re, sys

registry, out = sys.argv[1], sys.argv[2]
names = ["SRAbsoluteTimeGetCurrent", "SRAbsoluteTimeFromContinuousTime",
         "SRAbsoluteTimeToCFAbsoluteTime", "SRAbsoluteTimeFromCFAbsoluteTime"]
with open(out, "w") as handle:
    handle.write("// Generated by rename.py: the port's four time functions, under names of their own.\n")
    for name in names:
        handle.write("#define %s Charon%s\n" % (name, name))
