/*
 *    The Apple-prefixed spellings of the Aliro feature, forwarding to the methods this library carries.
 *
 *    Generated by tools/matter-alias.lua from the selectors the library carries, not written out: the
 *    SDK's surface spells these commands `apple<Command>` and these attribute accesses
 *    `read/write/subscribeAttributeApple<Attribute>` over the Aliro feature the open-source model declares
 *    under its own name, and a rename has no per-row judgement in it. Each forward reaches the same
 *    attribute or command id as the method it forwards to, because it is that method's own encoder call.
 *
 *    Measured: `AppleAliro` and `appleClearAliro` have zero occurrences in connectedhomeip master as well as
 *    in the tag this package builds, and the framework's own metadata carries the unprefixed methods.
 */

#import <Foundation/Foundation.h>
#import <Matter/Matter.h>

@interface MTRBaseClusterDoorLock (CharonAppleSpelling)
@end

@implementation MTRBaseClusterDoorLock (CharonAppleSpelling)

- (void)appleClearAliroReaderConfigWithCompletion:(MTRStatusCompletion)completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self clearAliroReaderConfigWithCompletion:completion];
}

- (void)readAttributeAppleAliroBLEAdvertisingVersionWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroBLEAdvertisingVersionWithCompletion:completion];
}

- (void)readAttributeAppleAliroExpeditedTransactionSupportedProtocolVersionsWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroExpeditedTransactionSupportedProtocolVersionsWithCompletion:completion];
}

- (void)readAttributeAppleAliroGroupResolvingKeyWithCompletion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroGroupResolvingKeyWithCompletion:completion];
}

- (void)readAttributeAppleAliroReaderGroupIdentifierWithCompletion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroReaderGroupIdentifierWithCompletion:completion];
}

- (void)readAttributeAppleAliroReaderGroupSubIdentifierWithCompletion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroReaderGroupSubIdentifierWithCompletion:completion];
}

- (void)readAttributeAppleAliroReaderVerificationKeyWithCompletion:(void (^)(NSData * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroReaderVerificationKeyWithCompletion:completion];
}

- (void)readAttributeAppleAliroSupportedBLEUWBProtocolVersionsWithCompletion:(void (^)(NSArray * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeAliroSupportedBLEUWBProtocolVersionsWithCompletion:completion];
}

- (void)readAttributeAppleNumberOfAliroCredentialIssuerKeysSupportedWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeNumberOfAliroCredentialIssuerKeysSupportedWithCompletion:completion];
}

- (void)readAttributeAppleNumberOfAliroEndpointKeysSupportedWithCompletion:(void (^)(NSNumber * _Nullable value, NSError * _Nullable error))completion MTR_AVAILABLE(ios(18.4), macos(15.4), watchos(11.4), tvos(18.4));
{
    [self readAttributeNumberOfAliroEndpointKeysSupportedWithCompletion:completion];
}

@end
