#import <UIKit/UIKit.h>

// Measurements of the host's own symbols, written out as the header the port draws by and the expectations of the device test.

static NSArray<NSString *> *record_names(NSString *path)
{
    NSMutableArray *names = [NSMutableArray array];
    for (NSString *line in [[NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil] componentsSeparatedByString:@"\n"]) {
        NSString *name = [line stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
        if (name.length && [UIImage systemImageNamed:name] && ![names containsObject:name])
            [names addObject:name];
    }
    return [names sortedArrayUsingSelector:@selector(compare:)];
}

static UIImage *record_host_image(NSString *name, double pointSize, NSInteger weight, NSInteger scale)
{
    return [UIImage systemImageNamed:name withConfiguration:[UIImageSymbolConfiguration configurationWithPointSize:pointSize weight:(UIImageSymbolWeight)weight scale:(UIImageSymbolScale)scale]];
}

// Renders an image into an 8 bit alpha bitmap of the given pixel size, the image scaled into the rectangle.
static NSData *record_alpha(UIImage *image, CGSize canvas, CGRect rect, CGFloat scale)
{
    size_t width = (size_t)ceil(canvas.width * scale), height = (size_t)ceil(canvas.height * scale);
    UIGraphicsBeginImageContextWithOptions(canvas, NO, scale);
    [[image imageWithTintColor:[UIColor blackColor] renderingMode:UIImageRenderingModeAlwaysOriginal] drawInRect:rect];
    UIImage *rendered = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    NSMutableData *data = [NSMutableData dataWithLength:width * height];
    CGContextRef context = CGBitmapContextCreate(data.mutableBytes, width, height, 8, width, NULL, kCGImageAlphaOnly);
    CGContextDrawImage(context, CGRectMake(0, 0, width, height), rendered.CGImage);
    CGContextRelease(context);
    return data;
}

static NSData *record_alpha_of(UIImage *image, CGFloat scale)
{
    return record_alpha(image, image.size, CGRectMake(0, 0, image.size.width, image.size.height), scale);
}

// The ink of an alpha bitmap: left, top, right, bottom in points.
static CGRect record_ink(NSData *alpha, CGSize canvas, CGFloat scale)
{
    size_t width = (size_t)ceil(canvas.width * scale), height = (size_t)ceil(canvas.height * scale);
    const uint8_t *pixels = alpha.bytes;
    long left = (long)width, top = (long)height, right = -1, bottom = -1;
    for (size_t y = 0; y < height; y++)
        for (size_t x = 0; x < width; x++)
            if (pixels[y * width + x] > 127) {
                left = MIN(left, (long)x); right = MAX(right, (long)x); top = MIN(top, (long)y); bottom = MAX(bottom, (long)y);
            }
    if (right < 0)
        return CGRectZero;
    return CGRectMake(left / scale, top / scale, (right + 1 - left) / scale, (bottom + 1 - top) / scale);
}

// A 16 by 16 grid of the cells whose mean alpha is at least half, a row to a 16 bit word.
static void record_bits(NSData *alpha, CGSize canvas, CGFloat scale, uint16_t out[16])
{
    size_t width = (size_t)ceil(canvas.width * scale), height = (size_t)ceil(canvas.height * scale);
    const uint8_t *pixels = alpha.bytes;
    for (int gy = 0; gy < 16; gy++) {
        unsigned row = 0;
        for (int gx = 0; gx < 16; gx++) {
            double sum = 0;
            long count = 0;
            for (size_t y = gy * height / 16; y < (gy + 1) * height / 16; y++)
                for (size_t x = gx * width / 16; x < (gx + 1) * width / 16; x++) {
                    sum += pixels[y * width + x];
                    count++;
                }
            row = (row << 1) | ((count && sum / count >= 127.5) ? 1 : 0);
        }
        out[gy] = (uint16_t)row;
    }
}

static int record_half(double value)
{
    return (int)lround(value * 2);
}

static NSString *record_metrics_header(NSArray<NSString *> *names)
{
    static const double sizes[2] = {17, 100};
    static const int weights[4] = {1, 4, 7, 9};
    NSMutableString *out = [NSMutableString stringWithString:@"// Generated by tests/backports/host/uikit2 (the symbols group) from measurements of the host's own UIKit. Do not edit.\n"
                            "// Sizes, insets and the margins around the drawing are in half points.\n\n"];
    [out appendFormat:@"#define CHARON_SYMBOL_COUNT %lu\n\nstatic const char *const CharonSymbolNames[CHARON_SYMBOL_COUNT] = {\n", (unsigned long)names.count];
    for (NSString *name in names)
        [out appendFormat:@"    \"%@\",\n", name];
    [out appendString:@"};\n\n// [pointSize 17, 100][weight 1, 4, 7, 9][scale small, medium, large][width, height, bottom inset]\n"
                       "static const int16_t CharonSymbolGrid[CHARON_SYMBOL_COUNT][72] = {\n"];
    NSMutableString *sides = [NSMutableString string];
    NSMutableString *margins = [NSMutableString string];
    NSUInteger index = 0;
    for (NSString *name in names) {
        NSMutableArray *grid = [NSMutableArray array], *lr = [NSMutableArray array];
        BOOL any = NO;
        for (int p = 0; p < 2; p++)
            for (int w = 0; w < 4; w++)
                for (int s = 1; s <= 3; s++) {
                    UIImage *image = record_host_image(name, sizes[p], weights[w], s);
                    UIEdgeInsets insets = image.alignmentRectInsets;
                    [grid addObject:@(record_half(image.size.width))];
                    [grid addObject:@(record_half(image.size.height))];
                    [grid addObject:@(record_half(insets.bottom))];
                    [lr addObject:@(record_half(insets.left))];
                    [lr addObject:@(record_half(insets.right))];
                    any = any || insets.left != 0 || insets.right != 0;
                }
        [out appendFormat:@"    {%@},\n", [grid componentsJoinedByString:@","]];
        if (any)
            [sides appendFormat:@"    {%lu, {%@}},\n", (unsigned long)index, [lr componentsJoinedByString:@","]];
        NSMutableArray *edges = [NSMutableArray array];
        for (int s = 1; s <= 3; s++) {
            UIImage *image = record_host_image(name, 100, 4, s);
            NSData *alpha = record_alpha_of(image, 8);
            CGRect ink = record_ink(alpha, image.size, 8);
            [edges addObjectsFromArray:@[@(record_half(CGRectGetMinX(ink))), @(record_half(CGRectGetMinY(ink))), @(record_half(image.size.width - CGRectGetMaxX(ink))),
                                         @(record_half(image.size.height - CGRectGetMaxY(ink)))]];
        }
        [margins appendFormat:@"    {%@},\n", [edges componentsJoinedByString:@","]];
        index++;
    }
    [out appendString:@"};\n\n// The left and right insets of the glyphs that have them, in the order of the grid: [pointSize][weight][scale][left, right]\n"
                       "static const struct { uint16_t index; int16_t values[48]; } CharonSymbolSideInsets[] = {\n"];
    [out appendString:sides];
    [out appendString:@"};\n\n// The space between the image and its drawing at 100 points and regular weight: [scale][left, top, right, bottom]\n"
                       "static const int16_t CharonSymbolMargins[CHARON_SYMBOL_COUNT][12] = {\n"];
    [out appendString:margins];
    [out appendString:@"};\n"];
    return out;
}

static NSString *record_expectations_header(NSArray<NSString *> *names)
{
    static const double configs[3][3] = {{17, 4, 2}, {34, 7, 3}, {12, 1, 1}};
    NSMutableString *out = [NSMutableString stringWithString:@"// Generated by tests/backports/host/uikit2 (the symbols group) from the host's own UIKit. Do not edit.\n"
                            "// For each symbol: width, height, alignment insets top, left, bottom, right and baseline offset at 17 points regular medium,\n"
                            "// 34 points bold large and 12 points ultra light small, then the 16 by 16 grid of the cells at least half covered at the first of them.\n\n"];
    [out appendFormat:@"static const struct { const char *name; float metrics[3][7]; uint16_t grid[16]; } CharonSymbolExpectations[] = {\n"];
    for (NSString *name in names) {
        NSMutableArray *rows = [NSMutableArray array];
        uint16_t bits[16] = {0};
        for (int c = 0; c < 3; c++) {
            UIImage *image = record_host_image(name, configs[c][0], (NSInteger)configs[c][1], (NSInteger)configs[c][2]);
            UIEdgeInsets i = image.alignmentRectInsets;
            [rows addObject:[NSString stringWithFormat:@"{%g,%g,%g,%g,%g,%g,%g}", image.size.width, image.size.height, i.top, i.left, i.bottom, i.right, image.baselineOffsetFromBottom]];
            if (c == 0)
                record_bits(record_alpha_of(image, 8), image.size, 8, bits);
        }
        NSMutableArray *words = [NSMutableArray array];
        for (int r = 0; r < 16; r++)
            [words addObject:[NSString stringWithFormat:@"0x%04x", bits[r]]];
        [out appendFormat:@"    {\"%@\", {%@}, {%@}},\n", name, [rows componentsJoinedByString:@","], [words componentsJoinedByString:@","]];
    }
    [out appendString:@"};\n"];
    return out;
}
