#!/usr/bin/env python3
"""Write the Core ML containers the device test carries as a C header.

The device test has to run a real model, and a real model is a .mlmodel file. A test binary
cannot open a file on the developer's machine, so the containers tools/coreml/make-models.py
writes are embedded here, byte for byte, with the name of each and what its answer is expected
to be. The bytes are the specification's own message: nothing is rebuilt here, so what the device
reads is exactly what the host differential and the interpreter check read.

    python3 tools/coreml/embed-models.py <model directory> <output header>
"""
import json
import os
import sys

# The containers to carry, smallest first: a test binary is a release artefact and a model of a
# few hundred bytes keeps it one. The GLM and the GLM classifier are enough to reach the reader,
# the description, a prediction, the class labels and the probabilities.
WANTED = ["glm", "glm_classifier", "tree_classifier", "nn_classifier"]


def escape(data):
    out = []
    for index, byte in enumerate(data):
        if index and index % 16 == 0:
            out.append("\n   ")
        out.append(" 0x%02x," % byte)
    return "".join(out)


def main(models, out):
    manifest_path = os.path.join(models, "manifest.json")
    manifest = json.load(open(manifest_path)) if os.path.exists(manifest_path) else {}
    written = []
    with open(out, "w") as target:
        target.write("/* Generated by tools/coreml/embed-models.py from the containers\n")
        target.write(" * tools/coreml/make-models.py writes. Do not edit by hand: run the generator and read the\n")
        target.write(" * diff. The bytes are the CoreML specification's own message, so what the device reads is what\n")
        target.write(" * the host differential and the interpreter check read. */\n")
        target.write("#ifndef CHARON_COREML_MODELS_H\n#define CHARON_COREML_MODELS_H\n\n")
        for name in WANTED:
            path = os.path.join(models, name + ".mlmodel")
            if not os.path.exists(path):
                continue
            data = open(path, "rb").read()
            guard = "charon_ml_model_" + name
            target.write("static const unsigned char %s[] = {%s\n};\n\n" % (guard, escape(data)))
            written.append((name, guard, len(data), manifest.get(name, {}).get("prediction")))
        target.write("typedef struct {\n"
                     "    const char *name;\n"
                     "    const unsigned char *bytes;\n"
                     "    unsigned long length;\n"
                     "} charon_ml_embedded_model;\n\n")
        target.write("static const charon_ml_embedded_model charon_ml_embedded_models[] = {\n")
        for name, guard, length, _ in written:
            target.write('    { "%s", %s, %dul },\n' % (name, guard, length))
        target.write("    { 0, 0, 0 }\n};\n\n#endif /* CHARON_COREML_MODELS_H */\n")
    for name, _, length, _ in written:
        print("embedded %s: %d bytes" % (name, length))
    if not written:
        print("no containers in %s: run tools/coreml/make-models.py --out %s first" % (models, models))
        return 1
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
