#!/bin/sh
target=$0
while [ -L "$target" ]; do
    link=$(readlink "$target")
    case $link in
        /*) target=$link ;;
        *) target=$(dirname "$target")/$link ;;
    esac
done
here=$(cd "$(dirname "$target")" && pwd)
exec python3 "$here/charon.py" "$@"
