#import <CoreMedia/CoreMedia.h>
#import <CoreVideo/CoreVideo.h>
#import <Foundation/Foundation.h>
#include <string.h>

// Generated from the family's own list of the constants the port carries. run.sh renames each name in
// the port's sources to CharonHost_<name>, so the bare name here is the host's and the CharonHost_
// name is the port's: the same declaration, two definitions, one comparison of the bytes.
static int failures, checks;

static void compare(const char *name, CFStringRef port, CFStringRef system)
{
    char mine[512], theirs[512];
    BOOL mineOk = port && CFStringGetCString(port, mine, sizeof mine, kCFStringEncodingUTF8);
    BOOL theirsOk = system && CFStringGetCString(system, theirs, sizeof theirs, kCFStringEncodingUTF8);
    checks++;
    if (mineOk != theirsOk || (mineOk && strcmp(mine, theirs) != 0)) {
        failures++;
        printf("DIFFERENT %s: port %s, host %s\n", name, mineOk ? mine : "(not a string)", theirsOk ? theirs : "(not a string)");
    }
}

extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_SetupData;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ContentLightLevelInfo;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_MasteringDisplayColorVolume;
extern const CFStringRef CharonHost_kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG;
extern const CFStringRef CharonHost_kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ;
extern const CFStringRef CharonHost_kCMFormatDescriptionTransferFunction_Linear;
extern const CFStringRef CharonHost_kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha;
extern const CFStringRef CharonHost_kCMFormatDescriptionAlphaChannelMode_StraightAlpha;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_AlphaChannelMode;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_AuxiliaryTypeInfo;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ContainsAlphaChannel;
extern const CFStringRef CharonHost_kCMFormatDescriptionTransferFunction_sRGB;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ProtectedContentOriginalFormat;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_AmbientViewingEnvironment;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_BitsPerComponent;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HorizontalFieldOfView;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_AlternativeTransferCharacteristics;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ContentColorVolume;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HasAdditionalViews;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HasLeftStereoEyeView;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HasRightStereoEyeView;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HeroEye;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_HorizontalDisparityAdjustment;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_StereoCameraBaseline;
extern const CFStringRef CharonHost_kCMFormatDescriptionHeroEye_Left;
extern const CFStringRef CharonHost_kCMFormatDescriptionHeroEye_Right;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_LogTransferFunction;
extern const CFStringRef CharonHost_kCMFormatDescriptionLogTransferFunction_AppleLog;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ProjectionKind;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ViewPackingKind;
extern const CFStringRef CharonHost_kCMFormatDescriptionProjectionKind_Equirectangular;
extern const CFStringRef CharonHost_kCMFormatDescriptionProjectionKind_HalfEquirectangular;
extern const CFStringRef CharonHost_kCMFormatDescriptionProjectionKind_Rectilinear;
extern const CFStringRef CharonHost_kCMFormatDescriptionViewPackingKind_OverUnder;
extern const CFStringRef CharonHost_kCMFormatDescriptionViewPackingKind_SideBySide;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationExtrinsicOriginSource_StereoCameraSystemBaseline;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationLensAlgorithmKind_ParametricLens;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationLensDomain_Color;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Left;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Mono;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Right;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_ExtrinsicOrientationQuaternion;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_ExtrinsicOriginSource;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrix;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrixProjectionOffset;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrixReferenceDimensions;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensAlgorithmKind;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensDistortions;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensDomain;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialX;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialY;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensIdentifier;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_LensRole;
extern const CFStringRef CharonHost_kCMFormatDescriptionCameraCalibration_RadialAngleLimit;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_CameraCalibrationDataLensCollection;
extern const CFStringRef CharonHost_kCMFormatDescriptionExtension_ConvertedFromExternalSphericalTags;
extern const CFStringRef CharonHost_kCMFormatDescriptionProjectionKind_AppleImmersiveVideo;
extern const CFStringRef CharonHost_kCMFormatDescriptionProjectionKind_ParametricImmersive;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_ConformingDataTypes;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_DataType;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_DataTypeNamespace;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_LanguageTag;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier;
extern const CFStringRef CharonHost_kCMFormatDescriptionColorPrimaries_DCI_P3;
extern const CFStringRef CharonHost_kCMFormatDescriptionColorPrimaries_ITU_R_2020;
extern const CFStringRef CharonHost_kCMFormatDescriptionColorPrimaries_P3_D65;
extern const CFStringRef CharonHost_kCMFormatDescriptionTransferFunction_ITU_R_2020;
extern const CFStringRef CharonHost_kCMFormatDescriptionYCbCrMatrix_ITU_R_2020;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionKey_StructuralDependency;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData;
extern const CFStringRef CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency;
extern const CFStringRef CharonHost_kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag;

int main(void)
{
    @autoreleasepool {
        compare("kCMMetadataFormatDescriptionKey_SetupData", CharonHost_kCMMetadataFormatDescriptionKey_SetupData, kCMMetadataFormatDescriptionKey_SetupData);
        compare("kCMFormatDescriptionExtension_ContentLightLevelInfo", CharonHost_kCMFormatDescriptionExtension_ContentLightLevelInfo, kCMFormatDescriptionExtension_ContentLightLevelInfo);
        compare("kCMFormatDescriptionExtension_MasteringDisplayColorVolume", CharonHost_kCMFormatDescriptionExtension_MasteringDisplayColorVolume, kCMFormatDescriptionExtension_MasteringDisplayColorVolume);
        compare("kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG", CharonHost_kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG, kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG);
        compare("kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ", CharonHost_kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ, kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ);
        compare("kCMFormatDescriptionTransferFunction_Linear", CharonHost_kCMFormatDescriptionTransferFunction_Linear, kCMFormatDescriptionTransferFunction_Linear);
        compare("kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha", CharonHost_kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha, kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha);
        compare("kCMFormatDescriptionAlphaChannelMode_StraightAlpha", CharonHost_kCMFormatDescriptionAlphaChannelMode_StraightAlpha, kCMFormatDescriptionAlphaChannelMode_StraightAlpha);
        compare("kCMFormatDescriptionExtension_AlphaChannelMode", CharonHost_kCMFormatDescriptionExtension_AlphaChannelMode, kCMFormatDescriptionExtension_AlphaChannelMode);
        compare("kCMFormatDescriptionExtension_AuxiliaryTypeInfo", CharonHost_kCMFormatDescriptionExtension_AuxiliaryTypeInfo, kCMFormatDescriptionExtension_AuxiliaryTypeInfo);
        compare("kCMFormatDescriptionExtension_ContainsAlphaChannel", CharonHost_kCMFormatDescriptionExtension_ContainsAlphaChannel, kCMFormatDescriptionExtension_ContainsAlphaChannel);
        compare("kCMFormatDescriptionTransferFunction_sRGB", CharonHost_kCMFormatDescriptionTransferFunction_sRGB, kCMFormatDescriptionTransferFunction_sRGB);
        compare("kCMFormatDescriptionExtension_ProtectedContentOriginalFormat", CharonHost_kCMFormatDescriptionExtension_ProtectedContentOriginalFormat, kCMFormatDescriptionExtension_ProtectedContentOriginalFormat);
        compare("kCMFormatDescriptionExtension_AmbientViewingEnvironment", CharonHost_kCMFormatDescriptionExtension_AmbientViewingEnvironment, kCMFormatDescriptionExtension_AmbientViewingEnvironment);
        compare("kCMFormatDescriptionExtension_BitsPerComponent", CharonHost_kCMFormatDescriptionExtension_BitsPerComponent, kCMFormatDescriptionExtension_BitsPerComponent);
        compare("kCMFormatDescriptionExtension_HorizontalFieldOfView", CharonHost_kCMFormatDescriptionExtension_HorizontalFieldOfView, kCMFormatDescriptionExtension_HorizontalFieldOfView);
        compare("kCMFormatDescriptionExtension_AlternativeTransferCharacteristics", CharonHost_kCMFormatDescriptionExtension_AlternativeTransferCharacteristics, kCMFormatDescriptionExtension_AlternativeTransferCharacteristics);
        compare("kCMFormatDescriptionExtension_ContentColorVolume", CharonHost_kCMFormatDescriptionExtension_ContentColorVolume, kCMFormatDescriptionExtension_ContentColorVolume);
        compare("kCMFormatDescriptionExtension_HasAdditionalViews", CharonHost_kCMFormatDescriptionExtension_HasAdditionalViews, kCMFormatDescriptionExtension_HasAdditionalViews);
        compare("kCMFormatDescriptionExtension_HasLeftStereoEyeView", CharonHost_kCMFormatDescriptionExtension_HasLeftStereoEyeView, kCMFormatDescriptionExtension_HasLeftStereoEyeView);
        compare("kCMFormatDescriptionExtension_HasRightStereoEyeView", CharonHost_kCMFormatDescriptionExtension_HasRightStereoEyeView, kCMFormatDescriptionExtension_HasRightStereoEyeView);
        compare("kCMFormatDescriptionExtension_HeroEye", CharonHost_kCMFormatDescriptionExtension_HeroEye, kCMFormatDescriptionExtension_HeroEye);
        compare("kCMFormatDescriptionExtension_HorizontalDisparityAdjustment", CharonHost_kCMFormatDescriptionExtension_HorizontalDisparityAdjustment, kCMFormatDescriptionExtension_HorizontalDisparityAdjustment);
        compare("kCMFormatDescriptionExtension_StereoCameraBaseline", CharonHost_kCMFormatDescriptionExtension_StereoCameraBaseline, kCMFormatDescriptionExtension_StereoCameraBaseline);
        compare("kCMFormatDescriptionHeroEye_Left", CharonHost_kCMFormatDescriptionHeroEye_Left, kCMFormatDescriptionHeroEye_Left);
        compare("kCMFormatDescriptionHeroEye_Right", CharonHost_kCMFormatDescriptionHeroEye_Right, kCMFormatDescriptionHeroEye_Right);
        compare("kCMFormatDescriptionExtension_LogTransferFunction", CharonHost_kCMFormatDescriptionExtension_LogTransferFunction, kCMFormatDescriptionExtension_LogTransferFunction);
        compare("kCMFormatDescriptionLogTransferFunction_AppleLog", CharonHost_kCMFormatDescriptionLogTransferFunction_AppleLog, kCMFormatDescriptionLogTransferFunction_AppleLog);
        compare("kCMFormatDescriptionExtension_ProjectionKind", CharonHost_kCMFormatDescriptionExtension_ProjectionKind, kCMFormatDescriptionExtension_ProjectionKind);
        compare("kCMFormatDescriptionExtension_ViewPackingKind", CharonHost_kCMFormatDescriptionExtension_ViewPackingKind, kCMFormatDescriptionExtension_ViewPackingKind);
        compare("kCMFormatDescriptionProjectionKind_Equirectangular", CharonHost_kCMFormatDescriptionProjectionKind_Equirectangular, kCMFormatDescriptionProjectionKind_Equirectangular);
        compare("kCMFormatDescriptionProjectionKind_HalfEquirectangular", CharonHost_kCMFormatDescriptionProjectionKind_HalfEquirectangular, kCMFormatDescriptionProjectionKind_HalfEquirectangular);
        compare("kCMFormatDescriptionProjectionKind_Rectilinear", CharonHost_kCMFormatDescriptionProjectionKind_Rectilinear, kCMFormatDescriptionProjectionKind_Rectilinear);
        compare("kCMFormatDescriptionViewPackingKind_OverUnder", CharonHost_kCMFormatDescriptionViewPackingKind_OverUnder, kCMFormatDescriptionViewPackingKind_OverUnder);
        compare("kCMFormatDescriptionViewPackingKind_SideBySide", CharonHost_kCMFormatDescriptionViewPackingKind_SideBySide, kCMFormatDescriptionViewPackingKind_SideBySide);
        compare("kCMFormatDescriptionCameraCalibrationExtrinsicOriginSource_StereoCameraSystemBaseline", CharonHost_kCMFormatDescriptionCameraCalibrationExtrinsicOriginSource_StereoCameraSystemBaseline, kCMFormatDescriptionCameraCalibrationExtrinsicOriginSource_StereoCameraSystemBaseline);
        compare("kCMFormatDescriptionCameraCalibrationLensAlgorithmKind_ParametricLens", CharonHost_kCMFormatDescriptionCameraCalibrationLensAlgorithmKind_ParametricLens, kCMFormatDescriptionCameraCalibrationLensAlgorithmKind_ParametricLens);
        compare("kCMFormatDescriptionCameraCalibrationLensDomain_Color", CharonHost_kCMFormatDescriptionCameraCalibrationLensDomain_Color, kCMFormatDescriptionCameraCalibrationLensDomain_Color);
        compare("kCMFormatDescriptionCameraCalibrationLensRole_Left", CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Left, kCMFormatDescriptionCameraCalibrationLensRole_Left);
        compare("kCMFormatDescriptionCameraCalibrationLensRole_Mono", CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Mono, kCMFormatDescriptionCameraCalibrationLensRole_Mono);
        compare("kCMFormatDescriptionCameraCalibrationLensRole_Right", CharonHost_kCMFormatDescriptionCameraCalibrationLensRole_Right, kCMFormatDescriptionCameraCalibrationLensRole_Right);
        compare("kCMFormatDescriptionCameraCalibration_ExtrinsicOrientationQuaternion", CharonHost_kCMFormatDescriptionCameraCalibration_ExtrinsicOrientationQuaternion, kCMFormatDescriptionCameraCalibration_ExtrinsicOrientationQuaternion);
        compare("kCMFormatDescriptionCameraCalibration_ExtrinsicOriginSource", CharonHost_kCMFormatDescriptionCameraCalibration_ExtrinsicOriginSource, kCMFormatDescriptionCameraCalibration_ExtrinsicOriginSource);
        compare("kCMFormatDescriptionCameraCalibration_IntrinsicMatrix", CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrix, kCMFormatDescriptionCameraCalibration_IntrinsicMatrix);
        compare("kCMFormatDescriptionCameraCalibration_IntrinsicMatrixProjectionOffset", CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrixProjectionOffset, kCMFormatDescriptionCameraCalibration_IntrinsicMatrixProjectionOffset);
        compare("kCMFormatDescriptionCameraCalibration_IntrinsicMatrixReferenceDimensions", CharonHost_kCMFormatDescriptionCameraCalibration_IntrinsicMatrixReferenceDimensions, kCMFormatDescriptionCameraCalibration_IntrinsicMatrixReferenceDimensions);
        compare("kCMFormatDescriptionCameraCalibration_LensAlgorithmKind", CharonHost_kCMFormatDescriptionCameraCalibration_LensAlgorithmKind, kCMFormatDescriptionCameraCalibration_LensAlgorithmKind);
        compare("kCMFormatDescriptionCameraCalibration_LensDistortions", CharonHost_kCMFormatDescriptionCameraCalibration_LensDistortions, kCMFormatDescriptionCameraCalibration_LensDistortions);
        compare("kCMFormatDescriptionCameraCalibration_LensDomain", CharonHost_kCMFormatDescriptionCameraCalibration_LensDomain, kCMFormatDescriptionCameraCalibration_LensDomain);
        compare("kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialX", CharonHost_kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialX, kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialX);
        compare("kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialY", CharonHost_kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialY, kCMFormatDescriptionCameraCalibration_LensFrameAdjustmentsPolynomialY);
        compare("kCMFormatDescriptionCameraCalibration_LensIdentifier", CharonHost_kCMFormatDescriptionCameraCalibration_LensIdentifier, kCMFormatDescriptionCameraCalibration_LensIdentifier);
        compare("kCMFormatDescriptionCameraCalibration_LensRole", CharonHost_kCMFormatDescriptionCameraCalibration_LensRole, kCMFormatDescriptionCameraCalibration_LensRole);
        compare("kCMFormatDescriptionCameraCalibration_RadialAngleLimit", CharonHost_kCMFormatDescriptionCameraCalibration_RadialAngleLimit, kCMFormatDescriptionCameraCalibration_RadialAngleLimit);
        compare("kCMFormatDescriptionExtension_CameraCalibrationDataLensCollection", CharonHost_kCMFormatDescriptionExtension_CameraCalibrationDataLensCollection, kCMFormatDescriptionExtension_CameraCalibrationDataLensCollection);
        compare("kCMFormatDescriptionExtension_ConvertedFromExternalSphericalTags", CharonHost_kCMFormatDescriptionExtension_ConvertedFromExternalSphericalTags, kCMFormatDescriptionExtension_ConvertedFromExternalSphericalTags);
        compare("kCMFormatDescriptionProjectionKind_AppleImmersiveVideo", CharonHost_kCMFormatDescriptionProjectionKind_AppleImmersiveVideo, kCMFormatDescriptionProjectionKind_AppleImmersiveVideo);
        compare("kCMFormatDescriptionProjectionKind_ParametricImmersive", CharonHost_kCMFormatDescriptionProjectionKind_ParametricImmersive, kCMFormatDescriptionProjectionKind_ParametricImmersive);
        compare("kCMMetadataFormatDescriptionKey_ConformingDataTypes", CharonHost_kCMMetadataFormatDescriptionKey_ConformingDataTypes, kCMMetadataFormatDescriptionKey_ConformingDataTypes);
        compare("kCMMetadataFormatDescriptionKey_DataType", CharonHost_kCMMetadataFormatDescriptionKey_DataType, kCMMetadataFormatDescriptionKey_DataType);
        compare("kCMMetadataFormatDescriptionKey_DataTypeNamespace", CharonHost_kCMMetadataFormatDescriptionKey_DataTypeNamespace, kCMMetadataFormatDescriptionKey_DataTypeNamespace);
        compare("kCMMetadataFormatDescriptionKey_LanguageTag", CharonHost_kCMMetadataFormatDescriptionKey_LanguageTag, kCMMetadataFormatDescriptionKey_LanguageTag);
        compare("kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType", CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType, kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType);
        compare("kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag", CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag, kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag);
        compare("kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier", CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier, kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier);
        compare("kCMFormatDescriptionColorPrimaries_DCI_P3", CharonHost_kCMFormatDescriptionColorPrimaries_DCI_P3, kCMFormatDescriptionColorPrimaries_DCI_P3);
        compare("kCMFormatDescriptionColorPrimaries_ITU_R_2020", CharonHost_kCMFormatDescriptionColorPrimaries_ITU_R_2020, kCMFormatDescriptionColorPrimaries_ITU_R_2020);
        compare("kCMFormatDescriptionColorPrimaries_P3_D65", CharonHost_kCMFormatDescriptionColorPrimaries_P3_D65, kCMFormatDescriptionColorPrimaries_P3_D65);
        compare("kCMFormatDescriptionTransferFunction_ITU_R_2020", CharonHost_kCMFormatDescriptionTransferFunction_ITU_R_2020, kCMFormatDescriptionTransferFunction_ITU_R_2020);
        compare("kCMFormatDescriptionYCbCrMatrix_ITU_R_2020", CharonHost_kCMFormatDescriptionYCbCrMatrix_ITU_R_2020, kCMFormatDescriptionYCbCrMatrix_ITU_R_2020);
        compare("kCMMetadataFormatDescriptionKey_StructuralDependency", CharonHost_kCMMetadataFormatDescriptionKey_StructuralDependency, kCMMetadataFormatDescriptionKey_StructuralDependency);
        compare("kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData", CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData, kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData);
        compare("kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency", CharonHost_kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency, kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency);
        compare("kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag", CharonHost_kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag, kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag);
        printf("%d checks, %d different\n", checks, failures);
    }
    return failures != 0;
}
