rule("daemon")
    add_deps("@self/apple-ios")

    on_load(function (target)
        target:set("kind", "binary")
        target:add("packages", "ldid", "firmware-tools")
    end)

    after_link(function (target)
        import("@self.apple.platform")
        platform.verify_packages(target)
        platform.verify_inputs(target)
        platform.verify_placed(target, (target:values("charon.install") or "/usr/libexec") .. "/" .. target:filename())
    end)

    on_install(function (target)
        import("@self.apple.platform")
        platform.install_placed(target, (target:values("charon.install") or "/usr/libexec") .. "/" .. target:filename())
        platform.install_files(target)
    end)
