#!/bin/zsh
# This is the actual generator for caches/sel/*.strings -- crash-demand.py's SEVENTH blind-spot
# note called that directory "not regenerated by anything in this repo" because this script was
# undiscoverable: it pointed at a dead Claude session's own per-session /private/tmp scratchpad
# (claude-501/.../priceless-kepler-a7622c/.../scratchpad), gone the moment that session's temp
# dir was cleaned. The real input, $HOME/.charon/dyld/, is durable; only the output path was
# wrong. Fixed to write to the same durable caches/ this session moved everything else to.
CACHES=${CHARON_CACHES_DIR:-$HOME/Git/projects/ios/coordination/corpus/caches}
mkdir -p "$CACHES/sel"
for pair in "7.0.1:dyld_shared_cache_arm64" "10.3.4:dyld_shared_cache_armv7s" "12.0:dyld_shared_cache_arm64"; do
  v=${pair%%:*}; f=${pair##*:}
  strings -a -n 3 "$HOME/.charon/dyld/$v/$f" | sort -u > "$CACHES/sel/$v.strings"
  echo "$v: $(wc -l < "$CACHES/sel/$v.strings") strings"
done
echo SEL-UNIVERSE-DONE
