#!/bin/sh
# check-harness-invokers.sh - the invoker list in Census.md is GENERATED, and this compares it.
#
#     sh tests/backports/host/metal-census/check-harness-invokers.sh
#     SELF_TEST=1 sh tests/backports/host/metal-census/check-harness-invokers.sh
#
# WHY THIS EXISTS: Census.md claimed the five harnesses in this directory are "named only by itself
# and by the facts file that describes it". That was false for three of the five - check-split-control
# INVOKES pre-export.sh, and argbinding.sh and reflection.m each name another harness in their header
# - so a sentence in a facts file had been wrong, and nothing checked it. A sentence cannot be
# diffed, so the falsifiable part of it is a GENERATED BLOCK between two markers, and this
# regenerates that block by the same `git grep` and refuses to pass when the two differ. Adding an
# invoker changes git grep's answer, so the block goes stale and this goes red; SELF_TEST=1 does
# exactly that with a fake invoker and requires the red.
#
# The block answers ONE question - what names each harness, and where - and not the one the sentence
# was reaching for. Whether any of it runs automatically is a separate question, measured by
# COUNTING invokers outside this directory, and it is reported here too.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../../../.." && pwd)
facts=$root/packages/a/apple-backports/facts/Metal/Census.md
work=${WORK:-$root/.agent-work/runs/metal-census/invokers}
# ONE guard for every script that removes a scratch path - see work-guard.sh.
. "$here/work-guard.sh"
work_ok "$work" || { echo "FAIL: WORK=$work is not a usable scratch path; see work-guard.sh" >&2; exit 1; }
rm -rf "$work"
mkdir -p "$work"

BEGIN='<!-- invokers: generated by check-harness-invokers.sh, do not edit by hand -->'
END='<!-- invokers: end -->'

# EVERY harness in this directory, so a new one is covered by the NEXT run rather than by whoever
# remembers to add it here: the list is the directory listing, which is what made the original claim
# checkable in the first place. work-guard.sh is a sourced library and is not a harness.
harnesses=$(cd "$here" && ls *.sh | grep -v "^work-guard\.sh$" | tr "\n" " ")

# The block, exactly as the facts file must carry it.
generate() {
    printf '%s\n' "$BEGIN"
    printf '%s\n' '```'
    for h in $harnesses; do
        # EXACT PATH EQUALITY, not a "^./" prefix: git grep prints `tests/...` with no leading
        # "./" whatever pathspec it is given, so a "^./tests/..." filter never matched and every
        # harness listed ITSELF - which is the very falsehood this check exists to catch.
        me="tests/backports/host/metal-census/$h"
        # BARE OR BY PATH, BUT NEVER ANOTHER DIRECTORY'S COPY. Searching the path alone misses a
        # file that says "sh check-split-control.sh"; searching the bare name alone matches
        # units/run.sh, pixel/run.sh and modelio/run.sh, which are not this harness. A line counts
        # when the name appears bare or after THIS directory's path, and never after another's.
        names=$(cd "$root" && git grep -n -F "$h" -- . \
            | grep -E "(^|[^A-Za-z0-9_./-])$h|metal-census/$h" | cut -d: -f1 | sort -u \
            | grep -v -x -F "$me" \
            | grep -v -x -F "tests/backports/host/metal-census/check-harness-invokers.sh" \
            | tr '\n' '\n' | sed 's/ $//' | tr '\n' ' ' | sed 's/ $//')
        [ -n "$names" ] || names='(nothing in the tree)'
        printf '%-24s %s\n' "$h" "$names"
    done
    printf '%s\n' '```'
    printf '%s\n' "$END"
}

block_matches() {   # the committed block against the generated one, line for line
    generate > "$work/generated.txt"
    awk -v b="$BEGIN" -v e="$END" 'index($0,b){on=1} on{print} index($0,e){on=0}' "$facts" \
        > "$work/committed.txt"
    if [ ! -s "$work/committed.txt" ]; then
        echo "FAIL: $facts has no generated invoker block between its markers" >&2
        return 1
    fi
    if ! diff -u "$work/committed.txt" "$work/generated.txt" > "$work/diff.txt" 2>&1; then
        echo "FAIL: the invoker list in $facts is stale; regenerate it" >&2
        sed 's/^/    /' "$work/diff.txt" >&2
        return 1
    fi
    return 0
}

# THE RED CONTROL: a fake invoker, and this check must refuse while it is there. A control that
# cannot go red proves nothing, and this one is what keeps the sentence honest.
if [ -n "${SELF_TEST:-}" ]; then
    fake="$here/zz-fake-invoker.sh"
    [ -e "$fake" ] && { echo "FAIL: $fake already exists; refusing to touch it" >&2; exit 1; }
    cleanup() {
        git -C "$root" rm --cached -f --ignore-unmatch "tests/backports/host/metal-census/zz-fake-invoker.sh" >/dev/null 2>&1 || true
        rm -f "$fake"
    }
    trap cleanup EXIT
    printf '%s\n' '#!/bin/sh' 'sh tests/backports/host/metal-census/stitch.sh' > "$fake"
    # -N so the file is VISIBLE to git grep without being committed: the question is what the tree
    # names, and a file nobody added is not yet part of the tree
    git -C "$root" add -N -- "tests/backports/host/metal-census/zz-fake-invoker.sh"
    if block_matches; then
        echo "FAIL: the self-test's fake invoker did not make the check red" >&2
        exit 1
    fi
    echo "  ok   the self-test's NEGATIVE: a fake invoker is caught, so the block cannot go stale"
    cleanup
    trap - EXIT
    if ! block_matches; then
        echo "FAIL: with the fake invoker removed the check is still red" >&2
        exit 1
    fi
    echo "  ok   the self-test's POSITIVE: the real tree matches the block again"
    rm -rf "$work"
    exit 0
fi


if ! block_matches; then
    rm -rf "$work"
    exit 1
fi

# THE OTHER HALF, measured rather than asserted, and it is what Census.md actually claims. Two things
# were wrong here before. The files were counted ONCE PER HARNESS, so a facts file naming two of them
# counted twice and the number meant nothing; they are DISTINCT files now. And "nothing outside the
# directory names them" is FALSE - four facts files name them - so the claim is restated as what is
# true and enforceable: every mention outside this directory is DOCUMENTATION under facts/, and
# nothing outside the directory drives a harness. A file that is not a facts file is a failure.
echo "  the generated block matches $facts"
outside=$(for h in $harnesses; do
    (cd "$root" && git grep -l -F "$h" -- . | grep -E "(^|[^A-Za-z0-9_./-])$h|metal-census/$h" | cut -d: -f1) | grep -v "^tests/backports/host/metal-census/"
done | sort -u)
count=$(printf '%s\n' "$outside" | grep -c . || true)
echo "  $count distinct file(s) outside this directory mention them:"
printf '%s\n' "$outside" | sed 's/^/    /'
# run.sh IS METALKIT'S OWN DIFFERENTIAL and tools/matter-host-diff.lua and
# tools/matter-pure-diff.lua really do drive it, so it is excluded from the failure set and NOT
# hidden: its drivers are in the generated block above, and the exclusion is named here rather than
# applied silently. The census harnesses are the ones nothing outside this directory may drive.
notfacts=$(printf '%s\n' "$outside" \
    | grep -v "^packages/a/apple-backports/facts/" \
    | grep -v "tools/matter-.*-diff\.lua" || true)
if [ -n "$notfacts" ]; then
    echo "FAIL: something outside this directory that is NOT a facts file now names a harness:" >&2
    printf '%s\n' "$notfacts" | sed 's/^/    /' >&2
    exit 1
fi
echo "  and all of them are facts files, so nothing outside this directory drives a harness"
echo "check-harness-invokers: OK"
# THE SCRATCH IS REMOVED HERE.
rm -rf "$work"
