os = "iOS"
sdk = "iphoneos"
deployment-environment = "IPHONEOS_DEPLOYMENT_TARGET"
distributions = ["jailbreak", "trollstore", "sideload"]
tool-requires = ["iphoneos-sdk/13.7@charon/stable"]
python-requires = ["charon-apple/1.0@charon/stable"]
extends = ["charon-apple.ApplePort"]
cross-toolchain = "apple-ios.cross-toolchain.cmake"
sysroot-conf = "tools.apple:sdk_path"

[compiler]
libcxx = "libc++"

[conf]
"tools.cmake.cmaketoolchain:generator" = "Ninja"

[architectures.armv7]
os-version = { min = "6.0" }
tool-requires = ["ld64/956.6@charon/stable"]

[architectures.armv8]
os-version = { min = "7.0" }
