static const char *const appgroup_expectations[] = {
    "/Library/Group Containers/group.test.app file 1 dir-url 1",
    "/Library/Group Containers/ABCDE12345.shared file 1 dir-url 1",
    "nil",
    "/Library/Group Containers/a file 1 dir-url 1",
    "/Library/Group Containers/group.a-b file 1 dir-url 1",
    "/Library/Group Containers/..-x file 1 dir-url 1",
    "/Library/Group Containers/group.with space file 1 dir-url 1",
    "/Library/Group Containers/group.e file 1 dir-url 1",
    "/Library/Group Containers/group.un file 1 dir-url 1",
    "/Library/Group Containers/group.-- file 1 dir-url 1",
    "/Library/Group Containers/GROUP.Mixed file 1 dir-url 1",
    "/Library/Group Containers/group.a-b file 1 dir-url 1",
    "/Library/Group Containers/group.a-b file 1 dir-url 1",
    "/Library/Group Containers/   file 1 dir-url 1",
    "/Library/Group Containers/group.e- file 1 dir-url 1",
    "/Library/Group Containers/group.a-b-c-d-e-f file 1 dir-url 1",
    "/Library/Group Containers/g-1--2--3- file 1 dir-url 1",
    "/Library/Group Containers/group.- file 1 dir-url 1",
    "/Library/Group Containers/a-b-c-d-e file 1 dir-url 1",
    "/Library/Group Containers/UPPER lower_09.- file 1 dir-url 1",
};
