static const char contacts_expectations[] =
    "{\"contact.birthday\":\"1990-5-17\",\"contact.contactType\":\"person\",\"contact.copyClass\":\"CNContact\",\"contact.copyEqual\":\"1\",\"contact.identifierNonEmpty\":\"1\",\"contact"
    ".mutableCopyIndependent\":\"original=Jane copy=Other\",\"contact.notEqualAfterChange\":\"1\",\"contact.values\":\"Jane|Doe|Acme|phones=1|emails=1\",\"contactProperty.plainI"
    "nit\":\"contact=0 key=0 value=0 identifier=0 label=0\",\"container.predicateByIdentifiersIsPredicate\":\"1\",\"container.predicateOfContactIsPredicate\":\"1\",\"container.p"
    "redicateOfGroupIsPredicate\":\"1\",\"container.typeValues\":\"0|1|2|3\",\"defaults.countryCodeIsTwoLetters\":\"1\",\"defaults.sortOrderIsKnown\":\"1\",\"formatter.classFullName"
    "\":\"Jane Doe\",\"formatter.descriptorConforms\":\"1\",\"formatter.emptyContact\":\"1\",\"formatter.fullName\":\"Jane Doe\",\"formatter.nameOrder\":\"given\",\"formatter.nilContact"
    "\":\"1\",\"formatter.organizationName\":\"Acme\",\"group.mutableIdentifierNonEmpty\":\"1\",\"group.mutableName\":\"Friends\",\"group.plainInitEmptyName\":\"1\",\"group.plainInitNon"
    "EmptyIdentifier\":\"1\",\"group.predicateByIdentifiersIsPredicate\":\"1\",\"group.predicateInContainerIsPredicate\":\"1\",\"instantMessage.values\":\"handle|AIM|equal=1\",\"lab"
    "eled.copy\":\"same=0 equal=1\",\"labeled.relabel\":\"label=_$!<Work>!$_ value=a@b.c sameIdentifier=1\",\"labeled.revalue\":\"label=_$!<Home>!$_ value=x@y.z sameIdentifier"
    "=1\",\"labeled.values\":\"label=_$!<Home>!$_ value=a@b.c identifierNonEmpty=1\",\"phone.copy\":\"same=1 equal=1\",\"phone.equality\":\"same=0 isEqual=1 hash=1 other=0\",\"pho"
    "ne.stringValue\":\"+15551234\",\"postal.copy\":\"class=CNPostalAddress equal=1\",\"postal.fields\":\"1 Infinite Loop|Cupertino|CA|95014|United States|us\",\"postal.mutableC"
    "opyIndependent\":\"original=Cupertino copy=Elsewhere\",\"postalFormatter.instance\":\"1 Infinite Loop\\nCupertino CA 95014\\nUnited States\",\"postalFormatter.mailing\":\"1"
    " Infinite Loop\\nCupertino CA 95014\\nUnited States\",\"predicate.describes.containerIdentifiers\":\"1\",\"predicate.describes.containerOfContact\":\"1\",\"predicate.descri"
    "bes.containerOfGroup\":\"1\",\"predicate.describes.email\":\"1\",\"predicate.describes.groupIdentifiers\":\"1\",\"predicate.describes.groupsInContainer\":\"1\",\"predicate.desc"
    "ribes.identifiers\":\"1\",\"predicate.describes.inContainer\":\"1\",\"predicate.describes.inGroup\":\"1\",\"predicate.describes.name\":\"1\",\"predicate.describes.phone\":\"1\",\"p"
    "redicate.equalForSameArguments\":\"1\",\"predicate.fetchRequestArchivesPredicate\":\"1\",\"predicate.fetchRequestRoundTrip\":\"kept\",\"predicate.format.containerIdentifier"
    "s\":\"identifier IN {\\\"C1\\\"}\",\"predicate.format.containerOfContact\":\"(nil)\",\"predicate.format.containerOfGroup\":\"(nil)\",\"predicate.format.email\":\"(nil)\",\"predicat"
    "e.format.groupIdentifiers\":\"identifier IN {\\\"G1\\\"}\",\"predicate.format.groupsInContainer\":\"(nil)\",\"predicate.format.identifiers\":\"identifier IN {\\\"A\\\", \\\"B\\\"}\",\""
    "predicate.format.inContainer\":\"(nil)\",\"predicate.format.inGroup\":\"(nil)\",\"predicate.format.name\":\"(nil)\",\"predicate.format.phone\":\"(nil)\",\"predicate.identifiers"
    "EqualAfterSecureRoundTrip\":\"1\",\"predicate.nameDescriptionNamesFactory\":\"1\",\"predicate.secureRoundTripKeepsClass.containerIdentifiers\":\"1\",\"predicate.secureRound"
    "TripKeepsClass.containerOfContact\":\"1\",\"predicate.secureRoundTripKeepsClass.containerOfGroup\":\"1\",\"predicate.secureRoundTripKeepsClass.email\":\"1\",\"predicate.sec"
    "ureRoundTripKeepsClass.groupIdentifiers\":\"1\",\"predicate.secureRoundTripKeepsClass.groupsInContainer\":\"1\",\"predicate.secureRoundTripKeepsClass.identifiers\":\"1\",\""
    "predicate.secureRoundTripKeepsClass.inContainer\":\"1\",\"predicate.secureRoundTripKeepsClass.inGroup\":\"1\",\"predicate.secureRoundTripKeepsClass.name\":\"1\",\"predicate"
    ".secureRoundTripKeepsClass.phone\":\"1\",\"predicate.unequalForOtherArguments\":\"0\",\"predicate.unequalForOtherKind\":\"0\",\"relation.values\":\"Jane|equal=1\",\"social.valu"
    "es\":\"https://twitter.com/handle|handle|Twitter|equal=1\",\"vcard.badData\":\"result=1 error=0\",\"vcard.encoded\":\"BEGIN:VCARD\\r\\nVERSION:3.0\\r\\nPRODID:-//Apple Inc.//"
    "macOS 27.0//EN\\r\\nN:Appleseed;John;;;\\r\\nFN:John Appleseed\\r\\nTEL;type=CELL;type=VOICE;type=pref:+15551234\\r\\nEND:VCARD\\r\\n\",\"vcard.roundtrip\":\"count=1 given=Jo"
    "hn family=Appleseed phones=1\"}"
;
