static const char custompresentation_expectations[] =
    "{\"bare.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"bare.dismiss.events\":\"willDisappear:bare,didDisappear:bare,completion\",\"bare.dismissed.presenterFr"
    "ame\":\"kept\",\"bare.present.end\":\"presented=1 class=UIPresentationController modalWindow=1 baseWindow=1 modalFrame=containerBounds style=4\",\"bare.present.events\":"
    "\"willAppear:bare,didAppear:bare,completion\",\"dim.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.didPresent\":\"containerSubviews=2 presentedFr"
    "ameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"dim.di"
    "smiss.events\":\"pc:willDismiss,willDisappear:dim,animateTransition,completeTransition,pc:didDismiss:1,didDisappear:dim,completion,animationEnded:1\",\"dim.dismiss."
    "start\":\"from=dim to=base fromViewNil=0 toViewNil=1 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"dim.dismissed.presenterFra"
    "me\":\"kept\",\"dim.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresented style=4\","
    "\"dim.present.events\":\"delegate:presentationController,pc:willPresent,willAppear:dim,animateTransition,completeTransition,pc:didPresent:1,didAppear:dim,completio"
    "n,animationEnded:1\",\"dim.present.layout\":\"laid out\",\"dim.present.start\":\"from=base to=dim fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFr"
    "om=full initialTo=zero finalTo=other\",\"dim.presented.presenterFrame\":\"kept\",\"dim.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindo"
    "w=0 presenterWindow=1\",\"full.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"full.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 pr"
    "esentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"full.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"full.dismiss.events\":\"pc"
    ":willDismiss,willDisappear:full,animateTransition,completeTransition,pc:didDismiss:1,didDisappear:full,completion,animationEnded:1\",\"full.dismiss.start\":\"from=f"
    "ull to=base fromViewNil=0 toViewNil=1 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"full.dismissed.presenterFrame\":\"kept\",\""
    "full.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=n/a style=4\",\"full.present.events\":\"d"
    "elegate:presentationController,pc:willPresent,willAppear:full,animateTransition,completeTransition,pc:didPresent:1,didAppear:full,completion,animationEnded:1\",\""
    "full.present.layout\":\"laid out\",\"full.present.start\":\"from=base to=full fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFrom=full initialTo="
    "zero finalTo=other\",\"full.presented.presenterFrame\":\"kept\",\"full.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWin"
    "dow=1\",\"info.dim.dismiss.start\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.dim.d"
    "ismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.dim.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalT"
    "o=20,60,280,360 container=UITransitionView\",\"info.dim.presented.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.dim.willPresent\":\"containerClass=UITr"
    "ansitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"info.full.dismiss.start\":\"initialFrom=20,60,280,360 finalFro"
    "m=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.full.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"inf"
    "o.full.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\",\"info.full.presented."
    "presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.full.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60"
    ",280,360 presentedViewSuper=(null)\",\"info.interactive.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480 presented=0\",\"info.native.dismissed.presente"
    "rFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.plain.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.plain.presented.presenterFrame\":\"b"
    "efore=0,0,320,480 now=0,0,320,480\",\"info.plain.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presente"
    "dViewSuper=(null)\",\"info.remove.dismiss.start\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionVi"
    "ew\",\"info.remove.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.remove.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,0,0 initial"
    "To=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\",\"info.remove.presented.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.remove.willPresen"
    "t\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"interactive.dismissed.presenterFrame\""
    ":\"kept\",\"native.dismissed.presenterFrame\":\"kept\",\"plain.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"plain.didPresent\":\"containerSubviews=2 pr"
    "esentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"plain.dismiss.end\":\"presented=0 modalWindow=0 baseWindow"
    "=1\",\"plain.dismiss.events\":\"pc:willDismiss,willDisappear:plain,pc:didDismiss:1,didDisappear:plain,completion\",\"plain.dismissed.presenterFrame\":\"kept\",\"plain.pre"
    "sent.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresented style=4\",\"plain.present.even"
    "ts\":\"delegate:presentationController,pc:willPresent,willAppear:plain,pc:didPresent:1,didAppear:plain,completion\",\"plain.present.layout\":\"laid out\",\"plain.presen"
    "ted.presenterFrame\":\"kept\",\"plain.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"remove.didDismiss\":\"dim"
    "mingIn=1 presenterWindow=0 presentedWindow=1\",\"remove.didPresent\":\"containerSubviews=3 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 prese"
    "nterWindow=1 presentedWindow=1\",\"remove.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"remove.dismiss.events\":\"pc:willDismiss,willDisappear:remove,willA"
    "ppear:base,animateTransition,completeTransition,pc:didDismiss:1,didAppear:base,didDisappear:remove,completion,animationEnded:1\",\"remove.dismiss.start\":\"from=rem"
    "ove to=base fromViewNil=0 toViewNil=0 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"remove.dismissed.presenterFrame\":\"kept\""
    ",\"remove.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=0 modalFrameRelative=frameOfPresented style=4\",\"remove"
    ".present.events\":\"delegate:presentationController,pc:willPresent,willDisappear:base,willAppear:remove,animateTransition,completeTransition,pc:didPresent:1,didAp"
    "pear:remove,didDisappear:base,completion,animationEnded:1\",\"remove.present.layout\":\"laid out\",\"remove.present.start\":\"from=base to=remove fromViewNil=0 toViewNi"
    "l=0 style=4 subviews=2 initialFrom=other finalFrom=zero initialTo=zero finalTo=other\",\"remove.presented.presenterFrame\":\"kept\",\"remove.willPresent\":\"container=1"
    " subviews=2 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\"}"
;
