static const char customtransition_expectations[] =
    "{\"dismiss.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"dismiss.end\":\"presented=1 baseWindow=1 modalWindow=0\",\"dismiss.events\":\"willDisappear:modal,willAp"
    "pear:base,animateTransition,completeTransition,didAppear:base,didDisappear:modal,completion,animationEnded:1\",\"dismiss.presenterFrame\":\"kept\",\"dismiss.start\":\"f"
    "rom=modal to=base fromClass=plain toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 i"
    "nteractive=0 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"icancel.afterComplet"
    "e\":\"fromWindow=1 toAlpha=0\",\"icancel.duration\":\"0.80\",\"icancel.end\":\"presented=1 modalWindow=1 modalAlpha=1\",\"icancel.events\":\"willDisappear:modal,willAppear:ba"
    "se,animateTransition,completeTransition,willDisappear:base,didDisappear:base,willAppear:modal,didAppear:modal,completion,animationEnded:0\",\"icancel.percent\":\"0."
    "40\",\"icancel.start\":\"from=modal to=base fromClass=plain toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containe"
    "rWindow=1 animated=1 interactive=1 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\""
    ",\"idismiss.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"idismiss.duration\":\"0.80\",\"idismiss.end\":\"presented=0 modalWindow=0 modalAlpha=1\",\"idismiss.event"
    "s\":\"willDisappear:modal,willAppear:base,animateTransition,completeTransition,didAppear:base,didDisappear:modal,completion,animationEnded:1\",\"idismiss.percent\":\""
    "0.40\",\"idismiss.presenterFrame\":\"kept\",\"idismiss.start\":\"from=modal to=base fromClass=plain toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirec"
    "t=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=1 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=fu"
    "ll subviews=1 containerSuper=window\",\"info.dismiss\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 cont"
    "ainer=UITransitionView super=UIWindow\",\"info.dismiss.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.durationCalls\":\"3\",\"info.icancel\":\"bounds=0,0,32"
    "0,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.idismiss\":\"bounds=0,0"
    ",320,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.idismiss.presenter"
    "Frame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.ipop\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 cont"
    "ainer=UIViewControllerWrapperView super=UINavigationTransitionView\",\"info.ipop.chains\":\"base UIView>UIViewControllerWrapperView>UINavigationTransitionView>UILay"
    "outContainerView>UIDropShadowView>UITransitionView>UIWindow> second UIView>\",\"info.ipopcancel\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 ini"
    "tialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitionView\",\"info.ipopcancel.chains\":\"base UIView> second UIView>"
    "UIViewControllerWrapperView>UINavigationTransitionView>UILayoutContainerView>UIDropShadowView>UITransitionView>UIWindow>\",\"info.pop\":\"bounds=0,0,320,480 initial"
    "From=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitionView\",\"info.present\":"
    "\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.push\":\"boun"
    "ds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitio"
    "nView\",\"ipop.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"ipop.end\":\"top=base baseWindow=1 secondWindow=0 count=1\",\"ipop.events\":\"willDisappear:second,wi"
    "llAppear:base,animateTransition,completeTransition,didDisappear:second,didAppear:base,animationEnded:1\",\"ipop.start\":\"from=second to=base fromClass=plain toClas"
    "s=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=1 cancelled=0 style=-1 tran"
    "sform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=other\",\"ipopcancel.afterComplete\":\"toWindow=0 fromWindow=1 toAlpha"
    "=0\",\"ipopcancel.end\":\"top=second baseWindow=0 secondWindow=1 count=2\",\"ipopcancel.events\":\"willDisappear:second,willAppear:base,animateTransition,completeTransi"
    "tion,willDisappear:base,didDisappear:base,willAppear:second,didAppear:second,animationEnded:0\",\"ipopcancel.start\":\"from=second to=base fromClass=plain toClass=p"
    "lain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=1 cancelled=0 style=-1 transfo"
    "rm=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=other\",\"pop.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"pop.e"
    "nd\":\"top=1 baseWindow=1 secondWindow=0 count=1\",\"pop.events\":\"willDisappear:second,willAppear:base,animateTransition,completeTransition,didDisappear:second,didA"
    "ppear:base,animationEnded:1\",\"pop.start\":\"from=second to=base fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWind"
    "ow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews"
    "=1 containerSuper=other\",\"present.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"present.end\":\"presented=1 presenting=1 modalWindow=1\",\"present.events\":\"wi"
    "llDisappear:base,willAppear:modal,animateTransition,completeTransition,didAppear:modal,didDisappear:base,completion,animationEnded:1\",\"present.start\":\"from=base"
    " to=modal fromClass=nav toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interacti"
    "ve=0 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"push.afterComplete\":\"toWindo"
    "w=1 fromWindow=0 toAlpha=1\",\"push.end\":\"top=1 secondWindow=1 baseWindow=0 count=2\",\"push.events\":\"willDisappear:base,willAppear:second,animateTransition,complet"
    "eTransition,didDisappear:base,didAppear:second,animationEnded:1\",\"push.start\":\"from=base to=second fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 to"
    "In=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero"
    " initialTo=zero finalTo=full subviews=1 containerSuper=other\"}"
;
