static const char customtransition_expectations[] =
    "{\"dismiss.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"dismiss.end\":\"presented=1 baseWindow=1 modalWindow=0\",\"dismiss.events\":\"willDisappear:modal,willAp"
    "pear:base,animateTransition,completeTransition,didAppear:base,didDisappear:modal,completion,animationEnded:1\",\"dismiss.start\":\"from=modal to=base fromClass=plai"
    "n toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=0"
    " transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"icancel.afterComplete\":\"fromWindow=1 toAlpha=0\",\"ica"
    "ncel.duration\":\"0.80\",\"icancel.end\":\"presented=1 modalWindow=1 modalAlpha=1\",\"icancel.events\":\"willDisappear:modal,willAppear:base,animateTransition,completeTra"
    "nsition,willDisappear:base,didDisappear:base,willAppear:modal,didAppear:modal,completion,animationEnded:0\",\"icancel.percent\":\"0.40\",\"icancel.start\":\"from=modal "
    "to=base fromClass=plain toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive"
    "=1 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"idismiss.afterComplete\":\"toWin"
    "dow=1 fromWindow=0 toAlpha=1\",\"idismiss.duration\":\"0.80\",\"idismiss.end\":\"presented=0 modalWindow=0 modalAlpha=1\",\"idismiss.events\":\"willDisappear:modal,willAppe"
    "ar:base,animateTransition,completeTransition,didAppear:base,didDisappear:modal,completion,animationEnded:1\",\"idismiss.percent\":\"0.40\",\"idismiss.start\":\"from=mod"
    "al to=base fromClass=plain toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interact"
    "ive=1 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"info.dismiss\":\"bounds=0,0,3"
    "20,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.durationCalls\":\"3\",\""
    "info.icancel\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\""
    ",\"info.idismiss\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWind"
    "ow\",\"info.ipop\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super="
    "UINavigationTransitionView\",\"info.ipop.chains\":\"base UIView>UIViewControllerWrapperView>UINavigationTransitionView>UILayoutContainerView>UIDropShadowView>UITran"
    "sitionView>UIWindow> second UIView>\",\"info.ipopcancel\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 conta"
    "iner=UIViewControllerWrapperView super=UINavigationTransitionView\",\"info.ipopcancel.chains\":\"base UIView> second UIView>UIViewControllerWrapperView>UINavigation"
    "TransitionView>UILayoutContainerView>UIDropShadowView>UITransitionView>UIWindow>\",\"info.pop\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initi"
    "alTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitionView\",\"info.present\":\"bounds=0,0,320,480 initialFrom=0,0,320,"
    "480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.push\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 f"
    "inalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitionView\",\"ipop.afterComplete\":\"toWindow=1 "
    "fromWindow=0 toAlpha=1\",\"ipop.end\":\"top=base baseWindow=1 secondWindow=0 count=1\",\"ipop.events\":\"willDisappear:second,willAppear:base,animateTransition,complete"
    "Transition,didDisappear:second,didAppear:base,animationEnded:1\",\"ipop.start\":\"from=second to=base fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toI"
    "n=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=1 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero "
    "initialTo=zero finalTo=full subviews=1 containerSuper=other\",\"ipopcancel.afterComplete\":\"toWindow=0 fromWindow=1 toAlpha=0\",\"ipopcancel.end\":\"top=second baseWin"
    "dow=0 secondWindow=1 count=2\",\"ipopcancel.events\":\"willDisappear:second,willAppear:base,animateTransition,completeTransition,willDisappear:base,didDisappear:bas"
    "e,willAppear:second,didAppear:second,animationEnded:0\",\"ipopcancel.start\":\"from=second to=base fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toIn=0"
    " fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=1 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero ini"
    "tialTo=zero finalTo=full subviews=1 containerSuper=other\",\"pop.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"pop.end\":\"top=1 baseWindow=1 secondWindow=0 c"
    "ount=1\",\"pop.events\":\"willDisappear:second,willAppear:base,animateTransition,completeTransition,didDisappear:second,didAppear:base,animationEnded:1\",\"pop.start\""
    ":\"from=second to=base fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animat"
    "ed=1 interactive=0 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=other\",\"present.afterC"
    "omplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"present.end\":\"presented=1 presenting=1 modalWindow=1\",\"present.events\":\"willDisappear:base,willAppear:modal,animat"
    "eTransition,completeTransition,didAppear:modal,didDisappear:base,completion,animationEnded:1\",\"present.start\":\"from=base to=modal fromClass=nav toClass=plain fr"
    "omView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=0 transform=1 ini"
    "tialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"push.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"push.end\":\""
    "top=1 secondWindow=1 baseWindow=0 count=2\",\"push.events\":\"willDisappear:base,willAppear:second,animateTransition,completeTransition,didDisappear:base,didAppear:"
    "second,animationEnded:1\",\"push.start\":\"from=base to=second fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow="
    "1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 "
    "containerSuper=other\"}"
;
