static const char customtransition_expectations[] =
    "{\"dismiss.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"dismiss.end\":\"presented=1 baseWindow=1 modalWindow=0\",\"dismiss.events\":\"willDisappear:modal,willAp"
    "pear:base,animateTransition,completeTransition,didAppear:base,didDisappear:modal,completion,animationEnded:1\",\"dismiss.start\":\"from=modal to=base fromClass=plai"
    "n toClass=nav fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=0"
    " transform=1 initialFrom=full finalFrom=full initialTo=zero finalTo=full subviews=1 containerSuper=window\",\"info.dismiss\":\"bounds=0,0,320,480 initialFrom=0,0,32"
    "0,480 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info.durationCalls\":\"3\",\"info.pop\":\"bounds=0,0,320"
    ",480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigationTransitionView\",\"in"
    "fo.present\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView super=UIWindow\",\"info"
    ".push\":\"bounds=0,0,320,480 initialFrom=0,0,320,480 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UIViewControllerWrapperView super=UINavigat"
    "ionTransitionView\",\"pop.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"pop.end\":\"top=1 baseWindow=1 secondWindow=0 count=1\",\"pop.events\":\"willDisappear:sec"
    "ond,willAppear:base,animateTransition,completeTransition,didDisappear:second,didAppear:base,animationEnded:1\",\"pop.start\":\"from=second to=base fromClass=plain t"
    "oClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=-1"
    " transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=other\",\"present.afterComplete\":\"toWindow=1 fromWindow=0 toAlp"
    "ha=1\",\"present.end\":\"presented=1 presenting=1 modalWindow=1\",\"present.events\":\"willDisappear:base,willAppear:modal,animateTransition,completeTransition,didAppea"
    "r:modal,didDisappear:base,completion,animationEnded:1\",\"present.start\":\"from=base to=modal fromClass=nav toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromD"
    "irect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated=1 interactive=0 cancelled=0 style=0 transform=1 initialFrom=full finalFrom=zero initialTo="
    "zero finalTo=full subviews=1 containerSuper=window\",\"push.afterComplete\":\"toWindow=1 fromWindow=0 toAlpha=1\",\"push.end\":\"top=1 secondWindow=1 baseWindow=0 count"
    "=2\",\"push.events\":\"willDisappear:base,willAppear:second,animateTransition,completeTransition,didDisappear:base,didAppear:second,animationEnded:1\",\"push.start\":\""
    "from=base to=second fromClass=plain toClass=plain fromView=1 toView=1 fromIn=1 toIn=0 fromDirect=1 toDirect=0 fromWindow=1 toWindow=0 containerWindow=1 animated"
    "=1 interactive=0 cancelled=0 style=-1 transform=1 initialFrom=full finalFrom=zero initialTo=zero finalTo=full subviews=1 containerSuper=other\"}"
;
