static const char custompresentation_expectations[] =
    "{\"dim.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 presentedSuperIsContainer="
    "1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"dim.dismiss.events\":\"pc:willDismiss,willDisappear"
    ":dim,animateTransition,completeTransition,pc:didDismiss:1,didDisappear:dim,completion,animationEnded:1\",\"dim.dismiss.start\":\"from=dim to=base fromViewNil=0 toVi"
    "ewNil=1 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"dim.dismissed.presenterFrame\":\"kept\",\"dim.present.end\":\"presented=1 p"
    "cIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresented style=4\",\"dim.present.events\":\"delegate:presentation"
    "Controller,pc:willPresent,willAppear:dim,animateTransition,completeTransition,pc:didPresent:1,didAppear:dim,completion,animationEnded:1\",\"dim.present.layout\":\"l"
    "aid out\",\"dim.present.start\":\"from=base to=dim fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFrom=full initialTo=zero finalTo=other\",\"dim."
    "presented.presenterFrame\":\"kept\",\"dim.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"full.didDismiss\":\"d"
    "immingIn=1 presenterWindow=1 presentedWindow=1\",\"full.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 prese"
    "nterWindow=1 presentedWindow=1\",\"full.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"full.dismiss.events\":\"pc:willDismiss,willDisappear:full,animateTran"
    "sition,completeTransition,pc:didDismiss:1,didDisappear:full,completion,animationEnded:1\",\"full.dismiss.start\":\"from=full to=base fromViewNil=0 toViewNil=1 style"
    "=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"full.dismissed.presenterFrame\":\"kept\",\"full.present.end\":\"presented=1 pcIsPresenta"
    "tionController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=n/a style=4\",\"full.present.events\":\"delegate:presentationController,pc:willPrese"
    "nt,willAppear:full,animateTransition,completeTransition,pc:didPresent:1,didAppear:full,completion,animationEnded:1\",\"full.present.layout\":\"laid out\",\"full.prese"
    "nt.start\":\"from=base to=full fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFrom=full initialTo=zero finalTo=other\",\"full.presented.present"
    "erFrame\":\"kept\",\"full.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"info.dim.dismiss.start\":\"initialFro"
    "m=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.dim.dismissed.presenterFrame\":\"before=0,0,320,48"
    "0 now=0,0,320,480\",\"info.dim.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\""
    ",\"info.dim.presented.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.dim.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 fr"
    "ameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"info.full.dismiss.start\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0"
    ",0,320,480 container=UITransitionView\",\"info.full.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.full.present.start\":\"initialFrom=20,60,28"
    "0,360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\",\"info.full.presented.presenterFrame\":\"before=0,0,320,480 now=0,0"
    ",320,480\",\"info.full.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"info.i"
    "nteractive.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480 presented=0\",\"info.native.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480"
    "\",\"info.plain.dismissed.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.plain.presented.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.pl"
    "ain.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"info.remove.dismiss.sta"
    "rt\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.remove.dismissed.presenterFrame\":"
    "\"before=0,0,320,480 now=0,0,320,480\",\"info.remove.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=20,60,280,360 container="
    "UITransitionView\",\"info.remove.presented.presenterFrame\":\"before=0,0,320,480 now=0,0,320,480\",\"info.remove.willPresent\":\"containerClass=UITransitionView contain"
    "erBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"interactive.dismissed.presenterFrame\":\"kept\",\"native.dismissed.presenterFrame\":\""
    "kept\",\"plain.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"plain.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 presentedSuperIsC"
    "ontainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"plain.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"plain.dismiss.events\":\"pc:willDismiss,"
    "willDisappear:plain,pc:didDismiss:1,didDisappear:plain,completion\",\"plain.dismissed.presenterFrame\":\"kept\",\"plain.present.end\":\"presented=1 pcIsPresentationCont"
    "roller=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresented style=4\",\"plain.present.events\":\"delegate:presentationController,pc:wil"
    "lPresent,willAppear:plain,pc:didPresent:1,didAppear:plain,completion\",\"plain.present.layout\":\"laid out\",\"plain.presented.presenterFrame\":\"kept\",\"plain.willPrese"
    "nt\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"remove.didDismiss\":\"dimmingIn=1 presenterWindow=0 presentedWindow="
    "1\",\"remove.didPresent\":\"containerSubviews=3 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"remove.dis"
    "miss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"remove.dismiss.events\":\"pc:willDismiss,willDisappear:remove,willAppear:base,animateTransition,completeTransi"
    "tion,pc:didDismiss:1,didAppear:base,didDisappear:remove,completion,animationEnded:1\",\"remove.dismiss.start\":\"from=remove to=base fromViewNil=0 toViewNil=0 style"
    "=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"remove.dismissed.presenterFrame\":\"kept\",\"remove.present.end\":\"presented=1 pcIsPres"
    "entationController=1 sameAsProperty=1 modalWindow=1 baseWindow=0 modalFrameRelative=frameOfPresented style=4\",\"remove.present.events\":\"delegate:presentationCont"
    "roller,pc:willPresent,willDisappear:base,willAppear:remove,animateTransition,completeTransition,pc:didPresent:1,didAppear:remove,didDisappear:base,completion,an"
    "imationEnded:1\",\"remove.present.layout\":\"laid out\",\"remove.present.start\":\"from=base to=remove fromViewNil=0 toViewNil=0 style=4 subviews=2 initialFrom=other fi"
    "nalFrom=zero initialTo=zero finalTo=other\",\"remove.presented.presenterFrame\":\"kept\",\"remove.willPresent\":\"container=1 subviews=2 presentedViewIsVCView=1 present"
    "edViewWindow=0 presenterWindow=1\"}"
;
