static const char custompresentation_expectations[] =
    "{\"dim.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 presentedSuperIsContainer="
    "1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"dim.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"dim.dismiss.events\":\"pc:willDismiss,willDisappear"
    ":dim,animateTransition,completeTransition,pc:didDismiss:1,didDisappear:dim,completion,animationEnded:1\",\"dim.dismiss.start\":\"from=dim to=base fromViewNil=0 toVi"
    "ewNil=1 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"dim.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProp"
    "erty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresented style=4\",\"dim.present.events\":\"delegate:presentationController,pc:willPresent,willAppear:d"
    "im,animateTransition,completeTransition,pc:didPresent:1,didAppear:dim,completion,animationEnded:1\",\"dim.present.layout\":\"laid out\",\"dim.present.start\":\"from=bas"
    "e to=dim fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFrom=full initialTo=zero finalTo=other\",\"dim.willPresent\":\"container=1 subviews=1 p"
    "resentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"full.didDismiss\":\"dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"full.didPresent\":\"container"
    "Subviews=2 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 presentedWindow=1\",\"full.dismiss.end\":\"presented=0 modalWindow="
    "0 baseWindow=1\",\"full.dismiss.events\":\"pc:willDismiss,willDisappear:full,animateTransition,completeTransition,pc:didDismiss:1,didDisappear:full,completion,anima"
    "tionEnded:1\",\"full.dismiss.start\":\"from=full to=base fromViewNil=0 toViewNil=1 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\""
    ",\"full.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=n/a style=4\",\"full.present.events\":"
    "\"delegate:presentationController,pc:willPresent,willAppear:full,animateTransition,completeTransition,pc:didPresent:1,didAppear:full,completion,animationEnded:1\""
    ",\"full.present.layout\":\"laid out\",\"full.present.start\":\"from=base to=full fromViewNil=1 toViewNil=0 style=4 subviews=1 initialFrom=other finalFrom=full initialT"
    "o=zero finalTo=other\",\"full.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"info.dim.dismiss.start\":\"init"
    "ialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.dim.present.start\":\"initialFrom=20,60,280,"
    "360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\",\"info.dim.willPresent\":\"containerClass=UITransitionView containerB"
    "ounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"info.full.dismiss.start\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initial"
    "To=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info.full.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,320,480 initialTo=0,0,0,0 finalTo="
    "20,60,280,360 container=UITransitionView\",\"info.full.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 pr"
    "esentedViewSuper=(null)\",\"info.plain.willPresent\":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper"
    "=(null)\",\"info.remove.dismiss.start\":\"initialFrom=20,60,280,360 finalFrom=20,60,280,360 initialTo=0,0,0,0 finalTo=0,0,320,480 container=UITransitionView\",\"info."
    "remove.present.start\":\"initialFrom=20,60,280,360 finalFrom=0,0,0,0 initialTo=0,0,0,0 finalTo=20,60,280,360 container=UITransitionView\",\"info.remove.willPresent\""
    ":\"containerClass=UITransitionView containerBounds=0,0,320,480 frameOfPresented=20,60,280,360 presentedViewSuper=(null)\",\"plain.didDismiss\":\"dimmingIn=1 presente"
    "rWindow=1 presentedWindow=1\",\"plain.didPresent\":\"containerSubviews=2 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindow=1 prese"
    "ntedWindow=1\",\"plain.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"plain.dismiss.events\":\"pc:willDismiss,willDisappear:plain,pc:didDismiss:1,didDisappe"
    "ar:plain,completion\",\"plain.present.end\":\"presented=1 pcIsPresentationController=1 sameAsProperty=1 modalWindow=1 baseWindow=1 modalFrameRelative=frameOfPresent"
    "ed style=4\",\"plain.present.events\":\"delegate:presentationController,pc:willPresent,willAppear:plain,pc:didPresent:1,didAppear:plain,completion\",\"plain.present.l"
    "ayout\":\"laid out\",\"plain.willPresent\":\"container=1 subviews=1 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\",\"remove.didDismiss\":\"dimmingIn=1 "
    "presenterWindow=0 presentedWindow=1\",\"remove.didPresent\":\"containerSubviews=3 presentedFrameInContainer=1 presentedSuperIsContainer=1 dimmingIn=1 presenterWindo"
    "w=1 presentedWindow=1\",\"remove.dismiss.end\":\"presented=0 modalWindow=0 baseWindow=1\",\"remove.dismiss.events\":\"pc:willDismiss,willDisappear:remove,willAppear:bas"
    "e,animateTransition,completeTransition,pc:didDismiss:1,didAppear:base,didDisappear:remove,completion,animationEnded:1\",\"remove.dismiss.start\":\"from=remove to=ba"
    "se fromViewNil=0 toViewNil=0 style=4 subviews=2 initialFrom=other finalFrom=other initialTo=zero finalTo=full\",\"remove.present.end\":\"presented=1 pcIsPresentatio"
    "nController=1 sameAsProperty=1 modalWindow=1 baseWindow=0 modalFrameRelative=frameOfPresented style=4\",\"remove.present.events\":\"delegate:presentationController,"
    "pc:willPresent,willDisappear:base,willAppear:remove,animateTransition,completeTransition,pc:didPresent:1,didAppear:remove,didDisappear:base,completion,animation"
    "Ended:1\",\"remove.present.layout\":\"laid out\",\"remove.present.start\":\"from=base to=remove fromViewNil=0 toViewNil=0 style=4 subviews=2 initialFrom=other finalFrom"
    "=zero initialTo=zero finalTo=other\",\"remove.willPresent\":\"container=1 subviews=2 presentedViewIsVCView=1 presentedViewWindow=0 presenterWindow=1\"}"
;
