static const char *const date_components_expectations[] = {
    "1:02:05",
    "1h 2m 5s",
    "1 hr, 2 min, 5 sec",
    "1 hour, 2 minutes, 5 seconds",
    "one hour, two minutes, five seconds",
    "1hr 2min 5sec",
    "0:00:45",
    "45",
    "00:00:45",
    "0:12",
    "00:12",
    "0h 12m",
    "0 hr, 12 min",
    "4d 15:06:40",
    "4d 15h",
    "5d",
    "1d",
    "0d 0:02",
    "About 5d",
    "5d remaining",
    "About 5d remaining",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "3 mths, 12 days",
    "3 months, 12 days, 4 hours, 0 minutes, 0 seconds",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "66w 0d 23h",
    "-1:01",
    "minus one hour, one minute",
    "90",
    "59",
    "0s",
    "0s",
    "60m 0s",
    "60m 5s",
    "60m 5s",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "raises NSInvalidArgumentException: Specifying positional units with gaps is ambiguous, and therefore unsupported",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 1d",
    "-1mo 2w 0d",
    "-1mo 2w 0d",
    "-1mo 2w 2d",
    "-1mo 2w 0d",
    "-1mo 2w 0d",
    "2mo 0w 0d",
    "2mo 0w 0d",
    "1mo 4w 0d",
    "2mo 0w 0d",
    "1mo 4w 1d",
    "-1mo 4w 0d",
    "-1mo 4w 0d",
    "-1mo 4w 2d",
    "-1mo 4w 0d",
    "-1mo 4w 0d",
    "1mo",
    "1mo",
    "1mo",
    "1mo",
    "1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "2mo",
    "2mo",
    "1mo",
    "2mo",
    "1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "13mo",
    "13mo",
    "13mo",
    "13mo",
    "13mo",
    "1mo 14d",
    "1mo 14d",
    "1mo 14d",
    "1mo 14d",
    "1mo 15d",
    "-1mo 14d",
    "-1mo 14d",
    "-1mo 16d",
    "-1mo 14d",
    "-1mo 14d",
    "2mo 0d",
    "2mo 0d",
    "1mo 28d",
    "2mo 0d",
    "1mo 29d",
    "-1mo 28d",
    "-1mo 28d",
    "-1mo 30d",
    "-1mo 28d",
    "-1mo 28d",
    "13mo 4d",
    "13mo 4d",
    "13mo 4d",
    "13mo 4d",
    "13mo 4d",
    "0y 1mo 14d",
    "0y 1mo 14d",
    "0y 1mo 14d",
    "0y 1mo 14d",
    "0y 1mo 15d",
    "0y 1mo 14d",
    "0y 1mo 14d",
    "0y 1mo 16d",
    "0y 1mo 14d",
    "0y 1mo 14d",
    "0y 2mo 0d",
    "0y 2mo 0d",
    "0y 1mo 28d",
    "0y 2mo 0d",
    "0y 1mo 29d",
    "0y 1mo 28d",
    "0y 1mo 28d",
    "0y 1mo 30d",
    "0y 1mo 28d",
    "0y 1mo 28d",
    "1y 1mo 4d",
    "1y 1mo 4d",
    "1y 1mo 4d",
    "1y 1mo 4d",
    "1y 1mo 4d",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 0d",
    "1mo 2w 1d",
    "-1mo 2w 0d",
    "-1mo 2w 0d",
    "-1mo 2w 2d",
    "-1mo 2w 0d",
    "-1mo 2w 0d",
    "2mo 0w 0d",
    "2mo 0w 0d",
    "1mo 4w 0d",
    "2mo 0w 0d",
    "1mo 4w 1d",
    "-1mo 4w 0d",
    "-1mo 4w 0d",
    "-1mo 4w 2d",
    "-1mo 4w 0d",
    "-1mo 4w 0d",
    "1mo",
    "1mo",
    "1mo",
    "1mo",
    "1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "2mo",
    "2mo",
    "1mo",
    "2mo",
    "1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "-1mo",
    "13mo",
    "13mo",
    "13mo",
    "13mo",
    "13mo",
    "1 month, 14 days",
    "1 month, 14 days",
    "1 month, 14 days",
    "1 month, 14 days",
    "1 month, 15 days",
    "-1 month, 14 days",
    "-1 month, 14 days",
    "-1 month, 16 days",
    "-1 month, 14 days",
    "-1 month, 14 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 15 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 16 days",
    "0 years, 1 month, 14 days",
    "0 years, 1 month, 14 days",
    "1 month, 2 weeks, 0 days",
    "1 month, 2 weeks, 0 days",
    "1 month, 2 weeks, 0 days",
    "1 month, 2 weeks, 0 days",
    "1 month, 2 weeks, 1 day",
    "-1 month, 2 weeks, 0 days",
    "-1 month, 2 weeks, 0 days",
    "-1 month, 2 weeks, 2 days",
    "-1 month, 2 weeks, 0 days",
    "-1 month, 2 weeks, 0 days",
    "1 month",
    "1 month",
    "1 month",
    "1 month",
    "1 month",
    "-1 month",
    "-1 month",
    "-1 month",
    "-1 month",
    "-1 month",
};
