static const char fontdesc_expectations[] =
    "{\"absent key\":\"nil\",\"adding\":\"NSFontFaceAttribute=Oblique;NSFontNameAttribute=Helvetica;NSFontSizeAttribute=30\",\"adding empty\":\"NSFontNameAttribute=Helvetica;NS"
    "FontSizeAttribute=14\",\"archive round trip\":\"1 NSFontNameAttribute=Helvetica;NSFontSizeAttribute=14\",\"bold by name\":\"ps=Helvetica-Bold size=0 traits=2\",\"bold obl"
    "ique to bold\":\"ps=Helvetica-Bold size=14 traits=2\",\"bold oblique to italic\":\"ps=Helvetica-Oblique size=14 traits=1\",\"bold oblique to none\":\"ps=Helvetica size=14"
    " traits=0\",\"copy is itself\":\"1\",\"courier bold\":\"ps=Courier-Bold size=12 traits=2\",\"courier bold oblique\":\"ps=Courier-BoldOblique size=12 traits=3\",\"empty descri"
    "ptor\":\"\",\"empty ps\":\"Helvetica\",\"empty size\":\"0\",\"equal\":\"1 1 0\",\"family\":\"Helvetica\",\"family attributes\":\"NSFontFamilyAttribute=Courier\",\"family bold\":\"ps=Cour"
    "ier-Bold size=0 traits=2\",\"family only\":\"ps=Courier size=0\",\"font descriptor\":\"NSFontNameAttribute=Helvetica-Bold;NSFontSizeAttribute=17 | ps=Helvetica-Bold siz"
    "e=17 traits=2\",\"font round trip\":\"Courier-Bold 13\",\"font with courier bold\":\"Courier-Bold 12\",\"font with descriptor size\":\"Helvetica-Bold 30\",\"font with descrip"
    "tor size zero\":\"Helvetica-Bold 17\",\"font with family descriptor\":\"Courier 15\",\"font with missing name\":\"Helvetica 11\",\"font with plain descriptor\":\"Helvetica 17"
    "\",\"helvetica with traits 0\":\"NSFontNameAttribute=Helvetica;NSFontSizeAttribute=14 | ps=Helvetica size=14 traits=0\",\"helvetica with traits 1\":\"NSFontNameAttribut"
    "e=Helvetica-Oblique;NSFontSizeAttribute=14 | ps=Helvetica-Oblique size=14 traits=1\",\"helvetica with traits 2\":\"NSFontNameAttribute=Helvetica-Bold;NSFontSizeAttr"
    "ibute=14 | ps=Helvetica-Bold size=14 traits=2\",\"helvetica with traits 3\":\"NSFontNameAttribute=Helvetica-BoldOblique;NSFontSizeAttribute=14 | ps=Helvetica-BoldOb"
    "lique size=14 traits=3\",\"helvetica with traits 20\":\"nil | nil\",\"helvetica with traits 40\":\"nil | nil\",\"helvetica with traits 400\":\"NSFontNameAttribute=Helvetica"
    ";NSFontSizeAttribute=14 | ps=Helvetica size=14 traits=0\",\"helvetica with traits 1000\":\"NSFontNameAttribute=Helvetica;NSFontSizeAttribute=14 | ps=Helvetica size="
    "14 traits=0\",\"matching family\":\"Courier,Courier-Bold,Courier-BoldOblique,Courier-Oblique\",\"matching none\":\"0\",\"name\":\"Helvetica\",\"name and size\":\"ps=Helvetica s"
    "ize=14 traits=0\",\"name and size attributes\":\"NSFontNameAttribute=Helvetica;NSFontSizeAttribute=14\",\"original untouched\":\"NSFontNameAttribute=Helvetica;NSFontSiz"
    "eAttribute=14\",\"secure coding\":\"1\",\"size\":\"14\",\"times\":\"ps=TimesNewRomanPSMT size=16 traits=0\",\"times bold\":\"ps=TimesNewRomanPS-BoldMT size=16 traits=2\",\"times "
    "italic\":\"ps=TimesNewRomanPS-ItalicMT size=16 traits=1\",\"with face\":\"NSFontFaceAttribute=Bold;NSFontSizeAttribute=14\",\"with family\":\"NSFontFamilyAttribute=Courie"
    "r;NSFontSizeAttribute=14\",\"with family ps\":\"Courier\",\"with size\":\"NSFontNameAttribute=Helvetica;NSFontSizeAttribute=20\",\"with size pointSize\":\"20\"}"
;
