static const char foundation8b_expectations[] =
    "{\"constant.NSExtensionHostDidBecomeActiveNotification\":\"NSExtensionHostDidBecomeActiveNotification\",\"constant.NSExtensionHostDidEnterBackgroundNotification\":\"NS"
    "ExtensionHostDidEnterBackgroundNotification\",\"constant.NSExtensionHostWillEnterForegroundNotification\":\"NSExtensionHostWillEnterForegroundNotification\",\"constan"
    "t.NSExtensionHostWillResignActiveNotification\":\"NSExtensionHostWillResignActiveNotification\",\"constant.NSMetadataItemContentTypeKey\":\"kMDItemContentType\",\"const"
    "ant.NSMetadataItemContentTypeTreeKey\":\"kMDItemContentTypeTree\",\"constant.NSMetadataQueryAccessibleUbiquitousExternalDocumentsScope\":\"NSMetadataQueryAccessibleUb"
    "iquitousExternalDocumentsScope\",\"constant.NSMetadataQueryUpdateAddedItemsKey\":\"kMDQueryUpdateAddedItems\",\"constant.NSMetadataQueryUpdateChangedItemsKey\":\"kMDQue"
    "ryUpdateChangedItems\",\"constant.NSMetadataQueryUpdateRemovedItemsKey\":\"kMDQueryUpdateRemovedItems\",\"constant.NSMetadataUbiquitousItemContainerDisplayNameKey\":\"N"
    "SMetadataUbiquitousItemContainerDisplayNameKey\",\"constant.NSMetadataUbiquitousItemDownloadingErrorKey\":\"NSMetadataUbiquitousItemDownloadingErrorKey\",\"constant.N"
    "SMetadataUbiquitousItemDownloadingStatusCurrent\":\"NSMetadataUbiquitousItemDownloadingStatusCurrent\",\"constant.NSMetadataUbiquitousItemDownloadingStatusDownloade"
    "d\":\"NSMetadataUbiquitousItemDownloadingStatusDownloaded\",\"constant.NSMetadataUbiquitousItemDownloadingStatusKey\":\"NSMetadataUbiquitousItemDownloadingStatusKey\","
    "\"constant.NSMetadataUbiquitousItemDownloadingStatusNotDownloaded\":\"NSMetadataUbiquitousItemDownloadingStatusNotDownloaded\",\"constant.NSMetadataUbiquitousItemDow"
    "nloadRequestedKey\":\"NSMetadataUbiquitousItemDownloadRequestedKey\",\"constant.NSMetadataUbiquitousItemIsExternalDocumentKey\":\"NSMetadataUbiquitousItemIsExternalDo"
    "cumentKey\",\"constant.NSMetadataUbiquitousItemIsSharedKey\":\"NSMetadataUbiquitousItemIsSharedKey\",\"constant.NSMetadataUbiquitousItemUploadingErrorKey\":\"NSMetadata"
    "UbiquitousItemUploadingErrorKey\",\"constant.NSMetadataUbiquitousItemURLInLocalContainerKey\":\"NSMetadataUbiquitousItemURLInLocalContainerKey\",\"constant.NSMetadata"
    "UbiquitousSharedItemCurrentUserPermissionsKey\":\"NSMetadataUbiquitousSharedItemCurrentUserPermissionsKey\",\"constant.NSMetadataUbiquitousSharedItemCurrentUserRole"
    "Key\":\"NSMetadataUbiquitousSharedItemCurrentUserRoleKey\",\"constant.NSMetadataUbiquitousSharedItemMostRecentEditorNameComponentsKey\":\"NSMetadataUbiquitousSharedIt"
    "emMostRecentEditorNameComponentsKey\",\"constant.NSMetadataUbiquitousSharedItemOwnerNameComponentsKey\":\"NSMetadataUbiquitousSharedItemOwnerNameComponentsKey\",\"con"
    "stant.NSMetadataUbiquitousSharedItemPermissionsReadOnly\":\"NSMetadataUbiquitousSharedItemPermissionsReadOnly\",\"constant.NSMetadataUbiquitousSharedItemPermissions"
    "ReadWrite\":\"NSMetadataUbiquitousSharedItemPermissionsReadWrite\",\"constant.NSMetadataUbiquitousSharedItemRoleOwner\":\"NSMetadataUbiquitousSharedItemRoleOwner\",\"co"
    "nstant.NSMetadataUbiquitousSharedItemRoleParticipant\":\"NSMetadataUbiquitousSharedItemRoleParticipant\",\"coordinate.both\":\"error=0 wrote=1 read=one\",\"coordinate.e"
    "mpty\":\"error=0\",\"coordinate.missing\":\"error=0 read=0\",\"coordinate.order\":\"1 2\",\"coordinate.read\":\"error=0 text=one onQueue=1 name=one.txt\",\"coordinate.result\":\""
    "two\",\"deallocator.blocks\":\"ran none=1\",\"deallocator.data\":\"32 7\",\"extension.main\":\"1\",\"intent.new\":\"one.txt two.txt 0\"}"
;
