static const char foundation11_expectations[] =
    "{\"decodeValue.roundTrip\":\"42\",\"decodeValue.wrongSize\":\"NSInvalidArgumentException: Cannot get decode with size 1. The type encoded as i is expected to be 4 byte"
    "s\",\"paths.stable\":\"charon11-array.plist\",\"queryItems.read.\?\":\"\",\"queryItems.read.\?=v\":\"=v\",\"queryItems.read.\?a\":\"a=(nil)\",\"queryItems.read.\?a+b=c+d\":\"a+b=c+d\",\""
    "queryItems.read.\?a=\":\"a=\",\"queryItems.read.\?a=%E2%82%AC&b=two%20words\":\"a=%E2%82%AC|b=two%20words\",\"queryItems.read.\?a=1\":\"a=1\",\"queryItems.read.\?a=1&&b=2\":\"a=1"
    "|=(nil)|b=2\",\"queryItems.read.\?a=1&a=2\":\"a=1|a=2\",\"queryItems.read.\?a=b=c\":\"a=b=c\",\"queryItems.read.(none)\":\"(nil array)\",\"queryItems.write.0\":\" / \",\"queryItems"
    ".write.1\":\"x=%41 / x=A\",\"queryItems.write.2\":\"x / x\",\"queryItems.write.3\":\"x= / x=\",\"queryItems.write.4\":\"=v / =v\",\"queryItems.write.5\":\"a=1&b=2 / a=1&b=2\",\"que"
    "ryItems.write.nil\":\"(nil)\",\"read.array\":\"(\\n    a,\\n    2\\n) nil\",\"read.dictionary\":\"{\\n    k = v;\\n} nil\",\"read.empty\":\"nil NSCocoaErrorDomain 259\",\"read.missi"
    "ng\":\"nil NSCocoaErrorDomain 260\",\"read.mutable\":\"mutable\",\"read.mutable.value\":\"(\\n    a,\\n    2\\n)\",\"read.nilURL\":\"nil nil\",\"read.wrongKind\":\"nil NSCocoaErrorD"
    "omain 259\",\"read.wrongKind.text\":\"says so\",\"release.characterBytesWidened\":\"\\u00c8|\\u2603|\\u221e\",\"transformer.allowedClasses\":\"(\\n    NSArray,\\n    NSDictionar"
    "y,\\n    NSSet,\\n    NSString,\\n    NSNumber,\\n    NSDate,\\n    NSData,\\n    NSURL,\\n    NSUUID,\\n    NSNull\\n)\",\"transformer.allowsReverse\":\"YES\",\"transformer.j"
    "unk\":\"NSInvalidUnarchiveOperationException\",\"transformer.refusesOtherClass\":\"NSInvalidArgumentException: Object of class NSConcreteValue is not among allowed to"
    "p level class list (\\n    NSArray,\\n    NSDictionary,\\n    NSSet,\\n    NSString,\\n    NSNumber,\\n    NSDate,\\n    NSData,\\n    NSURL,\\n    NSUUID,\\n    NSNull\\n"
    ")\",\"transformer.reverse\":\"non-empty\",\"transformer.reverseRoundTrip\":\"(\\n    b\\n)\",\"transformer.transform\":\"(\\n    a,\\n    1\\n)\",\"transformer.transformedValueCla"
    "ss\":\"nil\",\"transformer.transformNil\":\"nil\",\"transformer.transformNotData\":\"NSInvalidArgumentException\",\"validated.%-10@|%@\":\"ok A\",\"validated.%.1@|%@\":\"ok A\",\"v"
    "alidated.%'10f|%@\":\"ok '10f\",\"validated.%[k]@ %@|%@ %@\":\"ok %[k]@ A\",\"validated.%@ %@|%@\":\"NSCocoaErrorDomain 2048 Format '%@ %@' does not match expected '%@'\","
    "\"validated.%@ %|%@\":\"NSCocoaErrorDomain 2048 Format '%@ %' does not match expected '%@'\",\"validated.%@ %|%@ %\":\"ok A \",\"validated.%@ %1|%@ %1\":\"ok A \",\"validate"
    "d.%@ %1$|%@ %1$\":\"NSCocoaErrorDomain 2048 Format '%@ %1$' does not match expected '%@ %1$'\",\"validated.%@ %2$@ %@|%@ %@\":\"ok A B B\",\"validated.%@ %2$@|%@ %@\":\"o"
    "k A B\",\"validated.%@ has %@|%@ %@\":\"ok A has B\",\"validated.%@%@%@%@%@%@%@%@%@%@%@|%@%@%@%@%@%@%@%@%@%@\":\"NSCocoaErrorDomain 2048 Format '%@%@%@%@%@%@%@%@%@%@%@'"
    " does not match expected '%@%@%@%@%@%@%@%@%@%@'\",\"validated.%@%@%@%@%@%@%@%@%@%@|%@%@%@%@%@%@%@%@%@%@\":\"ok ABCDEFGHIJ\",\"validated.%@|\":\"NSCocoaErrorDomain 2048 "
    "Format '%@' does not match expected ''\",\"validated.%@|%@ %@\":\"ok A\",\"validated.%@|%@, %ld\":\"ok A\",\"validated.%@|%%\":\"NSCocoaErrorDomain 2048 Format '%@' does no"
    "t match expected '%%'\",\"validated.%@|%ld\":\"NSCocoaErrorDomain 2048 Format '%@' does not match expected '%ld'\",\"validated.%*d|%d\":\"NSCocoaErrorDomain 2048 Format"
    " '%*d' does not match expected '%d'\",\"validated.%#@|%#@\":\"ok \",\"validated.%#@key@ %@|%@\":\"NSCocoaErrorDomain 2048 Format '%#@key@ %@' does not match expected '%"
    "@'\",\"validated.%#@key@ %@|%@ %@\":\"ok %#@key@ A\",\"validated.%%@|%@\":\"ok %@\",\"validated.%|%@\":\"NSCocoaErrorDomain 2048 Format '%' does not match expected '%@'\",\"v"
    "alidated.%0$@|%@\":\"ok 0$@\",\"validated.%1$@ %@ %@|%@ %@\":\"ok A A B\",\"validated.%1$@ %0$@|%@\":\"ok A 0$@\",\"validated.%1$@ %1$@|%@\":\"ok A A\",\"validated.%1$@ %10$@ %"
    "2$@|%@%@%@%@%@%@%@%@%@%@\":\"ok A J B\",\"validated.%1$@|\":\"NSCocoaErrorDomain 2048 Format '%1$@' does not match expected ''\",\"validated.%1$d %f|%1$d %f\":\"NSCocoaEr"
    "rorDomain 2048 Format '%1$d %f' does not match expected '%1$d %f'\",\"validated.%2$@ %@ %@|%@ %@\":\"ok B A B\",\"validated.%2$@ %@|%@ %@\":\"ok B A\",\"validated.%2$@ %1"
    "$@ %@|%@ %@ %@\":\"ok B A A\",\"validated.%2$@ %1$@|%@ %@\":\"ok B A\",\"validated.%3$@|%@ %@\":\"NSCocoaErrorDomain 2048 Format '%3$@' does not match expected '%@ %@'\",\""
    "validated.%5$@|%@\":\"NSCocoaErrorDomain 2048 Format '%5$@' does not match expected '%@'\",\"validated.%9$@|%@%@%@%@%@%@%@%@%@\":\"ok I\",\"validated.%10@|%-10@||%@ %@\""
    ":\"ok A|B|\",\"validated.%10$@|%@%@%@%@%@%@%@%@%@%@\":\"ok J\",\"validated.%11$@|%@%@%@%@%@%@%@%@%@%@\":\"NSCocoaErrorDomain 2048 Format '%11$@' does not match expected "
    "'%@%@%@%@%@%@%@%@%@%@'\",\"validated.%12$@ %1$@|%@%@%@%@%@%@%@%@%@%@%@%@\":\"ok L A\",\"validated.%d|%C\":\"NSCocoaErrorDomain 2048 Format '%d' does not match expected "
    "'%C'\",\"validated.%d|%n\":\"NSCocoaErrorDomain 2048 Format '%d' does not match expected '%n'\",\"validated.%hC%1$c|%hC%1$c\":\"NSCocoaErrorDomain 2048 Format '%hC%1$c'"
    " does not match expected '%hC%1$c'\",\"validated.%k %@|%@\":\"ok k A\",\"validated.%Ld|%d\":\"NSCocoaErrorDomain 2048 Format '%Ld' does not match expected '%d'\",\"valida"
    "ted.%s|%S\":\"NSCocoaErrorDomain 2048 Format '%s' does not match expected '%S'\",\"validated.%S|%s\":\"NSCocoaErrorDomain 2048 Format '%S' does not match expected '%s"
    "'\",\"validated.|\":\"ok \",\"validated.|%@\":\"ok \",\"validated.100%% sure|%@\":\"ok 100% sure\",\"validated.characterBytes\":\"|\\u00e9|A|\",\"validated.characterBytesAccented\""
    ":\"\\u00e9 \\u00c8\",\"validated.characterBytesLocalized\":\"\\u00c8\\u2603\",\"validated.characterBytesWidened\":\"\\u00c8|\\u2603|\\u221e\",\"validated.counted\":\"AC\",\"validated"
    ".floats\":\"2.500000e+00 2.500000E+00 2.5 2.5 0x1.4p+1 0X1.4P+1 2.500000 2 2.\",\"validated.integers\":\"ff FF 10 0xff 010 7 7 10 +7  7 00007 7    |\",\"validated.lengt"
    "hs\":\"44 4464 1 2 3 4 5 6 2.500000\",\"validated.localized\":\"A 7\",\"validated.nilFormat\":\"NSInvalidArgumentException\",\"validated.numbers\":\"7 and 2.50\",\"validated.pl"
    "ain|\":\"ok plain\",\"validated.positionalStars\":\"    7|5|\",\"validated.sharedSlot\":\"41 A|3 3\",\"validated.shortened\":\"3 -2560 -2560 f600 ff\",\"validated.stars\":\"    7"
    "|7    |2.50|   2.500|\",\"validated.strings\":\"text|te|wide|pas|\\u0416|x\",\"validated.wideCharacters\":\"|A\",\"validated.wideStar\":\"601   7|\",\"write.array\":\"1 nil\",\"wr"
    "ite.dictionary\":\"1 nil\",\"write.format\":\"<\?xml version=\\\"1.0\\\"\",\"write.invalid\":\"0 NSCocoaErrorDomain 3851\",\"write.invalid.reason\":\"Property list invalid for for"
    "mat: 100 (property lists cannot contain objects of type 'CFType')\",\"write.numberKey\":\"0 NSCocoaErrorDomain 3851 Property list invalid for format: 100 (property "
    "list dictionaries may only have keys which are CFStrings, not 'CFNumber')\"}"
;
