NAME_CODE(GCKeyCodeApplication, 101)
NAME_CODE(GCKeyCodeBackslash, 49)
NAME_CODE(GCKeyCodeCapsLock, 57)
NAME_CODE(GCKeyCodeCloseBracket, 48)
NAME_CODE(GCKeyCodeComma, 54)
NAME_CODE(GCKeyCodeDeleteForward, 76)
NAME_CODE(GCKeyCodeDeleteOrBackspace, 42)
NAME_CODE(GCKeyCodeDownArrow, 81)
NAME_CODE(GCKeyCodeEight, 37)
NAME_CODE(GCKeyCodeEnd, 77)
NAME_CODE(GCKeyCodeEqualSign, 46)
NAME_CODE(GCKeyCodeEscape, 41)
NAME_CODE(GCKeyCodeF1, 58)
NAME_CODE(GCKeyCodeF10, 67)
NAME_CODE(GCKeyCodeF11, 68)
NAME_CODE(GCKeyCodeF12, 69)
NAME_CODE(GCKeyCodeF13, 104)
NAME_CODE(GCKeyCodeF14, 105)
NAME_CODE(GCKeyCodeF15, 106)
NAME_CODE(GCKeyCodeF16, 107)
NAME_CODE(GCKeyCodeF17, 108)
NAME_CODE(GCKeyCodeF18, 109)
NAME_CODE(GCKeyCodeF19, 110)
NAME_CODE(GCKeyCodeF2, 59)
NAME_CODE(GCKeyCodeF20, 111)
NAME_CODE(GCKeyCodeF3, 60)
NAME_CODE(GCKeyCodeF4, 61)
NAME_CODE(GCKeyCodeF5, 62)
NAME_CODE(GCKeyCodeF6, 63)
NAME_CODE(GCKeyCodeF7, 64)
NAME_CODE(GCKeyCodeF8, 65)
NAME_CODE(GCKeyCodeF9, 66)
NAME_CODE(GCKeyCodeFive, 34)
NAME_CODE(GCKeyCodeFour, 33)
NAME_CODE(GCKeyCodeGraveAccentAndTilde, 53)
NAME_CODE(GCKeyCodeHome, 74)
NAME_CODE(GCKeyCodeHyphen, 45)
NAME_CODE(GCKeyCodeInsert, 73)
NAME_CODE(GCKeyCodeInternational1, 135)
NAME_CODE(GCKeyCodeInternational2, 136)
NAME_CODE(GCKeyCodeInternational3, 137)
NAME_CODE(GCKeyCodeInternational4, 138)
NAME_CODE(GCKeyCodeInternational5, 139)
NAME_CODE(GCKeyCodeInternational6, 140)
NAME_CODE(GCKeyCodeInternational7, 141)
NAME_CODE(GCKeyCodeInternational8, 142)
NAME_CODE(GCKeyCodeInternational9, 143)
NAME_CODE(GCKeyCodeKeyA, 4)
NAME_CODE(GCKeyCodeKeyB, 5)
NAME_CODE(GCKeyCodeKeyC, 6)
NAME_CODE(GCKeyCodeKeyD, 7)
NAME_CODE(GCKeyCodeKeyE, 8)
NAME_CODE(GCKeyCodeKeyF, 9)
NAME_CODE(GCKeyCodeKeyG, 10)
NAME_CODE(GCKeyCodeKeyH, 11)
NAME_CODE(GCKeyCodeKeyI, 12)
NAME_CODE(GCKeyCodeKeyJ, 13)
NAME_CODE(GCKeyCodeKeyK, 14)
NAME_CODE(GCKeyCodeKeyL, 15)
NAME_CODE(GCKeyCodeKeyM, 16)
NAME_CODE(GCKeyCodeKeyN, 17)
NAME_CODE(GCKeyCodeKeyO, 18)
NAME_CODE(GCKeyCodeKeyP, 19)
NAME_CODE(GCKeyCodeKeyQ, 20)
NAME_CODE(GCKeyCodeKeyR, 21)
NAME_CODE(GCKeyCodeKeyS, 22)
NAME_CODE(GCKeyCodeKeyT, 23)
NAME_CODE(GCKeyCodeKeyU, 24)
NAME_CODE(GCKeyCodeKeyV, 25)
NAME_CODE(GCKeyCodeKeyW, 26)
NAME_CODE(GCKeyCodeKeyX, 27)
NAME_CODE(GCKeyCodeKeyY, 28)
NAME_CODE(GCKeyCodeKeyZ, 29)
NAME_CODE(GCKeyCodeKeypad0, 98)
NAME_CODE(GCKeyCodeKeypad1, 89)
NAME_CODE(GCKeyCodeKeypad2, 90)
NAME_CODE(GCKeyCodeKeypad3, 91)
NAME_CODE(GCKeyCodeKeypad4, 92)
NAME_CODE(GCKeyCodeKeypad5, 93)
NAME_CODE(GCKeyCodeKeypad6, 94)
NAME_CODE(GCKeyCodeKeypad7, 95)
NAME_CODE(GCKeyCodeKeypad8, 96)
NAME_CODE(GCKeyCodeKeypad9, 97)
NAME_CODE(GCKeyCodeKeypadAsterisk, 85)
NAME_CODE(GCKeyCodeKeypadEnter, 88)
NAME_CODE(GCKeyCodeKeypadEqualSign, 103)
NAME_CODE(GCKeyCodeKeypadHyphen, 86)
NAME_CODE(GCKeyCodeKeypadNumLock, 83)
NAME_CODE(GCKeyCodeKeypadPeriod, 99)
NAME_CODE(GCKeyCodeKeypadPlus, 87)
NAME_CODE(GCKeyCodeKeypadSlash, 84)
NAME_CODE(GCKeyCodeLANG1, 144)
NAME_CODE(GCKeyCodeLANG2, 145)
NAME_CODE(GCKeyCodeLANG3, 146)
NAME_CODE(GCKeyCodeLANG4, 147)
NAME_CODE(GCKeyCodeLANG5, 148)
NAME_CODE(GCKeyCodeLANG6, 149)
NAME_CODE(GCKeyCodeLANG7, 150)
NAME_CODE(GCKeyCodeLANG8, 151)
NAME_CODE(GCKeyCodeLANG9, 152)
NAME_CODE(GCKeyCodeLeftAlt, 226)
NAME_CODE(GCKeyCodeLeftArrow, 80)
NAME_CODE(GCKeyCodeLeftControl, 224)
NAME_CODE(GCKeyCodeLeftGUI, 227)
NAME_CODE(GCKeyCodeLeftShift, 225)
NAME_CODE(GCKeyCodeNine, 38)
NAME_CODE(GCKeyCodeNonUSBackslash, 100)
NAME_CODE(GCKeyCodeNonUSPound, 50)
NAME_CODE(GCKeyCodeOne, 30)
NAME_CODE(GCKeyCodeOpenBracket, 47)
NAME_CODE(GCKeyCodePageDown, 78)
NAME_CODE(GCKeyCodePageUp, 75)
NAME_CODE(GCKeyCodePause, 72)
NAME_CODE(GCKeyCodePeriod, 55)
NAME_CODE(GCKeyCodePower, 102)
NAME_CODE(GCKeyCodePrintScreen, 70)
NAME_CODE(GCKeyCodeQuote, 52)
NAME_CODE(GCKeyCodeReturnOrEnter, 40)
NAME_CODE(GCKeyCodeRightAlt, 230)
NAME_CODE(GCKeyCodeRightArrow, 79)
NAME_CODE(GCKeyCodeRightControl, 228)
NAME_CODE(GCKeyCodeRightGUI, 231)
NAME_CODE(GCKeyCodeRightShift, 229)
NAME_CODE(GCKeyCodeScrollLock, 71)
NAME_CODE(GCKeyCodeSemicolon, 51)
NAME_CODE(GCKeyCodeSeven, 36)
NAME_CODE(GCKeyCodeSix, 35)
NAME_CODE(GCKeyCodeSlash, 56)
NAME_CODE(GCKeyCodeSpacebar, 44)
NAME_CODE(GCKeyCodeTab, 43)
NAME_CODE(GCKeyCodeThree, 32)
NAME_CODE(GCKeyCodeTwo, 31)
NAME_CODE(GCKeyCodeUpArrow, 82)
NAME_CODE(GCKeyCodeZero, 39)
NAME_FLOAT(GCHapticDurationInfinite, 1000000)
NAME_STRING(GCControllerUserCustomizationsDidChangeNotification, @"GCControllerUserCustomizationsDidChangeNotification")
NAME_STRING(GCHapticsLocalityAll, @"All")
NAME_STRING(GCHapticsLocalityDefault, @"Default")
NAME_STRING(GCHapticsLocalityHandles, @"Handles")
NAME_STRING(GCHapticsLocalityLeftHandle, @"Left Handle")
NAME_STRING(GCHapticsLocalityLeftTrigger, @"Left Trigger")
NAME_STRING(GCHapticsLocalityRightHandle, @"Right Handle")
NAME_STRING(GCHapticsLocalityRightTrigger, @"Right Trigger")
NAME_STRING(GCHapticsLocalityTriggers, @"Triggers")
NAME_STRING(GCInputButtonA, @"Button A")
NAME_STRING(GCInputButtonB, @"Button B")
NAME_STRING(GCInputButtonHome, @"Button Home")
NAME_STRING(GCInputButtonMenu, @"Button Menu")
NAME_STRING(GCInputButtonOptions, @"Button Options")
NAME_STRING(GCInputButtonShare, @"Button Share")
NAME_STRING(GCInputButtonX, @"Button X")
NAME_STRING(GCInputButtonY, @"Button Y")
NAME_STRING(GCInputDirectionPad, @"Direction Pad")
NAME_STRING(GCInputDirectionalCardinalDpad, @"Cardinal Direction Pad")
NAME_STRING(GCInputDirectionalCenterButton, @"Button Center")
NAME_STRING(GCInputDirectionalDpad, @"Direction Pad")
NAME_STRING(GCInputDirectionalTouchSurfaceButton, @"Button A")
NAME_STRING(GCInputDualShockTouchpadButton, @"Touchpad Button")
NAME_STRING(GCInputDualShockTouchpadOne, @"Touchpad 1")
NAME_STRING(GCInputDualShockTouchpadTwo, @"Touchpad 2")
NAME_STRING(GCInputLeftShoulder, @"Left Shoulder")
NAME_STRING(GCInputLeftThumbstick, @"Left Thumbstick")
NAME_STRING(GCInputLeftThumbstickButton, @"Left Thumbstick Button")
NAME_STRING(GCInputLeftTrigger, @"Left Trigger")
NAME_STRING(GCInputMicroGamepadButtonA, @"Button A")
NAME_STRING(GCInputMicroGamepadButtonMenu, @"Button Menu")
NAME_STRING(GCInputMicroGamepadButtonX, @"Button X")
NAME_STRING(GCInputMicroGamepadDpad, @"Direction Pad")
NAME_STRING(GCInputRightShoulder, @"Right Shoulder")
NAME_STRING(GCInputRightThumbstick, @"Right Thumbstick")
NAME_STRING(GCInputRightThumbstickButton, @"Right Thumbstick Button")
NAME_STRING(GCInputRightTrigger, @"Right Trigger")
NAME_STRING(GCInputXboxPaddleFour, @"Paddle 4")
NAME_STRING(GCInputXboxPaddleOne, @"Paddle 1")
NAME_STRING(GCInputXboxPaddleThree, @"Paddle 3")
NAME_STRING(GCInputXboxPaddleTwo, @"Paddle 2")
NAME_STRING(GCKeyA, @"A")
NAME_STRING(GCKeyApplication, @"Application")
NAME_STRING(GCKeyB, @"B")
NAME_STRING(GCKeyBackslash, @"Backslash")
NAME_STRING(GCKeyC, @"C")
NAME_STRING(GCKeyCapsLock, @"CapsLock")
NAME_STRING(GCKeyCloseBracket, @"CloseBracket")
NAME_STRING(GCKeyComma, @"Comma")
NAME_STRING(GCKeyD, @"D")
NAME_STRING(GCKeyDeleteForward, @"DeleteForward")
NAME_STRING(GCKeyDeleteOrBackspace, @"DeleteOrBackspace")
NAME_STRING(GCKeyDownArrow, @"DownArrow")
NAME_STRING(GCKeyE, @"E")
NAME_STRING(GCKeyEight, @"Eight")
NAME_STRING(GCKeyEnd, @"End")
NAME_STRING(GCKeyEqualSign, @"EqualSign")
NAME_STRING(GCKeyEscape, @"Escape")
NAME_STRING(GCKeyF, @"F")
NAME_STRING(GCKeyF1, @"F1")
NAME_STRING(GCKeyF10, @"F10")
NAME_STRING(GCKeyF11, @"F11")
NAME_STRING(GCKeyF12, @"F12")
NAME_STRING(GCKeyF13, @"F13")
NAME_STRING(GCKeyF14, @"F14")
NAME_STRING(GCKeyF15, @"F15")
NAME_STRING(GCKeyF16, @"F16")
NAME_STRING(GCKeyF17, @"F17")
NAME_STRING(GCKeyF18, @"F18")
NAME_STRING(GCKeyF19, @"F19")
NAME_STRING(GCKeyF2, @"F2")
NAME_STRING(GCKeyF20, @"F20")
NAME_STRING(GCKeyF3, @"F3")
NAME_STRING(GCKeyF4, @"F4")
NAME_STRING(GCKeyF5, @"F5")
NAME_STRING(GCKeyF6, @"F6")
NAME_STRING(GCKeyF7, @"F7")
NAME_STRING(GCKeyF8, @"F8")
NAME_STRING(GCKeyF9, @"F9")
NAME_STRING(GCKeyFive, @"Five")
NAME_STRING(GCKeyFour, @"Four")
NAME_STRING(GCKeyG, @"G")
NAME_STRING(GCKeyGraveAccentAndTilde, @"GraveAccentAndTilde")
NAME_STRING(GCKeyH, @"H")
NAME_STRING(GCKeyHome, @"Home")
NAME_STRING(GCKeyHyphen, @"Hyphen")
NAME_STRING(GCKeyI, @"I")
NAME_STRING(GCKeyInsert, @"Insert")
NAME_STRING(GCKeyInternational1, @"International1")
NAME_STRING(GCKeyInternational2, @"International2")
NAME_STRING(GCKeyInternational3, @"International3")
NAME_STRING(GCKeyInternational4, @"International4")
NAME_STRING(GCKeyInternational5, @"International5")
NAME_STRING(GCKeyInternational6, @"International6")
NAME_STRING(GCKeyInternational7, @"International7")
NAME_STRING(GCKeyInternational8, @"International8")
NAME_STRING(GCKeyInternational9, @"International9")
NAME_STRING(GCKeyJ, @"J")
NAME_STRING(GCKeyK, @"K")
NAME_STRING(GCKeyKeypad0, @"Keypad0")
NAME_STRING(GCKeyKeypad1, @"Keypad1")
NAME_STRING(GCKeyKeypad2, @"Keypad2")
NAME_STRING(GCKeyKeypad3, @"Keypad3")
NAME_STRING(GCKeyKeypad4, @"Keypad4")
NAME_STRING(GCKeyKeypad5, @"Keypad5")
NAME_STRING(GCKeyKeypad6, @"Keypad6")
NAME_STRING(GCKeyKeypad7, @"Keypad7")
NAME_STRING(GCKeyKeypad8, @"Keypad8")
NAME_STRING(GCKeyKeypad9, @"Keypad9")
NAME_STRING(GCKeyKeypadAsterisk, @"KeypadAsterisk")
NAME_STRING(GCKeyKeypadEnter, @"KeypadEnter")
NAME_STRING(GCKeyKeypadEqualSign, @"KeypadEqualSign")
NAME_STRING(GCKeyKeypadHyphen, @"KeypadHyphen")
NAME_STRING(GCKeyKeypadNumLock, @"KeypadNumLock")
NAME_STRING(GCKeyKeypadPeriod, @"KeypadPeriod")
NAME_STRING(GCKeyKeypadPlus, @"KeypadPlus")
NAME_STRING(GCKeyKeypadSlash, @"KeypadSlash")
NAME_STRING(GCKeyL, @"L")
NAME_STRING(GCKeyLANG1, @"LANG1")
NAME_STRING(GCKeyLANG2, @"LANG2")
NAME_STRING(GCKeyLANG3, @"LANG3")
NAME_STRING(GCKeyLANG4, @"LANG4")
NAME_STRING(GCKeyLANG5, @"LANG5")
NAME_STRING(GCKeyLANG6, @"LANG6")
NAME_STRING(GCKeyLANG7, @"LANG7")
NAME_STRING(GCKeyLANG8, @"LANG8")
NAME_STRING(GCKeyLANG9, @"LANG9")
NAME_STRING(GCKeyLeftAlt, @"LeftAlt")
NAME_STRING(GCKeyLeftArrow, @"LeftArrow")
NAME_STRING(GCKeyLeftControl, @"LeftControl")
NAME_STRING(GCKeyLeftGUI, @"LeftGUI")
NAME_STRING(GCKeyLeftShift, @"LeftShift")
NAME_STRING(GCKeyM, @"M")
NAME_STRING(GCKeyN, @"N")
NAME_STRING(GCKeyNine, @"Nine")
NAME_STRING(GCKeyNonUSBackslash, @"NonUSBackslash")
NAME_STRING(GCKeyNonUSPound, @"NonUSPound")
NAME_STRING(GCKeyO, @"O")
NAME_STRING(GCKeyOne, @"One")
NAME_STRING(GCKeyOpenBracket, @"OpenBracket")
NAME_STRING(GCKeyP, @"P")
NAME_STRING(GCKeyPageDown, @"PageDown")
NAME_STRING(GCKeyPageUp, @"PageUp")
NAME_STRING(GCKeyPause, @"Pause")
NAME_STRING(GCKeyPeriod, @"Period")
NAME_STRING(GCKeyPower, @"Power")
NAME_STRING(GCKeyPrintScreen, @"PrintScreen")
NAME_STRING(GCKeyQ, @"Q")
NAME_STRING(GCKeyQuote, @"Quote")
NAME_STRING(GCKeyR, @"R")
NAME_STRING(GCKeyReturnOrEnter, @"ReturnOrEnter")
NAME_STRING(GCKeyRightAlt, @"RightAlt")
NAME_STRING(GCKeyRightArrow, @"RightArrow")
NAME_STRING(GCKeyRightControl, @"RightControl")
NAME_STRING(GCKeyRightGUI, @"RightGUI")
NAME_STRING(GCKeyRightShift, @"RightShift")
NAME_STRING(GCKeyS, @"S")
NAME_STRING(GCKeyScrollLock, @"ScrollLock")
NAME_STRING(GCKeySemicolon, @"Semicolon")
NAME_STRING(GCKeySeven, @"Seven")
NAME_STRING(GCKeySix, @"Six")
NAME_STRING(GCKeySlash, @"Slash")
NAME_STRING(GCKeySpacebar, @"Spacebar")
NAME_STRING(GCKeyT, @"T")
NAME_STRING(GCKeyTab, @"Tab")
NAME_STRING(GCKeyThree, @"Three")
NAME_STRING(GCKeyTwo, @"Two")
NAME_STRING(GCKeyU, @"U")
NAME_STRING(GCKeyUpArrow, @"UpArrow")
NAME_STRING(GCKeyV, @"V")
NAME_STRING(GCKeyW, @"W")
NAME_STRING(GCKeyX, @"X")
NAME_STRING(GCKeyY, @"Y")
NAME_STRING(GCKeyZ, @"Z")
NAME_STRING(GCKeyZero, @"Zero")
NAME_STRING(GCProductCategoryCoalescedRemote, @"Coalesced Remote")
NAME_STRING(GCProductCategoryControlCenterRemote, @"Control Center Remote")
NAME_STRING(GCProductCategoryDualSense, @"DualSense")
NAME_STRING(GCProductCategoryDualShock4, @"DualShock 4")
NAME_STRING(GCProductCategoryHID, @"HID")
NAME_STRING(GCProductCategoryKeyboard, @"Keyboard")
NAME_STRING(GCProductCategoryMFi, @"MFi")
NAME_STRING(GCProductCategoryMouse, @"Mouse")
NAME_STRING(GCProductCategorySiriRemote1stGen, @"Siri Remote (1st Generation)")
NAME_STRING(GCProductCategorySiriRemote2ndGen, @"Siri Remote (2nd Generation)")
NAME_STRING(GCProductCategoryUniversalElectronicsRemote, @"Universal Electronics Remote")
NAME_STRING(GCProductCategoryXboxOne, @"Xbox One")
