static const char itemprovider_expectations[] =
    "{\"builtin.string\":\"public.utf8-plain-text | 1 0 | h\\u00e9llo\",\"builtin.url\":\"public.url | https://a.b\",\"constants\":\"NSItemProviderErrorDomain NSItemProviderPref"
    "erredImageSize NSExtensionJavaScriptPreprocessingResultsKey -1 -1000 -1100 -1200\",\"copy\":\"1 public.plain-text\",\"extensionItem\":\"new=0001 0 | set=title text 1 ke"
    "ys=NSExtensionItemAttachmentsKey,NSExtensionItemAttributedContentTextKey,NSExtensionItemAttributedTitleKey | cleared=0 0 keys=NSExtensionItemAttributedContentTe"
    "xtKey | replaced={\\n    k = 1;\\n} 0 (null) | archive=NSExtensionItemUserInfoKey | back={\\n    k = 1;\\n} | nil=(null)\",\"extensionItem.keys\":\"NSExtensionItemAttri"
    "butedTitleKey NSExtensionItemAttributedContentTextKey NSExtensionItemAttachmentsKey\",\"file.contents\":\" String=NSString(hello) URL=NSItemProviderErrorDomain/-110"
    "0 Data=NSData(5) Image=NSItemProviderErrorDomain/-1100 Attr=NSAttributedString(5) Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Ar"
    "ray=NSItemProviderErrorDomain/-1200 id=NSData(5)\",\"file.image.types\":\"public.png,public.file-url,public.url\",\"file.types\":\"public.plain-text,public.file-url,pub"
    "lic.url\",\"file.url\":\" String=NSString($/provider.txt) URL=NSURL(file) Image=NSItemProviderErrorDomain/-1100 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemPr"
    "oviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSData(n)\",\"handler.fails.error\":\"NSItemProviderErrorDomain/-1000\",\"handler.fails.nil\":\"NSItemP"
    "roviderErrorDomain/-1000\",\"handler.noOptions\":\"NSString(from handler) | NSString empty | NSData empty | nil none\",\"handler.options\":\"NSString(from handler) | NS"
    "String options | NSData options | nil options\",\"load.missing.com.bogus\":\"NSItemProviderErrorDomain/-1000\",\"load.missing.public.image\":\"NSItemProviderErrorDomain"
    "/-1000\",\"matrix.array\":\" String=NSItemProviderErrorDomain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSItemProviderErrorDomain/-1200 Image=NSItemProviderErr"
    "orDomain/-1200 Attr=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSArray id=NSArray\",\"matri"
    "x.data\":\" String=NSItemProviderErrorDomain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSData(3) Image=NSItemProviderErrorDomain/-1100 Attr=NSItemProviderErr"
    "orDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSData(3)\",\"matrix.dictionar"
    "y\":\" String=NSItemProviderErrorDomain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSItemProviderErrorDomain/-1200 Image=NSItemProviderErrorDomain/-1200 Attr="
    "NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSDictionary Array=NSItemProviderErrorDomain/-1200 id=NSDictionary\",\"matrix.fileURL\""
    ":\" URL=NSURL(file) Data=NSData(5) Image=NSItemProviderErrorDomain/-1100 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItem"
    "ProviderErrorDomain/-1200 id=NSURL(file)\",\"matrix.fileURLAsData\":\" String=NSItemProviderErrorDomain/-1200 URL=NSURL(file) Data=NSData(5) Image=NSItemProviderErr"
    "orDomain/-1100 Attr=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/"
    "-1200 id=NSURL(file)\",\"matrix.image\":\" String=NSItemProviderErrorDomain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSItemProviderErrorDomain/-1200 Image=UII"
    "mage Attr=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=U"
    "IImage\",\"matrix.imageFileURL\":\" String=NSItemProviderErrorDomain/-1200 URL=NSURL(file) Data=NSData(png) Image=UIImage Attr=NSItemProviderErrorDomain/-1200 Numbe"
    "r=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSURL(file)\",\"matrix.number\":\" String=NSItemProv"
    "iderErrorDomain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSItemProviderErrorDomain/-1200 Image=NSItemProviderErrorDomain/-1200 Attr=NSItemProviderErrorDom"
    "ain/-1200 Number=NSNumber Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSNumber\",\"matrix.pngData\":\" String=NSItemProviderErrorD"
    "omain/-1200 URL=NSItemProviderErrorDomain/-1100 Data=NSData(png) Image=UIImage Attr=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict="
    "NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSData(png)\",\"matrix.pngDataAsImage\":\" String=NSItemProviderErrorDomain/-1200 URL=NSIte"
    "mProviderErrorDomain/-1100 Data=NSData(png) Image=UIImage Attr=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDo"
    "main/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSData(png)\",\"matrix.string\":\" String=NSString(hello) URL=NSItemProviderErrorDomain/-1100 Data=NSItemProvide"
    "rErrorDomain/-1200 Image=NSItemProviderErrorDomain/-1200 Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDo"
    "main/-1200 id=NSString(hello)\",\"matrix.textData\":\" String=NSString(abc) URL=NSItemProviderErrorDomain/-1100 Data=NSData(3) Image=NSItemProviderErrorDomain/-1100"
    " Attr=NSAttributedString(3) Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErrorDomain/-1200 id=NSData(3)\",\"mat"
    "rix.webURL\":\" String=NSString(https://a.b/c) URL=NSURL(web) Number=NSItemProviderErrorDomain/-1200 Dict=NSItemProviderErrorDomain/-1200 Array=NSItemProviderErro"
    "rDomain/-1200 id=NSURL(web)\",\"object.load\":\"com.charon.note:body\",\"object.types\":\"public.utf8-plain-text,com.charon.note | 1 1\",\"order.load\":\"NSString(public.pl"
    "ain-text)\",\"order.registered\":\"public.plain-text,public.utf8-plain-text\",\"preview\":\"UIImage | NSItemProviderErrorDomain/-1000\",\"representations.has\":\"1 1 1\",\"re"
    "presentations.load\":\"bogus=NSItemProviderErrorDomain/-1000 | data=NSData(5) | file=source.txt same=0 exists=1 body=source body | inplace2=0 | inplace=source.txt"
    " 1 1\",\"representations.types\":\"public.plain-text,public.data,public.png | public.plain-text,public.data,public.png | public.png\",\"types.conformance\":\"public.pla"
    "in-text=1 public.text=1 public.utf8-plain-text=0 public.image=0 public.data=1 com.bogus=0 public.content=1\",\"types.empty\":\"\",\"types.nilType\":\"NSInvalidArgumentE"
    "xception\",\"types.registered\":\"public.plain-text\"}"
;
