static const char *const relative_expectations[] = {
    "1w ago",
    "2 mo. ago",
    "twenty-one years ago",
    "in 1 min.",
    "in 8y",
    "in 4 months",
    "1 wk. ago",
    "eighteen hours ago",
    "in nine months",
    "in 23 yr.",
    "two hours ago",
    "2m ago",
    "4 hours ago",
    "2m ago",
    "6w ago",
    "2 wk. ago",
    "in 51 years",
    "7mo ago",
    "in 2 wk.",
    "23 months ago",
    "2h ago",
    "7 years ago",
    "3 hours ago",
    "in 19 yr.",
    "in twenty years",
    "in two weeks",
    "3 days ago",
    "4 mo. ago",
    "3h ago",
    "Next wk.",
    "in 9 hr.",
    "tomorrow",
    "in 52 minutes",
    "in 5 hr.",
    "in 11 yr.",
    "next yr.",
    "2 hours ago",
    "in 3 hr.",
    "in 48 years",
    "in 13 mo.",
    "4 hours ago",
    "in 30 sec.",
    "57y ago",
    "1 week ago",
    "last yr.",
    "last mo.",
    "16s ago",
    "1h ago",
    "2 weeks ago",
    "twenty-three months ago",
    "in six days",
    "2d ago",
    "in forty-two years",
    "four hours ago",
    "in 16y",
    "in 12 minutes",
    "one year ago",
    "in four days",
    "in 1 hr.",
    "25y ago",
    "three days ago",
    "1 day ago",
    "5h ago",
    "in 26y",
    "6 months ago",
    "in 3 hr.",
    "4 hr. ago",
    "in 3h",
    "2 hours ago",
    "in 24 weeks",
    "in 2h",
    "in 51y",
    "In 2 months",
    "in 1 hr.",
    "5y ago",
    "7 mo. ago",
    "yesterday",
    "in 1d",
    "in ten hours",
    "21y ago",
    "3 months ago",
    "in 0 sec.",
    "in 6 hr.",
    "3 days ago",
    "20 yr. ago",
    "6 days ago",
    "in 3 hr.",
    "1m ago",
    "in 8 mo.",
    "In three years",
    "2 mo. ago",
    "In 33y",
    "in 2 days",
    "In 4 years",
    "8y ago",
    "two days ago",
    "in 1y",
    "eleven months ago",
    "in one day",
    "3y ago",
    "2w ago",
    "3m ago",
    "in nine months",
    "three hours ago",
    "in 9 days",
    "27 min. ago",
    "3 days ago",
    "3 hours ago",
    "8 mo. ago",
    "twenty-four years ago",
    "two hours ago",
    "six days ago",
    "In 11 years",
    "6mo ago",
    "in 24h",
    "6mo ago",
    "45m ago",
    "6d ago",
    "3 hours ago",
    "13 yr. ago",
    "in 1 wk.",
    "5s ago",
    "in two weeks",
    "12y ago",
    "22y ago",
    "20 yr. ago",
    "5d ago",
    "in 49 minutes",
    "15 hours ago",
    "Next month",
    "two hours ago",
    "3 hr. ago",
    "in 2d",
    "in 1 minute",
    "in 12 years",
    "in 1 hour",
    "in 13 years",
    "1 minute ago",
    "two days ago",
    "in 1 second",
    "1 day ago",
    "in five days",
    "34 sec. ago",
    "2 minutes ago",
    "in six days",
    "two hours ago",
    "in 4 hours",
    "in 1 hr.",
    "2h ago",
    "in 13mo",
    "1mo ago",
    "in 8mo",
    "three days ago",
    "in 2 minutes",
    "17 sec. ago",
    "in 3mo",
    "in 4 weeks",
    "in 2 hours",
    "11 hr. ago",
    "in 7 weeks",
    "eleven months ago",
    "in 2 years",
    "2h ago",
    "4h ago",
    "in 17 yr.",
    "in six days",
    "2d ago",
    "26y ago",
    "4 days ago",
    "in five years",
    "3 hr. ago",
    "in one minute",
    "in 3 days",
    "5h ago",
    "In 14y",
    "in two days",
    "twenty-four seconds ago",
    "next week",
    "13 hr. ago",
    "6 yr. ago",
    "1d ago",
    "in 5 hours",
    "in 2 days",
    "In seven months",
    "25mo ago",
    "in 3 hr.",
    "four weeks ago",
    "2 wk. ago",
    "in 3 days",
    "in twenty-two months",
    "3d ago",
    "one day ago",
    "in 2 wk.",
    "4 months ago",
    "nineteen weeks ago",
    "next mo.",
    "1h ago",
    "in 4 hours",
    "in 3 days",
    "in three years",
    "last month",
    "1 wk. ago",
    "2 days ago",
    "now",
    "9 wk. ago",
    "In three hours",
    "in 3d",
    "2 wk. ago",
    "one second ago",
    "next week",
    "38m ago",
    "4 hours ago",
    "in 21s",
    "3 wk. ago",
    "in fifteen years",
    "in 29 seconds",
    "25 minutes ago",
    "36m ago",
    "in 22 yr.",
    "17y ago",
    "in 3 hours",
    "in 3 days",
    "7 hours ago",
    "in zero seconds",
    "10 years ago",
    "4d ago",
    "2 hr. ago",
    "3 hours ago",
    "one month ago",
    "last yr.",
    "2h ago",
    "five days ago",
    "in thirty-seven years",
    "eight months ago",
    "18 days ago",
    "In 1mo",
    "1w ago",
    "In 34 years",
    "tomorrow",
    "five months ago",
    "in 1mo",
    "in 10 mo.",
    "1 day ago",
    "in 2 hr.",
    "in twenty-two months",
    "in 2 hr.",
    "in 4 days",
    "2 hr. ago",
    "in 3 days",
    "5 yr. ago",
    "26 yr. ago",
    "in 3d",
    "2 days ago",
    "in sixteen hours",
    "in 9 yr.",
    "2 years ago",
    "1 month ago",
    "In 1 minute",
    "4h ago",
    "15 months ago",
    "2 hr. ago",
    "4 weeks ago",
    "in 2 weeks",
    "In 8 months",
    "Twenty-one years ago",
    "3 days ago",
    "four hours ago",
    "3d ago",
    "in 51 yr.",
    "in 10 months",
    "38 minutes ago",
    "29 yr. ago",
    "4 days ago",
    "In 3 days",
    "In 18 days",
    "in 4 days",
    "18 years ago",
    "5 mo. ago",
    "in 1 hr.",
    "in eleven weeks",
    "1m ago",
    "tomorrow",
    "in one year",
    "in 1m",
    "13 yr. ago",
    "in two days",
    "2 days ago",
    "3 months ago",
    "in 2 wk.",
    "in two years",
    "3 days ago",
    "two minutes ago",
    "In two months",
    "3 days ago",
    "17 days ago",
    "in two hours",
    "In 1m",
    "in 2 hr.",
    "in 19 hr.",
    "in 5y",
    "two minutes ago",
    "tomorrow",
    "eighteen hours ago",
    "2d ago",
    "12 years ago",
    "in 1 year",
    "three days ago",
    "in 1 day",
    "3 wk. ago",
    "6y ago",
    "In 1 hr.",
    "in 9 mo.",
    "3 days ago",
    "2 minutes ago",
    "9mo ago",
    "in 1 wk.",
    "3h ago",
    "50 yr. ago",
    "in 1 day",
    "in 22y",
    "6 hr. ago",
    "1m ago",
    "Two minutes ago",
    "in 39 yr.",
    "in three months",
    "three days ago",
    "5 hr. ago",
    "in 9 months",
    "18h ago",
    "in fourteen years",
    "in 2 days",
    "3 wk. ago",
    "In 23 years",
    "yesterday",
    "16 weeks ago",
    "in one week",
    "in 59y",
    "47 seconds ago",
    "In 2 months",
    "In 4 seconds",
    "In two minutes",
    "yesterday",
    "in 2 weeks",
    "22 hours ago",
    "25 mo. ago",
    "next mo.",
    "in 1w",
    "in 2 minutes",
    "in 1 hour",
    "eight months ago",
    "3d ago",
    "3 hr. ago",
    "three minutes ago",
    "3 wk. ago",
    "in 5y",
    "7 mo. ago",
    "next yr.",
    "In three hours",
    "in eight months",
    "in 16 mo.",
    "in 0 seconds",
    "In 2m",
    "in 7 months",
    "yesterday",
    "3w ago",
    "Tomorrow",
    "in 1 wk.",
    "3h ago",
    "3 hours ago",
    "in 19 days",
    "last week",
    "in three hours",
    "in ten years",
    "in 2m",
    "in 0m",
    "in 2 weeks",
    "three days ago",
    "2h ago",
    "6 mo. ago",
    "in 16w",
    "in 1m",
    "now",
    "2 minutes ago",
    "In 3h",
    "10 yr. ago",
    "In one minute",
    "in 1 min.",
    "in 7mo",
    "11 mo. ago",
    "In eleven years",
    "four hours ago",
    "next wk.",
    "in four hours",
    "in 1 month",
    "In eight minutes",
    "2 days ago",
    "in 4 hours",
    "3mo ago",
    "in 8mo",
    "in 20 years",
    "last mo.",
    "in 3 days",
    "next wk.",
    "in four minutes",
    "in 21 yr.",
    "in 23 min.",
    "3d ago",
    "2 hours ago",
    "In 50s",
    "13w ago",
    "in 1 month",
    "1 hr. ago",
    "27 yr. ago",
    "in 3 days",
    "23 mo. ago",
    "in two hours",
    "In 5 mo.",
    "in 4 days",
    "40 yr. ago",
    "in 13 mo.",
    "in four hours",
    "in 1 hr.",
    "in 1 hr.",
    "tomorrow",
    "twenty-three weeks ago",
    "in three hours",
    "in eight months",
    "in 2 hr.",
    "in 1 month",
    "3 mo. ago",
    "last wk.",
    "in three hours",
    "In 15h",
    "yesterday",
    "in 3 seconds",
    "4 days ago",
    "in 3h",
    "1 hour ago",
    "three hours ago",
    "In 16 mo.",
    "in 2d",
    "3 hours ago",
    "in eight months",
    "in two hours",
    "23 years ago",
    "3 weeks ago",
    "1 hr. ago",
    "in 3 years",
    "11 months ago",
    "in 11 years",
    "in 3 days",
    "3w ago",
    "in 5 min.",
    "In 2 weeks",
    "in 8 yr.",
    "in 4 wk.",
    "in 6h",
    "In 4w",
    "In one minute",
    "24 months ago",
    "in thirty-seven years",
    "25 years ago",
    "39y ago",
    "in 5h",
    "in 6 months",
    "in 2 days",
    "in 4h",
    "fifty-five seconds ago",
    "six hours ago",
    "17 months ago",
    "next month",
    "in 4 days",
    "1 day ago",
    "in 4 wk.",
    "in 10 wk.",
    "3 weeks ago",
    "In 2 hours",
    "3 days ago",
    "in 1 minute",
    "10 mo. ago",
    "In one day",
    "in thirty-one seconds",
    "1m ago",
    "3w ago",
    "23 yr. ago",
    "1 min. ago",
    "two hours ago",
    "2 days ago",
    "two weeks ago",
    "in six weeks",
    "in 24m",
    "One month ago",
    "last month",
    "1 hour ago",
    "in 12 years",
    "In 3 minutes",
    "6 hours ago",
    "in zero seconds",
    "in 24 sec.",
    "In 13y",
    "in 4mo",
    "4h ago",
    "three hours ago",
    "in 17 sec.",
    "in 15y",
    "in 13 years",
    "in 1m",
    "4 days ago",
    "in 3mo",
    "16 months ago",
    "in 1 hour",
    "in 23 hr.",
    "in 2d",
    "yesterday",
    "Twenty-three years ago",
    "Four days ago",
    "eight seconds ago",
    "1 min. ago",
    "1 month ago",
    "in 9y",
    "four hours ago",
    "in 1 hour",
    "37y ago",
    "2 days ago",
    "in 9y",
    "5h ago",
    "1 min. ago",
    "last month",
    "7 sec. ago",
    "eleven weeks ago",
    "30 yr. ago",
    "in 1 min.",
    "in 4h",
    "Next wk.",
    "in 11mo",
    "10 months ago",
    "in 2h",
    "next wk.",
    "55y ago",
    "in 9 months",
    "in 8 mo.",
    "last mo.",
    "in 44 years",
    "3 months ago",
    "in 5mo",
    "in 13 hours",
    "5 days ago",
    "6s ago",
    "4 hours ago",
    "24 yr. ago",
    "33 years ago",
    "2 hours ago",
    "43y ago",
    "4 weeks ago",
    "five months ago",
    "five hours ago",
    "In one hour",
    "in six days",
    "in 24 yr.",
    "twenty-three years ago",
    "in 8 yr.",
    "In 6 days",
    "two minutes ago",
    "Next mo.",
    "in 16 yr.",
    "2 weeks ago",
    "In 3 days",
    "in 2w",
    "one hour ago",
    "9mo ago",
    "in three days",
    "yesterday",
    "2 days ago",
    "in forty-one years",
    "16 mo. ago",
    "in 57y",
    "2 wk. ago",
    "51y ago",
    "20 years ago",
    "in 6 yr.",
    "in 2 hr.",
    "in 38y",
    "in 8 hr.",
    "in 42s",
    "in 13 years",
    "51 sec. ago",
    "next mo.",
    "four months ago",
    "in 2 mo.",
    "24 yr. ago",
    "last year",
    "4 days ago",
    "two months ago",
    "in 5 hours",
    "18 mo. ago",
    "in 48 seconds",
    "in 4 hours",
    "4 hours ago",
    "4 hours ago",
    "Twenty years ago",
    "in six months",
    "In 6 years",
    "in eleven years",
    "4 hours ago",
    "in 7 years",
    "one hour ago",
    "in two hours",
    "3d ago",
    "Two days ago",
    "in 18 wk.",
    "48 years ago",
    "five months ago",
    "in 5 hr.",
    "4 days ago",
    "eighteen years ago",
    "four weeks ago",
    "next mo.",
    "one minute ago",
    "tomorrow",
    "9 wk. ago",
    "next year",
    "5 days ago",
    "In 59m",
    "in 23h",
    "24 days ago",
    "In 22 years",
    "one day ago",
    "16 hours ago",
    "21 seconds ago",
    "in 6 yr.",
    "five days ago",
    "in 23h",
    "Last yr.",
    "fifteen years ago",
    "in 9 mo.",
    "In 2 wk.",
    "one hour ago",
    "in 11 months",
    "in 2 min.",
    "22mo ago",
    "4 hr. ago",
    "in six months",
    "In 2 minutes",
    "in 3 mo.",
    "in 22y",
    "in fifty-eight minutes",
    "six days ago",
    "three hours ago",
    "in 16y",
    "ten years ago",
    "in 3 wk.",
    "in 3 hours",
    "eight seconds ago",
    "4 hours ago",
    "in fourteen months",
    "in 2m",
    "Four hours ago",
    "Twenty-two seconds ago",
    "3 hours ago",
    "nineteen years ago",
    "in 2 days",
    "In 5h",
    "In 2 days",
    "4 mo. ago",
    "in fourteen weeks",
    "in 1 min.",
    "38m ago",
    "in 3 hr.",
    "in 1 min.",
    "twelve months ago",
    "in 2 wk.",
    "2 weeks ago",
    "in 1 hr.",
    "12h ago",
    "in twelve years",
    "6h ago",
    "In 4 hours",
    "3w ago",
    "6d ago",
    "13 wk. ago",
    "3 months ago",
    "in 1 minute",
    "in two weeks",
    "In 1h",
    "in 14 yr.",
    "four months ago",
    "in one day",
    "in 14 hours",
    "twenty-five years ago",
    "in 15 months",
    "1 min. ago",
    "In 59 years",
    "two days ago",
    "4 hr. ago",
    "Nineteen years ago",
    "in 2 hr.",
    "in 2 minutes",
    "in 2m",
    "3d ago",
    "in twelve years",
    "2h ago",
    "In three days",
    "next mo.",
    "Next week",
    "in 23 yr.",
    "11mo ago",
    "three hours ago",
    "52y ago",
    "two hours ago",
    "4 months ago",
    "in 1h",
    "one hour ago",
    "in 1h",
    "in 1m",
    "in 16 wk.",
    "two hours ago",
    "in 56 sec.",
    "In 27y",
    "in four hours",
    "in 10mo",
    "in one minute",
    "in 3h",
    "fifty-three years ago",
    "5 days ago",
    "tomorrow",
    "3d ago",
    "in 27m",
    "Eleven months ago",
    "In 1 year",
    "1y ago",
    "Four days ago",
    "in 19m",
    "1 hr. ago",
    "six hours ago",
    "two hours ago",
    "in three days",
    "33s ago",
    "19 years ago",
    "1 day ago",
    "14y ago",
    "in two days",
    "in 1 wk.",
    "in 2h",
    "in 3 min.",
    "5y ago",
    "1 week ago",
    "2 wk. ago",
    "26 yr. ago",
    "1 min. ago",
    "15w ago",
    "in 2 days",
    "in one minute",
    "2 months ago",
    "in four days",
    "14 yr. ago",
    "10 mo. ago",
    "In one week",
    "in 10mo",
    "five days ago",
    "8 months ago",
    "in 31s",
    "in twenty-three hours",
    "in 6m",
    "in 6d",
    "16 months ago",
    "last week",
    "1h ago",
    "15 years ago",
    "1y ago",
    "in eighteen years",
    "one day ago",
    "in six days",
    "two days ago",
    "In 2 wk.",
    "3w ago",
    "in five months",
    "In 3 days",
    "in two hours",
    "51y ago",
    "16 years ago",
    "1 minute ago",
    "in forty-four years",
    "in four days",
    "In 5d",
    "next yr.",
    "1 hour ago",
    "in 4w",
    "10mo ago",
    "last mo.",
    "In 13y",
    "three hours ago",
    "2d ago",
    "in five hours",
    "in one minute",
    "in 24 years",
    "30 years ago",
    "3 hours ago",
    "in 3 hr.",
    "in 8mo",
    "24 years ago",
    "4 days ago",
    "in 2h",
    "in 4w",
    "four days ago",
    "23 years ago",
    "47 yr. ago",
    "two days ago",
    "Thirty-five years ago",
    "1 hr. ago",
    "8 years ago",
    "in 2 hours",
    "In 1mo",
    "in 3 days",
    "next week",
    "in 17 yr.",
    "3mo ago",
    "three days ago",
    "in 2 days",
    "last week",
    "9 yr. ago",
    "in 37y",
    "in 3 days",
    "In 2d",
    "15 years ago",
    "2mo ago",
    "in two hours",
    "in five months",
    "tomorrow",
    "tomorrow",
    "in 13 years",
    "yesterday",
    "in 3d",
    "in two hours",
    "2d ago",
    "in 2y",
    "in 5 hours",
    "1h ago",
    "2m ago",
    "2m ago",
    "2 years ago",
    "1 wk. ago",
    "1 min. ago",
    "in 3 hr.",
    "In 3 days",
    "in 8y",
    "4 days ago",
    "2 days ago",
    "one hour ago",
    "52y ago",
    "in 9y",
    "last wk.",
    "in one hour",
    "2 weeks ago",
    "last yr.",
    "in 4y",
    "3h ago",
    "3h ago",
    "3 days ago",
    "In 4 months",
    "in 6 years",
    "now",
    "3 days ago",
    "next wk.",
    "in 2 days",
    "four years ago",
    "in 1 minute",
    "2 hr. ago",
    "two months ago",
    "In six months",
    "15y ago",
    "in 2 hours",
    "2 minutes ago",
    "in 7 min.",
    "5 hours ago",
    "in 7 hr.",
    "16h ago",
    "in 1 min.",
    "in three hours",
    "four hours ago",
    "in 13w",
    "in three days",
    "in two days",
    "in fifteen hours",
    "in 2 days",
    "in 22 years",
    "in one day",
    "In 1m",
    "two days ago",
    "Last month",
    "4 months ago",
    "in 6 months",
    "in 3 minutes",
    "29y ago",
    "2 wk. ago",
    "thirteen days ago",
    "In 2 hours",
    "Two weeks ago",
    "in 41y",
    "in 2 days",
    "In 18 months",
    "in zero seconds",
    "in 2h",
    "39 sec. ago",
    "Nine months ago",
    "2mo ago",
    "4 hr. ago",
    "in five years",
    "in 4 hours",
    "5 hr. ago",
    "10 years ago",
    "10mo ago",
    "4 hr. ago",
    "In 4 days",
    "In 13 min.",
    "25 mo. ago",
    "2 days ago",
    "in 2 hr.",
    "in four hours",
    "last week",
    "23 months ago",
    "16m ago",
    "in 5 minutes",
    "1 minute ago",
    "next wk.",
    "19y ago",
    "in two days",
    "in 29y",
    "thirteen minutes ago",
    "1 min. ago",
    "In 2h",
    "ten hours ago",
    "one hour ago",
    "38y ago",
    "in 16s",
    "in five months",
    "1 week ago",
    "In five months",
    "3 days ago",
    "17 yr. ago",
    "in 9 months",
    "In 9mo",
    "1 mo. ago",
    "in 2 days",
    "in 2d",
    "nine years ago",
    "Two minutes ago",
    "in 3w",
    "In 45 yr.",
    "six days ago",
    "in 20w",
    "in 3 hours",
    "1m ago",
    "1 wk. ago",
    "2 days ago",
    "4 years ago",
    "one minute ago",
    "40 years ago",
    "in 2 mo.",
    "tomorrow",
    "in 6 months",
    "in one hour",
    "yesterday",
    "in 2 wk.",
    "In one week",
    "20 yr. ago",
    "in 3 hr.",
    "in 4 hours",
    "12y ago",
    "in 4 months",
    "in 17 months",
    "in 43 years",
    "six months ago",
    "two weeks ago",
    "in 1 hr.",
    "In 24 days",
    "1y ago",
    "in 23 yr.",
    "in three hours",
    "in 2 min.",
    "in six years",
    "three hours ago",
    "5 hr. ago",
    "9 months ago",
    "one hour ago",
    "in 23 yr.",
    "in 1w",
    "1m ago",
    "last mo.",
    "yesterday",
    "20 years ago",
    "now",
    "In 1 week",
    "9mo ago",
    "6 days ago",
    "next year",
    "in four days",
    "in 4 hours",
    "one month ago",
    "1m ago",
    "19 mo. ago",
    "In 4 hr.",
    "two days ago",
    "6 days ago",
    "In three months",
    "in 13 yr.",
    "33 yr. ago",
    "last wk.",
    "in 2h",
    "10 hr. ago",
    "in twenty-two years",
    "1 month ago",
    "2 days ago",
    "in 2 hours",
    "twenty-three hours ago",
    "in six years",
    "in 2 hours",
    "One month ago",
    "two days ago",
    "in four hours",
    "in 12 yr.",
    "next month",
    "6d ago",
    "in 15h",
    "in one minute",
    "15h ago",
    "in 10 mo.",
    "next wk.",
    "11y ago",
    "49s ago",
    "in 21 years",
    "in one hour",
    "in 2 weeks",
    "in three hours",
    "2d ago",
    "22 weeks ago",
    "In 16 hours",
    "1 day ago",
    "in 4mo",
    "3 days ago",
    "today",
    "3d ago",
    "3d ago",
    "In 3d",
    "next mo.",
    "next yr.",
    "In 5 mo.",
    "in 5 hr.",
    "in 3 days",
    "2mo ago",
    "in 17y",
    "eight months ago",
    "1h ago",
    "in 4 days",
    "1 hour ago",
    "five weeks ago",
    "In 4 hr.",
    "in 1d",
    "twenty-three seconds ago",
    "31 years ago",
    "in twenty months",
    "in 5 days",
    "2 wk. ago",
    "11 months ago",
    "5 min. ago",
    "16d ago",
    "now",
    "next month",
    "1h ago",
    "in fifty-three years",
    "5 wk. ago",
    "In four days",
    "31m ago",
    "3 yr. ago",
    "in 5 mo.",
    "in 4mo",
    "in fifty-three years",
    "in 5 hr.",
    "In 2d",
    "thirty-eight years ago",
    "eighteen months ago",
    "1h ago",
    "1 hour ago",
    "in two weeks",
    "6d ago",
    "in thirteen minutes",
    "In 3 hr.",
    "1 day ago",
    "in 1 minute",
    "last mo.",
    "3y ago",
    "2w ago",
    "In 3h",
    "four hours ago",
    "two minutes ago",
    "in twenty months",
    "in 5 hr.",
    "1 min. ago",
    "tomorrow",
    "in 2 years",
    "in 6 years",
    "in 3 weeks",
    "last week",
    "six hours ago",
    "1h ago",
    "9 mo. ago",
    "Next wk.",
    "In 10 hr.",
    "2 days ago",
    "in 4 hr.",
    "22mo ago",
    "in 3 hours",
    "In 3 months",
    "4 hours ago",
    "one year ago",
    "twenty-two months ago",
    "8 min. ago",
    "27y ago",
    "in 3 hours",
    "in four hours",
    "in 6 yr.",
    "six days ago",
    "in 3 hours",
    "2h ago",
    "in 33 yr.",
    "20 weeks ago",
    "1mo ago",
    "9 yr. ago",
    "in 2 mo.",
    "in 1 day",
    "In 9 yr.",
    "two weeks ago",
    "fifty-nine seconds ago",
    "6mo ago",
    "in 3d",
    "in 16 months",
    "In 3 hours",
    "In 40y",
    "Twelve hours ago",
    "in twenty years",
    "in 11 mo.",
    "3d ago",
    "36 seconds ago",
    "tomorrow",
    "3 hr. ago",
    "last year",
    "four hours ago",
    "last mo.",
    "in 10h",
    "54 yr. ago",
    "2 months ago",
    "2d ago",
    "last week",
    "50s ago",
    "4 days ago",
    "In nineteen years",
    "1m ago",
    "in 19 years",
    "4 hours ago",
    "3h ago",
    "next mo.",
    "1d ago",
    "3 days ago",
    "in 2 hours",
    "7 months ago",
    "20y ago",
    "10mo ago",
    "yesterday",
    "3 days ago",
    "3 wk. ago",
    "in 7mo",
    "6 hours ago",
    "nine months ago",
    "last month",
    "4 yr. ago",
    "In 20 weeks",
    "in 5 months",
    "in two hours",
    "In 6mo",
    "in 9 mo.",
    "4 yr. ago",
    "next mo.",
    "In 4 hours",
    "2 months ago",
    "in six months",
    "in fifteen weeks",
    "3d ago",
    "6 days ago",
    "in twenty-five years",
    "in thirteen hours",
    "twenty-five years ago",
    "One minute ago",
    "in 1m",
    "38 years ago",
    "five days ago",
    "in 23 years",
    "next week",
    "In 28s",
    "in three days",
    "one day ago",
    "in 2 years",
    "four hours ago",
    "In 4 hr.",
    "in 4 mo.",
    "50y ago",
    "in twenty-three years",
    "two days ago",
    "2d ago",
    "fifteen minutes ago",
    "three months ago",
    "10mo ago",
    "in one day",
    "in 0 sec.",
    "17 seconds ago",
    "6 days ago",
    "in 17w",
    "in 30 minutes",
    "in 1h",
    "in 48 yr.",
    "26s ago",
    "Twenty-four years ago",
    "last wk.",
    "in 1 hr.",
    "in 3 hr.",
    "in 22y",
    "21 yr. ago",
    "last month",
    "in 52 minutes",
    "3 wk. ago",
    "3 days ago",
    "24 yr. ago",
    "In 7y",
    "tomorrow",
    "in 3 days",
    "5d ago",
    "13 months ago",
    "3 hr. ago",
    "3 minutes ago",
    "54s ago",
    "in 1 hour",
    "in 4y",
    "20 years ago",
    "in nineteen years",
    "yesterday",
    "in 12y",
    "in 6y",
    "in 2m",
    "In twenty-seven minutes",
    "in 1 hour",
    "in 2m",
    "In 19w",
    "Five months ago",
    "in 3d",
    "2m ago",
    "in 19 sec.",
    "3w ago",
    "3w ago",
    "3m ago",
    "16 years ago",
    "in 3m",
    "3 yr. ago",
    "2 yr. ago",
    "Next month",
    "In 3w",
    "In 5 hr.",
    "in 15 wk.",
    "2 hours ago",
    "in 1m",
    "last mo.",
    "Yesterday",
    "Six years ago",
    "3 wk. ago",
    "in 3 wk.",
    "in 2 days",
    "2 minutes ago",
    "in 7m",
    "In 2 days",
    "In 1m",
    "in 2d",
    "in 2 min.",
    "14mo ago",
    "in 45 minutes",
    "2d ago",
    "in eleven months",
    "two minutes ago",
    "18y ago",
    "9mo ago",
    "In sixteen hours",
    "17 hours ago",
    "in 2m",
    "In 1 yr.",
    "in 3 wk.",
    "3 days ago",
    "51 sec. ago",
    "2d ago",
    "in seven years",
    "next month",
    "in 2 weeks",
    "1 mo. ago",
    "in 4 days",
    "22 mo. ago",
    "2 hours ago",
    "1 year ago",
    "last wk.",
    "five hours ago",
    "7y ago",
    "1y ago",
    "2 months ago",
    "in 2 weeks",
    "1 wk. ago",
    "in six years",
    "1w ago",
    "in 3s",
    "last mo.",
    "yesterday",
    "nine years ago",
    "in thirty-four seconds",
    "6 days ago",
    "In 7 minutes",
    "in 31y",
    "Yesterday",
    "6 hr. ago",
    "in 3h",
    "19 yr. ago",
    "43 sec. ago",
    "in 20 days",
    "In 2 yr.",
    "In 34s",
    "last week",
    "in eighteen seconds",
    "24 mo. ago",
    "42y ago",
    "in 3 mo.",
    "sixteen years ago",
    "in 51 years",
    "in 19mo",
    "11 months ago",
    "tomorrow",
    "in 22 years",
    "In eleven months",
    "in 5 yr.",
    "in 40 sec.",
    "in 43y",
    "in 1 minute",
    "2 min. ago",
    "in 6 yr.",
    "in 4 days",
    "in 3 weeks",
    "in eleven months",
    "in 14 minutes",
    "in 9y",
    "two days ago",
    "2 minutes ago",
    "Yesterday",
    "2 hours ago",
    "in five months",
    "1m ago",
    "in fifty minutes",
    "in four hours",
    "in two days",
    "five years ago",
    "in 4 days",
    "Next month",
    "four days ago",
    "in zero seconds",
    "8y ago",
    "in 5 hours",
    "in 2 weeks",
    "in 3w",
    "in 2 hr.",
    "twenty hours ago",
    "two hours ago",
    "2m ago",
    "in 3 hr.",
    "48 years ago",
    "in 11y",
    "In 4 hours",
    "in 1 year",
    "in 11mo",
    "one minute ago",
    "4 yr. ago",
    "in two hours",
    "In two hours",
    "in 3 days",
    "in 2 hours",
    "In 3 yr.",
    "in 2 days",
    "five days ago",
    "in 3 wk.",
    "in 30 years",
    "in 16m",
    "in 10 mo.",
    "One hour ago",
    "in 3 hr.",
    "fifty-two years ago",
    "In 24 weeks",
    "in 5 hours",
    "in 2h",
    "in four seconds",
    "in 4 hours",
    "19 weeks ago",
    "4 hr. ago",
    "last wk.",
    "3m ago",
    "in 55 yr.",
    "in fourteen weeks",
    "three days ago",
    "6 days ago",
    "in 16 yr.",
    "4 hours ago",
    "twenty-three years ago",
    "3d ago",
    "In zero seconds",
    "in 1 minute",
    "fifty-two minutes ago",
    "22 yr. ago",
    "in 24y",
    "in 2 hr.",
    "19y ago",
    "in 4h",
    "in 24 wk.",
    "in 2 months",
    "in 3 hr.",
    "in two hours",
    "in 1 minute",
    "in seventeen months",
    "In 4h",
    "2 min. ago",
    "3s ago",
    "in eight months",
    "In 12 months",
    "in nine months",
    "5d ago",
    "in 3w",
    "23 yr. ago",
    "in 22 yr.",
    "3m ago",
    "39 sec. ago",
    "in 33 sec.",
    "in 11 months",
    "in 18 yr.",
    "in 3 days",
    "Last wk.",
    "2 hr. ago",
    "last mo.",
    "seventeen years ago",
    "two days ago",
    "in 4h",
    "4 wk. ago",
    "forty-two seconds ago",
    "in 20 years",
    "in 3 days",
    "last wk.",
    "in 3 weeks",
    "in 3mo",
    "23 years ago",
    "3h ago",
    "in four hours",
    "10mo ago",
    "In 1 year",
    "in 17 yr.",
    "8y ago",
    "in 15 yr.",
    "in 1 mo.",
    "in 10y",
    "in twenty-three months",
    "Next week",
    "2 days ago",
    "1 minute ago",
    "in one minute",
    "15y ago",
    "in one month",
    "in 3 wk.",
    "in 32 min.",
    "eight minutes ago",
    "18 months ago",
    "in 8 mo.",
    "49 yr. ago",
    "22 minutes ago",
    "in 2d",
    "1 month ago",
    "one hour ago",
    "next week",
    "in 47 seconds",
    "3 months ago",
    "3 weeks ago",
    "4 hours ago",
    "in 5 days",
    "three minutes ago",
    "In 1 hour",
    "in 20mo",
    "1y ago",
    "2 days ago",
    "In 46 sec.",
    "2h ago",
    "18y ago",
    "in 42 years",
    "in 2d",
    "in 45 yr.",
    "9 mo. ago",
    "in 13w",
    "in 2 months",
    "28y ago",
    "1h ago",
    "3 days ago",
    "in seventeen years",
    "2d ago",
    "9 min. ago",
    "next week",
    "16 yr. ago",
    "23w ago",
    "in 3 days",
    "in 5h",
    "3w ago",
    "in 4 days",
    "in 15 weeks",
    "1 hr. ago",
    "3 hr. ago",
    "in 1 month",
    "four hours ago",
    "20 yr. ago",
    "1 day ago",
    "tomorrow",
    "Four hours ago",
    "in 6 yr.",
    "3 years ago",
    "55m ago",
    "4h ago",
    "in 1 yr.",
    "three days ago",
    "in 18y",
    "three days ago",
    "next wk.",
    "58y ago",
    "eighteen hours ago",
    "15 mo. ago",
    "in 3 days",
    "next wk.",
    "1 day ago",
    "in one hour",
    "25 mo. ago",
    "3d ago",
    "1 hr. ago",
    "In 2 days",
    "in 34 seconds",
    "twenty-two weeks ago",
    "next week",
    "in 1d",
    "two hours ago",
    "last week",
    "nine years ago",
    "in three days",
    "in one hour",
    "3 wk. ago",
    "in four weeks",
    "In 8 years",
    "in 4mo",
    "in 1 min.",
    "in 8 yr.",
    "two minutes ago",
    "11 yr. ago",
    "two hours ago",
    "in three days",
    "1 mo. ago",
    "in one day",
    "ten weeks ago",
    "in three weeks",
    "2w ago",
    "in 9 mo.",
    "in 2 yr.",
    "two years ago",
    "in 2 days",
    "2d ago",
    "in 3 hr.",
    "One hour ago",
    "This hour",
    "3 days ago",
    "in 4 days",
    "In 4d",
    "10 months ago",
    "four years ago",
    "forty-five years ago",
    "10 months ago",
    "3 hr. ago",
    "3 days ago",
    "22w ago",
    "46 years ago",
    "1w ago",
    "2 hr. ago",
    "in 2d",
    "next mo.",
    "in 1 week",
    "In four hours",
    "2h ago",
    "2 hr. ago",
    "5y ago",
    "in 12 yr.",
    "in 35 years",
    "in 8 sec.",
    "in three days",
    "in 10 weeks",
};
