// The answers of the host's SceneKit, written by host/scenekit-defaults/refresh.sh from scenekit-defaults-cases.m.
    {"SCNLight.type", "omni"},
    {"SCNLight.color", "colour 1 1 1 1"},
    {"SCNLight.temperature", "6500"},
    {"SCNLight.intensity", "1000"},
    {"SCNLight.name", "nil"},
    {"SCNLight.castsShadow", "0"},
    {"SCNLight.shadowColor", "colour 0 0 0 1"},
    {"SCNLight.shadowRadius", "3"},
    {"SCNLight.zNear", "1"},
    {"SCNLight.zFar", "100"},
    {"SCNLight.attenuationStartDistance", "0"},
    {"SCNLight.attenuationEndDistance", "0"},
    {"SCNLight.attenuationFalloffExponent", "2"},
    {"SCNLight.spotInnerAngle", "0"},
    {"SCNLight.spotOuterAngle", "45"},
    {"SCNLight.categoryBitMask", "all bits"},
    {"SCNCamera.name", "nil"},
    {"SCNCamera.fieldOfView", "60"},
    {"SCNCamera.zNear", "1"},
    {"SCNCamera.zFar", "100"},
    {"SCNCamera.usesOrthographicProjection", "0"},
    {"SCNCamera.orthographicScale", "1"},
    {"SCNCamera.automaticallyAdjustsZRange", "0"},
    {"SCNParticleSystem.emissionDuration", "1"},
    {"SCNParticleSystem.loops", "1"},
    {"SCNParticleSystem.birthRate", "0"},
    {"SCNParticleSystem.warmupDuration", "0"},
    {"SCNParticleSystem.spreadingAngle", "0"},
    {"SCNParticleSystem.emittingDirection", "0 1 0"},
    {"SCNParticleSystem.acceleration", "0 0 0"},
    {"SCNParticleSystem.particleAngleVariation", "0"},
    {"SCNParticleSystem.particleVelocity", "0"},
    {"SCNParticleSystem.particleVelocityVariation", "0"},
    {"SCNParticleSystem.particleAngularVelocity", "0"},
    {"SCNParticleSystem.particleLifeSpan", "1"},
    {"SCNParticleSystem.particleLifeSpanVariation", "0"},
    {"SCNParticleSystem.particleImage", "nil"},
    {"SCNParticleSystem.particleColor", "colour 1 1 1 1"},
    {"SCNParticleSystem.particleColorVariation", "0 0 0 0"},
    {"SCNParticleSystem.particleSize", "1"},
    {"SCNParticleSystem.particleSizeVariation", "0"},
    {"SCNParticleSystem.blendMode", "0"},
    {"SCNParticleSystem.orientationMode", "0"},
    {"SCNParticleSystem.sortingMode", "0"},
    {"SCNParticleSystem.lightingEnabled", "0"},
    {"SCNParticleSystem.affectedByGravity", "0"},
    {"SCNParticleSystem.affectedByPhysicsFields", "0"},
    {"SCNParticleSystem.speedFactor", "1"},
    {"SCNParticleSystem.stretchFactor", "0"},
    {"SCNParticleSystem.propertyControllers", "nil"},
    {"SCNParticleSystem.emitterShape", "nil"},
    {"SCNMaterial.name", "nil"},
    {"SCNMaterial.lightingModelName", "SCNLightingModelBlinn"},
    {"SCNMaterial.doubleSided", "0"},
    {"SCNMaterial.transparency", "1"},
    {"SCNMaterial.shininess", "1"},
    {"SCNMaterial.blendMode", "0"},
    {"SCNMaterial.locksAmbientWithDiffuse", "1"},
    {"SCNMaterial.cullMode", "0"},
    {"SCNMaterial.writesToDepthBuffer", "1"},
    {"SCNMaterial.readsFromDepthBuffer", "1"},
    {"SCNMaterial.diffuse.contents", "colour 1 1 1 1"},
    {"SCNMaterial.diffuse.intensity", "1"},
    {"SCNMaterial.diffuse.minificationFilter", "2"},
    {"SCNMaterial.diffuse.magnificationFilter", "2"},
    {"SCNMaterial.diffuse.mipFilter", "1"},
    {"SCNMaterial.diffuse.wrapS", "1"},
    {"SCNMaterial.diffuse.wrapT", "1"},
    {"SCNMaterial.diffuse.mappingChannel", "0"},
    {"SCNMaterial.diffuse.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.ambient.contents", "colour 0.484529 0.484529 0.484529 1"},
    {"SCNMaterial.ambient.intensity", "1"},
    {"SCNMaterial.ambient.minificationFilter", "2"},
    {"SCNMaterial.ambient.magnificationFilter", "2"},
    {"SCNMaterial.ambient.mipFilter", "1"},
    {"SCNMaterial.ambient.wrapS", "1"},
    {"SCNMaterial.ambient.wrapT", "1"},
    {"SCNMaterial.ambient.mappingChannel", "0"},
    {"SCNMaterial.ambient.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.specular.contents", "colour 0 0 0 1"},
    {"SCNMaterial.specular.intensity", "1"},
    {"SCNMaterial.specular.minificationFilter", "2"},
    {"SCNMaterial.specular.magnificationFilter", "2"},
    {"SCNMaterial.specular.mipFilter", "1"},
    {"SCNMaterial.specular.wrapS", "1"},
    {"SCNMaterial.specular.wrapT", "1"},
    {"SCNMaterial.specular.mappingChannel", "0"},
    {"SCNMaterial.specular.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.normal.contents", "colour 1 1 1 1"},
    {"SCNMaterial.normal.intensity", "1"},
    {"SCNMaterial.normal.minificationFilter", "2"},
    {"SCNMaterial.normal.magnificationFilter", "2"},
    {"SCNMaterial.normal.mipFilter", "1"},
    {"SCNMaterial.normal.wrapS", "1"},
    {"SCNMaterial.normal.wrapT", "1"},
    {"SCNMaterial.normal.mappingChannel", "0"},
    {"SCNMaterial.normal.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.reflective.contents", "colour 0 0 0 1"},
    {"SCNMaterial.reflective.intensity", "1"},
    {"SCNMaterial.reflective.minificationFilter", "2"},
    {"SCNMaterial.reflective.magnificationFilter", "2"},
    {"SCNMaterial.reflective.mipFilter", "1"},
    {"SCNMaterial.reflective.wrapS", "1"},
    {"SCNMaterial.reflective.wrapT", "1"},
    {"SCNMaterial.reflective.mappingChannel", "0"},
    {"SCNMaterial.reflective.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.emission.contents", "colour 0 0 0 1"},
    {"SCNMaterial.emission.intensity", "1"},
    {"SCNMaterial.emission.minificationFilter", "2"},
    {"SCNMaterial.emission.magnificationFilter", "2"},
    {"SCNMaterial.emission.mipFilter", "1"},
    {"SCNMaterial.emission.wrapS", "1"},
    {"SCNMaterial.emission.wrapT", "1"},
    {"SCNMaterial.emission.mappingChannel", "0"},
    {"SCNMaterial.emission.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.transparent.contents", "colour 1 1 1 1"},
    {"SCNMaterial.transparent.intensity", "1"},
    {"SCNMaterial.transparent.minificationFilter", "2"},
    {"SCNMaterial.transparent.magnificationFilter", "2"},
    {"SCNMaterial.transparent.mipFilter", "1"},
    {"SCNMaterial.transparent.wrapS", "1"},
    {"SCNMaterial.transparent.wrapT", "1"},
    {"SCNMaterial.transparent.mappingChannel", "0"},
    {"SCNMaterial.transparent.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.multiply.contents", "colour 1 1 1 1"},
    {"SCNMaterial.multiply.intensity", "1"},
    {"SCNMaterial.multiply.minificationFilter", "2"},
    {"SCNMaterial.multiply.magnificationFilter", "2"},
    {"SCNMaterial.multiply.mipFilter", "1"},
    {"SCNMaterial.multiply.wrapS", "1"},
    {"SCNMaterial.multiply.wrapT", "1"},
    {"SCNMaterial.multiply.mappingChannel", "0"},
    {"SCNMaterial.multiply.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.displacement.contents", "colour 0 0 0 1"},
    {"SCNMaterial.displacement.intensity", "1"},
    {"SCNMaterial.displacement.minificationFilter", "2"},
    {"SCNMaterial.displacement.magnificationFilter", "2"},
    {"SCNMaterial.displacement.mipFilter", "1"},
    {"SCNMaterial.displacement.wrapS", "1"},
    {"SCNMaterial.displacement.wrapT", "1"},
    {"SCNMaterial.displacement.mappingChannel", "0"},
    {"SCNMaterial.displacement.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.ambientOcclusion.contents", "colour 1 1 1 1"},
    {"SCNMaterial.ambientOcclusion.intensity", "1"},
    {"SCNMaterial.ambientOcclusion.minificationFilter", "2"},
    {"SCNMaterial.ambientOcclusion.magnificationFilter", "2"},
    {"SCNMaterial.ambientOcclusion.mipFilter", "1"},
    {"SCNMaterial.ambientOcclusion.wrapS", "1"},
    {"SCNMaterial.ambientOcclusion.wrapT", "1"},
    {"SCNMaterial.ambientOcclusion.mappingChannel", "0"},
    {"SCNMaterial.ambientOcclusion.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.selfIllumination.contents", "colour 0 0 0 1"},
    {"SCNMaterial.selfIllumination.intensity", "1"},
    {"SCNMaterial.selfIllumination.minificationFilter", "2"},
    {"SCNMaterial.selfIllumination.magnificationFilter", "2"},
    {"SCNMaterial.selfIllumination.mipFilter", "1"},
    {"SCNMaterial.selfIllumination.wrapS", "1"},
    {"SCNMaterial.selfIllumination.wrapT", "1"},
    {"SCNMaterial.selfIllumination.mappingChannel", "0"},
    {"SCNMaterial.selfIllumination.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.metalness.contents", "colour 0 0 0 1"},
    {"SCNMaterial.metalness.intensity", "1"},
    {"SCNMaterial.metalness.minificationFilter", "2"},
    {"SCNMaterial.metalness.magnificationFilter", "2"},
    {"SCNMaterial.metalness.mipFilter", "1"},
    {"SCNMaterial.metalness.wrapS", "1"},
    {"SCNMaterial.metalness.wrapT", "1"},
    {"SCNMaterial.metalness.mappingChannel", "0"},
    {"SCNMaterial.metalness.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.roughness.contents", "colour 0.484529 0.484529 0.484529 1"},
    {"SCNMaterial.roughness.intensity", "1"},
    {"SCNMaterial.roughness.minificationFilter", "2"},
    {"SCNMaterial.roughness.magnificationFilter", "2"},
    {"SCNMaterial.roughness.mipFilter", "1"},
    {"SCNMaterial.roughness.wrapS", "1"},
    {"SCNMaterial.roughness.wrapT", "1"},
    {"SCNMaterial.roughness.mappingChannel", "0"},
    {"SCNMaterial.roughness.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.clearCoat.contents", "colour 0 0 0 1"},
    {"SCNMaterial.clearCoat.intensity", "1"},
    {"SCNMaterial.clearCoat.minificationFilter", "2"},
    {"SCNMaterial.clearCoat.magnificationFilter", "2"},
    {"SCNMaterial.clearCoat.mipFilter", "1"},
    {"SCNMaterial.clearCoat.wrapS", "1"},
    {"SCNMaterial.clearCoat.wrapT", "1"},
    {"SCNMaterial.clearCoat.mappingChannel", "0"},
    {"SCNMaterial.clearCoat.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.clearCoatRoughness.contents", "colour 0 0 0 1"},
    {"SCNMaterial.clearCoatRoughness.intensity", "1"},
    {"SCNMaterial.clearCoatRoughness.minificationFilter", "2"},
    {"SCNMaterial.clearCoatRoughness.magnificationFilter", "2"},
    {"SCNMaterial.clearCoatRoughness.mipFilter", "1"},
    {"SCNMaterial.clearCoatRoughness.wrapS", "1"},
    {"SCNMaterial.clearCoatRoughness.wrapT", "1"},
    {"SCNMaterial.clearCoatRoughness.mappingChannel", "0"},
    {"SCNMaterial.clearCoatRoughness.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterial.clearCoatNormal.contents", "colour 1 1 1 1"},
    {"SCNMaterial.clearCoatNormal.intensity", "1"},
    {"SCNMaterial.clearCoatNormal.minificationFilter", "2"},
    {"SCNMaterial.clearCoatNormal.magnificationFilter", "2"},
    {"SCNMaterial.clearCoatNormal.mipFilter", "1"},
    {"SCNMaterial.clearCoatNormal.wrapS", "1"},
    {"SCNMaterial.clearCoatNormal.wrapT", "1"},
    {"SCNMaterial.clearCoatNormal.mappingChannel", "0"},
    {"SCNMaterial.clearCoatNormal.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterialProperty.intensity", "1"},
    {"SCNMaterialProperty.minificationFilter", "2"},
    {"SCNMaterialProperty.magnificationFilter", "2"},
    {"SCNMaterialProperty.mipFilter", "0"},
    {"SCNMaterialProperty.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterialProperty.wrapS", "1"},
    {"SCNMaterialProperty.wrapT", "1"},
    {"SCNMaterialProperty.mappingChannel", "0"},
    {"SCNNode.name", "nil"},
    {"SCNNode.position", "0 0 0"},
    {"SCNNode.rotation", "0 0 0 0"},
    {"SCNNode.orientation", "0 0 0 1"},
    {"SCNNode.scale", "1 1 1"},
    {"SCNNode.hidden", "0"},
    {"SCNNode.opacity", "1"},
    {"SCNNode.renderingOrder", "0"},
    {"SCNNode.castsShadow", "1"},
    {"SCNNode.categoryBitMask", "1"},
    {"SCNNode.movabilityHint", "0"},
    {"SCNPlane.widthSegmentCount", "1"},
    {"SCNPlane.heightSegmentCount", "1"},
    {"SCNPlane.cornerRadius", "0"},
    {"SCNPlane.cornerSegmentCount", "10"},
    {"SCNScene.background.contents", "nil"},
    {"SCNScene.background.intensity", "1"},
    {"SCNScene.background.minificationFilter", "2"},
    {"SCNScene.background.magnificationFilter", "2"},
    {"SCNScene.background.mipFilter", "1"},
    {"SCNScene.background.wrapS", "1"},
    {"SCNScene.background.wrapT", "1"},
    {"SCNScene.background.mappingChannel", "0"},
    {"SCNScene.background.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNScene.lightingEnvironment.contents", "nil"},
    {"SCNScene.lightingEnvironment.intensity", "1"},
    {"SCNScene.lightingEnvironment.minificationFilter", "2"},
    {"SCNScene.lightingEnvironment.magnificationFilter", "2"},
    {"SCNScene.lightingEnvironment.mipFilter", "1"},
    {"SCNScene.lightingEnvironment.wrapS", "1"},
    {"SCNScene.lightingEnvironment.wrapT", "1"},
    {"SCNScene.lightingEnvironment.mappingChannel", "0"},
    {"SCNScene.lightingEnvironment.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNPhysicsWorld.gravity", "0 -9.8 0"},
    {"SCNPhysicsWorld.speed", "1"},
    {"SCNPhysicsWorld.timeStep", "0.0166667"},
    {"SCNPhysicsField.strength", "1"},
    {"SCNPhysicsField.falloffExponent", "0"},
    {"SCNPhysicsField.minimumDistance", "1e-06"},
    {"SCNPhysicsField.active", "1"},
    {"SCNPhysicsField.exclusive", "0"},
    {"SCNPhysicsField.halfExtent", "3.40282e+38 3.40282e+38 3.40282e+38"},
    {"SCNPhysicsField.usesEllipsoidalExtent", "0"},
    {"SCNPhysicsField.scope", "0"},
    {"SCNPhysicsField.offset", "0 0 0"},
    {"SCNPhysicsField.direction", "0 -1 0"},
    {"SCNPhysicsField.categoryBitMask", "all bits"},
    {"SCNParticlePropertyController.inputMode", "0"},
    {"SCNParticlePropertyController.inputScale", "1"},
    {"SCNParticlePropertyController.inputBias", "0"},
    {"SCNParticlePropertyController.inputProperty", "nil"},
