// The answers of the host's SceneKit, written by host/scenekit-defaults/refresh.sh from scenekit-defaults-cases.m.
    {"SCNLight.type", "omni"},
    {"SCNLight.color", "colour 1 1 1 1"},
    {"SCNLight.temperature", "6500"},
    {"SCNLight.intensity", "1000"},
    {"SCNLight.name", "nil"},
    {"SCNLight.castsShadow", "0"},
    {"SCNLight.shadowColor", "colour 0 0 0 1"},
    {"SCNLight.shadowRadius", "3"},
    {"SCNLight.zNear", "1"},
    {"SCNLight.zFar", "100"},
    {"SCNLight.attenuationStartDistance", "0"},
    {"SCNLight.attenuationEndDistance", "0"},
    {"SCNLight.attenuationFalloffExponent", "2"},
    {"SCNLight.spotInnerAngle", "0"},
    {"SCNLight.spotOuterAngle", "45"},
    {"SCNLight.categoryBitMask", "all bits"},
    {"SCNCamera.name", "nil"},
    {"SCNCamera.fieldOfView", "60"},
    {"SCNCamera.zNear", "1"},
    {"SCNCamera.zFar", "100"},
    {"SCNCamera.usesOrthographicProjection", "0"},
    {"SCNCamera.orthographicScale", "1"},
    {"SCNCamera.automaticallyAdjustsZRange", "0"},
    {"SCNParticleSystem.emissionDuration", "1"},
    {"SCNParticleSystem.loops", "1"},
    {"SCNParticleSystem.birthRate", "0"},
    {"SCNParticleSystem.warmupDuration", "0"},
    {"SCNParticleSystem.spreadingAngle", "0"},
    {"SCNParticleSystem.emittingDirection", "0 1 0"},
    {"SCNParticleSystem.acceleration", "0 0 0"},
    {"SCNParticleSystem.particleAngleVariation", "0"},
    {"SCNParticleSystem.particleVelocity", "0"},
    {"SCNParticleSystem.particleVelocityVariation", "0"},
    {"SCNParticleSystem.particleAngularVelocity", "0"},
    {"SCNParticleSystem.particleLifeSpan", "1"},
    {"SCNParticleSystem.particleLifeSpanVariation", "0"},
    {"SCNParticleSystem.particleImage", "nil"},
    {"SCNParticleSystem.particleColor", "colour 1 1 1 1"},
    {"SCNParticleSystem.particleColorVariation", "0 0 0 0"},
    {"SCNParticleSystem.particleSize", "1"},
    {"SCNParticleSystem.particleSizeVariation", "0"},
    {"SCNParticleSystem.blendMode", "0"},
    {"SCNParticleSystem.orientationMode", "0"},
    {"SCNParticleSystem.sortingMode", "0"},
    {"SCNParticleSystem.lightingEnabled", "0"},
    {"SCNParticleSystem.affectedByGravity", "0"},
    {"SCNParticleSystem.affectedByPhysicsFields", "0"},
    {"SCNParticleSystem.speedFactor", "1"},
    {"SCNParticleSystem.stretchFactor", "0"},
    {"SCNParticleSystem.propertyControllers", "nil"},
    {"SCNParticleSystem.emitterShape", "nil"},
    {"SCNMaterial.name", "nil"},
    {"SCNMaterial.lightingModelName", "SCNLightingModelBlinn"},
    {"SCNMaterial.doubleSided", "0"},
    {"SCNMaterial.transparency", "1"},
    {"SCNMaterial.shininess", "1"},
    {"SCNMaterial.blendMode", "0"},
    {"SCNMaterial.diffuse.contents", "colour 1 1 1 1"},
    {"SCNMaterial.diffuse.intensity", "1"},
    {"SCNMaterial.ambient.contents", "colour 0.484529 0.484529 0.484529 1"},
    {"SCNMaterial.ambient.intensity", "1"},
    {"SCNMaterial.specular.contents", "colour 0 0 0 1"},
    {"SCNMaterial.specular.intensity", "1"},
    {"SCNMaterial.normal.contents", "colour 1 1 1 1"},
    {"SCNMaterial.normal.intensity", "1"},
    {"SCNMaterial.reflective.contents", "colour 0 0 0 1"},
    {"SCNMaterial.reflective.intensity", "1"},
    {"SCNMaterial.emission.contents", "colour 0 0 0 1"},
    {"SCNMaterial.emission.intensity", "1"},
    {"SCNMaterial.transparent.contents", "colour 1 1 1 1"},
    {"SCNMaterial.transparent.intensity", "1"},
    {"SCNMaterial.multiply.contents", "colour 1 1 1 1"},
    {"SCNMaterial.multiply.intensity", "1"},
    {"SCNMaterial.displacement.contents", "colour 0 0 0 1"},
    {"SCNMaterial.displacement.intensity", "1"},
    {"SCNMaterial.ambientOcclusion.contents", "colour 1 1 1 1"},
    {"SCNMaterial.ambientOcclusion.intensity", "1"},
    {"SCNMaterial.selfIllumination.contents", "colour 0 0 0 1"},
    {"SCNMaterial.selfIllumination.intensity", "1"},
    {"SCNMaterial.metalness.contents", "colour 0 0 0 1"},
    {"SCNMaterial.metalness.intensity", "1"},
    {"SCNMaterial.roughness.contents", "colour 0.484529 0.484529 0.484529 1"},
    {"SCNMaterial.roughness.intensity", "1"},
    {"SCNMaterialProperty.intensity", "1"},
    {"SCNMaterialProperty.minificationFilter", "2"},
    {"SCNMaterialProperty.magnificationFilter", "2"},
    {"SCNMaterialProperty.mipFilter", "0"},
    {"SCNMaterialProperty.contentsTransform", "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"},
    {"SCNMaterialProperty.wrapS", "1"},
    {"SCNMaterialProperty.wrapT", "1"},
    {"SCNMaterialProperty.mappingChannel", "0"},
    {"SCNNode.name", "nil"},
    {"SCNNode.position", "0 0 0"},
    {"SCNNode.rotation", "0 0 0 0"},
    {"SCNNode.orientation", "0 0 0 1"},
    {"SCNNode.scale", "1 1 1"},
    {"SCNNode.hidden", "0"},
    {"SCNNode.opacity", "1"},
    {"SCNNode.renderingOrder", "0"},
    {"SCNNode.castsShadow", "1"},
    {"SCNNode.categoryBitMask", "1"},
    {"SCNNode.movabilityHint", "0"},
    {"SCNPlane.widthSegmentCount", "1"},
    {"SCNPlane.heightSegmentCount", "1"},
    {"SCNPlane.cornerRadius", "0"},
    {"SCNPlane.cornerSegmentCount", "10"},
    {"SCNPhysicsWorld.gravity", "0 -9.8 0"},
    {"SCNPhysicsWorld.speed", "1"},
    {"SCNPhysicsWorld.timeStep", "0.0166667"},
    {"SCNPhysicsField.strength", "1"},
    {"SCNPhysicsField.falloffExponent", "0"},
    {"SCNPhysicsField.minimumDistance", "1e-06"},
    {"SCNPhysicsField.active", "1"},
    {"SCNPhysicsField.exclusive", "0"},
    {"SCNPhysicsField.halfExtent", "3.40282e+38 3.40282e+38 3.40282e+38"},
    {"SCNPhysicsField.usesEllipsoidalExtent", "0"},
    {"SCNPhysicsField.scope", "0"},
    {"SCNPhysicsField.offset", "0 0 0"},
    {"SCNPhysicsField.direction", "0 -1 0"},
    {"SCNPhysicsField.categoryBitMask", "all bits"},
    {"SCNParticlePropertyController.inputMode", "0"},
    {"SCNParticlePropertyController.inputScale", "1"},
    {"SCNParticlePropertyController.inputBias", "0"},
    {"SCNParticlePropertyController.inputProperty", "nil"},
