static const char *const suitedefaults_expectations[] = {
    "nil",
    "0",
    "0",
    "0",
    "nil",
    "nil",
    "string:abc",
    "0",
    "0",
    "nil",
    "42",
    "42",
    "0",
    "1",
    "string:3.75",
    "3",
    "3.75",
    "1",
    "number:-7",
    "string:-7",
    "number:1",
    "string:1",
    "0.5",
    "array:(\n    a,\n    b\n)",
    "array:(\n    a,\n    b\n)",
    "nil",
    "array:(\n    a,\n    1\n)",
    "dict:{\n    k = v;\n}",
    "nil",
    "data(3)",
    "nil",
    "string:/tmp/charon-suite",
    "string:/tmp/charon-suite",
    "data",
    "string:https://example.invalid/a?b=c",
    "1 path",
    "string:fallback",
    "9",
    "string:abc",
    "string:own",
    "string:fallback",
    "string:ignored",
    "nil",
    "array:(\n    a,\n    b\n)",
    "number:9",
    "nil",
    "1",
    "array:(\n    a,\n    b\n)",
    "-7",
    "number:9",
};
