static const char textkit7_expectations[] =
    "{\"attributes.kept\":\"6 0.25 0.5 _UIKitNewLetterpressStyle\",\"constant.NSAttachmentAttributeName\":\"NSAttachment\",\"constant.NSBackgroundColorDocumentAttribute\":\"Bac"
    "kgroundColor\",\"constant.NSBaselineOffsetAttributeName\":\"NSBaselineOffset\",\"constant.NSCharacterEncodingDocumentAttribute\":\"CharacterEncoding\",\"constant.NSCharac"
    "terEncodingDocumentOption\":\"CharacterEncoding\",\"constant.NSDefaultAttributesDocumentAttribute\":\"DefaultAttributes\",\"constant.NSDefaultAttributesDocumentOption\":"
    "\"DefaultAttributes\",\"constant.NSDefaultTabIntervalDocumentAttribute\":\"DefaultTabInterval\",\"constant.NSDocumentTypeDocumentAttribute\":\"DocumentType\",\"constant.NS"
    "DocumentTypeDocumentOption\":\"DocumentType\",\"constant.NSExpansionAttributeName\":\"NSExpansion\",\"constant.NSHTMLTextDocumentType\":\"NSHTML\",\"constant.NSHyphenationF"
    "actorDocumentAttribute\":\"HyphenationFactor\",\"constant.NSLinkAttributeName\":\"NSLink\",\"constant.NSObliquenessAttributeName\":\"NSObliqueness\",\"constant.NSPaperMargi"
    "nDocumentAttribute\":\"PaperMargin\",\"constant.NSPaperSizeDocumentAttribute\":\"PaperSize\",\"constant.NSPlainTextDocumentType\":\"NSPlainText\",\"constant.NSReadOnlyDocum"
    "entAttribute\":\"ReadOnly\",\"constant.NSRTFDTextDocumentType\":\"NSRTFD\",\"constant.NSRTFTextDocumentType\":\"NSRTF\",\"constant.NSStrikethroughColorAttributeName\":\"NSStr"
    "ikethroughColor\",\"constant.NSTabColumnTerminatorsAttributeName\":\"NSTabColumnTerminatorsAttributeName\",\"constant.NSTextEffectAttributeName\":\"NSTextEffect\",\"const"
    "ant.NSTextEffectLetterpressStyle\":\"_UIKitNewLetterpressStyle\",\"constant.NSTextLayoutSectionOrientation\":\"NSTextLayoutSectionOrientation\",\"constant.NSTextLayoutS"
    "ectionRange\":\"NSTextLayoutSectionRange\",\"constant.NSTextLayoutSectionsAttribute\":\"NSTextLayoutSectionsAttribute\",\"constant.NSUnderlineColorAttributeName\":\"NSUnd"
    "erlineColor\",\"constant.NSViewModeDocumentAttribute\":\"ViewMode\",\"constant.NSViewSizeDocumentAttribute\":\"ViewSize\",\"constant.NSViewZoomDocumentAttribute\":\"ViewZoo"
    "m\",\"constant.NSWritingDirectionAttributeName\":\"NSWritingDirection\",\"html.bold\":\"bold {Font=12 Times-Bold; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0"
    " before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\n plain  {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mu"
    "lt=0.00 tabs=[] interval=36 lists=0}\\nitalic {Font=12 Times-Italic; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] int"
    "erval=36 lists=0}\",\"html.break\":\"line\\\\nbreak {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] int"
    "erval=36 lists=0}\",\"html.documentAttributes\":\"type=NSHTML error=0\",\"html.entities\":\"a & b < c A {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail"
    "=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.font\":\"big {Font=18 Times-Roman; Color=0.00,0.00,1.00,1.00; ParagraphStyle=align=4 fi"
    "rst=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.heading\":\"Title\\\\n {Font=24 Times-Bold; ParagraphStyle=align=4 first"
    "=0 head=0 tail=0 spacing=16 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\ntext {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spac"
    "ing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.link\":\"go  {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 befo"
    "re=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\nthere {Font=12 Times-Roman; Color=0.00,0.00,0.93,1.00; Link=http://example.com/x\?y=1; Underline=1; Paragraph"
    "Style=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\n now {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 "
    "head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.list\":\"\\t\\u2022\\t {Font=12 Times-Roman; ParagraphStyle=align=0 first=0 hea"
    "d=36 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[11 36] interval=36 lists=1}\\na\\\\n {Font=12 Times-Roman; ParagraphStyle=align=0 first=0 head=36 tail=0 spac"
    "ing=0 before=0 line=0 mult=0.00 tabs=[11 36] interval=36 lists=1}\\n\\t\\u2022\\t {Font=12 Times-Roman; ParagraphStyle=align=0 first=0 head=36 tail=0 spacing=0 befo"
    "re=0 line=0 mult=0.00 tabs=[11 36] interval=36 lists=1}\\nb\\\\n {Font=12 Times-Roman; ParagraphStyle=align=0 first=0 head=36 tail=0 spacing=0 before=0 line=0 mult"
    "=0.00 tabs=[11 36] interval=36 lists=1}\",\"html.paragraphs\":\"one\\\\ntwo\\\\n {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=12 before=0 "
    "line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.span\":\"red {Font=20 Times-Roman; Color=1.00,0.00,0.00,1.00; ParagraphStyle=align=4 first=0 head=0 tail=0 sp"
    "acing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.sub\":\"H {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 befor"
    "e=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\n2 {Font=10 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs"
    "=[] interval=36 lists=0}\\nO x {Font=12 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0"
    "}\\n2 {Font=10 Times-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"html.underline\":\"unde"
    "r {Font=12 Times-Roman; Underline=1; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\n  {Font=12 T"
    "imes-Roman; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\\nstruck {Font=12 Times-Roman; Striketh"
    "rough=1; ParagraphStyle=align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[] interval=36 lists=0}\",\"plain.import\":\"plain text\\\\nline two {}"
    "\",\"rtf.import\":\"Hello bold it  {}\\nu {Underline=1}\\n end\\\\n {}\",\"style.cleared\":\"align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[28 56 8"
    "4 112 140 168 196 224 252 280 308 336] interval=33 lists=0\",\"style.copy\":\"align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[50 20] interva"
    "l=33 lists=0 equal=1\",\"style.default\":\"align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[28 56 84 112 140 168 196 224 252 280 308 336] int"
    "erval=0 lists=0\",\"style.tabs\":\"align=4 first=0 head=0 tail=0 spacing=0 before=0 line=0 mult=0.00 tabs=[50 20] interval=33 lists=0\",\"tab.align.0\":\"alignment=0 lo"
    "cation=72.5 options=[]\",\"tab.align.1\":\"alignment=1 location=72.5 options=[]\",\"tab.align.2\":\"alignment=2 location=72.5 options=[]\",\"tab.align.3\":\"alignment=3 loc"
    "ation=72.5 options=[]\",\"tab.align.4\":\"alignment=4 location=72.5 options=[]\",\"tab.class\":\"NSTextTab named=1\",\"tab.equal\":\"same=1 hash=1 other=0 further=0 copy=1 "
    "self=1 nil=0\",\"tab.equal.options\":\"nil-empty=1 empty-empty=1\",\"tab.kind\":\"1 1\",\"tab.made\":\"1\",\"tab.options\":\"NSTabColumnTerminatorsAttributeName=U+002C U+002E \""
    ",\"tab.terminators.ar_SA\":\"U+066B \",\"tab.terminators.de_CH\":\"U+002E \",\"tab.terminators.de_DE\":\"U+002C \",\"tab.terminators.en_US\":\"U+002E \",\"tab.terminators.fr_FR\""
    ":\"U+002C \",\"tab.terminators.ja_JP\":\"U+002E \",\"tab.terminators.nil\":\"U+002E \",\"tab.terminators.ru_RU\":\"U+002C \"}"
;
