static const char UIKitConstants_expectations[] =
    "{\"NSTextListMarkerBox\":\"{box}\",\"NSTextListMarkerBox.class\":\"__NSCFConstantString\",\"NSTextListMarkerCheck\":\"{check}\",\"NSTextListMarkerCircle\":\"{circle}\",\"NSTextL"
    "istMarkerDecimal\":\"{decimal}\",\"NSTextListMarkerDiamond\":\"{diamond}\",\"NSTextListMarkerDisc\":\"{disc}\",\"NSTextListMarkerHyphen\":\"{hyphen}\",\"NSTextListMarkerLowerca"
    "seAlpha\":\"{lower-alpha}\",\"NSTextListMarkerLowercaseHexadecimal\":\"{lower-hexadecimal}\",\"NSTextListMarkerLowercaseLatin\":\"{lower-latin}\",\"NSTextListMarkerLowercas"
    "eRoman\":\"{lower-roman}\",\"NSTextListMarkerOctal\":\"{octal}\",\"NSTextListMarkerSquare\":\"{square}\",\"NSTextListMarkerUppercaseAlpha\":\"{upper-alpha}\",\"NSTextListMarker"
    "UppercaseHexadecimal\":\"{upper-hexadecimal}\",\"NSTextListMarkerUppercaseLatin\":\"{upper-latin}\",\"NSTextListMarkerUppercaseRoman\":\"{upper-roman}\",\"NSTextStorageDidP"
    "rocessEditingNotification\":\"NSTextStorageDidProcessEditingNotification\",\"NSTextStorageWillProcessEditingNotification\":\"NSTextStorageWillProcessEditingNotificati"
    "on\",\"NSUserActivityDocumentURLKey\":\"NSUserActivityDocumentURL\",\"predicate.currentItemAfterSet\":\"same\",\"predicate.currentItemAtStart\":\"nil\",\"predicate.directionA"
    "fterSet\":\"previous\",\"predicate.directionAtStart\":\"previous\",\"result.targetElementAfterClear\":\"nil\",\"result.targetElementIsSame\":\"same\",\"result.targetRange\":\"nil"
    "\",\"rotor.attributedNameAfterNameSet\":\"Headings\",\"rotor.attributedNameString\":\"Misspelled\",\"rotor.itemSearchBlock.isSet\":\"yes\",\"rotor.name\":\"Links\",\"rotor.nameAf"
    "terAttributedSet\":\"Misspelled\",\"rotor.nameAfterSet\":\"Headings\",\"rotor.plainName\":\"(nil)\",\"rotor.plainSystemRotorType\":\"none\",\"rotor.searchBlockCalls\":\"1\",\"rotor"
    ".searchBlockSawThePredicate\":\"same\",\"rotor.systemRotorType\":\"none\",\"rotor.systemRotorTypeAfterInit\":\"link\",\"rotors.afterClear\":\"nil\",\"rotors.count\":\"2\",\"rotors."
    "firstIsRotor\":\"same\",\"rotors.unset\":\"nil\",\"UIAccessibilityAssistiveTouchStatusDidChangeNotification\":\"UIAccessibilityAssistiveTouchStatusDidChangeNotification\","
    "\"UIAccessibilityHearingDevicePairedEarDidChangeNotification\":\"UIAccessibilityHearingDevicePairedEarDidChangeNotification\",\"UIActivityTypeAirDrop\":\"com.apple.UIK"
    "it.activity.AirDrop\",\"UIActivityTypeAirDrop.isKindOfString\":\"yes\",\"UIApplicationKeyboardExtensionPointIdentifier\":\"com.apple.keyboard-service\",\"UIApplicationLau"
    "nchOptionsBluetoothCentralsKey\":\"UIApplicationLaunchOptionsBluetoothCentralsKey\",\"UIApplicationLaunchOptionsBluetoothPeripheralsKey\":\"UIApplicationLaunchOptions"
    "BluetoothPeripheralsKey\",\"UIApplicationLaunchOptionsCloudKitShareMetadataKey\":\"UIApplicationLaunchOptionsCloudKitShareMetadataKey\",\"UIApplicationLaunchOptionsUs"
    "erActivityDictionaryKey\":\"UIApplicationLaunchOptionsUserActivityDictionaryKey\",\"UIApplicationLaunchOptionsUserActivityTypeKey\":\"UIApplicationLaunchOptionsUserAc"
    "tivityTypeKey\",\"UIApplicationStateRestorationSystemVersionKey\":\"UIApplicationStateRestorationSystemVersion\",\"UIApplicationStateRestorationTimestampKey\":\"UIAppli"
    "cationStateRestorationTimestamp\",\"UIContentSizeCategoryDidChangeNotification\":\"UIContentSizeCategoryDidChangeNotification\",\"UIContentSizeCategoryDidChangeNotifi"
    "cation.class\":\"__NSCFConstantString\",\"UIContentSizeCategoryNewValueKey\":\"UIContentSizeCategoryNewValueKey\",\"UIDocumentBrowserErrorDomain\":\"com.apple.DocumentMan"
    "ager\",\"UIFocusDidUpdateNotification\":\"UIFocusDidUpdateNotification\",\"UIFocusMovementDidFailNotification\":\"UIFocusMovementDidFailNotification\",\"UIFocusUpdateAnim"
    "ationCoordinatorKey\":\"UIFocusUpdateAnimationCoordinatorKey\",\"UIFocusUpdateContextKey\":\"UIFocusUpdateContextKey\",\"UIImagePickerControllerLivePhoto\":\"UIImagePicke"
    "rControllerLivePhoto\",\"UIPasteboardTypeAutomatic\":\"com.apple.uikit.type-automatic\",\"UISplitViewControllerAutomaticDimension\":\"{-3.4028234663852886e+38, 0}\",\"UIT"
    "extFieldDidEndEditingReasonKey\":\"UITextFieldEndEditingReasonKey\",\"UIUserNotificationActionResponseTypedTextKey\":\"UIUserNotificationActionResponseTypedTextKey\",\""
    "UIUserNotificationTextInputActionButtonTitleKey\":\"UIUserNotificationTextInputActionButtonTitleKey\",\"UIViewControllerShowDetailTargetDidChangeNotification\":\"UIVi"
    "ewControllerShowDetailTargetDidChangeNotification\"}"
;
