static const char webkit_expectations[] =
    "{\"async.afterCall\":\"url=https://charon.invalid/base title= loading=1 back=0 forward=0\",\"async.allow\":\"decide type=-1 main=1 url=https://charon.invalid/base -> 1"
    " | start url=https://charon.invalid/base title= loading=1 back=0 forward=0 | commit url=https://charon.invalid/base title= loading=1 back=0 forward=0 | finish u"
    "rl=https://charon.invalid/base title= loading=0 back=0 forward=0 progress=1.0\",\"async.cancel\":\"decide type=-1 main=1 url=https://charon.invalid/second -> 0\",\"as"
    "ync.cancelState\":\"url=https://charon.invalid/base title=T8 loading=0 back=0 forward=0\",\"async.state\":\"url=https://charon.invalid/base title=T8 loading=0 back=0 "
    "forward=0\",\"bad.events\":\"decide type=-1 main=1 url=charon-none://x/y -> 1 | start url=charon-none://x/y title= loading=1 back=0 forward=0 | failProvisional NSUR"
    "LErrorDomain/-1002\",\"bad.state\":\"url=nil title= loading=0 back=0 forward=0\",\"cancel.click\":\"decide type=0 main=1 url=charon-cancel://x -> 0\",\"cancel.events\":\"de"
    "cide type=-1 main=1 url=charon-cancel://x -> 0\",\"cancel.state\":\"url=https://charon.invalid/base title=T1 loading=0 back=0 forward=0\",\"config.controller\":\"presen"
    "t\",\"config.identity\":\"copy\",\"config.media\":\"airplay=1\",\"config.preferences\":\"js=1 windows=0 minfont=0\",\"config.sameController\":\"same\",\"config.samePreferences\":\""
    "same\",\"data.events\":\"decide type=-1 main=1 url=data:text/html,%3Ctitle%3ED%3C/title%3Ehi -> 1 | start url=data:text/html,%3Ctitle%3ED%3C/title%3Ehi title= loadi"
    "ng=1 back=0 forward=0 | commit url=data:text/html,%3Ctitle%3ED%3C/title%3Ehi title= loading=1 back=0 forward=0 | finish url=data:text/html,%3Ctitle%3ED%3C/title"
    "%3Ehi title= loading=0 back=0 forward=0 progress=1.0\",\"data.state\":\"url=data:text/html,%3Ctitle%3ED%3C/title%3Ehi title=D loading=0 back=0 forward=0\",\"early.js\""
    ":\"2\",\"early.title\":\"\\\"\\\"\",\"handler.afterRemove\":\"error WKErrorDomain/4\",\"handler.duplicate\":\"NSInvalidArgumentException\",\"handler.messages\":\"dup main=1 body=\\\"o"
    "ne\\\"\",\"history.back\":\"decide type=2 main=1 url=file://$/a.html -> 1 | start url=file://$/a.html title=B loading=1 back=0 forward=1 | commit url=file://$/a.html "
    "title= loading=1 back=0 forward=1 | finish url=file://$/a.html title=A loading=0 back=0 forward=1 progress=1.0\",\"history.backList\":\"back=0 forward=1 current=fil"
    "e://$/a.html\",\"history.click\":\"decide type=0 main=1 url=file://$/b.html -> 1 | start url=file://$/b.html title=A loading=1 back=0 forward=1 | commit url=file://"
    "$/b.html title= loading=1 back=1 forward=0 | finish url=file://$/b.html title= loading=0 back=1 forward=0 progress=1.0\",\"history.first\":\"decide type=-1 main=1 u"
    "rl=file://$/a.html -> 1 | start url=file://$/a.html title= loading=1 back=0 forward=0 | commit url=file://$/a.html title= loading=1 back=0 forward=0 | finish ur"
    "l=file://$/a.html title= loading=0 back=0 forward=0 progress=1.0\",\"history.forward\":\"decide type=2 main=1 url=file://$/b.html -> 1 | start url=file://$/b.html t"
    "itle=A loading=1 back=1 forward=0 | commit url=file://$/b.html title= loading=1 back=1 forward=0 | finish url=file://$/b.html title=B loading=0 back=1 forward=0"
    " progress=1.0\",\"history.fragment\":\"decide type=-1 main=1 url=file://$/b.html#z -> 1 || url=file://$/b.html#z title=B loading=0 back=1 forward=0\",\"history.list\":"
    "\"back=1 forward=0 current=file://$/b.html backItem=file://$/a.html\",\"history.reload\":\"decide type=3 main=1 url=file://$/b.html -> 1 | start url=file://$/b.html "
    "title=B loading=1 back=1 forward=0 | commit url=file://$/b.html title= loading=1 back=1 forward=0 | finish url=file://$/b.html title= loading=0 back=1 forward=0"
    " progress=1.0\",\"history.second\":\"decide type=-1 main=1 url=file://$/b.html -> 1 | start url=file://$/b.html title=A loading=1 back=0 forward=0 | commit url=file"
    "://$/b.html title= loading=1 back=1 forward=0 | finish url=file://$/b.html title= loading=0 back=1 forward=0 progress=1.0\",\"history.stop\":\"none\",\"html.afterCall"
    "\":\"url=https://charon.invalid/base title= loading=1 back=0 forward=0\",\"html.events\":\"decide type=-1 main=1 url=https://charon.invalid/base -> 1 | start url=http"
    "s://charon.invalid/base title= loading=1 back=0 forward=0 | commit url=https://charon.invalid/base title= loading=1 back=0 forward=0 | finish url=https://charon"
    ".invalid/base title= loading=0 back=0 forward=0 progress=1.0\",\"html.navigation\":\"object\",\"html.navigationEqual\":\"WKNavigation\",\"html.state\":\"url=https://charon."
    "invalid/base title=T1 loading=0 back=0 forward=0\",\"iframe.events\":\"decide type=-1 main=1 url=file://$/f.html -> 1 | start url=file://$/f.html title= loading=1 b"
    "ack=0 forward=0 | commit url=file://$/f.html title= loading=1 back=0 forward=0 | decide type=-1 main=0 url=file://$/c.html -> 1 | finish url=file://$/f.html tit"
    "le=F loading=0 back=0 forward=0 progress=1.0\",\"js -0\":\"-0\",\"js ''\":\"\\\"\\\"\",\"js '\\\\u00e9\\\\ud83d\\\\ude00'\":\"\\\"\\u00e9\\ud83d\\ude00\\\"\",\"js 'a'\":\"\\\"a\\\"\",\"js 'a\\\\u2028b'"
    "\":\"\\\"a\\u2028b\\\"\",\"js ({})\":\"{}\",\"js ({a:{b:{c:[1,2,3]}}})\":\"{a:{b:{c:[1,2,3]}}}\",\"js ({a:1,b:[2]})\":\"{a:1,b:[2]}\",\"js ({f: function(){}})\":\"{}\",\"js ({u: undefin"
    "ed})\":\"{}\",\"js (function(){ return arguments; })(1, 2)\":\"error WKErrorDomain/5\",\"js (function(){return function(){}})()\":\"error WKErrorDomain/5\",\"js []\":\"[]\",\"j"
    "s [1,'x',{a:2}]\":\"[1,\\\"x\\\",{a:2}]\",\"js [function(){}]\":\"error WKErrorDomain/5\",\"js [new Date(0)]\":\"[date 0]\",\"js [undefined, null]\":\"[null,null]\",\"js 0\":\"0\",\"js"
    " 1.5\":\"1.5\",\"js 1/0\":\"inf\",\"js 1+2\":\"3\",\"js 12345678901234567890\":\"1.23457e+19\",\"js document.body.innerHTML\":\"\\\"hello\\\"\",\"js document.title\":\"\\\"T1\\\"\",\"js false\""
    ":\"false\",\"js NaN\":\"nan\",\"js new Date(86400000)\":\"date 86400\",\"js new Object(5)\":\"{}\",\"js null\":\"null\",\"js this === window\":\"true\",\"js throw new Error('boom')\":\""
    "error WKErrorDomain/4\",\"js true\":\"true\",\"js undefined\":\"nil\",\"js var c = {}; c.c = c; c\":\"{c:{c:{c:{c:{c:{c:{c:deep}}}}}}}\",\"js var q = 5\":\"nil\",\"js.noHandler\":"
    "\"ok\",\"kvo.changes\":\"URL=<NSURL> | loading=true | loading=false | title=\\\"T2\\\" | title=\\\"T3\\\"\",\"loaddata.events\":\"decide type=-1 main=1 url=https://charon.invali"
    "d/base -> 1 | start url=https://charon.invalid/base title= loading=1 back=0 forward=0 | commit url=https://charon.invalid/base title= loading=1 back=0 forward=0"
    " | finish url=https://charon.invalid/base title= loading=0 back=0 forward=0 progress=1.0\",\"loaddata.title\":\"\\\"T6\\\"\",\"message.count\":\"7\",\"message.received\":\"h ma"
    "in=1 body=\\\"text\\\" | h main=1 body=42 | h main=1 body={a:1,b:[2,3],c:null} | h main=1 body=[1,\\\"x\\\"] | h main=1 body=true | h main=1 body=null | h main=1 body=1"
    ".5\",\"message.unknown\":\"\\\"threw\\\"\",\"new.backList\":\"0 0\",\"new.currentItem\":\"nil\",\"new.gestures\":\"0\",\"new.navigationDelegate\":\"set\",\"new.progress\":\"0.0\",\"new.scrol"
    "lView\":\"WKScrollView\",\"new.secure\":\"0\",\"new.state\":\"url=nil title= loading=0 back=0 forward=0\",\"new.UIDelegate\":\"nil\",\"new.userAgent\":\"set\",\"nilbase.events\":\"de"
    "cide type=-1 main=1 url=about:blank -> 1 | start url=about:blank title= loading=1 back=0 forward=0 | commit url=about:blank title= loading=1 back=0 forward=0 | "
    "finish url=about:blank title= loading=0 back=0 forward=0 progress=1.0\",\"nilbase.state\":\"url=about:blank title=T5 loading=0 back=0 forward=0\",\"script.hasHandlers"
    "\":\"\\\"function\\\"\",\"script.ran\":\"\\\"ran\\\"\",\"scripts.count\":\"1\",\"scripts.removed\":\"0\"}"
;
