// PDFKit's string constants of iOS 11.0, and the one numeric sentinel beside them.
//
// The values are the HOST's own, read out of its PDFKit at generation time with dladdr proving
// which image each symbol came from: the host framework has no file on disk - it lives in the dyld
// shared cache - so the image pointer is the only proof, and tests/backports/host/pdfkit-constants
// reads them the same way.  Each symbol was read in a fork()ed child, so one that cannot be read
// costs its own row and nothing else: kPDFDestinationUnspecifiedValue is a CGFloat sentinel rather
// than a string, and that is the one row the host does not answer.

#import <PDFKit/PDFKit.h>

PDFKIT_EXTERN NSString *const PDFAnnotationHighlightingModeInvert;
NSString *const PDFAnnotationHighlightingModeInvert = @"/I";
PDFKIT_EXTERN NSString *const PDFAnnotationHighlightingModeNone;
NSString *const PDFAnnotationHighlightingModeNone = @"/N";
PDFKIT_EXTERN NSString *const PDFAnnotationHighlightingModeOutline;
NSString *const PDFAnnotationHighlightingModeOutline = @"/O";
PDFKIT_EXTERN NSString *const PDFAnnotationHighlightingModePush;
NSString *const PDFAnnotationHighlightingModePush = @"/P";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyAction;
NSString *const PDFAnnotationKeyAction = @"/A";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyAdditionalActions;
NSString *const PDFAnnotationKeyAdditionalActions = @"/AA";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyAppearanceDictionary;
NSString *const PDFAnnotationKeyAppearanceDictionary = @"/AP";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyAppearanceState;
NSString *const PDFAnnotationKeyAppearanceState = @"/AS";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyBorder;
NSString *const PDFAnnotationKeyBorder = @"/Border";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyBorderStyle;
NSString *const PDFAnnotationKeyBorderStyle = @"/BS";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyColor;
NSString *const PDFAnnotationKeyColor = @"/C";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyContents;
NSString *const PDFAnnotationKeyContents = @"/Contents";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyDate;
NSString *const PDFAnnotationKeyDate = @"/M";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyDefaultAppearance;
NSString *const PDFAnnotationKeyDefaultAppearance = @"/DA";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyDestination;
NSString *const PDFAnnotationKeyDestination = @"/Dest";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyFlags;
NSString *const PDFAnnotationKeyFlags = @"/F";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyHighlightingMode;
NSString *const PDFAnnotationKeyHighlightingMode = @"/H";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyIconName;
NSString *const PDFAnnotationKeyIconName = @"/Name";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyInklist;
NSString *const PDFAnnotationKeyInklist = @"/InkList";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyInteriorColor;
NSString *const PDFAnnotationKeyInteriorColor = @"/IC";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyLineEndingStyles;
NSString *const PDFAnnotationKeyLineEndingStyles = @"/LE";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyLinePoints;
NSString *const PDFAnnotationKeyLinePoints = @"/L";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyName;
NSString *const PDFAnnotationKeyName = @"/NM";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyOpen;
NSString *const PDFAnnotationKeyOpen = @"/Open";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyPage;
NSString *const PDFAnnotationKeyPage = @"/P";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyParent;
NSString *const PDFAnnotationKeyParent = @"/Parent";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyPopup;
NSString *const PDFAnnotationKeyPopup = @"/Popup";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyQuadPoints;
NSString *const PDFAnnotationKeyQuadPoints = @"/QuadPoints";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyQuadding;
NSString *const PDFAnnotationKeyQuadding = @"/Q";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyRect;
NSString *const PDFAnnotationKeyRect = @"/Rect";
PDFKIT_EXTERN NSString *const PDFAnnotationKeySubtype;
NSString *const PDFAnnotationKeySubtype = @"/Subtype";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyTextLabel;
NSString *const PDFAnnotationKeyTextLabel = @"/T";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetAppearanceDictionary;
NSString *const PDFAnnotationKeyWidgetAppearanceDictionary = @"/MK";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetBackgroundColor;
NSString *const PDFAnnotationKeyWidgetBackgroundColor = @"/BG";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetBorderColor;
NSString *const PDFAnnotationKeyWidgetBorderColor = @"/BC";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetCaption;
NSString *const PDFAnnotationKeyWidgetCaption = @"/CA";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetDefaultValue;
NSString *const PDFAnnotationKeyWidgetDefaultValue = @"/DV";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetDownCaption;
NSString *const PDFAnnotationKeyWidgetDownCaption = @"/AC";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetFieldFlags;
NSString *const PDFAnnotationKeyWidgetFieldFlags = @"/Ff";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetFieldType;
NSString *const PDFAnnotationKeyWidgetFieldType = @"/FT";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetMaxLen;
NSString *const PDFAnnotationKeyWidgetMaxLen = @"/MaxLen";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetOptions;
NSString *const PDFAnnotationKeyWidgetOptions = @"/Opt";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetRolloverCaption;
NSString *const PDFAnnotationKeyWidgetRolloverCaption = @"/RC";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetRotation;
NSString *const PDFAnnotationKeyWidgetRotation = @"/R";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetTextLabelUI;
NSString *const PDFAnnotationKeyWidgetTextLabelUI = @"/TU";
PDFKIT_EXTERN NSString *const PDFAnnotationKeyWidgetValue;
NSString *const PDFAnnotationKeyWidgetValue = @"/V";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleCircle;
NSString *const PDFAnnotationLineEndingStyleCircle = @"/Circle";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleClosedArrow;
NSString *const PDFAnnotationLineEndingStyleClosedArrow = @"/ClosedArrow";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleDiamond;
NSString *const PDFAnnotationLineEndingStyleDiamond = @"/Diamond";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleNone;
NSString *const PDFAnnotationLineEndingStyleNone = @"/None";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleOpenArrow;
NSString *const PDFAnnotationLineEndingStyleOpenArrow = @"/OpenArrow";
PDFKIT_EXTERN NSString *const PDFAnnotationLineEndingStyleSquare;
NSString *const PDFAnnotationLineEndingStyleSquare = @"/Square";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeCircle;
NSString *const PDFAnnotationSubtypeCircle = @"/Circle";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeFreeText;
NSString *const PDFAnnotationSubtypeFreeText = @"/FreeText";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeHighlight;
NSString *const PDFAnnotationSubtypeHighlight = @"/Highlight";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeInk;
NSString *const PDFAnnotationSubtypeInk = @"/Ink";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeLine;
NSString *const PDFAnnotationSubtypeLine = @"/Line";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeLink;
NSString *const PDFAnnotationSubtypeLink = @"/Link";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypePopup;
NSString *const PDFAnnotationSubtypePopup = @"/Popup";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeSquare;
NSString *const PDFAnnotationSubtypeSquare = @"/Square";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeStamp;
NSString *const PDFAnnotationSubtypeStamp = @"/Stamp";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeStrikeOut;
NSString *const PDFAnnotationSubtypeStrikeOut = @"/StrikeOut";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeText;
NSString *const PDFAnnotationSubtypeText = @"/Text";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeUnderline;
NSString *const PDFAnnotationSubtypeUnderline = @"/Underline";
PDFKIT_EXTERN NSString *const PDFAnnotationSubtypeWidget;
NSString *const PDFAnnotationSubtypeWidget = @"/Widget";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeComment;
NSString *const PDFAnnotationTextIconTypeComment = @"/Comment";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeHelp;
NSString *const PDFAnnotationTextIconTypeHelp = @"/Help";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeInsert;
NSString *const PDFAnnotationTextIconTypeInsert = @"/Insert";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeKey;
NSString *const PDFAnnotationTextIconTypeKey = @"/Key";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeNewParagraph;
NSString *const PDFAnnotationTextIconTypeNewParagraph = @"/NewParagraph";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeNote;
NSString *const PDFAnnotationTextIconTypeNote = @"/Note";
PDFKIT_EXTERN NSString *const PDFAnnotationTextIconTypeParagraph;
NSString *const PDFAnnotationTextIconTypeParagraph = @"/Paragraph";
PDFKIT_EXTERN NSString *const PDFAnnotationWidgetSubtypeButton;
NSString *const PDFAnnotationWidgetSubtypeButton = @"/Btn";
PDFKIT_EXTERN NSString *const PDFAnnotationWidgetSubtypeChoice;
NSString *const PDFAnnotationWidgetSubtypeChoice = @"/Ch";
PDFKIT_EXTERN NSString *const PDFAnnotationWidgetSubtypeSignature;
NSString *const PDFAnnotationWidgetSubtypeSignature = @"/Sig";
PDFKIT_EXTERN NSString *const PDFAnnotationWidgetSubtypeText;
NSString *const PDFAnnotationWidgetSubtypeText = @"/Tx";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyBackgroundColor;
NSString *const PDFAppearanceCharacteristicsKeyBackgroundColor = @"BG";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyBorderColor;
NSString *const PDFAppearanceCharacteristicsKeyBorderColor = @"BC";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyCaption;
NSString *const PDFAppearanceCharacteristicsKeyCaption = @"CA";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyDownCaption;
NSString *const PDFAppearanceCharacteristicsKeyDownCaption = @"AC";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyRolloverCaption;
NSString *const PDFAppearanceCharacteristicsKeyRolloverCaption = @"RC";
PDFKIT_EXTERN NSString *const PDFAppearanceCharacteristicsKeyRotation;
NSString *const PDFAppearanceCharacteristicsKeyRotation = @"R";
PDFKIT_EXTERN NSString *const PDFBorderKeyDashPattern;
NSString *const PDFBorderKeyDashPattern = @"D";
PDFKIT_EXTERN NSString *const PDFBorderKeyLineWidth;
NSString *const PDFBorderKeyLineWidth = @"W";
PDFKIT_EXTERN NSString *const PDFBorderKeyStyle;
NSString *const PDFBorderKeyStyle = @"S";
PDFKIT_EXTERN NSString *const PDFDocumentAuthorAttribute;
NSString *const PDFDocumentAuthorAttribute = @"Author";
PDFKIT_EXTERN NSString *const PDFDocumentCreationDateAttribute;
NSString *const PDFDocumentCreationDateAttribute = @"CreationDate";
PDFKIT_EXTERN NSString *const PDFDocumentCreatorAttribute;
NSString *const PDFDocumentCreatorAttribute = @"Creator";
PDFKIT_EXTERN NSString *const PDFDocumentDidBeginFindNotification;
NSString *const PDFDocumentDidBeginFindNotification = @"PDFDidBeginDocumentFind";
PDFKIT_EXTERN NSString *const PDFDocumentDidBeginPageFindNotification;
NSString *const PDFDocumentDidBeginPageFindNotification = @"PDFDidBeginPageFind";
PDFKIT_EXTERN NSString *const PDFDocumentDidBeginPageWriteNotification;
NSString *const PDFDocumentDidBeginPageWriteNotification = @"PDFDidBeginPageWrite";
PDFKIT_EXTERN NSString *const PDFDocumentDidBeginWriteNotification;
NSString *const PDFDocumentDidBeginWriteNotification = @"PDFDidBeginDocumentWrite";
PDFKIT_EXTERN NSString *const PDFDocumentDidEndFindNotification;
NSString *const PDFDocumentDidEndFindNotification = @"PDFDidEndDocumentFind";
PDFKIT_EXTERN NSString *const PDFDocumentDidEndPageFindNotification;
NSString *const PDFDocumentDidEndPageFindNotification = @"PDFDidEndPageFind";
PDFKIT_EXTERN NSString *const PDFDocumentDidEndPageWriteNotification;
NSString *const PDFDocumentDidEndPageWriteNotification = @"PDFDidEndPageWrite";
PDFKIT_EXTERN NSString *const PDFDocumentDidEndWriteNotification;
NSString *const PDFDocumentDidEndWriteNotification = @"PDFDidEndDocumentWrite";
PDFKIT_EXTERN NSString *const PDFDocumentDidFindMatchNotification;
NSString *const PDFDocumentDidFindMatchNotification = @"PDFDidFindMatch";
PDFKIT_EXTERN NSString *const PDFDocumentDidUnlockNotification;
NSString *const PDFDocumentDidUnlockNotification = @"PDFDocumentDidUnlock";
PDFKIT_EXTERN NSString *const PDFDocumentKeywordsAttribute;
NSString *const PDFDocumentKeywordsAttribute = @"Keywords";
PDFKIT_EXTERN NSString *const PDFDocumentModificationDateAttribute;
NSString *const PDFDocumentModificationDateAttribute = @"ModDate";
PDFKIT_EXTERN NSString *const PDFDocumentOwnerPasswordOption;
NSString *const PDFDocumentOwnerPasswordOption = @"PDFDocumentOwnerPasswordOption";
PDFKIT_EXTERN NSString *const PDFDocumentProducerAttribute;
NSString *const PDFDocumentProducerAttribute = @"Producer";
PDFKIT_EXTERN NSString *const PDFDocumentSubjectAttribute;
NSString *const PDFDocumentSubjectAttribute = @"Subject";
PDFKIT_EXTERN NSString *const PDFDocumentTitleAttribute;
NSString *const PDFDocumentTitleAttribute = @"Title";
PDFKIT_EXTERN NSString *const PDFDocumentUserPasswordOption;
NSString *const PDFDocumentUserPasswordOption = @"PDFDocumentUserPasswordOption";
PDFKIT_EXTERN NSString *const PDFThumbnailViewDocumentEditedNotification;
NSString *const PDFThumbnailViewDocumentEditedNotification = @"PDFThumbnailViewDocumentEditedNotification";
PDFKIT_EXTERN NSString *const PDFViewAnnotationHitNotification;
NSString *const PDFViewAnnotationHitNotification = @"PDFViewAnnotationHit";
PDFKIT_EXTERN NSString *const PDFViewAnnotationWillHitNotification;
NSString *const PDFViewAnnotationWillHitNotification = @"PDFViewAnnotationWillHit";
PDFKIT_EXTERN NSString *const PDFViewChangedHistoryNotification;
NSString *const PDFViewChangedHistoryNotification = @"PDFViewChangedHistory";
PDFKIT_EXTERN NSString *const PDFViewCopyPermissionNotification;
NSString *const PDFViewCopyPermissionNotification = @"PDFViewCopyPermission";
PDFKIT_EXTERN NSString *const PDFViewDisplayBoxChangedNotification;
NSString *const PDFViewDisplayBoxChangedNotification = @"PDFViewDisplayBoxChanged";
PDFKIT_EXTERN NSString *const PDFViewDisplayModeChangedNotification;
NSString *const PDFViewDisplayModeChangedNotification = @"PDFViewDisplayModeChanged";
PDFKIT_EXTERN NSString *const PDFViewDocumentChangedNotification;
NSString *const PDFViewDocumentChangedNotification = @"PDFViewChangedDocument";
PDFKIT_EXTERN NSString *const PDFViewPageChangedNotification;
NSString *const PDFViewPageChangedNotification = @"PDFViewChangedPage";
PDFKIT_EXTERN NSString *const PDFViewPrintPermissionNotification;
NSString *const PDFViewPrintPermissionNotification = @"PDFViewPrintPermission";
PDFKIT_EXTERN NSString *const PDFViewScaleChangedNotification;
NSString *const PDFViewScaleChangedNotification = @"PDFViewScaleChanged";
PDFKIT_EXTERN NSString *const PDFViewSelectionChangedNotification;
NSString *const PDFViewSelectionChangedNotification = @"PDFViewSelectionChanged";
PDFKIT_EXTERN NSString *const PDFViewVisiblePagesChangedNotification;
NSString *const PDFViewVisiblePagesChangedNotification = @"PDFViewVisiblePagesChanged";
PDFKIT_EXTERN const CGFloat kPDFDestinationUnspecifiedValue;
const CGFloat kPDFDestinationUnspecifiedValue = (CGFloat)FLT_MAX;
