-- The Apple-prefixed spellings of the Aliro feature, as forwards to the methods this library carries.
--
-- Apple's own Matter.framework spells a command `apple<Command>` and an attribute access
-- `read/write/subscribeAttributeApple<Attribute>`, over the Aliro feature the open-source model declares under its own
-- name (measured: `AppleAliro` and `appleClearAliro` have zero occurrences in connectedhomeip master as well as in the
-- 1.6.1.0 this package builds, and master's templates/availability.yaml lists the names unprefixed). So every such row
-- is one selector forwarding to another over the same attribute or command id, and the forwarders are generated here
-- from the selectors the library actually carries rather than written out: a rename, and a rename has no per-row
-- judgement in it.
--
-- A target that the library does not carry is *not* emitted and is named here, because a forward to nothing is a
-- method that lies.
local objc = import("apple.objc", {rootdir = path.join(os.scriptdir(), "..", "modules"), anonymous = true})
-- Apple's two spellings, as the rename the SDK's surface shows.
local function target_of(selector)
    local renamed = selector:gsub("^(%a+Attribute)Apple", "%1"):gsub("^(%a+Attribute)", "%1")
    if renamed == selector then
        renamed = selector:gsub("^apple", "")
        renamed = renamed:sub(1, 1):lower() .. renamed:sub(2)
    end
    return renamed
end

function main(binary, corpus, diff, out)
    assert(binary and corpus and diff and out, "four paths: the dylib, the corpus, the differential, the output directory")
    local inventory = objc.binary_inventory(binary, "armv7")
    local function carried(owner, sign, selector)
        local seen, name = {}, owner
        while name and inventory.classes[name] and not seen[name] do
            seen[name] = true
            local entry = inventory.classes[name]
            if entry.instance[sign .. selector] or entry.class[sign .. selector] then
                return true
            end
            name = entry.superclass
        end
        return false
    end
    local hostmembers = {}
    for line in io.lines(diff) do
        local f = {}
        for field in (line:gsub("\n$", "") .. "\t"):gmatch("([^\t]*)\t") do
            table.insert(f, field)
        end
        if f[1] == "host_carries" and f[2] == "method" then
            hostmembers[f[3]] = true
        end
    end
    local forwards, absent = {}, {}
    for line in io.lines(corpus) do
        local f = {}
        for field in (line:gsub("\n$", "") .. "\t"):gmatch("([^\t]*)\t") do
            table.insert(f, field)
        end
        if f[1] == "Matter" and f[2] == "method" and hostmembers[f[4]] then
            local sign, owner, selector = f[4]:match("^([-+])%[([%w_]+) (.+)%]$")
            if sign and not carried(owner, sign, selector) then
                local to = target_of(selector)
                if carried(owner, sign, to) then
                    table.insert(forwards, {sign = sign, owner = owner, selector = selector, to = to})
                else
                    table.insert(absent, f[4] .. "  ->  " .. to)
                end
            end
        end
    end
    table.sort(forwards, function (a, b) return a.owner .. a.selector < b.owner .. b.selector end)

    -- One category per class, so a class that gains a spelling gains only its own.
    local byowner = {}
    for _, f in ipairs(forwards) do
        byowner[f.owner] = byowner[f.owner] or {}
        table.insert(byowner[f.owner], f)
    end
    os.mkdir(out)
    local written, classes = 0, 0
    for _, owner in ipairs(table.orderkeys(byowner)) do
        local lines = {
            "/*",
            " *    The Apple-prefixed spellings of the Aliro feature, forwarding to the methods this library carries.",
            " *",
            " *    Generated by tools/matter-alias.lua from the selectors the library carries, not written out: the",
            " *    SDK's surface spells these commands `apple<Command>` and these attribute accesses",
            " *    `read/write/subscribeAttributeApple<Attribute>` over the Aliro feature the open-source model declares",
            " *    under its own name, and a rename has no per-row judgement in it. Each forward reaches the same",
            " *    attribute or command id as the method it forwards to, because it is that method's own encoder call.",
            " *",
            " *    Measured: `AppleAliro` and `appleClearAliro` have zero occurrences in connectedhomeip master as well as",
            " *    in the tag this package builds, and the framework's own metadata carries the unprefixed methods.",
            " */",
            "",
            "#import <Foundation/Foundation.h>",
            "#import <Matter/" .. owner .. ".h>",
            "",
            "@interface " .. owner .. " (CharonAppleSpelling)",
            "@end",
            "",
            "@implementation " .. owner .. " (CharonAppleSpelling)",
            ""
        }
        -- The signature of the apple-prefixed method is the unprefixed method's, with the prefix put back: the same
        -- parameters and the same types, because it is the same command over the same ids. So it is read out of the
        -- framework's own header, which declares the unprefixed one, rather than assembled from the selector - a
        -- selector carries no types, and a forward with untyped parameters is not the same method.
        for _, f in ipairs(byowner[owner]) do
            local declaration = signature_in(header_for(owner, "packages/m/matter/headers"), f.to)
            if not declaration then
                table.insert(absent, f.api .. "  ->  " .. f.to .. "  (no declaration in the header to copy the types from)")
            else
                table.insert(lines, "-" .. rename(declaration))
                table.insert(lines, "{")
                local arguments = {}
                for parameter in f.selector:gmatch("([^:]*):") do
                    table.insert(arguments, parameter .. ":")
                end
                table.insert(lines, string.format("    return [self %s%s];", f.to, table.concat(arguments, " ")))
                table.insert(lines, "}")
                table.insert(lines, "")
                written = written + 1
            end
        end
        table.insert(lines, "@end")
        table.insert(lines, "")
        io.writefile(path.join(out, owner .. ".mm"), table.concat(lines, "\n"))
        classes = classes + 1
    end
    -- print takes one argument in this Lua, so a formatted line is string.format's work; and a gsub in an argument
    -- position hands io.lines the substitution count as its start offset, which is why the paths are passed whole.
    print(string.format("%d forwards over %d classes, each to a selector the library carries; %d rows with no carried target:",
                        written, classes, #absent))
    for _, row in ipairs(absent) do
        print("  no target: " .. row)
    end
end

-- The paths, in the order xmake l passes them, with the output directory last.
