#!/usr/bin/env python3
"""Asks the compiler what each type is, and writes the table the generator reads.

    VT_SDK=<an iPhoneOS*.sdk> python3 probe-types.py

THE TYPES COME FROM THE SDK, from two places and neither is a list anyone wrote: the argument types of
the seventeen initialisers, and the type of every property on the seventeen classes. The store line asks
about BOTH - init_body() for an argument, body() for a property - and a table that covered only the
arguments left NSDictionary<NSString *, id> * with no row, which store_branch refuses to invent.

TWO INDEPENDENT SIGNALS per type, and the walk fails if they disagree:

    __builtin_classify_type(*(T *)0)   the class, as THIS toolchain prints it - which is not the
                                       documented table: 1 integer, 4 boolean, 5 pointer, 8 real,
                                       12 record, and -1 for every Objective-C object pointer
    @encode(T)[0] == '@'              true of an Objective-C object type, and the second witness for
                                       the object branch, since -1 is not a documented class at all

BUILT FOR THE HOST, and the two build constraints are real and are why: the iOS SDK's CVPixelBuffer.h
includes the macOS-only CoreVideo.h umbrella (which wants CVDisplayLink.h, absent from the iOS SDK), and
Foundation/NSURL.h pulls an iOSSupport-era NSURLHandle.h that is not shipped. So no Foundation and no
CoreVideo.h here - the two concrete CoreVideo headers, which is all the probe needs.
"""
import glob
import importlib.util
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORKTREE = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
# the TABLE is written BESIDE the generator and committed - the generator reads it, so an untracked
# copy in .agent-work is a file the delivery does not have. The probe's own build output is scratch and
# stays under .agent-work, which is excluded from the repository.
OUT = os.path.join(WORKTREE, ".agent-work", "runs", "vt")
TABLE = os.path.join(HERE, "type-branches.tsv")


def load_gen_body():
    path = os.path.join(HERE, "gen_body.py")
    spec = importlib.util.spec_from_file_location("gen_body", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    assert os.path.abspath(module.__file__) == path, "loaded a copy that is not this one"
    return module


def collect_types(gen_body, sdk):
    """Every type the store line will be asked about, from the SDK's own declarations."""
    headers = os.path.join(sdk, "System/Library/Frameworks/VideoToolbox.framework/Headers")
    text = "\n".join(open(f).read() for f in sorted(glob.glob(os.path.join(headers, "*.h"))))
    protocols, classes = gen_body.parse(text)
    ordered, seen = [], set()

    def add(type_name):
        if type_name and type_name not in seen:
            seen.add(type_name)
            ordered.append(type_name)

    for cls in gen_body.ORDER:
        for _selector, arguments, _returns in gen_body.initialisers(text, cls):
            for _keyword, type_name, _piece in arguments:
                add(type_name)
    for cls in gen_body.ORDER:
        entry = classes[cls]
        inherited = [protocols[proto][name] for proto in entry["protocols"] for name in protocols[proto]]
        for _name, prop in list(entry["own"].items()) + list(zip(entry["own"], inherited)):
            add(prop["type"] + (" *" if prop["obj"] else ""))
    return ordered


def main():
    sdk = os.environ.get("VT_SDK", "")
    if not sdk:
        sys.exit("probe-types.py: set VT_SDK to an iPhoneOS*.sdk")
    gen_body = load_gen_body()
    types = collect_types(gen_body, sdk)
    if not os.path.isdir(OUT):
        os.makedirs(OUT)
    source = os.path.join(OUT, "classify.m")
    lines = ["// GENERATED by probe-types.py - one line per type, two signals.",
             "#import <VideoToolbox/VideoToolbox.h>",
             "#import <CoreMedia/CoreMedia.h>",
             "#import <CoreVideo/CVBuffer.h>",
             "#import <CoreVideo/CVPixelBuffer.h>",
             "#include <stdio.h>",
             "int main(void)",
             "{"]
    for type_name in types:
        lines.append('    printf("%s\\t%d\\t%s\\n", "' + type_name + '", __builtin_classify_type(*(' +
                     type_name + ' *)0), (@encode(' + type_name + ')[0] == \'@\' ? "objc" : "not-objc"));')
    lines += ["    return 0;", "}"]
    open(source, "w").write("\n".join(lines) + "\n")

    build = ["xcrun", "clang", "-framework", "CoreMedia", "-framework", "CoreVideo",
             source, "-o", os.path.join(OUT, "classify")]
    result = subprocess.run(build, capture_output=True, text=True)
    if result.returncode:
        sys.exit("the probe did not build:\n%s" % result.stderr[:2000])
    run = subprocess.run([os.path.join(OUT, "classify")], capture_output=True, text=True)
    rows, disagree = [], []
    for line in run.stdout.strip().split("\n"):
        name, klass, encode = line.split("\t")
        klass = int(klass)
        if (klass == -1) != (encode == "objc"):
            disagree.append(line)
        rows.append((name, klass, encode))
    table = TABLE
    print("table: %s" % table)
    with open(table, "w") as handle:
        for name, klass, encode in rows:
            handle.write("%s\t%d\t%s\n" % (name, klass, encode))
    print("probe: %d types, from the initialisers AND the properties" % len(rows))
    if disagree:
        for line in disagree:
            print("DISAGREE the two signals say different things: " + line)
        sys.exit(1)
    classes = {}
    for _name, klass, _encode in rows:
        classes[klass] = classes.get(klass, 0) + 1
    print("classes the compiler printed: %s" % ", ".join("%d x%d" % (k, v) for k, v in sorted(classes.items())))
    print("the two signals agree on all %d" % len(rows))
    print("table: %s" % table)


if __name__ == "__main__":
    main()
