#!/usr/bin/env python3
"""Renames every class and enumeration the port declares, so one host binary carries the port's build
and the host's own side by side. The class name is a string in the case file, so a rename has to be
visible to both the class and the string that looks it up: cases.m stringifies the name through
VTCLASS_NAME, which is how one line of it finds the host's class in one build and the port's in the
other. The enumerations come along because a class property's type is spelled with them."""
import sys

CLASSES = [
    "VTFrameProcessor", "VTFrameProcessorFrame", "VTFrameProcessorOpticalFlow",
    "VTFrameRateConversionConfiguration", "VTFrameRateConversionParameters",
    "VTLowLatencyFrameInterpolationConfiguration", "VTLowLatencyFrameInterpolationParameters",
    "VTLowLatencySuperResolutionScalerConfiguration", "VTLowLatencySuperResolutionScalerParameters",
    "VTMotionBlurConfiguration", "VTMotionBlurParameters", "VTOpticalFlowConfiguration",
    "VTOpticalFlowParameters", "VTSuperResolutionScalerConfiguration",
    "VTSuperResolutionScalerParameters", "VTTemporalNoiseFilterConfiguration",
    "VTTemporalNoiseFilterParameters",
]

with open(sys.argv[1], "w") as handle:
    handle.write("// Generated by rename.py: the port's own declarations, under names of their own.\n")
    for name in CLASSES:
        handle.write("#define %s Charon%s\n" % (name, name))
    # The protocol names are NOT renamed: a class is asked whether it conforms to
    # VTFrameProcessorConfiguration by that name, and the port declares that protocol itself.
