#!/bin/sh
# vt-classes.sh — one commit per VideoToolbox class, and the class is in the committed lists only after
# its own commit exists.
#
# For each class, in the order given: its own value file, its declaration in the port's header, and a
# staged copy of covered.txt and mutants.txt that names it. Then armv7 compiles every value file against
# the lowered 16.4 SDK, the host differential runs - which must be green and must catch that class's
# mutation - and only then are the class and its two list lines committed together.
#
# The staging is the point. covered.txt used to be appended to BEFORE the commit, so a class whose
# differential failed left its name behind and the next run skipped it as "already covered": four classes
# were lost that way. A class that fails now leaves nothing behind, because nothing is written until it
# has earned its commit.
#
# Resumable: a class already in the committed covered.txt is skipped, so a run that stopped resumes.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
work=$(cd "$here/../../../.." && pwd)
vt="$work/packages/a/apple-backports/VideoToolbox"
t="$work/tests/backports/host/vtclass"
gen="$work/.agent-work/generated/vt"
# THIS SCRIPT'S OWN OUTPUT GOES UNDER THE WORKTREE, never in the temp path. An armv7 .o and the message
# handed to git commit are both durable artefacts, and the temp path is wiped - so a run that wrote a commit
# message there and was interrupted before committing lost it with nothing left to find.
runs="$work/.agent-work/runs/vtclass"
log=$work/.agent-work/runs/vt-classes.log
mkdir -p "$(dirname "$log")"
sdk=${VT_SDK:-$HOME/.xmake/packages/i/iphoneos-sdk/26.2/05d7872150914e1884a8de9d9dc71896/Developer.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS26.2.sdk}
low=$(ls -d "$HOME"/.xmake/packages/i/iphoneos-sdk/16.4/*/Developer.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk 2>/dev/null | head -1)
[ -n "$low" ] || { echo "no lowered 16.4 SDK under ~/.xmake/packages/i/iphoneos-sdk/16.4"; exit 1; }
[ -d "$sdk" ] || { echo "no iOS SDK at $sdk - set VT_SDK"; exit 1; }
export VT_SDK=$sdk

# the generator is checked before anything is generated from it: the star bug it had once produced
# by-value returns of interface types, and the compiler caught those only after a class was written
python3 "$t/test-gen-body.py" > "$log.gen" 2>&1 || { echo "the generator's own test failed:"; cat "$log.gen"; exit 1; }
tail -1 "$log.gen" | sed 's/^/gen_body: /'
python3 "$t/emit.py" "$sdk" | sed 's/^/emit: /'

# These classes' value files were written by runs that then failed - VTFrameProcessor's and
# VTLowLatencyFrameInterpolationConfiguration's were committed into the tree by the NEXT class's
# `git add -A`, which is why a class could be in the tree and out of covered.txt at the same time. They are
# finished here rather than rolled back, and each is regenerated from the fixed generator, so what lands is
# what the generator says now.
# VTOpticalFlowParameters is first because the tree does not compile until its header block is replaced:
# that block was generated by the generator as it was then, with the star bug, and four of its properties
# are declared by value. It is half-added - its block is not committed - so replacing it rewrites nothing.
# VTFrameProcessorFrame is the other half-added class and follows it.
order="VTOpticalFlowParameters
VTFrameProcessorFrame
VTLowLatencySuperResolutionScalerConfiguration
VTLowLatencyFrameInterpolationConfiguration
VTLowLatencyFrameInterpolationParameters
VTFrameProcessorOpticalFlow
VTFrameProcessor"

for cls in $order; do
    if grep -qx "$cls" "$t/covered.txt"; then
        echo "== $cls already covered, skipping"
        continue
    fi
    echo "== $cls"

    # 1. the value file, one class per file: it is what makes a mutation's anchor unique, so mutate.py can
    #    insist on exactly one match instead of changing the first of several
    {
        echo '#import "CharonVideoToolbox.h"'
        echo '#import "VideoToolboxValueStore.h"'
        echo ''
        cat "$gen/$cls.m"
    } > "$vt/$cls.m"

    # 2. the declaration, inside the guard the host comparison needs: the host's own VideoToolbox declares
    #    these classes, so redeclaring them in that one translation unit is a duplicate. Idempotent, because
    #    a declaration left behind by an earlier failed run belongs to the class being finished, not to
    #    another one.
    python3 - "$vt/CharonVideoToolbox.h" "$gen/$cls.h" <<'PY'
import re, sys
header, block = sys.argv[1], open(sys.argv[2]).read()
name = re.search(r'@interface\s+(\w+)', block).group(1)
text = open(header).read()
marker = "#endif // CHARON_HOST_DIFFERENTIAL"
assert marker in text, "the header's guard end is not where it was"
if re.search(r'@interface\s+%s\b' % name, text):
    # already declared by a run that failed later; the block is replaced so it cannot disagree
    print("   declaration already present, replacing it")
    text = re.sub(r'@interface\s+%s\b.*?@end\n\n?' % name, block + "\n", text, flags=re.S)
else:
    text = text.replace(marker, block + "\n" + marker)
open(header, "w").write(text)
PY

    # 3. the staged lists: the differential asks about this class, the committed lists do not know it yet
    staged=$(mktemp -d)
    cp "$t/covered.txt" "$staged/covered.txt"
    echo "$cls" >> "$staged/covered.txt"
    cp "$t/mutants.txt" "$staged/mutants.txt"
    python3 - "$cls" "$staged/mutants.txt" "$gen/$cls.m" <<'PY'
import json, re, sys
cls, mutants, path = sys.argv[1], sys.argv[2], sys.argv[3]
summary = json.load(open('%s/summary.json' % path.rsplit('/', 1)[0]))[cls]
text = open(path).read()
# A property's accessor is spelled by its GETTER, which is not always the property's own name: `supported`
# is declared getter=isSupported, and an anchor written with the property's name would look for
# + (BOOL)supported in a file that has + (BOOL)isSupported. The generated header ties the two together.
getters = {}
for attrs, decl in re.findall(r'@property \(([^)]*)\) ([^;]*);', open(path[:-2] + '.h').read(), re.S):
    name = decl.strip().split()[-1]
    g = re.search(r'getter=(\w+)', attrs)
    getters[name] = g.group(1) if g else name
accessors = summary["classProps"] or summary["own"] or summary["inherited"]
if not accessors:
    # The SDK declares NO property on this class - measured: its header has no @property line at all. There
    # is therefore nothing for "where its class properties live" to be a question about, and no mutant is
    # invented to fill the slot. Its members are seven METHODS, and where a method lives is step 3's mutant.
    sys.stderr.write("no properties declared for %s: no mutant for it in this step\n" % cls)
    raise SystemExit(0)
name = getters.get(accessors[0], accessors[0])
if summary["classProps"]:
    m = re.search(r'^\+ \([^)]*\)(%s)$' % re.escape(name), text, re.M)
    assert m, "no class accessor spelled %s in %s" % (name, cls)
    before, after = m.group(0), m.group(0).replace('+ (', '- (', 1)
else:
    m = re.search(r'^- \([^)]*\)(%s)$' % re.escape(name), text, re.M)
    assert m, "no instance accessor spelled %s in %s" % (name, cls)
    before, after = m.group(0), m.group(0).replace('- (', '+ (', 1)
assert text.count(before) == 1, "%r appears %d times in %s" % (before, text.count(before), cls)
with open(mutants, "a") as handle:
    handle.write("%s\t%s.m\t%s\t%s\n" % (cls, cls, before, after))
print("   mutant: %s -> %s" % (before, after))
PY

    # 4. armv7, against the lowered SDK: the release the port has to build for
    for f in "$vt"/*.m; do
        xcrun clang -target armv7-apple-ios6.1 -isysroot "$low" -I"$vt/.." -c "$f" \
            -o $runs/vtclass-$(basename "$f" .m).o -w
    done
    echo "   armv7: $(ls "$vt"/*.m | wc -l | tr -d ' ') value files clean"

    # 5. the differential, green, with this class's mutation caught - no pipe, so its status is the status
    if ! VTCLASS_COVERED="$staged/covered.txt" VTCLASS_MUTANTS="$staged/mutants.txt" \
        sh "$t/run.sh" > "$log" 2>&1; then
        echo "   RED - the differential failed, nothing is committed and the lists are untouched:"
        tail -20 "$log"
        exit 1
    fi
    grep -E "^compared|caught: .*\.$cls\b" "$log" | sed 's/^/   /'

    # 6. the commit: the class, and its two list lines, together - and only now
    cp "$staged/covered.txt" "$t/covered.txt"
    cp "$staged/mutants.txt" "$t/mutants.txt"
    python3 - "$cls" "$gen/$cls.m" > $runs/vtclass-msg.txt <<'PY'
import json, sys
cls, path = sys.argv[1], sys.argv[2]
s = json.load(open('%s/summary.json' % path.rsplit('/', 1)[0]))[cls]
n_own, n_inh = len(s["own"]), len(s["inherited"])
proto = ", ".join(s["protocols"]) or "nothing"
cls_props = s["classProps"]
where = ("where %d of them live on the class" % len(cls_props)) if cls_props else \
        ("every one of them an instance accessor")
print(cls)
print()
if n_own + n_inh == 0:
    print("One of the seventeen VideoToolbox classes, from the iOS 26.2 SDK's own headers. It declares no")
    print("property at all - measured: its header has no @property line - so what it carries is its methods,")
    print("and those are step 3's work. What is here is the class itself and the store its values live in.")
else:
    print("One of the seventeen VideoToolbox classes, from the iOS 26.2 SDK's own headers. It conforms to %s." % proto)
    print("Of its %d properties, %d are its own and %d are the protocol's, implemented here per class: %s."
          % (n_own + n_inh, n_own, n_inh, where))
print()
print("Every accessor is written out rather than @dynamic, for the reason the header gives: a class the")
print("port defines inherits the conformance its protocol declares, so a @dynamic would leave the compiler")
print("synthesising a getter over an ivar nothing ever writes. A class property's value is kept on the class,")
print("because a class property's value belongs to the type rather than to an instance; a struct is held as")
print("an NSValue over its own bytes, and a CFTypeRef is retained out of one with CFRetain.")
print()
print("The file is one class per file for a reason that is mechanical and not stylistic: each class's one")
print("mutation needs an anchor that appears exactly once, so the differential can insist on it rather than")
print("change the first of several. The class joins covered.txt and mutants.txt in THIS commit, which is why")
print("the lists are staged and written after the run rather than before it: a class that fails leaves")
print("nothing behind for the next run to skip.")
print()
print("    covered: %s" % cls)
if s["own"] or s["inherited"] or s["classProps"]:
    print("    mutation: where an accessor lives - caught")
else:
    print("    no mutant: the SDK declares no property on this class, so there is none to move.")
if s.get("unavailable_ios"):
    print("    not carried: %s, which the SDK declares API_UNAVAILABLE(ios)" % ", ".join(s["unavailable_ios"]))
print()
print("Co-Authored-By: OpenCode <opencode@local>")
print("Self-review: clean. Two limits are the differential's and are named in the runner, not hidden: it")
print("reads no values, because the host's VideoToolbox refuses dimensions it does not support; and four")
print("members of this family are judged from the iOS table alone, because the host's SDK 27.0 does not")
print("declare them at all.")
PY
    git add -A -- packages tests
    git -c user.name=opencode -c user.email=opencode@local commit -q -F $runs/vtclass-msg.txt
    rm -rf "$staged"
    echo "   committed $(git log --oneline -1 | cut -c1-58)"
done
# The completeness check is against the GENERATOR's class list, not this script's order variable. The
# first version of this driver ended on "every class in the list is committed" - true, and worthless: the
# list itself was short by one class, VTLowLatencySuperResolutionScalerConfiguration, and nothing said so
# until the coverage was counted against the table. So the table is the authority.
python3 - "$t/covered.txt" "$gen/summary.json" <<'PY'
import json, sys
covered = {l.strip() for l in open(sys.argv[1]) if l.strip()}
classes = set(json.load(open(sys.argv[2])))
missing = sorted(classes - covered)
extra = sorted(covered - classes)
if missing or extra:
    if missing:
        print("NOT COVERED: %s" % ", ".join(missing))
    if extra:
        print("COVERED BUT NOT IN THE TABLE: %s" % ", ".join(extra))
    sys.exit(1)
print("== every one of the generator's %d classes is committed and covered" % len(classes))
PY
