#import "CharonSensorKit.h"
#import "CharonSensorKitValue.h"
#import "../CharonValueStore.h"

// SensorKit of iOS 26.0, the properties that arrived then.
@implementation SRAcousticSettings
@dynamic environmentalSoundMeasurementsEnabled, audioExposureSampleLifetime, headphoneSafetyAudioLevel, musicEQSettings, accessibilitySettings;
CHARON_SCALAR_PROPERTY(BOOL, environmentalSoundMeasurementsEnabled)
CHARON_SCALAR_PROPERTY(SRAcousticSettingsSampleLifetime, audioExposureSampleLifetime)
CHARON_VALUE_PROPERTY(NSNumber *, headphoneSafetyAudioLevel)
CHARON_VALUE_PROPERTY(SRAcousticSettingsMusicEQ *, musicEQSettings)
CHARON_VALUE_PROPERTY(SRAcousticSettingsAccessibility *, accessibilitySettings)
@end
@implementation SRAcousticSettings (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
@implementation SRAcousticSettingsAccessibility
@dynamic leftRightBalance, monoAudioEnabled, backgroundSounds, headphoneAccommodations;
CHARON_SCALAR_PROPERTY(double, leftRightBalance)
CHARON_SCALAR_PROPERTY(BOOL, monoAudioEnabled)
CHARON_VALUE_PROPERTY(SRAcousticSettingsAccessibilityBackgroundSounds *, backgroundSounds)
CHARON_VALUE_PROPERTY(SRAcousticSettingsAccessibilityHeadphoneAccommodations *, headphoneAccommodations)
@end
@implementation SRAcousticSettingsAccessibility (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
@implementation SRAcousticSettingsAccessibilityBackgroundSounds
@dynamic enabled, soundName, relativeVolume, playWithMediaEnabled, relativeVolumeWithMedia, stopOnLockEnabled;
CHARON_SCALAR_PROPERTY(BOOL, enabled)
CHARON_SCALAR_PROPERTY(SRAcousticSettingsAccessibilityBackgroundSoundsName, soundName)
CHARON_SCALAR_PROPERTY(double, relativeVolume)
CHARON_SCALAR_PROPERTY(BOOL, playWithMediaEnabled)
CHARON_SCALAR_PROPERTY(double, relativeVolumeWithMedia)
CHARON_SCALAR_PROPERTY(BOOL, stopOnLockEnabled)
@end
@implementation SRAcousticSettingsAccessibilityBackgroundSounds (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
@implementation SRAcousticSettingsAccessibilityHeadphoneAccommodations
@dynamic enabled, mediaEnhanceTuning, mediaEnhanceBoosting, mediaEnhanceApplication;
CHARON_SCALAR_PROPERTY(BOOL, enabled)
CHARON_SCALAR_PROPERTY(SRAcousticSettingsAccessibilityHeadphoneAccommodationsMediaEnhanceTuning, mediaEnhanceTuning)
CHARON_SCALAR_PROPERTY(SRAcousticSettingsAccessibilityHeadphoneAccommodationsMediaEnhanceBoosting, mediaEnhanceBoosting)
CHARON_SCALAR_PROPERTY(SRAcousticSettingsAccessibilityHeadphoneAccommodationsMediaEnhanceApplication, mediaEnhanceApplication)
@end
@implementation SRAcousticSettingsAccessibilityHeadphoneAccommodations (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
@implementation SRAcousticSettingsMusicEQ
@dynamic soundCheckEnabled, lateNightModeEnabled;
CHARON_SCALAR_PROPERTY(BOOL, soundCheckEnabled)
CHARON_SCALAR_PROPERTY(BOOL, lateNightModeEnabled)
@end
@implementation SRAcousticSettingsMusicEQ (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
@implementation SRSleepSession
@dynamic startDate, duration, identifier;
CHARON_VALUE_PROPERTY(NSDate *, startDate)
CHARON_SCALAR_PROPERTY(NSTimeInterval, duration)
CHARON_VALUE_PROPERTY(NSString *, identifier)
@end
@implementation SRSleepSession (CharonSensorKitValue)
CHARON_SENSORKIT_VALUE_STORE_IMPLEMENTATION
@end
